### ISSUE TITLE
Wind stream lines density unbalanced with map scale

### ISSUE THREAD

**Issue by nvbargen** [electricitymaps/electricitymaps-contrib#1157]
On the wind potential map, the scaling of the wind stream line density is not balanced with the overall map scale:  When taking a global view, hardly any stream lines are visible, and even big cyclone system hardly show up, whereas on a detailed scale (e.g. North Sea), even low-speed wind fields have a stream line density and length that visually would be more appropriate for a hurricane. The speed of the animation at large scale is also impressively fast (I don't get sea sick :-)).
This could probably be fine-tuned by reducing the scale sensitivity of the wind stream density (and stream line velocity).

![windstreamlinesok](https://user-images.githubusercontent.com/36658179/36722602-d714bf36-1ba5-11e8-94cf-0ed19c926b41.JPG)
![windstreamlinestoodense](https://user-images.githubusercontent.com/36658179/36722610-dbc61e26-1ba5-11e8-9fac-f22c92b0c6b7.JPG)
![windstreamlinestoofew](https://user-images.githubusercontent.com/36658179/36722614-de390eb6-1ba5-11e8-8e33-e2d2a241e431.JPG)

**Comment by alixunderplatz** [comment]
@corradio @ovbm No similar issues for this stream-line related, visual topic were opened since then.
Do you want this to be fixed or leave it as it is?

**Comment by corradio** [comment]
Let's keep the issue opened for now as indeed it could be nice to have this fixed

**Comment by Kongkille** [comment]
For someone interested in looking into this, it would make sense to add wind/solar data to the mockserver as well (see #1876)
