### ISSUE TITLE
Data for Colombia

### ISSUE THREAD

**Issue by camilogavo** [electricitymaps/electricitymaps-contrib#1509]
Are you working on colombia dataset?

Could I contribute for this?

**Comment by corradio** [comment]
Hi @camilogavo !
Feel free to start ahead and keep track of your progress here.
Did you find any real-time data?

**Comment by camilogavo** [comment]
Data are published by XM as @systemcatch said but it is 24 hours delayed. Is it useful @corradio?

**Comment by corradio** [comment]
Unfortunately it won't appear on electricityMap if it's > 24h.
Any other sources available?

**Comment by systemcatch** [comment]
@alixunderplatz Found some other links that may be useful.

http://www.xm.com.co/Paginas/Generacion/Despacho-nacional.aspx
Zip files going back years showing breakdown by hour for what I think is every power plant in Columbia. It might might also show interconnections.

http://www.xm.com.co/Paginas/Generacion/Despacho-Termico.aspx
Same but for thermal plants only.

I think we might have enough to build a historical parser.

**Comment by Kongkille** [comment]
Thanks for all the valuable information shared here! 🙌

We're closing this issue and adding to our main issue for missing countries as it doesn't currently seem possible to build a real-time parser given the data provided here.
If you find new information that might help us get it done, please comment and reopen the issue [when a parser is buildable](https://github.com/electricityMap/electricitymap-contrib/wiki/Technical-requirements-for-parser-data) :)

**Comment by alixunderplatz** [comment]
🇨🇴 I found the API source for real-time consumption data for Colombia 🇨🇴 with 5-minute-granularity (original link was mentioned 2 comments earlier):

https://serviciosfacturacion.xm.com.co/XM.Portal.Indicadores/api/Operacion/DemandaTiempoReal

Working on getting a consumption parser done =)

**Comment by alixunderplatz** [comment]
<img width="1320" alt="grafik" src="https://user-images.githubusercontent.com/25743609/218874944-0e928bae-4052-4ccf-8d13-e20625390415.png">

community, are you aware that IEA now has their version of electricityMaps?
They seem to use one of the above sources to create the hourly post-production profile for Colombia, which is lagging behind about 2 days.

https://www.iea.org/data-and-statistics/data-tools/real-time-electricity-tracker?tracker=true&from=2023-2-9&to=2023-2-14&category=generation&country=COL&fuel=Renewables

(off topic but relevant: No surprises on that IEA map, except Philippines (#679), India as a whole (#1664), nice subregional production for the US, cleaner , less-bumpy data for Nigeria and demand data for Iran)

**Comment by VIKTORVAV99** [comment]
With the merge of #5338 I think we can close this. If there anything more to add feel free to re-open this.
