### ISSUE TITLE
Add organization contact links for zones with no data

### ISSUE THREAD

**Issue by systemcatch** [electricitymaps/electricitymaps-contrib#1981]
This was discussed on slack.

It's a simple idea, we add a new key to the zones file for zones where we have no data but know who could provide that data.

For example South Africa;

```
"ZA": {
    "contact_link: "http://www.eskom.co.za/CustomerCare/CustomerFeedback/Pages/Customer_Feedback.aspx"
},
```

Then when a user hovers/clicks an empty zone the popup reads something like;

"There is no data currently available for this area.
Get in touch with **insert contact link here** and ask them to provide public real-time data."

We could even include twitter handles if they're available. There's many ways we can leverage activism to open up new sources of data imo.

**Comment by martincollignon** [comment]
This is a great idea!

**Comment by brandongalbraith** [comment]
Along the same lines, is there a reference API spec that can be provided (the ideal way to provide the necessary generation/consumption mix data to Tomorrow's electricity map scrapper) to orgs that haven't yet provided a public interface? (If this is excessively out of scope for this issue, please say so!)

**Comment by martincollignon** [comment]
Definitely not out of scope, @brandongalbraith . Here is what our parsers need (can also be found here https://github.com/tmrowco/electricitymap-contrib#adding-a-new-country):

```
def fetch_production(zone_key='FR', session=None, target_datetime=None, logger=None):
    return {
      'countryCode': 'FR',
      'datetime': '2017-01-01T00:00:00Z',
      'production': {
          'biomass': 0.0,
          'coal': 0.0,
          'gas': 0.0,
          'hydro': 0.0,
          'nuclear': None,
          'oil': 0.0,
          'solar': 0.0,
          'wind': 0.0,
          'geothermal': 0.0,
          'unknown': 0.0
      },
      'storage': {
          'hydro': -10.0,
      },
      'source': 'mysource.com'
    }
```

I think we could draft a simple email asking for this data, and then even add a mailto link to make @systemcatch 's suggestion even more powerful

**Comment by jarek** [comment]
See previous discussion in https://github.com/tmrowco/electricitymap-contrib/issues/1232

**Comment by corradio** [comment]
I think it could make sense also for zones *with* data, so we can make sure people contact directly the data provider instead of us (we get a lot of requests!)

**Comment by corradio** [comment]
I'm closing the issue right now as it's stale.
