### ISSUE TITLE
Spanish mainland data from REE

### ISSUE THREAD

**Issue by pdunamuno** [electricitymaps/electricitymaps-contrib#2203]
We haven't found the data for this region yet, but that doesn't mean you can't make it happen!

Ranked from best to useful information, here is what we could use:
- real-time data of energy generation by energy source
- historical data of energy generation by energy source (as recent and as granular as possible)
- contact details (contact form, email or social media) of someone who may have access to that data
- contact details (contact form, email or social media) of an organisation which may have access to that data

**Comment by pdunamuno** [comment]
Could you change the source of the data to https://demanda.ree.es/visiona/peninsula/demanda/total it is more accurate than the one that is now

**Comment by jarek** [comment]
Can you briefly describe in which ways is it more accurate than the data we have which comes from ENTSOE?

**Comment by pdunamuno** [comment]
The information in ENTSOE updates every hour and creates in the graph of electricity production like a stair boxines, instead if you use REE it updates more frecuently and there is not that stair looking graph.
In Mallorca electricity map uses REE and doesn´t has the stair looking graph.
thank you for answering.

**Comment by liacds** [comment]
Hi, can I work on this issue?

**Comment by jarek** [comment]
Yes that should be fine! You can use the current implementation of Balearic and/or Canary Islands as a template since they already use REE data.

**Comment by corradio** [comment]
As discussed in https://github.com/tmrowco/electricitymap-contrib/pull/2370#issuecomment-640562408 we will need a PR with both real-time *and* historical data in order to be able to replace ENTSOE.
Work was already done here by @liacds https://github.com/tmrowco/electricitymap-contrib/pull/2370 so it would be great to re-use it.

**Comment by CheneyZeng** [comment]
Can I work on adding historical data? @corradio @pierresegonne

**Comment by Kongkille** [comment]
It seems the dashboard is still live and has quite a long historical range :)

**Comment by VIKTORVAV99** [comment]
I'm going to close this as the `ES.py` parser now support parsing ES mainland data.

If anyone feels it should be re-opened let me know.
