### ISSUE TITLE
Add historical data for Maharashtra (India)

### ISSUE THREAD

**Issue by FelixDQ** [electricitymaps/electricitymaps-contrib#2989]
Historical data is available from here: https://mahasldc.in/home.php/daily-reports/

The format is a bit annoying because it is returned as 1 pdf per day.

This report is hosted on the same URL as the current live parser, so it is likely that the data will match. We should still compare the data to be sure.

**Comment by gwpicard** [comment]
A separate data source is available here - [https://npp.gov.in/dgrReports](https://npp.gov.in/dgrReports) - which may be helpful for obtaining additional historical data. The advantage is that the NPP offers .csv files as well.

**Comment by VIKTORVAV99** [comment]
Closing this as we have removed the old India zones.
