### ISSUE TITLE
interconnections between Corsica and Sardinia and between Italy-Central-North and Sardinia (from the DC-connection)

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#2991]
From @alixunderplatz 
> There are 2 more paths to consider which are missing on the map: interconnections between Corsica and Sardinia and between Italy-Central-North and Sardinia (from the DC-connection).

See https://github.com/tmrowco/electricitymap-contrib/issues/1029#issuecomment-537910683 and https://github.com/tmrowco/electricitymap-contrib/issues/1029#issuecomment-537956654

@alixunderplatz feel free to give more context here!

**Comment by VIKTORVAV99** [comment]
I think this should be safe to close now since the addition of the `FR-COR_IT-SAR.py` exchange parser was added.
