### ISSUE TITLE
IN-UP down

### ISSUE THREAD

**Issue by pierresegonne** [electricitymaps/electricitymaps-contrib#3213]
The Uttar Pradesh (UP) region has been down since early may 2021 (2021-05-03). 

It seems like the data provider's website, http://www.upsldc.org/real-time-data, has faulty or malicious code and is blocked. The website currently returns 403 and this page when queried. 

<img width="1440" alt="Screenshot 2021-07-12 at 10 31 26" src="https://user-images.githubusercontent.com/32778266/125256025-50ca4000-e2fc-11eb-966d-2e32a669067a.png">
 
Potential ways forward:

* Find a point of contact at USPSLDC to check if they're aware of it / working on it
* Find out what SOPHOS is and why this blocked page is returned

**Comment by hdatteln** [comment]
Hi There, 
I contacted UPSLDC via their Facebook site, https://www.facebook.com/sldcup/, to ask about their website.
Sophos is a security software. The above message comes probably from a Sophos firewall they are using.

**Comment by pierresegonne** [comment]
Thanks for that @hdatteln ! Let's hope they'll be reactive :)

**Comment by saurabhchatterjee23** [comment]
looks like they have moved to HTTPS 
https://www.upsldc.org/real-time-data works for me

**Comment by madsnedergaard** [comment]
We're not using this zone anymore, closing.
