### ISSUE TITLE
Solar layer is moving when zooming

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#3217]
## Description

As mentioned by @veqtrus in #3215, it seems like the solar layer is being offset incorrectly when zooming on the map.

### Examples

See the cloud of Queensland in this example when zooming:

https://user-images.githubusercontent.com/3296643/125889923-b578d356-dfce-41d2-b494-a6aa86567e5a.mp4

And when moving around:

https://user-images.githubusercontent.com/3296643/125890099-9a8aed60-740f-4204-9db3-ab07fe701b65.mp4

**Comment by piotrek124-1** [comment]
When moving the map along the Y axis of the solar layer is also moving, but when moving the X axis it seems to be ok.

1:
![obraz](https://user-images.githubusercontent.com/66417442/130328897-69562681-abe8-40fc-964b-a6805883f71c.png)

Moving in the X axis:
![obraz](https://user-images.githubusercontent.com/66417442/130328951-083f694b-1324-4fff-ae17-15e6e0328c36.png)

Moving in the Y axis:
![obraz](https://user-images.githubusercontent.com/66417442/130328962-6e46f265-1916-4909-8eaf-a7d862e5d77b.png)
