### ISSUE TITLE
scrape prices in India 🇮🇳 

### ISSUE THREAD

**Issue by Manu1400** [electricitymaps/electricitymaps-contrib#3256]
ie: [price in Himachal Pradesh](http://www.vidyutpravah.in/state-data/himachal-pradesh)
> Exchange Price
> Current : 3.05  ₹/Unit

* [all prices](http://www.vidyutpravah.in/)

### checks
- [X] Data is live
- [X] This website is a valid source
- [X] ElectricityMap don't have prices for this zone ([zone IN-HP in ElectricityMap](https://www.electricitymap.org/zone/IN-HP))
- [X] scrapping is possible

### ⚠️ warning(s)
- the website is slow to respond but it's works

**Comment by VIKTORVAV99** [comment]
I'm taking a look at all our old issues and seeing which can be closed or revived.

It does look like the source used in here is no longer available, returning 404s and with the recent change to the India zones I think it would be best to close this issue. But if you have another source feel free to open a new issue or discussion for it.
