### ISSUE TITLE
Serving first response of https://www.electricitymap.org/map faster

### ISSUE THREAD

**Issue by steren** [electricitymaps/electricitymaps-contrib#3262]
It looks like https://www.electricitymap.org/map has a pretty bad Lighthouse score for Performance: 17/100

While many optimization can be done. One seems particularly impactful:

When disabling cache, it looks like serving the HTML of  the first request sent to https://www.electricitymap.org/map takes about a second. That's very long for a page that I assume can be generated at build time and served over a CDN. Knowing that this response will trigger the download of all JavaScript and CSS, it's pretty important to serve it as fast as possible.

* In production, is `server.js` serving this page?  Could it be generated at build time?
* Where is it hosted? is there a CDN in front of the website?

**Comment by skovhus** [comment]
Thanks @steren! Yes we have a lot of performance optimization we should be doing. 

Currently `server.js` is serving the page and I would love if this was a static file instead.

**Comment by corradio** [comment]
A note of (historical) context: the reason why server.js is dynamic is that it serves language-specific content based on headers. This could (should!) be changed however.
Relevant code is here:
https://github.com/tmrowco/electricitymap-contrib/blob/master/web/server.js#L210-L220

**Comment by VIKTORVAV99** [comment]
There have been substantial improvements in our performance mostly due to size reductions for now but in the refractor the custom server will be removed and should take care of the rest.

**Comment by VIKTORVAV99** [comment]
Now that the refractor has been deployed this should have improved significantly. In the near future we will also enable service workers that should make repeat visits near instant.
