### ISSUE TITLE
data-QA: get live demand in Georgia 🇬🇪 to validate live data

### ISSUE THREAD

**Issue by Manu1400** [electricitymaps/electricitymaps-contrib#3268]
### issue

http://www.gse.com.ge/apps/gsebackend/rest/map have `timestamp":null`

### proposal : get live demand

source: live graph in [ELECTRICITY DEMAND TRACKING](http://www.gse.com.ge/for-customers/data-from-the-power-system/production-and-consumption) (green line = demand

JSON : http://www.gse.com.ge/apps/gsebackend/rest/diagram?minusHours=4&plusHours=20 to get demand
=> `realDataList[<last item>]` to get ```{"time":"2021-08-03T11:45:00.000+0000","data":1259.0}``` live demand

And then compare demand and production : 
* `production - demand` MUST be into an interval [-1000 MW, 1000 MW] (example)

**Comment by madsnedergaard** [comment]
Seems like the data on the app is just fine, so closing this again - sorry for keeping you hanging for 3 years 😅
