### ISSUE TITLE
Data for IN-DL (India)

### ISSUE THREAD

**Issue by Manu1400** [electricitymaps/electricitymaps-contrib#3270]
### now
Zone [IN-DL](https://www.electricitymap.org/zone/IN-DL) have some realtime data 👍  from two webpages : 
* [DELHI POWER SUMMARY](http://www.delhisldc.org/Redirect.aspx?Loc=0804)
* [homepage](http://www.delhisldc.org/)

### my proposal
Get (too) realtime value from [SCADA Load for DATE_SELECTED](http://www.delhisldc.org/Loaddata.aspx?mode=03/08/2021)

TIMESLOT | DELHI | BRPL | BYPL | NDPL | NDMC | MES
-- | -- | -- | -- | -- | -- | --
00:00 | 4668.040 | 1992.510 | 1061.280 | 1372.610 | 171.820 | 26.300
03:55 | 3798.830 | 1627.960 | 845.240 | 1118.710 | 147.670 | 23.920

=> `3798.830` MW => good precision for this live data 👍

**Comment by pierresegonne** [comment]
Hi @Manu1400,

Thanks for your proposal, 

It's a nice find! To integrate this source as a parser, we would need a better breakdown of the total production/consumption by production mode. From past experience I think one could do that from http://www.delhisldc.org/Redirect.aspx?Loc=0804 by matching the different power plants with their production modes. For example, quickly looking at the 2nd substation under grid loadings led me to http://ipgcl-ppcl.gov.in/newprojects.htm which explains that "bamnauli" is a gas powered plant. 

The difficulty then comes from the duality between the state and central grid. The central grid is basically linked to an entire region, handles inter-region exchanges and supply electricity to state grids to compensate for the difference between production and consumption. 

You can see a chart detailing the functioning of the Indian power grid here: https://docs.google.com/drawings/d/1AiYBapHk5aY8Kds5GAwDqmCeHANLQzr0FnRF59En6Ww/edit?usp=sharing

Let us know if you feel confident going forward with this or need some assistance :)

**Comment by VIKTORVAV99** [comment]
Closing this as we have no longer use the old India zones.
