### ISSUE TITLE
Memory leak(s) in ElectricityMap

### ISSUE THREAD

**Issue by Manu1400** [electricitymaps/electricitymaps-contrib#3285]
### To reproduce this issue
* Open a tab in Google Chrome [without an ad-blocker]
* Open any zone in ElectricityMap
* Wait some hours

# Expected
memory : 100 Mo

# issue
memory : 1+ Go (per tab with ElectricityMap) => huge memory leak in ElectricityMap

# hashtag (Github label)
* bug

**Comment by CloCkWeRX** [comment]
![image](https://user-images.githubusercontent.com/365751/135814293-1ca7b1d3-ea31-4241-93c0-7d93a9d61226.png)

Unfortunately, things keep crashing when I try to profile them.

**Comment by skovhus** [comment]
@CloCkWeRX thanks for trying to profile this. Which Browser did you use?

**Comment by VIKTORVAV99** [comment]
I ran profiling for about 2.5 hour and it indicates the issue has been fixed. The app is hovering at around 50 to 60 mb of memory usage when just looking at the map and around 60 to 70 mb of memory usage when the side panel is open. There where some monetary spikes to 100 mb or so when fetching new data but then it fell down to normal levels withing a minute or two.
