### ISSUE TITLE
Black bar at the bottom of page when using solar layer

### ISSUE THREAD

**Issue by piotrek124-1** [electricitymaps/electricitymaps-contrib#3327]
When using full screen there is bar in the bottom of page. (Tested with Firefox and Chrome)

With full screen:
![obraz](https://user-images.githubusercontent.com/66417442/130329229-88e1d989-2152-42d1-9a7a-f0a1d54322dc.png)
Without full screen:
![obraz](https://user-images.githubusercontent.com/66417442/130329231-b08e518f-b027-454f-8fc6-0265a1ab4801.png)

**Comment by jarek** [comment]
I get the black bar whenever solar layer is on, regardless of fullscreen status, in Firefox 90.0.2 / Ubuntu

![bar](https://user-images.githubusercontent.com/47415/130337326-36c5e9f7-3f23-4eb8-a532-69fbc187932b.png)

**Comment by piotrek124-1** [comment]
I also get the black bar even without full screen when using a different resolution than 1920x1080.

**Comment by madsnedergaard** [comment]
This has been fixed as far as I can tell, can't reproduce it anymore :)
