### ISSUE TITLE
Remove deprecated US zones

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#3358]
### Description

Some of the US zones we have are deprecated by EIA.

List:

- https://github.com/tmrowco/electricitymap-contrib/issues/3345
- https://github.com/tmrowco/electricitymap-contrib/issues/3344
- https://github.com/tmrowco/electricitymap-contrib/issues/3343
- https://github.com/tmrowco/electricitymap-contrib/issues/3342

**Comment by KabelWlan** [comment]
The zone US-MIDW-GLHB retired their last coal power plant at the beginning of September 2022 which means that this zone can be removed as well.
