### ISSUE TITLE
German - Poland Border Flows

### ISSUE THREAD

**Issue by davidedickjr** [electricitymaps/electricitymaps-contrib#3378]
Triple chevron indicator shows electricity outflows from Poland to Germany (accurate), but when I drag the cursor across the chevrons the data box indicates inflows.

**Comment by gwpicard** [comment]
Hi @davidedickjr - thanks for opening this issue! Would you be able to add screenshots or some more information so that we can get a better sense of what's going on?

**Comment by VIKTORVAV99** [comment]
Closing this as there has been no update for a year and I can't replicate it locally.
