### ISSUE TITLE
True Dark-Mode

### ISSUE THREAD

**Issue by Bohne13** [electricitymaps/electricitymaps-contrib#3389]
most Apps and a lot of websites are nowerdays able to show in "dark mode"
would be nice to see not only the map in a dark mode, but also the informationpanel, etc.

**Comment by piotrek124-1** [comment]
Agree with that. There is already branch for it if someone would like to contribute: https://github.com/tmrowco/electricitymap-contrib/tree/mn/dark-mode 
And also discussion: https://github.com/tmrowco/electricitymap-contrib/discussions/3325#discussioncomment-1231997

**Comment by VIKTORVAV99** [comment]
We now have dark mode in the web app and mobile apps, it currently follows device preferences but we plan on implementing a feature in the future that allows the user to control this behavior.
