### ISSUE TITLE
La Réunion (RE) 🇫🇷 : support `turbines_a_combustion` production

### ISSUE THREAD

**Issue by Manu1400** [electricitymaps/electricitymaps-contrib#3427]
* Zone: https://app.electricitymap.org/zone/RE
* Parser: https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/FR_O.py

Add support field `turbines_a_combustion`
> Production de la filière turbines à combustion fioul en MW

dataset : https://opendata-reunion.edf.fr/explore/dataset/prod-electricite-temps-reel/information/

ping @PETILLON-Sebastien

**Comment by edouardkleinhans** [comment]
Any news on this ?

**Comment by VIKTORVAV99** [comment]
This will be included in the parser rewrite in #4742.
