### ISSUE TITLE
Fetch API cannot load file:///clientVersion due to access control checks.

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#3573]
Error seen on the mobile app:

`Fetch API cannot load file:///clientVersion due to access control checks.`

See https://github.com/tmrowco/electricitymap-contrib/blob/master/web/src/layout/main.js#L75-L82

**Comment by VIKTORVAV99** [comment]
I can no longer reproduce this and seeing as we rebuilt the whole app and frontend in the rewrite I think we can consider this resolved for now. But if it shows up again don't hesitate to reopen this issue.
