### ISSUE TITLE
DK coal/biomass discrepancy between energinet and ENTSOE

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#3602]
It has been brought to our attention (on [twitter](https://twitter.com/SSjessing/status/1453696194446757894)) that the data from ENTSOE might be different from what is published by energinet (even though ENTSOE data come from energinet in the first place).
This seems to provide some discrepancies on biomass / coal.
Help would be appreciated here!

**Comment by SorenJessing** [comment]
@corradio this has been pointed out before. Your final comment was:

["yay! This probably means we should rescrap the entirety of our Danish data, now that some power plants are categorised differently."](https://github.com/electricityMap/electricitymap-contrib/issues/1161#issuecomment-450382998)

What happened afterwards?

**Comment by corradio** [comment]
@mathilde-daugy is this being addressed as part of our efforts on regional emission factors? Thanks in advance for the clarification.

**Comment by mathilde-daugy** [comment]
> @mathilde-daugy is this being addressed as part of our efforts on regional emission factors? Thanks in advance for the clarification.

Yes, thank you for flagging this. I'm currently looking at the generation per unit data we have extracted for 2021 and it looks like some plants are labeled with the wrong fuels (the plant highlighted below should be biomass and not coal).  This will be taken into consideration for the calculation of regional emission factors. 
![image](https://user-images.githubusercontent.com/107848894/198972391-44aee60b-a346-4d42-9da2-55bea0f12d23.png)

I don't know why there are such big discrepancies for hard coal and oil capacities. For oil, there is only one power plant in DK with oil as a main fuel and it has  a capacity of 520MW so the ENTSO-E 1 GW seems unlikely. Regarding the high hard coal capacity, I suspect that there is some double-counting as most biomass plants were converted from coal but this is just a hypothesis.

**Comment by jenshoej** [comment]
The capacity data for Solar in Denmark is very outdated. The newest account by the Danish Energy Agency states 3.645 GW solar, whereas the ENTSO-E data is 2.3 GW

The report can be found here: https://energinet.dk/om-publikationer/publikationer/redegorelse-for-elforsyningssikkerhed-2023/

**Comment by corradio** [comment]
@madsnedergaard can this be closed given your recent work on emission factors?
