### ISSUE TITLE
Solar layer rendering incorrect in half screen when zoomed in/out

### ISSUE THREAD

**Issue by bhalbert** [electricitymaps/electricitymaps-contrib#3688]
![image](https://user-images.githubusercontent.com/6343690/150141301-707eb4a6-fc68-4332-b93c-857fc7a5f597.png)

Browser: Firefox 96.0.1
Display: 1920x1080

Minor UI issue where if the browser is taking up half the screen and the browsers zoom level is not 100% then the solar layer gets distorted

**Comment by madsnedergaard** [comment]
Thanks for raising this! There's definitely some problems with the solar layer that we haven't had time to prioritise, so we'd love some help to fix these problems :)

Related issues:
#3327, #3217

**Comment by bhalbert** [comment]
@madsnedergaard Is there guidance on getting the wind and solar potential layers working in the dev environment? Looks to me that the static state file only contains the country consumption statistics so a logical first step for me helping with this would be to get solar and wind layers for dev

**Comment by madsnedergaard** [comment]
I just checked and unfortunately it hasn't been set up - it should be fairly straightforward to copy the weather files used by the production app to a `mockserver/public/v3/gfs` folder, but I'm not sure if more work needs to be done afterwards :)

**Comment by madsnedergaard** [comment]
Can't reproduce any longer, so seems like it has been fixed :)
