### ISSUE TITLE
Get AR.py working again - use other data sources

### ISSUE THREAD

**Issue by alixunderplatz** [electricitymaps/electricitymaps-contrib#3699]
Hi folks,

seems like our old AR.py parser for Argentina isn't working anymore.
However, there is an option to get the data back running, with more granularity than ever and to simplify the parser in the same run. No more need for detailed plant mappings.

[As I mentioned about 1 year ago in this comment](https://github.com/electricitymap/electricitymap-contrib/issues/2378#issuecomment-751355231), there are 2 websites that can be used to get the total generation mix and the renewable mix.
From this general website, we can get nuclear, large hydro, and thermal (mostly gas, very little oil and even less coal, so we'll put this to the "unknown" category or entirely to "gas"). 
Discard "renewables", as we will get the mix from the second source.
https://microfe.cammesa.com/demandaregionchart/#/operaciones
From the renewable website, we can get small hydro, biomass, solar and wind.
Adding both in a new parser should do the job.

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/25743609/150689478-4035f612-4904-4c06-8b2c-9b216b69b6a8.png">

Renewables:
https://cdsrenovables.cammesa.com/renovableschart/#/totalesLineAndPie

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/25743609/150689502-77eb97df-69f5-465d-ab78-5a3921709080.png">

Regarding fixing the exchanges with its neighbouring zones, I'd neglect this for the moment, until we have the data back on the map. Let's come back to that at a later point.
See the other two open AR-related issues #2378 for what else we could implement for AR and its national control areas and #565 for an older general issue with some more insights on the grid topology.

**Comment by alixunderplatz** [comment]
@aemartinez @madsnedergaard happy to see Argentina back on the map! :) The data looks great in the chart!
Fetching the exports/imports with Chile, Paraguay, Uruguay and Brasil will be the next step to implement, then rewriting will be done 👍 I'll take a look at the data sources this weekend, will keep you updated ;)

![grafik](https://user-images.githubusercontent.com/25743609/153183969-06a5b841-8a8e-4778-9eaf-c8cdfbaf3177.png)

**Comment by alixunderplatz** [comment]
hm, fetching the data doesn't seem to work since yesterday:
![grafik](https://user-images.githubusercontent.com/25743609/153354777-31516026-8296-4320-9031-1ae53ebf83d7.png)

**Comment by madsnedergaard** [comment]
https://storage.googleapis.com/electricitymap-parser-logs/AR.html

<img width="1243" alt="Screenshot 2022-02-10 at 13 06 33" src="https://user-images.githubusercontent.com/3296643/153405642-7b640dd5-8281-4219-8bdb-24c6226bd804.png">

**Comment by aemartinez** [comment]
Could this be a deployment issue? The logs seem to be referring to older code before the last PR was merged.

[Here](https://github.com/electricitymap/electricitymap-contrib/blob/86ad87a07e6b1ba38ebf697f9a4710dbc5688754/parsers/AR.py#L873) is line 873 of AR.py right before the new version committed. On that older version that line of code is `gdt = get_datetime(session=None)` as the log shows.

**Comment by q--** [comment]
Do we need a separate issue for adding back the interconnections (also on https://cammesaweb.cammesa.com/), or keep this one open>
