### ISSUE TITLE
[IN-PB] Add price for Punjab 🇮🇳 

### ISSUE THREAD

**Issue by Manu1400** [electricitymaps/electricitymaps-contrib#3713]
15-minutes data is available in page https://www.iexindia.com/MarketData/AreaPrice.aspx?Area=N3 for Punjab

### Description
* N3 = Punjab (source: https://www.iexindia.com/maps.aspx )

**Comment by ykabusalah** [comment]
Can I try adding/working on this?

**Comment by madsnedergaard** [comment]
Yes, that would be awesome! 💪

**Comment by madsnedergaard** [comment]
We now use different regions, so closing this
