### ISSUE TITLE
Add visuals for Panama interconnections onto the map

### ISSUE THREAD

**Issue by r24mille** [electricitymaps/electricitymaps-contrib#3717]
#3630 added exchanges to the Panama (PA) parser. However, I think there's some additional front-end work required to get different exchanges and arrows visualized on the map.

https://app.electricitymap.org/zone/PA

We should get this data visualized!

**Comment by VIKTORVAV99** [comment]
I have some doubts about this data, I find it quite hard to believe there is a direct interconnection between Guatemala and Panama.

The electricity is probably passing through Honduras, Nicaragua and Costa Rica to get there. Assuming there is not a dedicated power line through all these countries the exchange volume should be added to the CR->PA exchange.

But then we also need to add the previous exchanges between Guatemala, and Honduras to Costa Rica to the CR->NI exchange and so forth, then it a much bigger undertaking than just adding the exchanges to the map.
