### ISSUE TITLE
Estimate production for Belgium is off. 

### ISSUE THREAD

**Issue by Fred-3000** [electricitymaps/electricitymaps-contrib#3793]
The new estimations produce some strange results for Belgium. The estimation methodology is not added to the wiki yet, so I don't have a clue what causes this. 
A small amount of coal production is reported, but Belgium doesn't have any coal capacity.
Additionally, 5% of production is said to be unknown while Elia (TSO) doesn't report data from unknown sources anymore. 

<img width="697" alt="Schermafbeelding 2022-02-11 om 13 27 59" src="https://user-images.githubusercontent.com/64587657/153591982-45ad0cac-a992-443b-aa58-ad889a23104c.png">

**Comment by VIKTORVAV99** [comment]
Closing this as it no longer seem to be an issue and the reported values for coal and unknown is both 0 (0 and Null respectively) with the estimated data.
