### ISSUE TITLE
Review odd German zone-names of US-zones

### ISSUE THREAD

**Issue by alixunderplatz** [electricitymaps/electricitymaps-contrib#3811]
Hi all,
the translation of most of the US-zone names is very odd in German, seems like it was translated automatically? They should remain being named in English.

my favourites:
![grafik](https://user-images.githubusercontent.com/25743609/154788844-7dc6e33f-0658-421f-8e06-89c9bd046a4e.png)

![grafik](https://user-images.githubusercontent.com/25743609/154788858-8dbeecc2-355c-4f8e-8454-446f4e7eb4b1.png)

![grafik](https://user-images.githubusercontent.com/25743609/154788881-eaaee42c-34e4-439e-9bc8-a9fcfecaef6d.png)

**Comment by jarek** [comment]
They're not much better in English :rofl: 

Looks like the German translations come from https://github.com/electricitymap/electricitymap-contrib/pull/2785

**Comment by madsnedergaard** [comment]
Google Translate at least returns the actual English names in use, so you're probably right:
<img width="1312" alt="Screenshot 2022-02-22 at 11 46 08" src="https://user-images.githubusercontent.com/3296643/155116778-c57f9afa-bee1-4c15-b344-e0ab1b15f95c.png">

We'd happily approve of a PR that uses the English names here if that makes more sense - my German skills are not good enough to know what's best practice for something like this 😄

**Comment by alixunderplatz** [comment]
@madsnedergaard Fine, I'll take care of this on my way to Copenhagen in March ;)
