### ISSUE TITLE
NL: overestimation and underestimation of nuclear

### ISSUE THREAD

**Issue by KabelWlan** [electricitymaps/electricitymaps-contrib#3906]
In #3821 I mentioned an overestimation of wind generation. I haven't seen that happen anymore, it wasn't very windy in the last weeks anyway. However, I noticed that nuclear generation is overestimated and underestimated. It exeeds the capacity in peak usage time and during the day, when solar generation is high, nuclear generation is reduced.

![Unbenannt](https://user-images.githubusercontent.com/49598085/159931557-9189441a-e952-4dd7-b7b7-c126cfe40f2a.png)

I don't know how trustworthy [Entsoe data on Energy-Charts](https://www.energy-charts.info/charts/power/chart.htm?c=NL&stacking=stacked_absolute_area&l=de) (they use Entsoe data, the website just looks nicer) for the Netherlands is but they show a constant nuclear generation. Energy-Charts also reports more and steadier coal generation and than the estimation model does.

**Comment by Kongkille** [comment]
CC @pierresegonne

**Comment by VIKTORVAV99** [comment]
I can't see this issue anymore so I'm going to close it as fixed. If you see it happening again please do comment here so we can reopen the issue.
