### ISSUE TITLE
Replace co2eq parameters .js test to python test for config files

### ISSUE THREAD

**Issue by pierresegonne** [electricitymaps/electricitymaps-contrib#3927]
## Description

Currently, the co2eq parameters are being tested by [co2eq_parameters.test.js](https://github.com/electricitymap/electricitymap-contrib/blob/master/config/co2eq_parameters.test.js). In order to improve consistency of the codebase, it would be nice to port these tests in python and remove the js code.

**Comment by kruschk** [comment]
I could use some practical experience with unit testing; could I take a shot at this?

**Comment by pierresegonne** [comment]
Of course!

**Comment by kruschk** [comment]
I've almost got a PR ready! I had to invoke a sketchy regex to extract the `modeOrder` array from [constants.js](https://github.com/electricitymap/electricitymap-contrib/blob/master/web/src/helpers/constants.js), but I think it should work well enough. Should the [co2eq_parameters_direct.json](https://github.com/electricitymap/electricitymap-contrib/blob/master/config/co2eq_parameters_direct.json) file be included in the tests as well? At the moment, only [co2eq_parameters_all.json](https://github.com/electricitymap/electricitymap-contrib/blob/master/config/co2eq_parameters_all.json) and [co2eq_parameters_lifecycle.json](https://github.com/electricitymap/electricitymap-contrib/blob/master/config/co2eq_parameters_lifecycle.json) are included.

**Comment by pierresegonne** [comment]
Super!
Yes if you can, please do it :)

**Comment by kruschk** [comment]
I noticed the [co2eq_parameters_direct.json](https://github.com/electricitymap/electricitymap-contrib/blob/master/config/co2eq_parameters_direct.json) and [co2eq_parameters_lifecycle.json](https://github.com/electricitymap/electricitymap-contrib/blob/master/config/co2eq_parameters_lifecycle.json) files are similar enough that if they are combined into one object (similarly to the current approach), whichever comes second will clobber some of the keys in the first. This could easily lead to a situation where all tests pass even though one of the files isn't really valid. I think that a more robust approach would be to test each of the three files separately, applying only the relevant tests from the original test suite to each. Does this sound reasonable?

**Comment by pierresegonne** [comment]
Yes indeed. I think you can separate the tests for each file as they each represent different information. For the distinction lifecycle VS direct, you can probably write a single test that can be executed independently on either file :)

**Comment by CorentinBrtx** [comment]
Hi, looks like this issue can be closed ?

**Comment by VIKTORVAV99** [comment]
Looks like it can! Thanks for doing some housekeeping in the repository for us.

There are still some work to be done in the tests but that is unrelated to this issue.
