### ISSUE TITLE
[feature in development] Historical view 🗺️ 🔨

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#3938]
<div align="center">
<img width="589" alt="Historical View" src="https://user-images.githubusercontent.com/3296643/161724357-4c085909-0816-407e-8cf0-76267ac7fd18.png">
</div>

### Description

**tl;dr: It's finally time to show historical data!**

You (and we) have been asking for it since the dawn of electricityMap, and now is the time to take the map to a whole new level by looking further into the past.

Thanks to all the amazing contributions over time(!) from so many amazing people(!), we have the data available and we have decided to make it publicly available in the name of the climate 🌱 

With this new feature users will be able to not only see the real-time/recent status of the grid, but also...
- deep-dive into the evolution of the grid
- uncover patterns
- compare zones and countries over time
- have more data-driven discussions

### Current status

We are currently shaping the feature, looking into required data structure changes and have started early design prototyping.

We hope you’ll help test this new feature and provide feedback when we have the early prototypes ready to be shared :)

**Comment by steren** [comment]
My use case for historical view is to be able to determine, for a given location, the time of the day with the lowest carbon intensity based on a monthly or yearly average

**Comment by madsnedergaard** [comment]
Oh hey, we forgot to share that the first prototype is actually live now: https://app.electricitymap.org/?feature=history 😄 
It's currently only showing hourly and only working on desktop, but any feedback is very welcome! 💚

**Comment by VIKTORVAV99** [comment]
> Oh hey, we forgot to share that the first prototype is actually live now: https://app.electricitymap.org/?feature=history 😄 It's currently only showing hourly and only working on desktop, but any feedback is very welcome! 💚

Very cool! 🎉
Just one thing I spotted right away that can be problematic, all the exchange arrows are gone. 🙈

**Comment by Kongkille** [comment]
> > Oh hey, we forgot to share that the first prototype is actually live now: https://app.electricitymap.org/?feature=history 😄 It's currently only showing hourly and only working on desktop, but any feedback is very welcome! 💚
> 
> Very cool! 🎉 Just one thing I spotted right away that can be problematic, all the exchange arrows are gone. 🙈

That's true! This initial version will be launched without exchange arrows, as we haven't quite gotten the data ready yet :D

**Comment by VIKTORVAV99** [comment]
> > > Oh hey, we forgot to share that the first prototype is actually live now: https://app.electricitymap.org/?feature=history 😄 It's currently only showing hourly and only working on desktop, but any feedback is very welcome! 💚
> > 
> > 
> > Very cool! 🎉 Just one thing I spotted right away that can be problematic, all the exchange arrows are gone. 🙈
> 
> That's true! This initial version will be launched without exchange arrows, as we haven't quite gotten the data ready yet :D

No need to worry just yet then!

**Comment by madsnedergaard** [comment]
_Hi all, time for an update!_ 

We've been hard at work at full speed on this new feature, and we're **very close to being ready to release it**!

Keeping up with the feature-flag turned out to be too difficult as we've done a lot of changes behind the scene, so we're instead continuing work on our staging site: https://staging.electricitymap.org/ 

Thanks for all the great feedback we've received so far, it's been super helpful! 🙇 

<img width="989" alt="Screenshot 2022-06-30 at 12 46 13" src="https://user-images.githubusercontent.com/3296643/176659441-7c1d8e6e-79df-472d-ba32-0d13a6ab2090.png">

**Comment by VIKTORVAV99** [comment]
> _Hi all, time for an update!_
> 
> We've been hard at work at full speed on this new feature, and we're **very close to being ready to release it**!
> 
> Keeping up with the feature-flag turned out to be too difficult as we've done a lot of changes behind the scene, so we're instead continuing work on our staging site: https://staging.electricitymap.org/
> 
> Thanks for all the great feedback we've received so far, it's been super helpful! 🙇

Looking great visually!
A few things I noticed right away:
* You can't hover on the first value in the graphs (jumps to last value if you try).
* On the history views we need to make it clear the current production/consumption is a hourly average or switch to GWh or kWh as the unit.
* There seem to be no way to navigate between `/ranking` and `/map` on mobile.

I'll poke it some more later and see if I find anything else.

Great work from all of the team!

**Comment by VIKTORVAV99** [comment]
> @madsnedergaard Thanks to all the people working in historical data. Do you see a possibility to integrate historical data of El Hierro? the source is: https://demanda.ree.es/visiona/canarias/el_hierro5m/tablas//yyyy-mm-dd/2 example with diesel only: https://demanda.ree.es/visiona/canarias/el_hierro5m/tablas/2013-05-03/2 example with first day with wind/water: https://demanda.ree.es/visiona/canarias/el_hierro5m/tablas/2014-07-21/2
> 
> It would be really show the change coming with Gorona de Viento -GDV- Thank you for checking.

I recently updated the parser that is used for El Hierro to be able to parse historical data so I think all that's needed is for the backend to fetch the historical data. @Kongkille please let me know if I need to add something like `@refetch frequency` for this to function properly. (I forgot it when I merged the ES parsers.)

**Comment by Kongkille** [comment]
@strassburger @VIKTORVAV99 yes it looks like it is sort of working right now. There are no daily aggregates just yet but the 12 month view has some data. I can try to look into why there's no daily aggregates yet.

![image](https://user-images.githubusercontent.com/45588799/179564975-b49ad4ad-7a81-4046-81bf-ce0b54cf03fa.png)

**Comment by strassburger** [comment]
@Kongkille
Thanks for checking El Hierro Data.
I can see now that 24 hours and 12 month.
30 days and 5 years are missing data.

**Comment by pierresegonne** [comment]
Weird behaviour were data does not load for some zones: https://we.tl/t-xQo9hORDTF

**Comment by Kongkille** [comment]
> Weird behaviour were data does not load for some zones: https://we.tl/t-xQo9hORDTF

Talked IRL adding some notes here for those following the issue

1. We've had some issues with the backend of the app causing slower load times. This should be mainly resolved now, but will keep looking into this
2. UI issue with ZA is caused by a change in the way we handle config. See more here #4376

**Comment by magol** [comment]
The FAQ must be updated. It now say

> Can I see the history for an area further back in time than 24 hours?
> You can purchase access to all of our historical data through our [database](https://electricitymap.org/?utm_source=app.electricitymap.org&utm_medium=referral).

**Comment by madsnedergaard** [comment]
I think we can consider this closed now, huge thanks to everyone that helped make it happen!! 👏 👏 👏
