### ISSUE TITLE
California production differs from real time data

### ISSUE THREAD

**Issue by Bauer33333** [electricitymaps/electricitymaps-contrib#3954]
https://www.caiso.com/TodaysOutlook/Pages/supply.aspx reports different productions than the map. Eg. for wind yesterdays and todays production was always around 5000MW, but the map only showed around 3GW, so about half that. Something seems to be off with the estimation. Why is there even an estimation while real time data is available?

There are also real time electricity prices for California available: http://oasis.caiso.com/oasisapi/prc_hub_lmp/PRC_HUB_LMP.html

**Comment by jarek** [comment]
We do have a CAISO parser https://github.com/electricitymap/electricitymap-contrib/blob/master/parsers/US_CA.py but Electricity Map currently uses EIA data for CAISO: https://github.com/electricitymap/electricitymap-contrib/blob/5cd62e2aa35c843df9acefe42ace250e743dd120/config/zones.json#L6015

**Comment by Bauer33333** [comment]
The map seems to use the CAISO parser now, there are no more estimations and therefore no issues anymore.

Should I open a seperate issue for the price data? If yes I guess this could be closed
