### ISSUE TITLE
Divide East Malaysia into 2 separate grid (Sarawak and Sabah-Labuan)

### ISSUE THREAD

**Issue by PPsyrius** [electricitymaps/electricitymaps-contrib#4035]
I've found this out by chance while looking for TH's data in https://github.com/electricitymap/electricitymap-contrib/pull/4002

Seems like the two grids in East Malaysia are run independently by [SESCO](https://en.wikipedia.org/wiki/Sarawak_Energy) in Sarawak and [SESB](https://en.wikipedia.org/wiki/Sabah_Electricity) in Sabah and Labuan.

[SESCO have a deal to supply electricity from Sarawak to West Kalimantan to Indonesia since 2016](https://www.sarawakenergy.com/what-we-do/beyond-sarawak) at around 190-200MW

Similarly, [SESB also planned to start importing electricity from SESCO grid](https://www.sarawakenergy.com/what-we-do/beyond-sarawak), starting from 2023 onwards initially with 30-50MW (from the designed cap of 300MW) 

Thus, I propose to separate the existing `MY-EM` (East Malaysia) into `MY-SWK` (Sarawak) and `MY-SBH` (Sabah - Labuan), even though we currently lack any usable source of parsers for these zones.

**Comment by jaretkadlec** [comment]
Hey team,
Are you all still looking for someone to jump onto this issue? If so I would love to try and tackle this. Let me know!

**Comment by userdend** [comment]
Hello, I live in Sabah, let me know what I can help! :D

**Comment by PPsyrius** [comment]
@userdend please do so 👀

**Comment by madsnedergaard** [comment]
We have made data models based on available data, and this did not allow us to separate the region further. Closing this again for now :)
