### ISSUE TITLE
EIA timestamp convention

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#4052]
The EIA documentation [stipulates](https://www.eia.gov/electricity/gridmonitor/about):
> TIME REPORTING
> BAs report all data as hourly integrated values, meaning they are time-weighted hourly averaged values. Hourly data are published using the hour ending time reporting convention. For example, the data for the hour ending 1:00 a.m. on August 1, 2019, is reported with a timestamp of August 1, 2019, 1:00 a.m.

This means the timestamp given by EIA represents the *end* of the time interval. electricityMap using another convention, where the timestamp represents the *beginning* of the interval.

From what I can see, our EIA parser simply takes the timestamp returned by `eiapy`. @systemcatch did you encounter that issue? Is there something we should change on our end?

**Comment by systemcatch** [comment]
Hey @corradio I didn't really find it an issue as `eiapy` is only a wrapper for the API.

Do the timestamp values simply need to be shifted back an hour?

**Comment by corradio** [comment]
I'm not 100% sure but it would be wise to investigate. I'll cc @pierresegonne from our side so he's aware of the potential issue.

**Comment by pierresegonne** [comment]
Hmm interesting, I'll flag this on our side to check.
An easy check would be to use solar production - we know when the sun rises so we should be able to tell whether the hours are shifted or not.

**Comment by VIKTORVAV99** [comment]
Are the timestamps the same between EIA APIv1 and EIA APIv2 or does #4464 fix this issue?

If #4464 does not solve this should this be addressed in that PR or separately?

**Comment by pierresegonne** [comment]
Good question - I'll ask in the other issue

**Comment by pierresegonne** [comment]
**Actually we've ran an internal investigation on this topic - and indeed we're using the wrong convention!**

Some elements from the investigation:

The EIA [documentation](https://www.eia.gov/electricity/gridmonitor/about) reports that their data is published using the ending hour time reporting convention. On the contrary, Electricity Maps uses the beginning hour convention:

Ending hour convention: The data represented is the average of the previous hour
Starting hour convention : The data represented is the average of the following hour

<img width="487" alt="Screenshot 2022-09-01 at 11 25 36" src="https://user-images.githubusercontent.com/32778266/187880617-c79b4873-f1b9-4d34-946b-598d79f4e79b.png">

One way to determine which convention the data is following, is to compare it with the actual solar rise. Given the following example:
<img width="462" alt="Screenshot 2022-09-01 at 11 26 05" src="https://user-images.githubusercontent.com/32778266/187880701-03a8d97f-75e5-4eae-bfc2-e2e27a5ddfb2.png">

If the data follows the beginning hour convention, PV production will be greater than 0 at the hour timestamp where the sunrise happens.
If the data follows the ending hour convention, the PV production will be greater than 0 one timestamp after the sunrise happens.

Two zones have been chosen for testing the data, US-CAL-BANC (Balancing Authority Of Northern California)  and US-FLA-FPL(Florida Power & Light Company).


| Zone        | Date                  | Sunrise     | PV production start |
|-------------|-----------------------|-------------|---------------------|
| US-CAL-BANC | 10 - 12 August 2021   | 6:21 - 6:22 | 7:00                |
| US-CAL-BANC | 10 - 12 December 2021 | 7:14 - 7:15 | 8:00                |
| US-FLA-FPL  | 06 - 08 January 2022  | 7:08 - 7:08 | 8:00                |
| US-FLA-FPL  | 10  - 12 June 2022    | 6:36 - 6:37 | 8:00                |
