### ISSUE TITLE
Replace outdated animation libraries

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#4143]
We're using two animation libraries. They are both outdated and blocks updating to react@18.
Maybe consider using [react-spring](https://react-spring.io/) which is more popular and frequently updated?

---

**[react-motion](https://github.com/chenglou/react-motion)**
It hasn't been updated since 2017 and it's blocking for updating to react@17.

It's only used for `<CircularGauge />`, so it shouldn't be hard - would be nice to keep the animation with another library (or maybe styled-components is enough?), but might also be fine to just remove the animation entirely at first :)

**[react-transition-group](https://github.com/reactjs/react-transition-group)**
It's not working with react@18 according to [this issue](https://github.com/reactjs/react-transition-group/issues/816).

Only used for CSSTransition, maybe we can just use styled-components functionality for this?

**Comment by VIKTORVAV99** [comment]
PR #4168 should take care of react-motion. 🙂

**Comment by VIKTORVAV99** [comment]
Since we changed the whole graphing stack in the refractor we can consider this one closed.
