### ISSUE TITLE
[a11y] Work without JavaScript, and with screen readers

### ISSUE THREAD

**Issue by Tjoppen** [electricitymaps/electricitymaps-contrib#4149]
Currently if a user visits the site with JS disabled then they are greeted with a white screen, even if they have CSS disabled. This makes using the site with a screen reader nearly impossible. Render the HTML serverside instead, delivering updates via JS for clients that have it enabled. ```<meta>``` refresh could be used to enable JS-free refresh.

This is also one of the times where a ```<table>``` is appropriate for blind users, each country having their own row. Use rowspan to deal with multiple regions in one country.

**Comment by VIKTORVAV99** [comment]
Some of these concerns are definitely valid and should be looked at as soon as possible but I believe making the map/application work with JS disabled and using server-side rendering is outside the scope of what is possible, it would require big changes in both code and infrastructure. Not even Google let's you use Google Maps with JS disabled.

We should probably add a fallback message telling users that JavaScript is required if they have it disabled though.

**Comment by madsnedergaard** [comment]
Closing this as it's not something we can do at the moment. Thanks for the JS fallback message which at least makes it clear to users :)
