### ISSUE TITLE
[RFC] Use UN Life Cycle Assessment of Electricity Generation Options gCO2-eq/kWh values for EU28.

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#4161]
## Consider using the UN Life Cycle Assessment of Electricity Generation Options reports gCO2-eq/kWh values for EU28

The UN has published a report that contains LCAs for several modes of electricity production with specific values for EU28, I would propose we use these values for EU28 countries (current EU countries + UK) as an interim solution until #738 is finalized.

Link to the report: https://unece.org/sites/default/files/2021-10/LCA-2.pdf

Table with current value and the proposed UN value we should use:
| PER KWH     | Type                                   | Current | UN EU28 value                    |
|-------------|----------------------------------------|---------|----------------------------------|
| Hard Coal   | PC, without CSS                        | 820     | 1000 (highest coal value)        |
| Natural Gas | NGCC, without CCS                      | 490     | 430 (highest gas value)          |
| Hydro       | 660 MW                                 | 24      | 150                              |
| Hydro       | 360 MW                                 | 24      | 11                               |
| Nuclear     | average                                | 12      | 5.1                              |
| Solar       | poly-Si, ground-mounted / roof-mounted | 45      | 37 (highest photovoltaic value)  |
| Wind        | onshore                                | 11      | 12                               |

Full details of UN EU28 values on page 74 of the report (PDF page 84)

I realize hydro is probably not an option to implement but the others should be pretty straight forward, especially Gas, Nuclear, Solar and Wind.

**Comment by q--** [comment]
If the highest possible value from the report is lower than the IPPC 2014 average ElectricityMap is using now, it makes sense to use the lower value. However, if the value from the report is higher we probably shouldn't switch. After all, we don't know if a plant is using Pulverized Coal technology (the worst option, worse than current coal carbon intensity value) or Supercritical (the best option, lower than current coal carbon intensity value)

**Comment by VIKTORVAV99** [comment]
> If the highest possible value from the report is lower than the IPPC 2014 average ElectricityMap is using now, it makes sense to use the lower value. However, if the value from the report is higher we probably shouldn't switch. After all, we don't know if a plant is using Pulverized Coal technology (the worst option, worse than current coal carbon intensity value) or Supercritical (the best option, lower than current coal carbon intensity value)

Makes sense, that would mean just the values for Gas, Nuclear and Solar.

But what do you think of the switch for wind? Everyone would be using the same "type" there (electricityMap don't split out offshore yet) so should the higher value be used there or do you think we should still use the lower.

As a side note: We could also use the UN values for local overrides for coal/gas if the production mode is known, this is already being done for Estonia (with EASAC 2007 values for fossil oil shale) so there is a precedent for it.

**Comment by VIKTORVAV99** [comment]
Just realized we use the Pulverized Coal values from IPCC currently so it would make sense to also use the UN values for PC as well when we don't know the exact coal source.

**Comment by VIKTORVAV99** [comment]
@pierresegonne you seem to be the "data guy", what do you think of this?

**Comment by pierresegonne** [comment]
Hey @VIKTORVAV99, "data guy" speaking. thanks for raising awareness around this new assessment! It is very exhaustive and is definitely a good lead for helping us update the emission factors. 

I'm not too keen on changing the factors right now. We're planning to start working on #738 in June, so I don't think the effort (notably because we would need to communicate about this change) is worth making the emission factors more up-to-date for just a few weeks. 

On top of my mind, I also see a slight challenge in adopting these emission factors. They're much more specific than ours, with e.g pulverised vs hard coal, which would force us to either take averages respective to the proportion of each technology in the world, or informed guesses by region (e.g if a country uses only hard coal).

**Comment by archie-bal** [comment]
The numbers for GHG-emissions of nuclear energy from the UN are not realistic (5-12 g/kWh CO2-eq.).
At least, they should be discussed!

For germany, there are much higher numbers assumed: 22,3 g/kWh Co2-eq.

[Study for GHG-emissions from the Umweltbundesamt](https://www.umweltbundesamt.de/sites/default/files/medien/1410/publikationen/2019-11-07_cc-37-2019_emissionsbilanz-erneuerbarer-energien_2018.pdf): 22,37 CO2-Äq. (g/kWh)
The World Information Service of Energy (WISE) is calculating [in this study with 117 g/kWh CO2-Equivalent](https://wiseinternational.org/sites/default/files/u93/climatenuclear.pdf).
You might argue, WISE is not agnostic to atomic energy, but there are other independant studies which show similar results: Stanford University Study is calculating 68-180 g/kWh [in this study](https://www.sciencedirect.com/science/article/pii/S0301421521002330).

Please use realistic and regional green-house gas emissions for nuclear energy, as the current used values which are derived from 2014 from IPCC (12 g/kWH) are not realistic.

**Comment by q--** [comment]
>, but there are other independant studies which show similar results: Stanford University Study is calculating 68-180 g/kWh [in this study](https://www.sciencedirect.com/science/article/pii/S0301421521002330).

Quote from your article:

>[Jacobson (2009)](https://www.sciencedirect.com/science/article/pii/S0301421521002330#bib31) presented life cycle analyses for different electricity generation technologies and included also so called “opportunity cost emissions”, i.e. CO2 costs due to delays from planning to operation where a faster deployable technology could have avoided emissions

Yeah, that's not going to work for ElectricityMap. "What if someone built something else - but faster?" is useless for this project's purpose, especially since most most NPPs in operation today were built when the realistic alternatives did not include not solar or wind but only fossil fuels. 

(To avoid cluttering the issue too much, I suggest opening a [discussion](https://github.com/electricitymap/electricitymap-contrib/discussions) if you want to discuss the subject further.)

**Comment by VIKTORVAV99** [comment]
> The method you suggest @VIKTORVAV99 is indeed what would need to be done: collect the mix of technologies within each category for each grid on a given year, and calculate the aggregate factors for these broad categories.

@thomasgibon this is currently how we generate static emission factors for unknown production (several mixed sources that are unknown at the time) (per year if possible). What I propose is opening up the parser for more production modes so we can generate the emission factors dynamically in real time (hourly granularity currently), so it will differ somewhat but will be the same general principle and method but it will require some backend changes.

I would also like to take the opportunity say thanks for the detailed and extensive report!
