### ISSUE TITLE
Request https://app.electricitymap.org/zone/$ZONE fails on unknown zones

### ISSUE THREAD

**Issue by pierresegonne** [electricitymaps/electricitymaps-contrib#4172]
### Description

Access to `https://app.electricitymap.org/zone/US-NW-SCL` makes the app crash. 

It seems like it also happens with any zone that should not exist. 

### Screenshot

<img width="1440" alt="Screenshot 2022-05-23 at 13 54 04" src="https://user-images.githubusercontent.com/32778266/169813661-bf21dc6e-ecdd-4eda-8d90-fb2081cd49ef.png">

### Further context

I'm not sure that the fixes from https://github.com/electricitymap/electricitymap-contrib/pull/3817 work as expected. 
If I remember correctly, this test was supposed to ~verify a 1:1 mapping between zones defined in world.json and zones.json.~ [EDIT: it actually verifies that all zones in world.json are in zones.json, not the other way around]

Here it's not the case as e.g `US-NW-SCL` still exists in `zones.json` but not in world.json

FYI @Kongkille

**Comment by VIKTORVAV99** [comment]
We should probably also handle zone keys passed in lowercase and redirect/convert them to uppercase.

It's not ever something that should ever occur with internal links but it's more than likely this will happen if someone manually enters the full URL including a zone key.

**Comment by VIKTORVAV99** [comment]
@madsnedergaard is this something we should consider closed by #4645 or is this something we should look closer at in the refractor? It would be nice to transform lowercase letters to uppercase to be more reliable when users are manually inputting the URL.

**Comment by madsnedergaard** [comment]
I think we can consider it fixed with #4645.
The upper/lower-case issue will most likely be easier to fix after the rewrite :)
