### ISSUE TITLE
Illogical exchange between Costa Rica and Nicaragua

### ISSUE THREAD

**Issue by autipial** [electricitymaps/electricitymaps-contrib#4179]
I noticed today unusual and illogical exports from Costa Rica to Nicarague (10GW+), as shown below on the screenshots.
Time on the screenshots is UTC+2.

![Screenshot_20220524_002559](https://user-images.githubusercontent.com/7460404/169915367-855f3def-82e7-4c73-80f4-5cb6a19c582a.png)
![Screenshot_20220524_002701](https://user-images.githubusercontent.com/7460404/169915392-2e42631e-72e1-4e1d-9e54-daf26e839ab3.png)

**Comment by madsnedergaard** [comment]
Yeah, I also noticed that one actually! My best guess is that there was a mistake on the data side, so let's see if it happens again.

As an alternative it seems like we could use exchange data from Costa Rica instead, but the numbers seems to differ, so let's keep an eye on the existing data first :) 
https://apps.grupoice.com/CenceWeb/data/sen/json/OperacionTiempoReal

**Comment by VIKTORVAV99** [comment]
I think we can close this issue now as it seems to have been a one off instance. It should be possible to add some sanity checks to the exchange data to flag/reject these instances internally and I'll talk to the team about it.
