### ISSUE TITLE
Update to EIA APIv2

### ISSUE THREAD

**Issue by FelixDQ** [electricitymaps/electricitymaps-contrib#4296]
We are currently using the APIv1 which will be deprecated in November 2022:

> Notice: EIA will discontinue support for its legacy API (APIv1) in November, 2022. Excel add-in v1 sheets will continue to function as they are. Please refer to our [documentation](https://www.eia.gov/opendata/documentation.php) for the APIv2 interaction methods and our [APIv2 query browser](https://www.eia.gov/opendata/browser/) to view the data.

Depending on how much of a change this requires, we can either create a new parser or submit a PR to https://github.com/systemcatch/eiapy which we are using to fetch the data.

**Comment by corradio** [comment]
cc @systemcatch

**Comment by FelixDQ** [comment]
Just linking https://github.com/systemcatch/eiapy/issues/26 here in case anyone has time to contribute. The EIA parser is down right now due to https://github.com/systemcatch/eiapy/issues/28 and it might be fixed if we upgrade to the EIA v2 api.
