### ISSUE TITLE
Yearly data older than from 2017?

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#4361]
Now that historical view has launched I was wondering if it would be possible to get yearly data from further back? I know most of our parsers have data from at the very least 2015 and some even go back as far as 2011. In addition to this the average carbon intensity for hydro and battery discharge is also calculated back to 2015 for a lot of zones.

It would be interesting to get this data into Electricity Maps so we can better see long term trends like solar and wind increases and such.

I realize some of the parsers don't have information dating that far back and it could be a lot more grey "gaps" in the map but I still think it's worth it.

**Comment by Kongkille** [comment]
One of the issues from a user experience side is that when looking further back than 5 years a lot of our countries will become grey.

Perhaps that is worth it, but it can also be a bit odd.

**Comment by strassburger** [comment]
@Kongkille  @VIKTORVAV99 
It is a great idea to check data older than 2017.
Hope it is not double mentioned, but here the situation of canary Island and balearic Islands:
24 hours and 12 month data are shown
30 days and 5 years data are missing.
Last check: 23.07.2022

Data source example of El Hierro:
https://demanda.ree.es/visiona/canarias/el_hierro5m/tablas//yyyy-mm-dd/2
example with diesel only:
https://demanda.ree.es/visiona/canarias/el_hierro5m/tablas/2013-05-03/2
example with first day with wind/water:
https://demanda.ree.es/visiona/canarias/el_hierro5m/tablas/2014-07-21/2

It would be really help show the change coming with Gorona de Viento -GDV-
Thank you for checking.

**Comment by strassburger** [comment]
@Kongkille @VIKTORVAV99
here the situation of canary Island and balearic Islands:
24 hours,30 days and 12 month data are shown
5 years data still  missing.
Last check: 27.07.2022

**Comment by Kongkille** [comment]
@strassburger when I try to test for older data, I can see if something pops up on the zones you mention :)

**Comment by strassburger** [comment]
@Kongkille @VIKTORVAV99 
New Info.
first date of data ifor El Hieroo n "demanda.ree.es" is 2012-02-29
works:
https://demanda.ree.es/visiona/canarias/el_hierro5m/tablas/2012-02-29/2
does nor work:
https://demanda.ree.es/visiona/canarias/el_hierro5m/tablas/2012-02-28/2
Hope helps
