### ISSUE TITLE
[RFC] Turn source field in state files into an array to help facilitate frontend formatting

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#4362]
Currently the source field in the state files are represented as a string, I would like to propose we turn this into an array of string instead so we can us [Intl.ListFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat) to properly format the sources in the frontend.

Example of how the sources are formatted today:
<img width="285" alt="image" src="https://user-images.githubusercontent.com/30777521/180438501-10c38af0-b3de-4140-b9a6-dc34a472e990.png">

How it would look with the proposed change:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/30777521/180440820-e9c0e41f-317f-4fe8-9177-48962ef04611.png">
>**Note**
>It's technically already possible to do this by splitting the string at <code>,</code> and turning it into an array but it would be cleaner if it was an array in the first place.

So the change I propose is that we change this field:
```json
"source": "\"electricityMap Estimation\",\"entsoe.eu\"",
```
into:
```json
"source": ["electricityMap Estimation", "entsoe.eu"],
```
And then in the frontend we need to change:
```jsx
<span className="country-data-source">{data.source || '?'}</span>
```
into:
```jsx
{const { i18n } = useTranslation();}
{const formatter = new Intl.ListFormat(i18n.language, { style: 'long', type: 'conjunction' });}
<span className="country-data-source">{formatter.format(data.source) || '?'}</span>
```
<sup>This could be turned into a helper function to be used elsewhere as well.</sup>

**Comment by Kongkille** [comment]
I would also like to have it as an array, but it's a bit tricky as a lot of stuff depends on this value. In theory we could still keep the same format for the config but then just have the app-backend send it as an array.

It does make more sense to have it as an array since we almost always have multiple entries for aggregated data

**Comment by VIKTORVAV99** [comment]
> I would also like to have it as an array, but it's a bit tricky as a lot of stuff depends on this value. In theory we could still keep the same format for the config but then just have the app-backend send it as an array.
> 
> It does make more sense to have it as an array since we almost always have multiple entries for aggregated data

Ah I see, not as straightforward as I thought then.

However we could still move forward with the Intl.FormatList functionality if we went with the split option in the meantime. Could even include some code to allow for both so the switch would be seamless if it changed in the future.

**Comment by VIKTORVAV99** [comment]
Sounds like a plan, I'll see if I can get a PR ready later today.

**Comment by VIKTORVAV99** [comment]
@Kongkille could we return it as an array for the v6 state files?
It shouldn't involve much more than moving this piece of code to the app backend (in theory):
```js
function removeDuplicateSources(source) {
  if (!source) {
    return undefined;
  }

  const sources = [
    ...new Set(
      source
        .split('","')
        .map((x) => x.split(',').map((x) => x.replaceAll('\\', '').replaceAll('"', '')))
        .flat()
    ),
  ];

  return sources;
}
```
