### ISSUE TITLE
[Data Issue]: Missing data for Montenegro (ME)

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#4388]
### On what platform are you seeing the problem?

Android, iOS, Web

### When did this happen?

This is a ongoing issue.

### What zones are affected?

Montenegro (ME)

### What is the problem?

Even though ENTSO-E has data for Montenegro it is not showing up on the map.
Montenegro has the correct parsers and there is no obvious reason why it's missing.

PS: This issue was made with the new Data Issue form.

**Comment by Kongkille** [comment]
Did a bit of investigating here,

Turns out this is caused by #4398. I'll take a full stab at it tomorrow and hopefully we can resolve it.

**Comment by VIKTORVAV99** [comment]
Awesome! Would be nice to see it colored on the realtime map.

BTW what do you think of the issue form?
I thought about removing the first 2 fields as they are pretty redundant and making the last 3 ones required.

**Comment by Kongkille** [comment]
> BTW what do you think of the issue form? I thought about removing the first 2 fields as they are pretty redundant and making the last 3 ones required.

Yeah let's just keep the last 3

**Comment by VIKTORVAV99** [comment]
Closing this as Montenegro now has visibility on the map.
