### ISSUE TITLE
[RFC] Split out capacities from zones.json to facilitate historical capacities

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#4396]
We now have historical production information in the map but I found myself missing seeing the installed capacities on these new time periods.

So in this RFC I request we split out the capacities from the zones.json file into a new capacity.json file.

This new file would only contain capacities (either just zone capacities or zone + exchange capacities) but would allow for historical values.

I propose we adopt the same structure as for the co2eq values and allow the capacity object for each zone to be either a single capacity object or a array of objects containing the capacity object and a datetime (and possibly source).

**Comment by VIKTORVAV99** [comment]
Another small benefit from this would be auto labeling for PRs that affects the capacity 😅

**Comment by Kongkille** [comment]
I like this idea,

For context, when we added historical view we disabled capacity because the live one of course is not valid for the full 5 year period. Having multiple capacity values seems like a good idea however there are some things we'd need to consider

Off the top of my head:

- Which time periods are capacity valid for, eg for a full year, or less?
- Do we accept multiple different sources for capacity
- How do we update this retrospectively with the current capacities, i.e. some of them may be quite recent whereas others may be from a few years ago

Also adding this discussion for some context on splitting out zones.json #2962

**Comment by VIKTORVAV99** [comment]
> I like this idea,
> 
> For context, when we added historical view we disabled capacity because the live one of course is not valid for the full 5 year period. Having multiple capacity values seems like a good idea however there are some things we'd need to consider
> 
> Off the top of my head:
> 
> * Which time periods are capacity valid for, eg for a full year, or less?
> * Do we accept multiple different sources for capacity
> * How do we update this retrospectively with the current capacities, i.e. some of them may be quite recent whereas others may be from a few years ago
> 
> Also adding this discussion for some context on splitting out zones.json #2962

My ide was to use the same structure as the co2eq intensities so:
* A capacity would be valid until a newer entry is found, this would also allow os to backfill capacities without much of a problem.
```json5
"capacities": {
  "DK-DK1": [
    {
      "datetime": "2020-01-01" // This would be valid from 2020-01-01 to indefinitely.
      "capacity": "capacityObject"
    }
  ],
  "DK-DK2": [
    {
      "datetime": "2020-01-01" // This would be valid from 2020-01-01 to 2020-12-31.
      "capacity": "capacityObject"
    },
    {
      "datetime": "2021-01-01" // This would be valid from 2021-01-01 to indefinitely.
      "capacity": "capacityObject"
    },
  ]
}
* I think we might have to accept multiple sources as say ENTSO-E might not have all the historical data we need. That is why I propose we include a source field as well.
```json5
{
  "datetime": "2020-01-01"
  "capacity": "capacityObject"
  "source": "sourceString"
  "_comment": "full_source_or_clarification" // Optional
},
