### ISSUE TITLE
Map geometries are re-rendered too often

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#4423]
## Description
The map geometries are created at https://github.com/electricitymap/electricitymap-contrib/blob/master/web/src/components/zonemap.jsx#L73-L97 by defining a `sources` object, which will be passed to the Mapbox engine.
This object is memoized and will be recalculated if the time scale changes, or if the `zones` object changes (i.e. when new data arrives from the server).
This is unnecessary, as the geometries do not change.

The consequence is that changing timescale or receiving new data causes unnecessary work. A better solution would be to separate geometries and colour data to avoid unnecessary work.

## Definition of done
The `sources` object is only recalculated when geometries change.

**Comment by VIKTORVAV99** [comment]
Technically I don't think we need re-calculate the `sources` object ever as the geometries will never change without the whole frontend bundle changing as they are currently bundled together, and if the bundle changes the app will be re-initialized and the `sources` object will update.

**Comment by Kongkille** [comment]
Good points. We are intending to work on a feature to aggregate countries, eg showing different spatial aggregations at runtime. This will properly require us to take a step back on how we handle geometries, so we can include that as part of the solution.

**Comment by VIKTORVAV99** [comment]
Closing this as it was marked as fixed in the refractor (and we forgot to close it then), if it is still relevant feel free to reopen it.
