### ISSUE TITLE
Historical prices

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#4424]
**Is your feature request related to a problem? Please describe.**
As a user, I would be very curious to see the long-term evolution of electricity prices

**Describe the solution you'd like**
Show the price graphs in the aggregated views.

**Comment by VIKTORVAV99** [comment]
Would these be just daily/monthly/yearly averages or would it be averages weighed by the current load for that price period?

Using just the average might give people the wrong idea when electricity usually is very cheap at night and expensive during the day when there is strain on the grid.

**Comment by corradio** [comment]
Yes indeed I believe a consumption-based average would be appropriate.

**Comment by VIKTORVAV99** [comment]
Would this be just the consumption or would it include exports as well?

For some regions exports account for a significant amount of the load.

**Comment by corradio** [comment]
As the unit of prices is a currency per unit of electricity *consumed*, I
believe consumption should be used. Note that consumption takes into
account exports (the *mix* isn't affected by exports, but the absolute
value is).

**Comment by VIKTORVAV99** [comment]
Ah I assumed consumption and exports where calculated separately.

But since it's included I also think it's the best way to calculate the averages for the longer time periods.
