### ISSUE TITLE
Create time series graph of net exchanges to give insight into net autarky

### ISSUE THREAD

**Issue by TheNewCivilian** [electricitymaps/electricitymaps-contrib#4430]
**Is your feature request related to a problem?**
To monitor and tackle the rise of a possible energy crisis, per country energy autarky or clear contract regulated energy dependence needs to be preserved.

**Describe the solution you'd like**
To get a clearer view on the energy autarky of a country a time series representation of total summed import / export volumes could be very helpful.

![Frame 49](https://user-images.githubusercontent.com/24456478/183401285-d776148f-2f0a-4c66-8470-99d80cdd356a.png)

**Describe alternatives you've considered**
A new map view setting, showing all live dependencies following a positive (exporting), neutral, negative (importing) color scheme. e.g. In case of an global energy shortage we could see more and more countries going red.

**Comment by VIKTORVAV99** [comment]
I'm not sure this would accurately represent energy dependance/independence as there is market conditions that causes a country to import/export even when it's not strictly needed from a grid security standpoint. This would also be a issue with countries that have internal bidding zones where there is a internal market where one bidding zone is constantly exporting and others are constantly importing. This is only natural and happens in every country but internal bidding zones make it much more apparent.

However it would be nice with a graph, similar to the price graph, that showed the net import/exports without any mention of dependance/independence.

**Comment by Kongkille** [comment]
We are also intending to work on a feature to aggregate regions into countries so it's easier to compare countries to each other. In that case, I also think this feature becomes even more relevant. 

If you agree that this also addresses your original issue @TheNewCivilian , perhaps we rename this issue to be about creating a time series graph of net exchanges?
