### ISSUE TITLE
Faded bar on origin of electricity graph

### ISSUE THREAD

**Issue by gwpicard** [electricitymaps/electricitymaps-contrib#4433]
**Describe the bug**
The penultimate top bar for "net" imports on the origin of electricity graph was showing as fading to gray.

**To Reproduce**
Unfortunately, I wasn't able to find the right parameters for this as the data refreshed on the hour.
PT looks ok now but it might occur again if real-time data is being estimated (and exchanges are not available since they are not estimated).

**Expected behavior**
We should only see a complete bar graph without any colour changes.

**Screenshots**
<img width="474" alt="Screenshot 2022-08-08 at 16 47 16" src="https://user-images.githubusercontent.com/7591224/183617835-59459c77-d95a-41d6-8ef4-502d9e788833.png">

**Additional context**
According to @corradio, it may been happening because:
> the last gradient stop must be based on an unknown value (when the interconnector disappears). The unknown value maps to gray, whereas it should instead be replaced by the last color of the timeseries.

**Comment by VIKTORVAV99** [comment]
Fixed in #4748 as we no longer fade the graphs.
