### ISSUE TITLE
Click and drag on cross border export arrow not panning map

### ISSUE THREAD

**Issue by cshuenss** [electricitymaps/electricitymaps-contrib#4434]
**Describe the bug**
Clicking and dragging when the mouse cursor is on a cross border exprort arrow drags the image of the cross border export arrow.

**To Reproduce**
At [https://app.electricitymaps.com/map](https://app.electricitymaps.com/map), hover the mouse above a cross border export such that the info box appears. Click, hold and drag.

**Expected behavior**
The map pans.

**Screenshots**
![Screenshot 2022-08-09 153201](https://user-images.githubusercontent.com/71438287/183677200-7f6cdf38-3e2e-468a-aae3-0e69746378ef.png)
The large arrow pointing straight down above Poland is the dragged image.

**Desktop (if relevant):**
Bug appears to be Firefox specific (Firefox 103.0). Works as intended on Chrome 104.0, Edge 104.0.

**Comment by nicolasca** [comment]
I can reproduce the issue with Chrome 107
<img width="1336" alt="Capture d’écran 2022-10-28 à 09 14 50" src="https://user-images.githubusercontent.com/2886734/198526504-aa7458bc-d199-4077-8486-f4e2fbc5d2c7.png">

**Comment by BStephenBB** [comment]
Going to take this one if that's okay
