### ISSUE TITLE
Added a checkbox to agglomerate the data to the country scale. 

### ISSUE THREAD

**Issue by Spadice** [electricitymaps/electricitymaps-contrib#4439]
The idea may have already been suggested, I think it would be useful to have an option to agglomerate the results at the country level (checked box) or to keep them at the region level (unchecked box). 

This would facilitate reading, both on the world map, and in the ranking. 

Sincerely,

**Comment by madsnedergaard** [comment]
Thanks for sharing your feedback, we're currently working on this and you can try it out here: https://app.electricitymaps.com/map?aggregatedViewFF=true

We'll soon finish it and make it public, so I'll close this issue again :)
