### ISSUE TITLE
Frontend breaks at split screen (767 px width)

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#4441]
**Describe the bug**
Frontend styling breaks when using the app split screen.

**To Reproduce**
1. Go to app.electricitymaps.com
2. Set width to 767 px.
3. See error

**Expected behavior**
A responsive style.

**Screenshots**
![image](https://user-images.githubusercontent.com/30777521/183989473-8859b38a-0e84-4323-b454-cc795e3a6f0c.png)

**Comment by Kongkille** [comment]
Yikes that looks chaotic. Which browser were you using?

On chrome it seems to work as expected

![image](https://user-images.githubusercontent.com/45588799/184089371-ee96ad6b-90e9-4e41-8aa3-c2ae611a9c3d.png)
![image](https://user-images.githubusercontent.com/45588799/184089551-bb66ce2e-8125-444b-ab2d-2806e0ad18b5.png)

**Comment by VIKTORVAV99** [comment]
I'm using Edge 104.0.1293.47 on Windows 11 with 125% scaling (if that matters).

**Comment by VIKTORVAV99** [comment]
Tried it on another device that uses Brave `Version 1.42.95 Chromium: 104.0.5112.81` as well on Windows 11 Home Insider Preview build 25174.1010 with 150% scale.
Here is the result:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/30777521/184828983-a2458761-1bce-4294-8b99-2d039f44fb69.png">

**Comment by tonypls** [comment]
I've tested this on Mac with Chrome, Firefox and Safari and the layout is working as expected. Because this is quite an edge case, I don't think there is priority right now. @VIKTORVAV99 Feel free to close the issue and we can open it again if we have and more reports of this becoming a problem.

**Comment by VIKTORVAV99** [comment]
> I've tested this on Mac with Chrome, Firefox and Safari and the layout is working as expected. Because this is quite an edge case, I don't think there is priority right now. @VIKTORVAV99 Feel free to close the issue and we can open it again if we have and more reports of this becoming a problem.

I would prefer to leave it open but I don't (and didn't) expect this to be a priority.
I'll see if I can try and narrow down the issue in the coming days but I understand if you want yo close it. 🙂
(Leaving it open would allow other contributors to take a crack at solving it.)

**Comment by VIKTORVAV99** [comment]
@tonypls did a quick search of the frontend codebase for 766, 767 and 768 and I think I found the cause, there are some media queries that use 767 and a few (newer) ones that use 768 so I'll try and replace the 768 ones with 767 and see if that fixes it. (and don't break anything else)

If it works I'll create a PR later today.

**Comment by tonypls** [comment]
Nice 🧐
