### ISSUE TITLE
Update "Info" and "Settings" icons for the mobile app

### ISSUE THREAD

**Issue by rasmusjeppsen** [electricitymaps/electricitymaps-contrib#4490]
## Description
Update the "Info" and "Settings" icons for the mobile app using the [Fontawesome](https://fontawesome.com/) library:
- Info icon: https://fontawesome.com/icons/circle-info?s=regular
- Settings icon: https://fontawesome.com/icons/sliders-up?s=regular

Possibly some adjustments to the icon sizes are required to match the [design mockup](https://user-images.githubusercontent.com/58597172/186380627-2f6cb519-fb57-456a-bf1c-ebe4c14e9632.png).

## Design mockups
Here are some mockups comparing the current icons in the mobile app with a design mockups of the new icons.

**Current icons:**
![home_current](https://user-images.githubusercontent.com/58597172/186382077-fe070f5c-e29c-43fd-8815-f3b384213cc3.png)

**New icons:**
![home_new-icons](https://user-images.githubusercontent.com/58597172/186382091-bd139362-87b0-4968-abb8-de88b0198a11.png)

**Comment by VIKTORVAV99** [comment]
Any specific reason we need to change them?

I am not totally fond of replacing the current SVG icons with premium font icons that we need to license to use.

If it's just the rotation and fill we can take care of that with the current icons.

**Comment by rasmusjeppsen** [comment]
@VIKTORVAV99 Hey Viktor! No other reason than these icons are the icons from the design and they match better with the rest of the UI IMO. 

Also, we do have a license for Fontawesome in Electricity Maps which we use for all icons, but if that was not the case I totally agree that it would be a lot just for changing the two icons. As we use the Fontawesome icons everywhere, at least that is what we are catering towards with the recent rebranding, this will also improve consistency in the UI in the long run.

**Comment by VIKTORVAV99** [comment]
Oh okay, but just FYI it's doubtful open source contributors can help with this as you can't even access the icon code on the fontawesome website without the license.

So might be better if someone from the team did that.

However I am slightly concerned about adding these icons to the repository since we use a MIT license and it's doubtful we are allowed to re-distribute the icons (haven't checked the full license yet).

**Comment by tonypls** [comment]
"Font Awesome is fully open source and is GPL friendly. You can use it for commercial projects, open source projects, or really just about whatever you want." - (https://fontawesome.com/license/free)

I suggest we use https://react-icons.github.io/react-icons/ 

This way we should only have access to free icons and when importing them to our project only the icons we use are loaded 🚀

**Comment by VIKTORVAV99** [comment]
> "Font Awesome is fully open source and is GPL friendly. You can use it for commercial projects, open source projects, or really just about whatever you want." - (https://fontawesome.com/license/free)
> 
> I suggest we use https://react-icons.github.io/react-icons/
> 
> This way we should only have access to free icons and when importing them to our project only the icons we use are loaded 🚀

Yeah the free icons should be fine, it's the premium ones that might cause issues.

That react library does look good but I'm biased towards our current SVG sprite implementation. (It should be more performant as it bundles all SVG files and only requires one http request while keeping the JS bundle small (or smaller in our case).

**Comment by jaretkadlec** [comment]
Hey team,
I'm looking to start contributing to this project and this seems like a good first issue for me. Could I be assigned to this issue? Or are there other steps I need to take before I can be assigned to an issue? Just checking to see how I can get started on helping.

**Comment by VIKTORVAV99** [comment]
Hello @jaretkadlec!

We are currently re-writing the frontend in #4731 and I do believe the icons have already been changed there. So I'm not sure we actually want to fix it in the current app when we are aiming to replace it all together soon.

But if you do decide to update it I don't think there will be any problem with that but keep in mind the change will not be long lived.

**Comment by jaretkadlec** [comment]
Sounds good, I'll go look for an issue that is more pertained to the backend. Thanks for letting me know!

**Comment by PalAman-git** [comment]
can I work on this issue ?

**Comment by VIKTORVAV99** [comment]
These have been changed completely since this issue was first opened. So I'm not sure if it's still actual but I'll double check with the team (can take a few days due to easter holidays).
