### ISSUE TITLE
Improve Page Speed

### ISSUE THREAD

**Issue by tonypls** [electricitymaps/electricitymaps-contrib#4510]
## Description
**This is a master issue please link sub issues below**

The current app has poor performance for based on Google's PageSpeed Insights. 

Check the results here:
[**Desktop**](https://pagespeed.web.dev/report?url=https%3A%2F%2Fapp.electricitymaps.com%2F&form_factor=desktop)
[**Mobile**](https://pagespeed.web.dev/report?url=https%3A%2F%2Fapp.electricitymaps.com%2F&form_factor=mobile)

We should improve the web app performance to provide users with a better experience and help improve our SEO.

The Page Speed results give actionable opportunities and help us identify the lowest hanging fruit. We should investigate each of these opportunities to get verifiable pieces of work to complete and improve the performance of the app.

**Comment by tonypls** [comment]
Here's a good issue to start with feel free to add any more issues, not everything will be identified from the PageSpeed Insights so all performance improvements are welcome.

https://github.com/electricitymap/electricitymap-contrib/issues/4115

**Comment by VIKTORVAV99** [comment]
This also relates to the [static web project](https://github.com/orgs/electricitymap/projects/29) that should bring some nice overall improvements. So please have a look in there as well if you need more information.

**Comment by VIKTORVAV99** [comment]
This should in theory be "fixed" in the refractor.

**Comment by VIKTORVAV99** [comment]
While there are still a few things we can do in to improve the page speed even further (or perceived page speed) I'll consider this one closed for now as the rewrite is a substantial improvement that will get even faster with #5027.
