### ISSUE TITLE
Hidden values when there are multiple missing time periods

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#4514]
**Describe the bug**
There is hidden values for the oldest non visible time period when there is multiple datapoints missing.

**To Reproduce**
1. Go to a zone with multiples datapoints missing (like Montenegro right now).
3. Scroll down to the origin graph.
4. Hover over the oldest missing data point.
5. See error.

**Expected behavior**
That the oldest missing data point is displayed since it has data.

**Screenshots**
![image](https://user-images.githubusercontent.com/30777521/187377119-e33c76af-206e-4880-a9ed-99072a8d5374.png)

**Desktop:**
 - OS: Windows 11
 - Browser: Edge
 - Version: 104.0.1293.70

**Comment by Kongkille** [comment]
I think this is due to some release cadence issue, I'm going to update the app again today!

**Comment by VIKTORVAV99** [comment]
> This is not due to the release cadence, but is something else :)

I think the issue is related to how we color the graphs (color transition) in some way since it also happens when there is just missing exchange data.

Now I just have to find where the bug actually is...
