### ISSUE TITLE
First render on the map is sometimes grey

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#4517]
**Describe the bug**
I sometimes get a first loading of the map where no colors appear.
I can drag around and it doesn't trigger any colouring.

I suspect this happens due to a race condition in `ZoneMap` that triggers `isLoaded` (which would color the map) before the initial `sources` object is created (which doesn't contain any colours).

Maybe this can help: https://gis.stackexchange.com/questions/240134/mapbox-gl-js-source-loaded-event

cc @tonypls as this might come into play when the `sources` object is modified upon change of geometries in the country/regional view.

**To Reproduce**
1. Open the app or the web app
2. Sometimes the map will not have any colours even though the data is here

Have not been able to repro on desktop.

**Expected behavior**
First render should always be coloured when data is present.

**Screenshots**
<img width="375" alt="image" src="https://user-images.githubusercontent.com/1655848/187859423-2b57626a-180f-408f-be58-2cb2accb441c.png">

**Desktop (if relevant):**

**Smartphone (if relevant):**
 - Device: iPhone 8
 - Browser: Safari

**Comment by tonypls** [comment]
I've been able to replicate this on android using chrome. 

Steps to replicate:

Open electricity maps app 
Return to home screen
Wait for chrome to become idle, not sure how long this takes (10+ minutes)
Open chrome, if the page does not refresh then the map does not render.

I think we need to find what event triggers on mobile when opening / focussing on the browsers and using this to trigger a render of the map.

**Comment by corradio** [comment]
I haven't encountered this anymore. Do you @tonypls ?
Maybe we can close the issue.

**Comment by madsnedergaard** [comment]
I also haven't seen it in a while, so let's close it! :)
