### ISSUE TITLE
Crash loading page

### ISSUE THREAD

**Issue by PedroFRCSantos** [electricitymaps/electricitymaps-contrib#4527]
Error message: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
Url: https://app.electricitymaps.com/zone/PT

Go to https://app.electricitymaps.com/zone/PT in chrome, windows

**Comment by VIKTORVAV99** [comment]
It crashes on the website when using Chrome on windows?

We have gotten previous bug reports about these crashes but they where all in the mobile apps.

**Comment by madsnedergaard** [comment]
Should be fixed now :)
