### ISSUE TITLE
Colourblind mode checkbox/info panel obstructs region list on short desktop screens or when zoomed in

### ISSUE THREAD

**Issue by tahsbahs** [electricitymaps/electricitymaps-contrib#4530]
Also bug report form

This app is [Open Source](https://github.com/tmrowco/electricitymap-contrib) (see [data sources](https://github.com/tmrowco/electricitymap-contrib/blob/master/DATA_SOURCES.md)). Contribute by [adding your territory](https://github.com/tmrowco/electricitymap-contrib/wiki/Getting-started).

Found bugs or have ideas? Report them [here](https://github.com/tmrowco/electricitymap-contrib/issues/new).

Anything unclear? Check out our [frequently asked questions.](https://app.electricitymaps.com/faq)

[ Tweet](https://twitter.com/intent/tweet?url=https://www.app.electricitymaps.com)[Slack](https://slack.tmrow.com/)

Is in the way of the menue

**Comment by jarek** [comment]
Could you please attach a screenshot or specify your device and/or browser? Which menu is obstructed?

I'm assuming you mean this section? (Screenshot from Firefox on desktop)
![image](https://user-images.githubusercontent.com/47415/188284800-af9e413d-05b3-402e-926c-7769e32d8473.png)

**Comment by tahsbahs** [comment]
![image](https://user-images.githubusercontent.com/43064125/188285142-220f0b5d-72f6-4621-9aa8-0b26583ee5c5.png)

Yes it is. 
It's on chrome on windows. When zooming out the panel gets visible like in your screenshot.

**Comment by jarek** [comment]
Got it, thanks!

**Comment by jarek** [comment]
I can reproduce this in desktop Firefox 104.0 with zoom 100% and viewport size approximately 1570x583:

![image](https://user-images.githubusercontent.com/47415/188294716-114c9191-01a6-431d-a6ed-98e2b0a70e2f.png)

Or with zoom 150%, viewport approx 1473x934:

![image](https://user-images.githubusercontent.com/47415/188294744-4267f552-bcc0-44ab-9722-1775068501cc.png)

Looks like any viewport wider than 720px will show this layout. We might need to ensure the region list is always tall enough to fit at least a few regions?

**Comment by VIKTORVAV99** [comment]
I think the best way to "fix" this would be to move the color blind settings to a settings menu like we did for mobile.
