### ISSUE TITLE
Android app: Value unit out of range for Intl.NumberFormat options property style

### ISSUE THREAD

**Issue by martian-maniac** [electricitymaps/electricitymaps-contrib#4533]
**To Reproduce**
1. Open electricityMap on Android

**Screenshots**

> Oh no, something went wrong...
> Please let us know on Github so we can fix this!
> 
> Error message: Value unit out of range for Intl.NumberFormat options property style
> Url: file:///android_asset/www/electricitymap/index_sv.html#/map
> Back to map

**Smartphone (if relevant):**
 - Device: LG G5
 - OS: Android 9
 - Browser: Firefox
 - Version: 104.1.0

**Comment by VIKTORVAV99** [comment]
Seems to be the same issue as #4521, #4519 and #4524.

**Comment by VIKTORVAV99** [comment]
Closing this as it seem to have been resolved!

**Comment by martian-maniac** [comment]
Just tested and it's *not* fixed. No new app was available in play store.

**Comment by VIKTORVAV99** [comment]
The app fetches updates in the background and can update outside store updates (for some content) but I have re-opened it for now.

**Comment by FelixDQ** [comment]
@martian-maniac can you check which version of the app you have installed?

**Comment by martian-maniac** [comment]
app version 1.3.7
updated on 1st sept 2022

**Comment by martian-maniac** [comment]
Still broken. I see you are using https://sentry.io/ which should report these errors with more details?

**Comment by martian-maniac** [comment]
Still broken. I see you are using https://sentry.io/ which should report these errors with more details?

**Comment by jarek** [comment]
Hi @martian-maniac, can you confirm if you are using the web page version of Electricity Map (via Firefox), or via the app installed from Play Store?

**Comment by martian-maniac** [comment]
Using app from play store.

I don't have Chrome on my Android only Firefox app.

In Firefox app the website works fine.

**Comment by VIKTORVAV99** [comment]
Hmm, maybe we can just include the polyfills in cordova then?
That would remove any negative impact from the size increase as it would only be downloaded once anyway.
@tonypls is this something we can actally do with cordova?

**Comment by tonypls** [comment]
I think we should check if Intl.NumberFormat etc.  are available constructors then if not return the number without formatting.
