### ISSUE TITLE
On IOS, iPhone 13 mini, detail of production breaks 

### ISSUE THREAD

**Issue by otmezger** [electricitymaps/electricitymaps-contrib#4553]
**Describe the bug**
See top of the screen:
![C7541A52-E914-4851-B39D-F5FF6FFFFD63](https://user-images.githubusercontent.com/2758346/189277658-bc9dccd6-62aa-46fb-8834-501a86588af9.png)

![F40B50CE-04AB-40C7-8B81-ED03B2985A96](https://user-images.githubusercontent.com/2758346/189277807-a38c4e49-71c1-491e-8800-68181bbd79bc.png)

![169E194E-325D-4744-BE25-2DEA5C77969E](https://user-images.githubusercontent.com/2758346/189277833-f8247d7a-1f8f-4791-a3ec-c5a730949226.png)

![08BE25D9-1EC5-4B6C-9FFD-944AA2EDBC09](https://user-images.githubusercontent.com/2758346/189277845-d2dac28c-22c9-407c-9eb9-c831e00a9bdf.png)

**To Reproduce**
1. Go to map
2. Click on any country 
3. Click on 
any of the graphs.

**Expected behavior**
Respect the boundaries of the screen and UI
**Screenshots**
See above 

**Smartphone (if relevant):**
 - Device: [e.g. iPhone6] 13 mini 
 - OS: iOS 15.6.1

**Comment by tonypls** [comment]
Nice catch, looks like we need a way to find the safe area insets for iOS devices

**Comment by otmezger** [comment]
Happy to help! Let me know if you have a fix and I could test.

**Comment by GrzegorzWidla** [comment]
FYI, same on iPhone 13 running iOS 16. It'll probably affect all models with the notch, if not all altogether.

**Comment by madsnedergaard** [comment]
This has been fixed :)
