### ISSUE TITLE
[feedback request] Spatial Aggregations 🗺️ 

### ISSUE THREAD

**Issue by tonypls** [electricitymaps/electricitymaps-contrib#4554]
## Description
We're super excited to release a brand new feature **Spatial Aggregations**

We've released this under a feature flag which you can check out [here](https://app.electricitymaps.com/map?aggregatedViewFF=true&aggregated=true) and give some feedback

We've introduced a new toggle between an Aggregated and Detailed view. This will either show you the highest fidelity view of our zone data or a combined / aggregated view. Currently the aggregated view combines all countries we have complete sub-zone data for i.e. Norway, Sweden, Denmark and Italy. 

We'd love for you to play around with the new feature, give any feedback and share the link:https://app.electricitymaps.com/map?aggregatedViewFF=true&aggregated=true 

The next update is to be able to aggregate countries we don't have complete data for i.e. The US. We want to do this in a transparent and accurate way. 

Let us no what you think of the feature and any opportunities to improve it.

![image](https://user-images.githubusercontent.com/18622768/189304327-d7d5dc62-aea7-43b9-b5c2-bff86f7815bf.png)

**Comment by VIKTORVAV99** [comment]
I might be a little biased as I already Gabe some feedback around this but I really only have one big piece of feedback and that is that the exchange data is missing on the detailed views.

![Screenshot_20220909_103947.jpg](https://user-images.githubusercontent.com/30777521/189309674-74e128ae-6bb3-4d5c-91ba-13b3b0a3a8b9.jpg)

Another note is that we should have complete data for the Faroe Islands as well so we should be able to aggregate those. But that brings into question if we should aggregate physically separated grids (no interconnections between them) or not.

**Comment by tonypls** [comment]
Issue here https://github.com/electricitymaps/electricitymaps-contrib/issues/4555 😎
