### ISSUE TITLE
Add exchange information for aggregated zone details

### ISSUE THREAD

**Issue by tonypls** [electricitymaps/electricitymaps-contrib#4555]
## Description
As a map user I would like to see exchange information in the zone overview for aggregated zones so that I can understand country to country exchange information

![image](https://user-images.githubusercontent.com/18622768/189322505-a2fbcbef-254d-489d-8d16-39a4d41125be.png)

**Comment by VIKTORVAV99** [comment]
Closing this as the newest release now contains the requested information! 🎉
