### ISSUE TITLE
Border flows NO-DK gone missing

### ISSUE THREAD

**Issue by Gazer75** [electricitymaps/electricitymaps-contrib#4567]
As title say it has disappeared from the map. Not even the bars in each area is showing as empty with a question mark.

**Comment by VIKTORVAV99** [comment]
Looks like this is a issue with the `DK.py` parser at first glance. We might be able to simply switch to `ENTSOE.py` for the exchange as they have the data as well.

I'll look into it later today.

**Comment by VIKTORVAV99** [comment]
Looks like the API has moved:
```
"Not found" fetching exchange data for DK-DK1->NO-NO2: ['API has moved. See https://www.energidataservice.dk/news'
```

I'll try and fix it later.

**Comment by VIKTORVAV99** [comment]
I am currently re-writing the parser but I won't be able to get it done until tomorrow at the earliest.
