### ISSUE TITLE
Safari 12.1.2 throws error `style must be either "decimal", "percent", or "currency"`

### ISSUE THREAD

**Issue by eljonco** [electricitymaps/electricitymaps-contrib#4570]
Oh no, something went wrong...

Please let us know on Github so we can fix this!

Error message: style must be either "decimal", "percent", or "currency"
Url: https://app.electricitymaps.com/

**Comment by VIKTORVAV99** [comment]
I can't replicate this locally, perhaps you could provide some more information?

What language are you using?
Did this happen for a particular zone/region?
What device are you using? (desktop, ios or Android)

**Comment by eljonco** [comment]
Sent from my iPhone

> On 14 Sep 2022, at 23:42, Viktor Andersson ***@***.***> wrote:
> 
> I can't replicate this locally, perhaps you could provide some more information?
> 
> What language are you using?
> 
British English
> Did this happen for a particular zone/region?
> 
No, just the base URL (although I first tried zone NL)
> What device are you using?
> 
problems on
iMac Safari 12.1.2 macos Sierra 10.12.6
Macbook Pro, same software configuration

Working on Safari 15.5, macos 12.4

**Comment by jarek** [comment]
Judging by the error message, possibly related to #4533?

**Comment by VIKTORVAV99** [comment]
> Judging by the error message, possibly related to #4533?

Could be, but I can't seem to replicate either one of them so it's hard to tell if they are related.
