### ISSUE TITLE
Feature request/Help wanted: automatic capacity for wind/solar in Belgium.

### ISSUE THREAD

**Issue by Fred-3000** [electricitymaps/electricitymaps-contrib#4571]
Elia, the Belgian TSO has started updating the wind/solar capacity figures much more often, at least once a month.
As the these figures are on the website in text format, it should be relatively easy to pull them automatically.
Unfortunately, I don't know enough about coding to implement this myself. 
Anyone up for the challenge or able to provide me with an example code that would need very little changes? 😄 

Sources: https://www.elia.be/en/grid-data/power-generation/wind-power-generation ; https://www.elia.be/en/grid-data/power-generation/solar-pv-power-generation-data

**Comment by VIKTORVAV99** [comment]
Electricity Maps don't currently parse capacities (as far as I know) but perhaps we can add this as a part of #4219. 

What do you guys think @mathilde-daugy, @FelixDQ and @pierresegonne?

**Comment by Fred-3000** [comment]
Oh, I was under the impression that some parsers were already handling capacities. 
But I don't know where I got that from.

**Comment by jarek** [comment]
A production parser can report capacity, and as far as I know this will be used (and override the capacity set in config files). See for example https://github.com/electricitymaps/electricitymaps-contrib/blob/a17bade010b93307a5293330e5c296840d792f01/parsers/OPENNEM.py#L312-L326

**Comment by VIKTORVAV99** [comment]
> A production parser can report capacity, and as far as I know this will be used (and override the capacity set in config files). See for example https://github.com/electricitymaps/electricitymaps-contrib/blob/a17bade010b93307a5293330e5c296840d792f01/parsers/OPENNEM.py#L312-L326

Interesting, I didn't know the production parsers accepted the capacity object as well. Now I'm curious why this isn't a separate parser function (or documented for that matter).

Should be easy enough to add then but it does raise some questions about what will happen if the capacity parser fails to return any data, does it show none, fall back to the last value or fall back to the capacities in the zone file? (I realize you might not be able to awnser this jarek so this is more a open question to the team.)

**Comment by pierresegonne** [comment]
Hey, the current setup does allow for adding capacity data to production/exchange events. 
If nevertheless the production data is faulty, then it will not be propagated in the processing pipeline and the capacity data will be lost.
This means overall that the capacity data can only be processed together with the production or exchange data. It could definitely make sense to have a separate pipeline in the future for processing capacity data, but that's not currently on our roadmap and would require some rework of the backend.

**Comment by pierresegonne** [comment]
Adding the help wanted flag here as it seams that it would be possible to add the dynamic capacity data to BE

**Comment by madsnedergaard** [comment]
We have internally developer automated capacity updates, so closing this
