### ISSUE TITLE
Sweden: windpower production mismatch to svenska kraftsnäts live page

### ISSUE THREAD

**Issue by janhal** [electricitymaps/electricitymaps-contrib#4578]
Windpower part of Swedens mix seem to constantly beeing underestimated in Electricity maps compared to Svenska kraftnäts live production-mix page.
https://www.svk.se/om-kraftsystemet/kontrollrummet/
Known issue?

**Comment by VIKTORVAV99** [comment]
This is due to #4577 and will be corrected when SvK starts reporting data to ENTSO-E again.

There isn't really anything we can do until then.

**Comment by VIKTORVAV99** [comment]
Looks like SVK is reporting live data again so I'll go ahead and close this issue as everyone should match now.

However I'll leave the other one open since it concerns the historical data as well.

**Comment by janhal** [comment]
Strange, because today SvK says wind= 5.75 GW but electricitymap approx 2.1 (sum of the 4 regions).
Water is also different but the other way.

**Comment by VIKTORVAV99** [comment]
The last value on electricity maps is often estimated for Sweden
![image](https://user-images.githubusercontent.com/30777521/191053654-3986d680-24ff-4497-8677-8c42205cfec6.png)
But it will update when the new data has been fetched. This is a bit unfortunate but there are some ideas floating around to help fix it so hopefully it will get better.
