### ISSUE TITLE
Ireland data incorrect

### ISSUE THREAD

**Issue by andys73** [electricitymaps/electricitymaps-contrib#4585]
The CO2 Electricity map does not match with what is reported on the Irish grid for some days now. Can someone please check it out?

Please see info below. Many thanks!

Electricity Map live
![image](https://user-images.githubusercontent.com/77861753/191224966-2db64bc4-f48c-440a-bc3a-d74569cdcab1.png)
Eirgrid fuel mix
https://www.eirgridgroup.com/
![image](https://user-images.githubusercontent.com/77861753/191225447-ce9b3e3b-4a6a-4e80-b48a-803b61211c17.png)

Also https://www.smartgriddashboard.com/DashboardService.svc/stats?area=CO2Stats&region=ROI

{
  "ErrorMessage": null,
  "LastUpdated": "20-Sep-2022 10:49:42",
  "Rows": [
    {
      "EffectiveTime": "20-Sep-2022 10:30:00",
      "FieldName": "LATEST_EMISSIONS",
      "Region": "ROI",
      "Value": 1744
    },
    {
      "EffectiveTime": "20-Sep-2022 10:15:00",
      "FieldName": "LATEST_INTENSITY",
      "Region": "ROI",
      "Value": 452
    },
    {
      "EffectiveTime": "20-Sep-2022 09:45:00",
      "FieldName": "MIN_INTENSITY_TODAY",
      "Region": "ROI",
      "Value": 445
    }
  ],
  "Status": "Success"
}

**Comment by jarek** [comment]
Electricity Maps had estimated data at that time. 40% of supply was estimated to come from wind, whereas the Eirgrid dashboard had 7% renewables. Also Electricity Maps estimated total supply was 3 GW and a small amount of exports to NI, whereas Eirgrid had system demand for Ireland at 3.7 GW. So the estimate is quite wrong for wind generation and for total generation.

Electricity Maps gets Ireland data from ENTSOE. Data in ENTSOE should be at [this link](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=20.09.2022+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=20.09.2022+00:00|CET|DAYTIMERANGE&area.values=CTY|10YIE-1001A00010!BZN|10Y1001A1001A59C&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&showConsumption.values=SHOW_CONSUMPTION&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)) it looks like this hasn't been fully updated and reliable in months and is currently completely empty :/ That is why estimated data is used, but the estimate probably doesn't have enough recent data to work well.

Past discussion about Ireland data source were https://github.com/electricitymaps/electricitymaps-contrib/issues/2339 and https://github.com/electricitymaps/electricitymaps-contrib/issues/3383 - in general data availability and reliability was thought to be bad there, but it might be worth revisiting? Though if the operator isn't submitting good data to ENTSOE, any other source might also be wonky.

**Comment by andys73** [comment]
Hello,

I think the rest API https://www.smartgriddashboard.com/DashboardService.svc/stats?area=CO2Stats&region=ROI is what is reliable at least to me as I am tracking this in Home assistant. Maybe the integration should have fallback to this url if there is no data in ENTSOE?

Thank you!

**Comment by VIKTORVAV99** [comment]
> Hello,
> 
> I think the rest API https://www.smartgriddashboard.com/DashboardService.svc/stats?area=CO2Stats&region=ROI is what is reliable at least to me as I am tracking this in Home assistant. Maybe the integration should have fallback to this url if there is no data in ENTSOE?
> 
> Thank you!

Electricity Maps don't support parsing emission information but calculates this from the energy mix (production + imports). So unfortunately, unless you have a source that has a good breakdown of the production mix, we can't switch away from ENTSO-E.

**Comment by pierresegonne** [comment]
> Electricity Maps gets Ireland data from ENTSOE. Data in ENTSOE should be at [this link](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=20.09.2022+00:00%7CCET%7CDAYTIMERANGE&dateTime.endDateTime=20.09.2022+00:00%7CCET%7CDAYTIMERANGE&area.values=CTY%7C10YIE-1001A00010!BZN%7C10Y1001A1001A59C&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&showConsumption.values=SHOW_CONSUMPTION&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)) it looks like this hasn't been fully updated and reliable in months and is currently completely empty :/ That is why estimated data is used, but the estimate probably doesn't have enough recent data to work well.


Exactly, the estimation model is kind of running into thin air as the ENTSO-E data has been very inconsistent for a while. We've tried to get in contact with Eirgrid many times to ask them to provide the data they're mandated to provide to ENTSO-E without much success. 

I guess we could use https://www.eirgridgroup.com/ as a fallback. It must be possible to scrape that little graph, together with demand to get a real time value for the latest fuel mix. If anybody has capacity, feel free to try it out!

**Comment by pierresegonne** [comment]
Hey @phiphou that regularity comes from the fact that we are not receiving any information for IE from ENTSO-E since 2022-07. 

The last measured data points are so far away that our estimation model can't really extract any meaningful information from it, and fallbacks to predicting that semi-constant value. 

The only alternative is to disable estimations for IE, which we might do if the situation does not change.

**Comment by phiphou** [comment]
Seems datas are back...

**Comment by msaynevirta** [comment]
This issue seems to be still ongoing as ENTSO-E data hasn't seen updates in months. Wind generation alone fluctuates quite heavily while the estimation keeps predicting rather constant generation.

Recently, I've been building a parser for Northern Ireland based on the SONI / EirGrid SmartGrid dashboard and extending for ROI wouldn't be too difficult (see PR #4904). One additional benefit it could also give is the higher smaller update period of 15 minutes vs 30 minutes in the UK data currently used for the GB-IE exchange data.

I could look into this in January if it's something of interest for the project.

**Comment by pierresegonne** [comment]
Definitely!

We've been looking doing the switch to EirdGrid internally as well. 

As far as I know, it would not solve the issue perfectly though as the dashboard provides an incomplete breakdown in real time. Specifically, we don't know when the breakdown below is updated, which makes it hard to understand what's the current breakdown.


<img width="526" alt="Screenshot 2023-01-02 at 15 23 04" src="https://user-images.githubusercontent.com/32778266/210244039-740fcf98-9343-447b-94f8-0c623b338100.png">

If that breakdown is updated at an hourly or subhourly level we could do scrape that data, and use the above graph to make a complete breakdown for Ireland and Northern Ireland though, which would be awesome

**Comment by pierresegonne** [comment]
Actually, it seems like the data that populates that chart comes from `https://www.smartgriddashboard.com/DashboardService.svc/data?area=fuelmix&region=ROI&datefrom=02-Jan-2023+00%3A00&dateto=02-Jan-2023+23%3A59`  and might be updated every 15 mins (to verify) (also seems like the dates given in url are useless)

**Comment by msaynevirta** [comment]
Yeah, there are some discrepancies between the different data views. Last week I did some analysis on the ROI / NI generation and consumption data last week, and it seems that the figures don't match exactly even after accounting for flows between the different jurisdictions of the island.

It might be worth mentioning that in addition to the rolling 24h fuelmix there is another fuel mix graph on the Overview page. It pull the data as percentages from ```https://www.smartgriddashboard.com/DashboardService.svc/stats?area=GenerationStats&region=ALL``` and seems to update every 15 minutes.
