### ISSUE TITLE
tmrow-bot is no longer publishing releases on GitHub

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#4593]
It seems like @tmrow-bot has stopped publishing releases on GitHub.

While this isn't a critical issue at all it was a nice feature to have to know when new features and bugfixes have been deployed.

**Comment by FelixDQ** [comment]
Thanks for flagging this. I think something went wrong as the `v0.290.0` tag existed but it had no release attached. This made the bot fail because it tried to release `v0.290.0`, but the tag already existed. I manually added release `v0.291.0` which should hopefully fix the issue.
