### ISSUE TITLE
Failure after starting App on ipad

### ISSUE THREAD

**Issue by haerribuhn** [electricitymaps/electricitymaps-contrib#4598]
[no information was provided, issue template was left unfilled]

**Comment by tonypls** [comment]
Hi there, could you please add a screen shot of this issue? Thanks

**Comment by tonypls** [comment]
If anyone has an iPad to test on this would be a great hacktoberfest issue to investigate and fix if it can be replicated.

**Comment by haerribuhn** [comment]
Sorry, I forgot to make a screenshot of the bug. I'i is currently not possible for me to take a screenshot, because I moved today to my hometown (Hamburg) without my ipad ;-).

**Comment by tonypls** [comment]
All good, would be great to fix this if anyone else could try replicate :)

**Comment by haerribuhn** [comment]
Bug still exist. 

Regards Rainer

**Comment by jarek** [comment]
Is this same issue as #4625?

As you are able to tell that the bug still exists, can you provide a screenshot so we can check?

**Comment by haerribuhn** [comment]
![0A6553C4-77FC-4CEF-ACB7-E5EBED72CE24](https://user-images.githubusercontent.com/8195369/193404397-2db29c35-25fd-44e8-b36d-c2a5c8a569c0.png)

**Comment by haerribuhn** [comment]
iPad Version 15.7 iOS; Model 9th Generation.
Cu Rainer

**Comment by haerribuhn** [comment]
![01CD492D-BB1C-44BC-8279-679826CF8E12](https://user-images.githubusercontent.com/8195369/193404830-f6f99d3e-befc-45ad-9096-4aca6c2b83d3.png)

landscape format provides more information 😳

**Comment by jarek** [comment]
Ah in that case it's the same issue as https://github.com/electricitymaps/electricitymaps-contrib/issues/4537 and https://github.com/electricitymaps/electricitymaps-contrib/issues/4521 but those issues indicate that it has been resolved.

Can you confirm if there is an update for the Electricity Maps app in your App Store that you could install?

**Comment by haerribuhn** [comment]
I updated the app and the bug no longer occurs.

**Comment by haerribuhn** [comment]
Issue fixed
