### ISSUE TITLE
Month names in "Display data from past" selector are not abbreviated in Estonian

### ISSUE THREAD

**Issue by Ankitchaudharyy** [electricitymaps/electricitymaps-contrib#4609]
**Describe the bug**
X labels (Month names) are collapsing in 'Eesti' language.

**To Reproduce**
1. Go to 'http://localhost:8081/map'.
2. Choose 'Eesti' language from the language menu.
3. In the bottom of left panel, select '12 Kuud' under 'Display data from the past'.
4. See x labels in the image.

<img width="504" alt="Screenshot 2022-09-26 at 10 15 28 PM" src="https://user-images.githubusercontent.com/46367738/192335938-9fd0604c-02c0-4357-89bd-575689566ebd.png">

**Desktop (if relevant):**

**Smartphone (if relevant):**

**Comment by VIKTORVAV99** [comment]
This issue should already have been taken care of by #4588 but we have to wait for a new release in order for the changes to show on the app. I'll leave this issue open until then.

**Comment by Ankitchaudharyy** [comment]
Yes, Its shortening the month name using formatDateTick function in [timeaxis.jsx](https://github.com/electricitymaps/electricitymaps-contrib/blob/master/web/src/components/graph/timeaxis.jsx)

But not showed up in the UI.

**Comment by jarek** [comment]
I can confirm this in Firefox 104.0 on Ubuntu. Estonian seems to be the only language among our supported languages with this issue, so this might be a browser support error - or maybe month names aren't possible to abbreviate in Estonian?

**Comment by Ankitchaudharyy** [comment]
@jarek I agree. Its only in Estonian language.

Can these x-labels be rotated to 45 degree angle, to make it readable?

**Comment by VIKTORVAV99** [comment]
> @jarek I agree. Its only in Estonian language.
> 
> Can these x-labels be rotated to 45 degree angle, to make it readable?

Before making any such changes we should try and figure out why it's not abbreviated.

A quick test with the following code shows that there are indeed abbreviated months for Estonian but that they aren't used even when set to short, it does however work when there is additional output like a day.
Code:
```js
const options1 = {month: 'short', day: 'numeric' };
const dateTimeFormat1 = new Intl.DateTimeFormat('et', options1);
for (i = 0; i <= 11; i++){
	const date1 = new Date(2012, i);
	console.log(dateTimeFormat1.format(date1));
}
console.log("---")
const options2 = {month: 'short'};
const dateTimeFormat2 = new Intl.DateTimeFormat('et', options2);
for (i = 0; i <= 11; i++){
	const date1 = new Date(2012, i);
	console.log(dateTimeFormat2.format(date1));
}
```
Output:
```log
> "1. jaan"
> "1. veebr"
> "1. märts"
> "1. apr"
> "1. mai"
> "1. juuni"
> "1. juuli"
> "1. aug"
> "1. sept"
> "1. okt"
> "1. nov"
> "1. dets"
> "---"
> "jaanuar"
> "veebruar"
> "märts"
> "aprill"
> "mai"
> "juuni"
> "juuli"
> "august"
> "september"
> "oktoober"
> "november"
> "detsember"
```

**Comment by jarek** [comment]
Hm. I do wonder if this is a bug in browsers and/or `Intl.DateTimeFormat` localizations database. I'm not seeing how we could fix it, other than reducing number of month labels we show for the 12-month view, like skipping every other month name :thinking:

**Comment by Ankitchaudharyy** [comment]
```
const options2 = {month: 'short', day: 'numeric' };
const dateTimeFormat2 = new Intl.DateTimeFormat('et', options2);
for (i = 0; i <= 11; i++){
	const date1 = new Date(2012, i);
	console.log(dateTimeFormat2.format(date1));
}
```


If I include day as numeric in options2, then the output is 
```
1. jaan
1. veebr
1. märts
1. apr
1. mai
1. juuni
1. juuli
1. aug
1. sept
1. okt
1. nov
1. dets
```

Can we use ``` {month: 'short', day: 'numeric' } ``` and then just use shortened month name by cropping it only from the entire string?

**Comment by VIKTORVAV99** [comment]
> [jarek](https://github.com/jarek), [VIKTORVAV99](https://github.com/VIKTORVAV99)
> 
> ```
> const options2 = {month: 'short', day: 'numeric' };
> const dateTimeFormat2 = new Intl.DateTimeFormat('et', options2);
> for (i = 0; i <= 11; i++){
> 	const date1 = new Date(2012, i);
> 	console.log(dateTimeFormat2.format(date1));
> }
> ```
> 
> If I include day as numeric in options2, then the output is
> 
> ```
> 1. jaan
> 1. veebr
> 1. märts
> 1. apr
> 1. mai
> 1. juuni
> 1. juuli
> 1. aug
> 1. sept
> 1. okt
> 1. nov
> 1. dets
> ```
> 
> Can we use `{month: 'short', day: 'numeric' }` and then just use shortened month name by cropping it only from the entire string for all the languages or may be Estonian?

No not in a reliable way as all languages format things differently, some put the number first, some put it last etc.

For example in simple mandarin (zh-Hans) it would render like this:
> 1月1日
2月1日
3月1日
4月1日
5月1日
6月1日
7月1日
8月1日
9月1日
10月1日
11月1日
12月1日

**Comment by Kongkille** [comment]
We can use [formatToParts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts) which I believe was made for more complex locale-aware formatting

```
const options2 = {month: 'short', day: 'numeric' };
const dateTimeFormat2 = new Intl.DateTimeFormat('et', options2);
for (i = 0; i <= 11; i++){
	const date1 = new Date(2012, i);
	console.log(dateTimeFormat2.formatToParts(date1)[2].value);
}
```

Outputs:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/45588799/194295021-40e34db3-c785-47b7-a16b-8381bbdd5744.png">


Perhaps there's a larger question around whether we need to have a process for allowing overrides to intl formatting depending on the language but if it's only an issue for Estonian then this might just work

**Comment by Ankitchaudharyy** [comment]
Yes, Its issue with Estonian language only.
