### ISSUE TITLE
Language selected in web page is different from language shown.

### ISSUE THREAD

**Issue by Ankitchaudharyy** [electricitymaps/electricitymaps-contrib#4623]
**Is your feature request related to a problem? Please describe.**
For this app, we have local storage. It stores ```i18nextLng``` as key, and ```languageKey``` as value. 
When the tab is closed in browser, and reopens it takes language key from local storage and update and translates the language.

If ```Estonian``` is stored language in local storage, then it will show Estonian on new window.

But the issue is, In language select menu, 'English' is by default selected, even if the language is translated according to localstorage.

<img width="1725" alt="Screenshot 2022-09-29 at 7 19 00 PM" src="https://user-images.githubusercontent.com/46367738/193050394-8c4e4bad-0527-466f-92d9-def219a35013.png">

**Describe the solution you'd like**
Solution to this can be while selecting the language by default, it should fetch it from local storage. If not present there, then default could be English.

**Comment by Ankitchaudharyy** [comment]
Can I work on this issue ahead?

**Comment by VIKTORVAV99** [comment]
Sure 👍🏻
