### ISSUE TITLE
style must be either "decimal", "percent", or "currency" error on iOS 14.4.1

### ISSUE THREAD

**Issue by Fournier65** [electricitymaps/electricitymaps-contrib#4625]
**Describe the bug**
The app does not work at all
Error message: style must be either "decimal", "percent", or "currency"
Url: file:///private/var/containers/Bundle/Application/520DE3A2-3C5F-4A95-921D-4E7D5B663038/Electricity%20Maps.app

See screenshot

**Smartphone (if relevant):**
 - Device: iPhone 11 Pro
 - OS: IOS 14.4.1 (18D61) #
![52FAF9B5-F167-4346-AA23-3DBD9FF2E51D](https://user-images.githubusercontent.com/114708590/193162537-1979a0f5-606e-4b2f-abd5-6fa91d88f833.png)

**Comment by PPsyrius** [comment]
Possible duplication with #4570 ?

**Comment by tonypls** [comment]
I'll take a look at this on the simulator with the mentioned iOS and iPhone versions, is this the mobile app or the web app? If web app could you confirm which browser? Thanks

**Comment by Fournier65** [comment]
Mobile app 1.3.7

**Comment by Fournier65** [comment]
Upgrade to 16.0.2 (20A380) solved the issue. 
(it was documented that the issue only happens for 14.4 and lower versions)

**Comment by Fournier65** [comment]
Closing the issue

**Comment by Fournier65** [comment]
See related issue #4630
