### ISSUE TITLE
[Data Issue]: Free trial API GET request Italy zone not working

### ISSUE THREAD

**Issue by JotaroLucas** [electricitymaps/electricitymaps-contrib#4668]
### When did this happen?

16/10/2022 Down from 8 pm to 11 pm

### What zones are affected?

Italy Zone API not working
 https://api-access.electricitymaps.com/tw0j3yl62nfpdjv4/power-breakdown/latest?zone=IT
 {
  "error": "Request unauthorized for zoneKey=IT,requestType=latest,dataType=power-breakdown."
}

### What is the problem?

I just subscribed for a personal free trial and i couldn't get any data at all with a GET request. 
(I'm working on a power automate project for italy)
![Immagine 2022-10-16 232037](https://user-images.githubusercontent.com/115954064/196058885-49081faf-f706-4b52-b75f-3e816e2b31cd.png)

**Comment by madsnedergaard** [comment]
Hey, thanks for raising this!
It seems like it's not possible (via the trial access) to do aggregated country level (like IT) on countries where we have more regions.
As a workaround you can call the subzones/regions as seen on the map instead (e.g. IT-CNO).

I'll raise this problem with the relevant team and ask them to give an update on this issue :)

**Comment by JotaroLucas** [comment]
When will this be fixed?

**Comment by madsnedergaard** [comment]
Hey @JotaroLucas,
Is your trial still active? (Look for this box under the subscription):

![Screenshot 2022-10-18 at 14 37 40](https://user-images.githubusercontent.com/3296643/196431562-c60b4889-0b13-4f10-85c8-3c939253597d.png)

That error message indicates that the problem is something with the trial setup and not the actual API (which has data). 

If that is not the problem, then please reach out to the sales team via [our contact form here](https://www.electricitymaps.com/#contact-us) :)

**Comment by JotaroLucas** [comment]
yes trial is active germany works. 
![Immagine 2022-10-18 145141](https://user-images.githubusercontent.com/115954064/196434600-43b4e163-5166-4378-8edd-42393085343f.png)

**Comment by JotaroLucas** [comment]
it is true what you said. Only IT zones are working for me

**Comment by madsnedergaard** [comment]
I'm sorry about that - it's only a problem for the free trial, so if you decide to go paid after it will work :)

**Comment by JotaroLucas** [comment]
how much does it cost? I'm not using it for commercial purposes

**Comment by madsnedergaard** [comment]
Then maybe https://co2signal.com/ is what you need. If not, then please reach out to the sales team via [our contact form here](https://www.electricitymaps.com/#contact-us) :)

**Comment by JotaroLucas** [comment]
what is the auth key for this? It says http error

**Comment by JotaroLucas** [comment]
maybe i have have to wait 1 hour but sometimes the api goes down

**Comment by madsnedergaard** [comment]
CO2Signal is a different product than the commercial API, so you need to sign up for a new token on https://co2signal.com/
