### ISSUE TITLE
[Data Issue]: Electricitymix Netherlands

### ISSUE THREAD

**Issue by GENETX** [electricitymaps/electricitymaps-contrib#4669]
### When did this happen?

2022-10-16 and onwards it seems (maybe before)

### What zones are affected?

NL

### What is the problem?

The overall data seems to be far off. Today (2022-10-17) is a rainy day, but still the electricity map for the Netherlands shows a lot of PV generation. On the other hand, for the last two days, the contribution of hard coal seems to be very limited (way smaller than ENTSO-E reports), as well as the steady nuclear production. I assume the the fossil fuel generators are reported correctly by ENTSO-E. As a result, the CO2 emissions are very low and probably far off from what they should be realistically.

**Comment by madsnedergaard** [comment]
We have recently made great improvements for the Netherlands data, so should be good now :)
