### ISSUE TITLE
[Data Issue]: Exchange CO2 intensity in country view is unreasonably high

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#4677]
### When did this happen?

Ongoing

### What zones are affected?

NO, SE, DK and US.

### What is the problem?

The exchange shows a carbon intensity that is higher than both Norway's carbon intensity in country mode (45 g/co2eq) and higher than the average of NO->SE exchanges for zone mode (roughly 48.6 gco2eq)
![image](https://user-images.githubusercontent.com/30777521/196732730-1360c8ea-2c2d-4dd0-a5af-c8ebd48cd4e3.png)

UPDATE:
Exchange on map:
![image](https://user-images.githubusercontent.com/30777521/196759952-ad98e60d-2dfd-4fd7-b74f-6c952bd6307d.png)
Exchange on NO page:
![image](https://user-images.githubusercontent.com/30777521/196760033-2361cd36-97e9-482b-9089-56d8d3f57dfe.png)
Exchange on SE page:
![image](https://user-images.githubusercontent.com/30777521/196760115-d5495d4c-3e91-4cfb-86da-6b50b0b69861.png)

From these last 3 screenshots we can see there are in fact 3 diffrent co2eq values for this exchange but it looks like the value on the NO page is what should be used.

**Comment by VIKTORVAV99** [comment]
@pierresegonne @tonypls I think this might be a blocker for the aggregated country view and we should probably hold off on merging any others until we know what is going on. I am seeing this issue with multiple exchanges regarding aggregated countries.

This one is even more crazy, I mean how does this even work?
![image](https://user-images.githubusercontent.com/30777521/196761390-d2a81201-54f7-47d2-b643-a67295f183f2.png)

**Comment by madsnedergaard** [comment]
Ah, classic Sweden being good guys and sending us some spare carbon offsets to help us Danes look better on the map 😂

**Comment by Gazer75** [comment]
There also appears to be a duplicate border flow between North Norway and North Central Sweden.
As of writing this there is one flow from Norway to Sweden at 138MW and then a wrong one going Sweden to Norway at 749MW.
![NO-SE border error](https://user-images.githubusercontent.com/13599949/197484077-74ce827c-23b1-4ba6-a063-820773c4ce75.jpg)

**Comment by VIKTORVAV99** [comment]
> There also appears to be a duplicate border flow between North Norway and North Central Sweden. As of writing this there is one flow from Norway to Sweden at 138MW and then a wrong one going Sweden to Norway at 749MW. ![NO-SE border error](https://user-images.githubusercontent.com/13599949/197484077-74ce827c-23b1-4ba6-a063-820773c4ce75.jpg)

Is this on the app by any chance?
The app don't update quite as fast as the website so it's possible it don't have the latest code to filter out the zone exchanges when in country view and vice versa.

**Comment by Gazer75** [comment]
Its on the map on PC right now. And its visible in both zone and country view.

**Comment by VIKTORVAV99** [comment]
> Its on the map on PC right now. And its visible in both zone and country view.

I'll dig into it but I'd suggest you open a new issue for it as these are not related issues.

**Comment by tonypls** [comment]
> There also appears to be a duplicate border flow between North Norway and North Central Sweden. As of writing this there is one flow from Norway to Sweden at 138MW and then a wrong one going Sweden to Norway at 749MW. ![NO-SE border error](https://user-images.githubusercontent.com/13599949/197484077-74ce827c-23b1-4ba6-a063-820773c4ce75.jpg)

We're aware of this and getting fix out asap 👍

**Comment by VIKTORVAV99** [comment]
@pierresegonne I think the same issue is affecting some of the zone exchanges as well (not just country exchanges).

Between NO-NO2 to GB:
![image](https://user-images.githubusercontent.com/30777521/198819223-43ae1ac6-9151-4cb0-9220-31804b2d1685.png)
NO-NO2 carbon intensity:
![image](https://user-images.githubusercontent.com/30777521/198819247-57ffdeed-35e3-4102-8803-861484e80bb5.png)

I have only spotted it for this exchange but I felt it was worth mentioning.

**Comment by VIKTORVAV99** [comment]
Just adding this is affecting the new US aggregated data as well, on the screenshot below you can see 3 different US exchanges that have 3 different carbon emission factors.

- US->CA-BC: 68
- US->CA-AB: 721
- US->MX: 243

![image](https://user-images.githubusercontent.com/30777521/204352812-2a6e0363-33fd-414c-b56f-7facf07878b3.png)

**Comment by VIKTORVAV99** [comment]
As far as I can tell this has been fixed now! 🎉

**Comment by pierresegonne** [comment]
Well spotted @VIKTORVAV99 ;) 

A fix has been merged yesterday, it might not solve *all* of the issues that appeared, so let's keep an eye out and reopen this if the issue arises again :)
