### ISSUE TITLE
Translations needed country-zone toggle

### ISSUE THREAD

**Issue by Ankitchaudharyy** [electricitymaps/electricitymaps-contrib#4689]
## Description
Translation for `tooltips.aggregateinfo`, `aggregateButtons.country` & `aggregateButtons.zone` are missing in locals/*.json for all languages except English, Espanol, and Svenska.

Edit:
Dutch (DE) has also been translated in https://github.com/electricitymaps/electricitymaps-contrib/pull/5228

**Comment by madsnedergaard** [comment]
This has been fixed :)
