### ISSUE TITLE
Fix alignment of info button.

### ISSUE THREAD

**Issue by Ankitchaudharyy** [electricitymaps/electricitymaps-contrib#4690]
**Describe the bug**
Alignment for InfoButton for production-consumption toggle gets distorted when other language[Pyccknn] is selected.

<img width="546" alt="Screenshot 2022-10-22 at 2 52 57 PM" src="https://user-images.githubusercontent.com/46367738/197332020-a271116f-1a92-437c-a05b-2cbf385fd40a.png">

**Comment by Gr33nLight** [comment]
Can you assign me the issue? I can do this for you
