### ISSUE TITLE
Net border flow between Norway and Sweden shows in zone view

### ISSUE THREAD

**Issue by Gazer75** [electricitymaps/electricitymaps-contrib#4700]
There also appears to be a duplicate border flow between North Norway and North Central Sweden.
As of writing this there is one flow from Norway to Sweden at 138MW and then a wrong one going Sweden to Norway at 749MW.
![NO-SE border error](https://user-images.githubusercontent.com/13599949/197484077-74ce827c-23b1-4ba6-a063-820773c4ce75.jpg)

_Originally posted by @Gazer75 in https://github.com/electricitymaps/electricitymaps-contrib/issues/4677#issuecomment-1288645927_

**Comment by Gazer75** [comment]
After looking at this is looks like the number is the net border transmission between Sweden and Norway that is showing up in zone view. Changing to country view also doesn't remove the internal border flow arrows in Norway and Sweden.

**Comment by tonypls** [comment]
This is fixed, just needs to be deployed, WIP

**Comment by tonypls** [comment]
Deployed 🚀
