### ISSUE TITLE
Updated generation capacities for Norway

### ISSUE THREAD

**Issue by Gazer75** [electricitymaps/electricitymaps-contrib#4701]
If anyone plan to do capacity updates, please update these.

As of September 6th 2022
Hydro (rounded to nearest MW per zone):
NO1   3754 MW
NO2 11498 MW
NO3   4845 MW
NO4   5288 MW
NO5   8240 MW
Total 33625 MW

There is also some more wind installed in NO1 and NO4.
For NO1 Odal wind farm is now fully operational so capacity should be 385MW 
In NO4 Øyfjellet is still bringing online more turbines, but the zone capacity is now up to 962MW. It should increase by another 170MW when Øyfjellet is at its full 400MW installed capacity.
Total wind for Norway is now 4886 MW

**Comment by VIKTORVAV99** [comment]
Is it the same source as before?

**Comment by Gazer75** [comment]
Yep, NVE. Pulled out the hydro power database last month to be able to filter it.
Can view it here if you like: https://docs.google.com/spreadsheets/d/1_Wm17vaw9eHTjQ338AolQURa_VlRZgND6ZJOugXCNug/edit?usp=sharing

**Comment by nicolasca** [comment]
Hey ! Could I pick this issue (as a first one) ?
I could do that on Friday.

**Comment by VIKTORVAV99** [comment]
> Hey ! Could I pick this issue (as a first one) ?
> I could do that on Friday.

Sure! 🎉 
Do you want me to assign you?
