### ISSUE TITLE
Zone access issue on MacOS Safari

### ISSUE THREAD

**Issue by gregbarton** [electricitymaps/electricitymaps-contrib#4705]
**Describe the bug**
Total failure accessing any zone on MacOS Safari.  Chrome remains unaffected.

![image](https://user-images.githubusercontent.com/1505300/197594450-8c17342e-9dfb-4e11-84ba-a4b5e6dcd983.png)

**To Reproduce**
1. Go to 'https://app.electricitymaps.com/zone/GB' or any zone URL.
2. See error

**Expected behavior**
Display of zone UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/1505300/197595345-a0dd7c13-aa64-4ca4-b733-19564f23a68b.png)

**Desktop (if relevant):**
 - OS: MacOS 10.15.7
 - Browser: Safari
 - Version: 15.6.1

**Comment by VIKTORVAV99** [comment]
Does this happen for all zones or just a select few? Does it happen consistently every time you visit a zone?

**Comment by gregbarton** [comment]
All zones I’ve tried. (10 or so.) I haven’t done an exhaustive test.
