### ISSUE TITLE
clicking on a country on the map - error

### ISSUE THREAD

**Issue by RobvanderLinden** [electricitymaps/electricitymaps-contrib#4708]
When clicking on a country on the map:
Error message: undefined is not an object (evaluating 'g.join')
Url: https://app.electricitymaps.com/zone/NL

**Comment by VIKTORVAV99** [comment]
Could you provide some more information like what browser you used? What zones it happens on and if it happens consistently when you click on a zone?

**Comment by RobvanderLinden** [comment]
I'm using Safari 15.6.1 (15613.3.9.1.16, 15613) on MacOs Catalina 10.15.7
It happens consistently when clicking on a region.
