### ISSUE TITLE
Price graph cannot handle extreme negatives (-999$ MWh)

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#4729]
**Describe the bug**
The bars in the price graph overflows when there's a very high negative price. See screenshot for example.
I'm not sure how frequent this really is across the world, I just noticed by accident while looking at Australia.

I have verified that data is actually correct ([see AEMO graph here](https://aemo.com.au/energy-systems/electricity/wholesale-electricity-market-wem/data-wem/data-dashboard#market-balancing)), so this is only a frontend error.

**To Reproduce**
1. Go to https://app.electricitymaps.com/zone/AUS-WA
2. Scroll down to price graph

**Expected behavior**
The graph should not overflow if bars are extreme in any end.

**Screenshots**
<img width="446" alt="Screenshot 2022-10-30 at 20 51 05" src="https://user-images.githubusercontent.com/3296643/198899814-ac7147f8-fa80-494a-9587-949945416aea.png">

**Desktop:**
 - OS: MacOS
 - Browser: Chrome

**Smartphone:**
 - Device: iPhone 12 Mini
 - OS: iOS 16.0
 - Browser: Native app

**Comment by VIKTORVAV99** [comment]
How do we replicate this for the Nordic grid so we can test it properly? 😂
