### ISSUE TITLE
[Data Issue]: DK-DK2 consumption is nil and breakdown is 0

### ISSUE THREAD

**Issue by mbnissen** [electricitymaps/electricitymaps-contrib#4734]
### When did this happen?

2022-11-01 12:00

### What zones are affected?

DK-DK2

### What is the problem?

Consumption is nil and breakdown is 0.

Response from power breakdowns history range endpoint:

```
%{
    "createdAt" => "2022-10-27T00:51:07.021Z",
    "datetime" => "2022-10-30T00:00:00.000Z",
    "estimationMethod" => nil,
    "fossilFreePercentage" => 49,
    "isEstimated" => false,
    "powerConsumptionBreakdown" => %{
      "battery discharge" => 0,
      "biomass" => 0,
      "coal" => 0,
      "gas" => 0,
      "geothermal" => 0,
      "hydro" => 0,
      "hydro discharge" => 0,
      "nuclear" => 0,
      "oil" => 0,
      "solar" => 0,
      "unknown" => 0,
      "wind" => 0
    },
    "powerConsumptionTotal" => nil,
    "powerExportBreakdown" => %{"DE" => 351, "DK-DK1" => 20},
    "powerExportTotal" => 371,
    "powerImportBreakdown" => %{"DE" => 0, "DK-DK1" => 0},
    "powerImportTotal" => 0,
    "powerProductionBreakdown" => %{
      "battery discharge" => nil,
      "biomass" => 74,
      "coal" => 86,
      "gas" => 53,
      "geothermal" => nil,
      "hydro" => nil,
      "hydro discharge" => nil,
      "nuclear" => nil,
      "oil" => 17,
      "solar" => 0,
      "unknown" => nil,
      "wind" => 75
    },
    "powerProductionTotal" => 305,
    "renewablePercentage" => 49,
    "updatedAt" => "2022-10-31T09:49:23.675Z",
    "zone" => "DK-DK2"
  }
```

**Comment by madsnedergaard** [comment]
This is for the Electricity Maps API, right? In that case please reach out [through our commercial website](https://www.electricitymaps.com/#contact-us) so the right people can help :)

**Comment by mbnissen** [comment]
@madsnedergaard when I follow the website Im just send here again. So now Im in a endless loop :|

**Comment by madsnedergaard** [comment]
Not sure I understand, did you use the contact form on https://www.electricitymaps.com/ ?

**Comment by mbnissen** [comment]
The Contact Form is for Commercial Inquiries. 

We are already using the API, but this is related to missing or invalid data

**Comment by madsnedergaard** [comment]
Hey again, sorry for the delay in getting back to you!

I'm not 100% sure what happened here, but I only found one hour in 2022 where this happened for `DK-DK2` (and none for `DK-DK1`). We'll investigate further how/why it happened, but at least it doesn't seem like a common thing :)

**Comment by mbnissen** [comment]
I think its related to daylights savings time

**Comment by VIKTORVAV99** [comment]
@mbnissen the API dates should be in UTC in accordance with ISO standards so that should be unaffected by daylight savings and time zones issues.

@madsnedergaard have you had the time to investigate it yet? I do find it odd that the estimation method didn't catch it and estimate that hour even if the parser data was missing.

**Comment by madsnedergaard** [comment]
It's on our backlog, but since it's happening so rarely it's not something that we're prioritising right now :) I suggest we keep the issue open for now to track this.

**Comment by VIKTORVAV99** [comment]
@FelixDQ do you think we can close this now?
