### ISSUE TITLE
[Data Issue]: US-SPP source is down

### ISSUE THREAD

**Issue by pierresegonne** [electricitymaps/electricitymaps-contrib#4753]
### When did this happen?

Since around `2022-07-01` if I remember correctly.

### What zones are affected?

`US-CENT-SWPP`

### What is the problem?

The [parser](https://storage.googleapis.com/electricitymap-parser-logs/US-CENT-SWPP.html) encounters a lot of issues.

It is for example unable to run the `productionPerModeForecast` parser. 

The production parser was changed to EIA for that reason [here](https://github.com/electricitymaps/electricitymaps-contrib/pull/4639) 

The issue is therefore to answer the following questions:

1. Is the source completely down?
2. If yes are there any alternatives besides EIA?
3. If no, can we fix some of the parsers?

**Comment by KabelWlan** [comment]
As already mentioned in #4345 the source is geo blocked. I just tested it again and I do have access to the website (https://marketplace.spp.org/) with a vpn.

**Comment by madsnedergaard** [comment]
I'll add it to our US proxy :)
