### ISSUE TITLE
Missing unit on price chart

### ISSUE THREAD

**Issue by pierresegonne** [electricitymaps/electricitymaps-contrib#4764]
**Describe the bug**

The unit for the price chart is missing the currency symbol.

<img width="592" alt="Screenshot 2022-11-14 at 17 33 43" src="https://user-images.githubusercontent.com/32778266/201714644-491bc25b-7e19-4d1b-86e7-ef9d62d91ebc.png">

**To Reproduce**

Go on live map and go to price chart for historical views (not real time)

**Expected behavior**
Currency should be specified

**Screenshots**
See above

**Comment by VIKTORVAV99** [comment]
This appears to be a backend issue.
In aggregated state files the data is returned as this:
```json
                "price": {
                    "currency": "\"EUR\"",
                    "value": 31.86
                },
```
When it should be returned as this like the daily state file:
```json
                "price": {
                    "currency": "EUR",
                    "value": 31.86
                },
```
Granted it would be possible to work around this in the frontend and sanitize/clean up the string but it would increase tech debt and complexity. The best option would be to change the aggregation function in the backend return strings in the same format as the daily state.
