### ISSUE TITLE
Italian interconnectors disappear when toggling country aggregation

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#4767]
**Describe the bug**
Italian interconnectors disappear when toggling country aggregation

**To Reproduce**
1. Move to Italy
2. Click on "Country" aggregation
3. Notice some interconnectors have disappeared (e.g. Montenegro)

**Expected behavior**
All interconnectors should be present

**Screenshots**
<img width="45%" alt="image" src="https://user-images.githubusercontent.com/1655848/201930071-60d7caed-b82b-47b7-ac2e-75e7b88d9140.png"> <img width="45%" alt="image" src="https://user-images.githubusercontent.com/1655848/201930116-36783089-ab0f-4166-bff7-8f92cf3f17d3.png">

**Comment by VIKTORVAV99** [comment]
Looks like we haven't added a Italy to Montenegro exchange at first glance.

I'll take a look at it.

**Comment by purplepaste5** [comment]
@VIKTORVAV99 Hey! I'm looking to start contributing to open source projects and this one has caught my eye. I have setup the local dev environment and am wondering if I can take a crack at this?

**Comment by VIKTORVAV99** [comment]
Sure thing @purplepaste5!

I'll assign you and if there is any problems just give me a ping and I'll see if I can help out.

**Comment by purplepaste5** [comment]
@VIKTORVAV99 thanks!

**Comment by purplepaste5** [comment]
@VIKTORVAV99 https://github.com/electricitymaps/electricitymaps-contrib/pull/4800
