### ISSUE TITLE
Zone g co2eq/kWh values is exceeding the range defined in the frontend (max 800 g co2eq/kWh) 

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#4771]
With the recent updates to the co2eq/kWh factors we now exceed the co2eq/kWh range defined in the frontend (0-800 g co2eq/kWh).
Example with the current range in the lower right corner:
![image](https://user-images.githubusercontent.com/30777521/202039603-318441bc-868a-4906-b502-28548d6ff263.png)
Since the current highest value is 1197 g co2eq/kWh for oil in US-NW-WACM I propose we update the new range to 0-1200 g co2eq/kWh.

**Comment by VIKTORVAV99** [comment]
> Very good point. However, both the Faroe Islands have an even higher value with 1437 g co2eq/kWh for oil. The range would probably need to be something like 0-1500 g co2eq/kWh.

Jesus that's high.
But yeah then 0-1500 seems like a better range. 👍🏻

**Comment by BStephenBB** [comment]
Would love to start contributing to this project! Could I work on this issue?

Would we want to add a 6th step to the legend and have it show `0 300 600 900 1200 1500`? Or keep 5 steps and sacrifice having nice round numbers?

**Comment by BStephenBB** [comment]
Yes please!

**Comment by VIKTORVAV99** [comment]
Done!
