### ISSUE TITLE
Carbon intensity for Nuclear is not the same for all Européan Countries as mention 5 g CO2 / kWh

### ISSUE THREAD

**Issue by BXMichel** [electricitymaps/electricitymaps-contrib#4781]
In a country where electricity is very carbon-free, such as France, this does not really add CO2 to the operation of the plant, which by itself does not produce any.
On the other hand, in a country with little nuclear power (which is the case for almost all the other countries), the electricity is generally quite dirty, and this is what adds CO2 to the nuclear power plant taken as a whole, with everything it needs to function.

Dans un pays où l'électricité est très décarbonée, comme la France, cela n'ajoute pas vraiment de CO2 au fonctionnement de la centrale qui par elle même n'en produit pas du tout.
Par contre, dans un pays peu nucléarisé (ce qui est le cas de la quasi totalité des autres pays), l'électricité est globalement assez sale, et c'est cela qui rajoute du CO2 à la centrale nucléaire prise dans sa globalité, avec tout ce dont elle a besoin pour fonctionner.

Merci

PS France is even less than 4 g CO2 / kWh
https://www.sfen.org/rgn/les-emissions-carbone-du-nucleaire-francais-37g-de-co2-le-kwh/

**Comment by VIKTORVAV99** [comment]
I have discussed this somewhat already with @pierresegonne but regarding Sweden and I think the plan is to leave it at the new EU averages for now until we find verifiable 3rd party research that don't come from Vattenfall (or EDF in the case for France).

The team has a lot of work going on at the moment creating regional averages for the rest of the world (among other things) so I don't think this will be a priority right now since the change would be so small on the resulting co2eq intensity, but I'm sure we will get around to looking at these values closer once that is done (and we can retroactively change the emissions factors if the numbers can be independently verified).

I'll leave this issue open for now so we can keep track of these requested changes to regional values though, I hope you understand. In the meanwhile if you find a 3rd party report or another source please do share it.

**Comment by BXMichel** [comment]
OK understood nevertheless I give you 3 others links from EDF & last summer 2022
https://www.edf.fr/sites/groupe/files/2022-06/edfgroup_acv-4_plaquette_20220616.pdf

https://www.youtube.com/watch?v=HrJTC5Aokjs&ab_channel=Sfen-Soci%C3%A9t%C3%A9fran%C3%A7aised%27%C3%A9nergienucl%C3%A9aire

https://www.lemonde.fr/blog/huet/2022/06/22/nucleaire-4-g-de-co2-par-kwh/ 
Merci

**Comment by asfi30** [comment]
Here  (https://www.iaea.org/sites/default/files/iaea-ccnp2022-body-web.pdf ) is a report from International Energy Agency. They confirm 5-6 gCo2eq/KWh. The general concept is to be even less if heat is used for Hydrogen production. In Bulgaria we already have program  part of the heat from the NPP to be used for district heating as well.  It adds up about 54 000 MWh/year (page 37 of the report to confirm) as direct heating. Number increases as more people getting connected still.  The other point is that until couple of years ago Nuclear power was measured mainly as carbon sink. In a sense measuring saved CO2 eq emissions saved in comparison to emissions produced by coal CHP .

**Comment by tortoisedoc** [comment]
Some more food for thought : are the numbers given in Life Cycle Assessment of Uranium  also considered in the calculations ? 
See for example Lenzen, 2008; Fthenakis and Kim, 2007

(Includes the uranium mining stage, the uranium milling stage, the conversion to uranium hexafluoride, enrichment, fuel fabrication, reactor construction, reactor operation, decommissioning, fuel re-processing, nuclear waste storage, nuclear waste disposal, and transport).

**Comment by VIKTORVAV99** [comment]
> Some more food for thought : are the numbers given in Life Cycle Assessment of Uranium  also considered in the calculations ? 
> 
> See for example Lenzen, 2008; Fthenakis and Kim, 2007
> 
> or
> 
> Poinssot et al., 2014; Norgate et al., 2014; Mallia and Lewis, 2013; Hondo, 2005
> 
> 
> 
> (Includes the uranium mining stage, the uranium milling stage, the conversion to uranium hexafluoride, enrichment, fuel fabrication, reactor construction, reactor operation, decommissioning, fuel re-processing, nuclear waste storage, nuclear waste disposal, and transport). 

Was a while ago since I looked at the paper but they should be, and in the case of at least Vattenfall they break it down by, mining, processing and storage even after it has been used. This is actually where most of the emissions come from in that environmental declaration.

**Comment by madsnedergaard** [comment]
The full study from UNECE is available here: https://www.iaea.org/sites/default/files/iaea-ccnp2022-body-web.pdf

And here one of the author's answer some common criticism of the paper: https://x.com/ThomasGibon/status/1714566947008843796?s=20

This paper specifically on LCA models of nuclear is also very interesting and points towards the same approximate number: https://pubs.acs.org/doi/full/10.1021/acs.est.3c03190

**Comment by madsnedergaard** [comment]
Closing this issue in favor of gathering discussions here: https://github.com/electricitymaps/electricitymaps-contrib/discussions/2629
