### ISSUE TITLE
Production carbon footprint calculation

### ISSUE THREAD

**Issue by ecl98** [electricitymaps/electricitymaps-contrib#4788]
Hi, I guess there's an error in the production CO2e calculation. 
For example, in this moment (at midnight between saturday 19/11/22 and sunday 20/11/22) Germany CO2e/kWh emission in production is 543g and in consumption is 692g. It is not possibile since Germany is importing energy from country with a lower CO2e/kWh emission. 
I think that you are calculating the CO2e in production by the following formula:
sum(energy_source_power*energy_source_CO2e) / tot.energy.consumption
It is misleading and you should divide by tot.energy.production
With my formula Germany CO2e/kWh emission in this moment is of 759g which is in accordance with my previous consideration. 
Hope my message is understandable, english is not my primar language and I'm quite tired. 
Thank you, have a nice night :)

**Comment by Tachy** [comment]
![7C87900D-3B13-46AD-9FC7-86167D0CD0B1](https://user-images.githubusercontent.com/2771003/202890897-b9a31073-9709-48c2-b2fe-58fc471b45e2.jpeg)
![A38C5A3F-27C6-44ED-A24C-1771AB23FB98](https://user-images.githubusercontent.com/2771003/202890900-398b6359-1b4f-40a7-99a5-fe2a7d9b0c81.jpeg)

**Comment by VIKTORVAV99** [comment]
Thanks for opening the issue, however this is already being tracked in #4776 so I'll be closing this one as it's a duplicate.
