### ISSUE TITLE
Biomass emission factors

### ISSUE THREAD

**Issue by Stefhis974** [electricitymaps/electricitymaps-contrib#4796]
### Discussed in https://github.com/electricitymaps/electricitymaps-contrib/discussions/4794

<div type='discussions-op-text'>

<sup>Originally posted by **Stefhis974** November 21, 2022</sup>
Dear all,

I went on the Electricity map website to better understand the recently announced emissions factors update. I am quite puzzled about the emisssion factor value for biomass power plant in Europe. It is stated that “Direct biomass emissions are generally accounted as 0 (See [BEIS 2021]). We have therefore accounted reported emissions from power plants as upstream emissions. » But in the EU ETS, biomass combustion is accounted to 0. Thus emissions reported in the EU ETS for a so called biomass power plant means that the plant runs under a co-combustion mode ie burning biomass + fossils fuels and reported emissions are due to the combustion of fossil fuels. Nothing to do with the biomass life cycle. In one of your file, you mentioned about a biomass to power plant in France that is reported to emit more than 800 gr CO2/KWh in 2021. In fact the plant did run mostly on coal in 2021. 

I really believe that there an issue here since your emissions factors for biomass plant are not life cycle emissions factors but rather co-combustion emissions. This is very different, but I may be wrong. Let me know your views on this. 

Best Regards. </div>

**Comment by VIKTORVAV99** [comment]
Concerns about the new biomass co2eq emission values are being tracked in #4777 and since this issue don't create a new issue, I'll close this as a duplicate but feel free to add any concerns you have to #4777.
