### ISSUE TITLE
[Data Issue]: Export CO2 emissions are much higher than production

### ISSUE THREAD

**Issue by basetian** [electricitymaps/electricitymaps-contrib#4813]
### When did this happen?

2022-11-28

### What zones are affected?

Denmark and Sweden in aggregated view

### What is the problem?

Denmark to Sweden has an export CO2 emission of 979g, despite Denmark only having production emissions of 137g.  Something seems fairly wrong

![grafik](https://user-images.githubusercontent.com/5641706/204292771-63f767ac-def0-48f2-b392-88e0d08b8e99.png)

**Comment by VIKTORVAV99** [comment]
Closing this as it is already being tracked in #4677, feel free to add any additional information to that issue.
