### ISSUE TITLE
Replace "electricityMap" with "Electricity Maps" in the config files

### ISSUE THREAD

**Issue by pierresegonne** [electricitymaps/electricitymaps-contrib#4816]
## Description

We are mentioning `electricityMap` multiple times in the config files. It would be awesome if someone could replace all of these mentions to `Electricity Maps`. 

Ex: https://github.com/electricitymaps/electricitymaps-contrib/blob/master/config/zones/CH.yaml multiple zone overrides cite as source `electricityMap`

**Comment by SaumyaBhushan** [comment]
Hi @pierresegonne ! Can you please review the pull request?

**Comment by VIKTORVAV99** [comment]
> Hi @pierresegonne ! Can you please review the pull request?

I'll take a look at it later today.

**Comment by SaumyaBhushan** [comment]
Sure Thanks @VIKTORVAV99
