### ISSUE TITLE
[Data Issue]: GB wind missing, reading zero

### ISSUE THREAD

**Issue by samtygier** [electricitymaps/electricitymaps-contrib#4829]
### When did this happen?

Around 2022-12-02

### What zones are affected?

GB

### What is the problem?

GB wind is currently reading as zero. I know it has low for the last week, but other sources are showing ~ 10GW:

e.g.

https://app.electricitymaps.com/zone/GB (24h)
![image](https://user-images.githubusercontent.com/1113988/205433858-83948b99-f1b7-46a9-a247-38fabca54f46.png)

https://gridwatch.templar.co.uk/ (24h)
![image](https://user-images.githubusercontent.com/1113988/205433905-78b577cb-5184-454e-a9ed-9d86c7703c1e.png)

https://gridwatch.templar.co.uk/ (1week)
![image](https://user-images.githubusercontent.com/1113988/205433640-48311e0d-b844-4605-b209-91e1dffe934f.png)

https://www.energydashboard.co.uk/fourtyeight 
![image](https://user-images.githubusercontent.com/1113988/205433821-06ab0357-26b1-436c-a533-93ca3676f21b.png)

**Comment by VIKTORVAV99** [comment]
That's weird, it should definitely not be zero.
@unitrium could you take a look at this?

**Comment by pierresegonne** [comment]
Hey @samtygier Thanks for reporting this issue :)

It should have been fixed by now
