### ISSUE TITLE
[Data Issue]: Corsica no data anymore

### ISSUE THREAD

**Issue by ludo20243** [electricitymaps/electricitymaps-contrib#4833]
### When did this happen?

Hello, why corsica became blank area now? Why data aren’t published anymore ?

### What zones are affected?

Corse (France)

### What is the problem?

Data after 12 November isn’t available

**Comment by VIKTORVAV99** [comment]
It is the same as #4828 as they use the same parser so I'll close this issue but feel free to add any related information to #4828.
