### ISSUE TITLE
Bad french translation

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#4845]
Hi,

In the snapshot below, for the french version, the text in yellow should be "représentant 38.35% des émissions de CO2".

![translation](https://user-images.githubusercontent.com/364418/206524844-7dec4f48-7f16-4caa-8210-11148dede64a.png)

**Comment by cynding** [comment]
Hi! Can I be assigned this issue?

**Comment by VIKTORVAV99** [comment]
Sure thing!
