### ISSUE TITLE
Wind Installed Capacities

### ISSUE THREAD

**Issue by asfi30** [electricitymaps/electricitymaps-contrib#4865]
## Description
Hi,

According to Betz's Law Theoretical Maximum of Wind turbines can NOT be more than 59.3%. In Some areas (i.e Romania, Serbia) it shows utilization 70-80% of installed capacities. It might have other areas as well. In any case, any area that exceed the 59% value, this simply means that the installed capacity needs to be updated as they are higher.

**Comment by VIKTORVAV99** [comment]
Hi @asfi30!
Unless I'm mistaken that law only refers to efficiency?
I think (and I hope) this is taken into account when calculating the installed capacity of each turbine?

In either case I don't see how this is a issue in it self and if you think there is a issue with the capacity for a region or zone I suggest opening a issue for that directly.

**Comment by asfi30** [comment]
Hi,

I give direct example with Bulgaria- recently updated. Installed wind power is 705MW in total. If you see 60% production that is 0.6*705=423 MW in particular hour. This make it impossible to achieve due to the Betz's Law. This can only mean that real installed power is more than 705 MW, So if you have just 1 Turbine with installed power of 10MW, this turbine never make more than 6MW electricity. Same for Wind farms with multiple number of turbines apply. And this is regardless of the Turbine design. In reality in Electricity Maps (EM) efficiency of total Installed capacity is presented as: (utilizing 39.98 % of installed capacity). I saw you have Estimate model and this might be helpfull for it as well.

**Comment by jarek** [comment]
Yes but the question is whether the 705 MW figure already takes the limit into account. The limit is the amount of energy that can ever be extracted from wind. It would make some sense to rate wind turbines on their actual max output (taking the 59.3% limit into account), so capacity _could_ be 1189 MW theoretical, 705 MW practical. I don't know if this is actually done - do companies actually sell a "10 MW" turbine that can't ever produce more than 6 MW?

**Comment by jarek** [comment]
As a data point, right now IESO lists Ontario as [producing 3.85 GW of wind energy](https://ieso.ca/en/Power-Data) from [4.88 GW installed capacity (as of September 2022)](https://ieso.ca/en/Power-Data/Supply-Overview/Transmission-Connected-Generation). That's about 79% of capacity (it is quite windy today). Per the [September 2022 reliability outlook report](https://ieso.ca/en/Sector-Participants/Planning-and-Forecasting/Reliability-Outlook), no more than 60 MW of wind generation capacity would have been added since September. It seems more straightforward to conclude that at least in Ontario's case, the rated capacity takes the theoretical limit of extraction of energy from wind into account.

**Comment by asfi30** [comment]
Hi.

The 10MW turbine was illustrative example only. In any case if for wind is taken Nominal Power Output this is reasonable explanation. It could be my mistake as for other sources (i.e coal, gas, biomass, hydro) it is stated the maximum power installed, which in reality can not be achieved, which represents in a sense the efficiency. Our Electric System Operator (ESO) provides weekly report ( https://www.eso.bg/doc/?39 ) Based on the 705MW installed capacity, the average wind turbine efficiency is: 1413926MWh/345(days)/24(hours) /705(installed capacity)*100 = 24.22% from jan 1st 2022 until 11th December 2022. 

In any case it is important to have common understanding if Nominal or Maximum Power is presented in different geographical zones.

**Comment by VIKTORVAV99** [comment]
An other example would be Åland (AX) where we counted the individual (rated) capacity of each installed wind turbine and that added up to 63.8 MW and I have seen utilization at 99% here when it's really windy. 

This makes me think the rated capacity for wind turbines already take Betz's Law Theoretical Maximum into account.

**Comment by asfi30** [comment]
I guess this is the case then.
