### ISSUE TITLE
Mobile app don't save user settings

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#4872]
I like to use country mode instead of zone mode on the mobile app. But when I launch it, I always got the zone mode. I go in settings, select country mode, but when I close the app and launch it again, the zone mode is back, my settings are not saved.

Could you consider store the user settings on the mobile app ?

**Comment by VIKTORVAV99** [comment]
@madsnedergaard this should be simple enough to add to the rewrite right?

I know you don't want to add more features but it would only involve saving the atom state to local storage.

**Comment by madsnedergaard** [comment]
Great feedback! 🙌  And yes, we're already doing it in [the new app](https://github.com/electricitymaps/electricitymaps-contrib/issues/4731), so once that is ready this will be fixed :)

**Comment by VIKTORVAV99** [comment]
Since the new app has been deployed to all platforms I'll close this issue.

**Comment by phiphou** [comment]
Yes, I confirm the issue has been fixed.
