### ISSUE TITLE
All installed apps that used to work cover and connect to all apps.  It has now been blocked and reset and redirected.  Please allow me to put an end to this problem.

### ISSUE THREAD

**Issue by Masterkenshin** [electricitymaps/electricitymaps-contrib#4877]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (if relevant):**

**Smartphone (if relevant):**

**Additional context**

**Comment by VIKTORVAV99** [comment]
Not really sure what you mean here?
Could you provide more information and fill out the issue template correctly so we can triage this issue?

**Comment by VIKTORVAV99** [comment]
Closing this as there has been no response from the creator of the issue and there is no description of the issue at hand.
