### ISSUE TITLE
Historical Data Canary Islands and Balear Islands

### ISSUE THREAD

**Issue by strassburger** [electricitymaps/electricitymaps-contrib#4883]
Historical data missing of Canary Islands and Balear Islands beginning at 12 month.
Verified El Hierro data:
Data exist in source since at least 2015-01-20 in the source:
See:
https://demanda.ree.es/visiona/canarias/el_hierro5m/total/2015-01-01
Sorry, electricity map really was better quality in past time.....
Rainer

**Comment by strassburger** [comment]
misstype, sorry.
Historical data missing of Canary Islands and Balear Islands beginning at **12 month**

**Comment by VIKTORVAV99** [comment]
> Historical data missing of Canary Islands and Balear Islands beginning at 12 month. Verified El Hierro data: Data exist in source since at least 2015-01-20 in the source: See: https://demanda.ree.es/visiona/canarias/el_hierro5m/total/2015-01-01

I'll ask the team to re-fetch the data but even then it might take a while to show up.

> Sorry, electricity map really was better quality in past time..... Rainer
This is a totally unnecessary comment. What exactly are we supposed to do with this information?
Critique is fine as long as it's constructive, this is not.
(I'd even argue this is false but that's besides the point.)

**Comment by strassburger** [comment]
More exactly about Hierro missing data en electricity map:
Looks like data of November 2021 is missing.

Result is 12 month data missing:
![grafik](https://user-images.githubusercontent.com/28303688/208746156-7405373b-0c79-4ee4-99b8-22270df18d7c.png)
Changingmonth selector  to Okt, Sep, Aug, Jul, Jun, Mai, April, Mär, Febr, Jan data shows up.

And 5 years data missing:
![grafik](https://user-images.githubusercontent.com/28303688/208746847-82537545-9311-4053-b80e-cc92faec3db7.png)
Changing year selector to 2020, 2019, 2018, 2017 data shows up.

Checked source from 1.Nov  2021 till 30.Nov 2021:
https://demanda.ree.es/visiona/canarias/el_hierro5m/total/2021-11-30
Hope helps

**Comment by VIKTORVAV99** [comment]
We are re-fetching data for this zone and several other right now but it will take a while until all the data has finished processing.

**Comment by strassburger** [comment]
@VIKTORVAV99 
Just a question to understand:
What means "a while" just to have an idea.
Really interested special in El Hiero data.
I give and gave the link to electricitymaps to friends living on EL Hierro or interested where am I living right now. Special the history data. It is a great feature. 
So i look every day  myself. 
Watched development of the electricity of El Hierro since first production hours of the the project "Gorona del Viento" https://www.goronadelviento.es/ and collected information about it personal. https://casaprimavera.de/rst-cloud-data/.
Was the first who asked to put El Hierro in electricitymaps, what was realised, thanks

**Comment by VIKTORVAV99** [comment]
Not really sure how long it will take but we are fetching years worth of 5 minute data and then processing that so it can a significant amount of time. The only thing we can do now is wait while the processing pipelines runs.

**Comment by strassburger** [comment]
@[VIKTORVAV99
Sorry about my impatience. With 72 i do not have the time like young people,sorry....
Feliz navidad from "The Island at the End of the world" to you and all electricity members and callaboratores.
Rainer

**Comment by VIKTORVAV99** [comment]
Just providing a small update, I don't think the re-fetch is completely done yet but there is now historical data up until October 2022 at least. Hopefully the last month should get added soon 🙂.

**Comment by strassburger** [comment]
@VIKTORVAV99,
Good news:
looks like all Canaria islands date up to date, thanks for solving this problem.

Less good news:
looks like all Balear islands still have problems with historic data:
More precise:
data of year 2022 not shown.

2022:
![grafik](https://user-images.githubusercontent.com/28303688/210275247-743d428b-9485-4593-ad67-cae9f7e87ba1.png)

Other years are OK:
![grafik](https://user-images.githubusercontent.com/28303688/210275439-75d21d50-74df-4bec-8ca7-5e4ae9a1992c.png)
Sure it will be fixed soon
Rainer

**Comment by VIKTORVAV99** [comment]
Actually there is 2022 data and it's 2018 that is missing but due to #4916 they are not aligned properly and is not colored accurately on the map. This has already been fixed in the refractor of the frontend and if everything goes as planned it should be released this month.

**Comment by strassburger** [comment]
@strassburger VIKTORVAV99
Finally even Balear Islands shows 5 years data. 
Only 2018 data empty.
Thanks for all the work.
Think this issue can be closed?

**Comment by VIKTORVAV99** [comment]
Yeah hopefully we can get data further back at a later date but right now I think we can close it.
