### ISSUE TITLE
CA-ON (Ontario) Emission factors

### ISSUE THREAD

**Issue by pierresegonne** [electricitymaps/electricitymaps-contrib#4886]
**Is your feature request related to a problem? Please describe.**

What appear to be trustworthy emission factors have been computed for Ontario. See [here](https://github.com/electricitymaps/electricitymaps-contrib/discussions/4869) and [here](https://github.com/electricitymaps/electricitymaps-contrib/discussions/4791#discussioncomment-4295383) for discussions.

**Describe the solution you'd like**
Add the identified lifecycle emission factors for CA-ON

* Coal (not applicable, retired in 2014): 1,069gCO2/kWh
* Natural Gas: 497gCO2/kWh
* Hydro: 22gCO2/kWh
* Wind: 10.69gCO2/kWh
* Nuclear: 4.8gCO2/kWh
* Solar: TBD with INCERACV as was done for other zones, see [here](http://viewer.webservice-energy.org/incer-acv/app/)

<img width="705" alt="Screenshot 2022-12-20 at 11 38 42" src="https://user-images.githubusercontent.com/32778266/208647378-ca90315e-ab3a-4f70-bc8a-140da88e2f3e.png">

The source for those should be (except for solar)

`Mallia, Eric, and Geoffrey Lewis. "Life cycle greenhouse gas emissions of electricity generation in the province of Ontario, Canada." The International Journal of Life Cycle Assessment 18.2 (2013): 377-391.`

with a link to https://link.springer.com/article/10.1007/s11367-012-0501-0

**Comment by MisterClean** [comment]
🙋‍♂️ I'll take this one!

**Comment by VIKTORVAV99** [comment]
Sure thing! I'll assign the issue to you and if you have any questions just ping me and I'll see what I can do.

**Comment by Nil-Cipher** [comment]
Does this still need help?

**Comment by VIKTORVAV99** [comment]
Looks like it does as the other PR has gone stale. Feel free to pick this up but please take note of the feedback for the other PR.
