### ISSUE TITLE
Update link is almost invisible when available update on web app

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#4892]
The update link is almost invisible when an update is available on the web app (see snapshot).

![FireShot Capture 1126 - Electricity Maps - Émissions CO₂ de la consommation électrique en te_ - app electricitymaps com](https://user-images.githubusercontent.com/364418/208707928-2f8a0120-328f-43d5-b090-6d7068336330.png)

**Comment by Ankitchaudharyy** [comment]
How to reproduce this issue?

**Comment by VIKTORVAV99** [comment]
> How to reproduce this issue?

It's pretty tricky to reproduce as it's only triggered when an update has been released and the website is saved in the local cache already. However I do think this will be fixed in the frontend re-write.

**Comment by Ankitchaudharyy** [comment]
https://github.com/electricitymaps/electricitymaps-contrib/blob/0f2174c6a7a15bb372486cfd8a55cbbe58df78b9/web/src/layout/main.jsx#L98

Setting `isClientVersionOutdated` to `true`, can reproduce it for fixing this issue in localhost.

**Comment by Ankitchaudharyy** [comment]
@VIKTORVAV99, Can I work on this issue?

**Comment by VIKTORVAV99** [comment]
@Ankitchaudharyy sure but like I said before I think this has already been fixed in the rewrite of the frontend.

But if you still want to work on it do feel free to do so and I'd happily assign you if you wish.

**Comment by Ankitchaudharyy** [comment]
I will work. Assign it to me.

**Comment by VIKTORVAV99** [comment]
Sure thing!

**Comment by Ankitchaudharyy** [comment]
Thanks, @VIKTORVAV99 for the quick response. Appreciate it. :)
