### ISSUE TITLE
Timeslider period are not aligned with data period

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#4916]
As you can see in the image below the time slider is set to December 2021 but the data is from September 2022 (and this is correct, we did not have a parser in place for FO subzones in December 2021 and it don't support fetching historical data).

This causes some inconsistencies and is very confusing to users when using the map as the time slider says data is unavailable for September 2021.

So the issue seems to be that the available data is placed first in the time slider regardless of what period the data is actually for.

September 2022 data:
![image](https://user-images.githubusercontent.com/30777521/210106913-256b208e-a8df-4de4-906b-9e6a02ef370a.png)
November 2022 data:
![image](https://user-images.githubusercontent.com/30777521/210106577-6b8f365b-1315-48e2-b98e-c2801d44c62e.png)

**Comment by Ankitchaudharyy** [comment]
I can work on this. You can assign it to me.

**Comment by VIKTORVAV99** [comment]
I really appreciate the offer but I'm not sure this is something that can be fixed in the contrib repository alone and might need changes in the backend as well as I haven't noticed any frontend changes that would have broken this.

Also it seems to still be working correctly at https://beta.electricitymaps.com (which is the rewrite) I'm not sure we want to invest too much effort to fix it in the current version.

@madsnedergaard how do you think we should proceed? (Basically is the frontend still on track? 😅)

**Comment by madsnedergaard** [comment]
Yes, we've tackled this in the rewrite - both on frontend and backend, so let's not do more work on this topic here :)
Keeping this issue open so that we can ensure it still works after release
