### ISSUE TITLE
[Data Issue]: Denmark exchanges missing

### ISSUE THREAD

**Issue by KabelWlan** [electricitymaps/electricitymaps-contrib#4945]
### When did this happen?

Started a few days ago.

### What zones are affected?

Dk-DK1, Dk-DK2

### What is the problem?

All of Denmarks exchanges  are missing, exept of the ones with Sweden.

![Unbenannt](https://user-images.githubusercontent.com/49598085/211830230-94306b36-dc9c-45f1-9ec2-d87a6ef0fef6.png)

**Comment by VIKTORVAV99** [comment]
It has already been fixed in #4936 but we need to wait for a new release.
