### ISSUE TITLE
Greece Installed Capacities

### ISSUE THREAD

**Issue by asfi30** [electricitymaps/electricitymaps-contrib#4947]
## Description
Hi and Happy new year all,

Greece Installed capacities needs to be updated, From the ENTSO E platform https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2021+00:00|UTC|YEAR&dateTime.endDateTime=01.01.2023+00:00|UTC|YEAR&area.values=CTY|10YGR-HTSO-----Y!BZN|10YGR-HTSO-----Y&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19 

Biomass: 127MW
Coal: 2650MW
Wind: 4547MW
Solar: 5100MW
hydro and hydro storage as in Electricity Maps
Gas: 6030MW
unknown 120MW

In addition, the cross border maximum interconnection capacity between Greece and Bulgaria is 700MW, This could be found https://ibex.bg/ Additional interconnection should be finalized towards the end of the year.

On the following link https://www.enexgroup.gr/ you can find day ahead generations by production type for better estimation of Greece,

Regards,
Aleks

**Comment by VIKTORVAV99** [comment]
Thanks for providing a update on the installed capacity and it's great you found the exchange capacity as well!

As for the new source, we currently only use our own estimations but we are looking into if we can parse estimations from 3rd parties as well and if that works out the new source will be great!

I'll update them myself right away!

**Comment by VIKTORVAV99** [comment]
@asfi30 could you provide the exact link for the interconnection capacity?

**Comment by VIKTORVAV99** [comment]
Thanks, I'll update the PR later today.
