### ISSUE TITLE
new UX : missing translations

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#4955]
With the new UX, some parts of left panel are not translated. See snapshot (header and time slider).

![FireShot Capture 1253 - Electricity Maps - Émissions CO₂ de la consommation électrique en te_ - app electricitymaps com](https://user-images.githubusercontent.com/364418/213178360-d1f6a40c-da24-4480-ba4a-19455a18565a.png)

**Comment by VIKTORVAV99** [comment]
@madsnedergaard Did we launch the new website already? 😅

**Comment by madsnedergaard** [comment]
Good catch, we'll fix it right away! :)

**Comment by madsnedergaard** [comment]
> @madsnedergaard Did we launch the new app already? 😅

Yes, just did today 😉
