### ISSUE TITLE
skip-onboarding url parameter doesn't work any more

### ISSUE THREAD

**Issue by Kezii** [electricitymaps/electricitymaps-contrib#4957]
**Describe the bug**
the url option to skip the onboaring doesn't work since the last update

**To Reproduce**
1. open a private tab on the browser
2. go to https://app.electricitymaps.com/zone/IT?skip-onboarding=true
3. the onboarding is shown

**Expected behavior**
the onboaring should not appear

**Comment by madsnedergaard** [comment]
Thanks for reporting this, it has been fixed now :)
