### ISSUE TITLE
broken link on the doc page "Carbon-intensity-calculations"

### ISSUE THREAD

**Issue by gturri** [electricitymaps/electricitymaps-contrib#4958]
## Description
On the page https://github.com/electricitymaps/electricitymaps-contrib/wiki/Carbon-intensity-calculations there is a link to https://github.com/electricitymaps/electricitymaps-contrib/blob/master/config/co2eq_parameters_lifecycle.json (on the sentence `The carbon intensity of discharged electricity per zone is accessible [here](https://github.com/electricitymap/electricitymap-contrib/blob/master/config/co2eq_parameters_lifecycle.json)`. However that link is broken (and I have currently no clue what the correct link should be)

**Comment by VIKTORVAV99** [comment]
Should be updated to point to the directory where all the individual zone configuration files are now. Thanks for reporting the issue.
