### ISSUE TITLE
Doesn't work on Firefox?

### ISSUE THREAD

**Issue by Granite9652** [electricitymaps/electricitymaps-contrib#4964]
Instead of the map it just shows white

**Comment by VIKTORVAV99** [comment]
Thanks for reporting the issue.

Just tried locally with Firefox and I have no issues.
Could you double check that there isn't any extension causing things to break before we look into this further?

**Comment by Granite9652** [comment]
Hey @VIKTORVAV99, I found the source: I disabled WebGL. If I activate it again, it works just fine. Sorry for bringing this up!
