### ISSUE TITLE
[Data Issue]: South Australia not showing imports from Victoria

### ISSUE THREAD

**Issue by chalg** [electricitymaps/electricitymaps-contrib#4973]
### When did this happen?

Not sure however the problem existed in Dec 2022 as well as now (although there is a small amount of coal in Jan so far). See example of Dec:
![dec-22_cie_power_cons_gt_tbl](https://user-images.githubusercontent.com/26208482/214746832-d70755de-1aa5-401e-aada-466ae9240db0.png)

### What zones are affected?

AU-SA, AU-VIC

### What is the problem?

South Australia should show coal imports from victoria as per OpenNem when looking at consumption. Could be something related to the recent zone name changes?

**Comment by VIKTORVAV99** [comment]
Thanks for reporting this issue.
Where are you currently seeing the missing exchanges? We currently don't aggregate exchanges yet for the historical view but it's on the todo list.

As for the zone name changing, it should have no effect on this data as we ran a extensive database job afterwards that migrated all affected zone data.

**Comment by chalg** [comment]
I use your API (https://api.electricitymap.org/v3/power-breakdown/past-range) to extract historical data for visualisations such as the table above. Is this what you mean by 'where'?

**Comment by VIKTORVAV99** [comment]
> I use your API (https://api.electricitymap.org/v3/power-breakdown/past-range) to extract historical data for visualisations such as the table above. Is this what you mean by 'where'?

Yes it is! Now it should work with both the old and the new zone keys via the API as far as I know.

This repo is focused on the open source parts like the app and parsers and because the API code and system are in our backend there isn't much we can do in here.

With that said I'll assign the issue to someone that has a better understanding of the API and leave it open for now.

**Comment by madsnedergaard** [comment]
Thanks for raising this :) 
I'm not quite sure why you're not seeing imports though, looks fine to me when I try 🤔  Are you looking at the `powerConsumptionBreakdown` object? And can you share the query you used?

Here's a recent example when I call that endpoint, where coal appears due to Victoria imports:
```json
{
    "zone": "AU-SA",
    "datetime": "2023-01-29T13:00:00.000Z",
    "updatedAt": "2023-01-30T01:00:06.514Z",
    "createdAt": "2023-01-26T13:54:41.733Z",
    "powerConsumptionBreakdown": {
        "nuclear": 0,
        "geothermal": 0,
        "biomass": 0,
        "coal": 149,
        "wind": 543,
        "solar": 0,
        "hydro": 3,
        "gas": 566,
        "oil": 0,
        "unknown": 0,
        "hydro discharge": 0,
        "battery discharge": 4
    },
    "powerProductionBreakdown": {
        "nuclear": null,
        "geothermal": null,
        "biomass": null,
        "coal": null,
        "wind": 525,
        "solar": 0,
        "hydro": null,
        "gas": 566,
        "oil": 0,
        "unknown": null,
        "hydro discharge": null,
        "battery discharge": 3
    },
    "powerImportBreakdown": {
        "AU-VIC": 171
    },
    "powerExportBreakdown": {
        "AU-VIC": 0
    },
    "fossilFreePercentage": 43,
    "renewablePercentage": 43,
    "powerConsumptionTotal": 1265,
    "powerProductionTotal": 1094,
    "powerImportTotal": 171,
    "powerExportTotal": 0,
    "isEstimated": false,
    "estimationMethod": null
}
```

**Comment by chalg** [comment]
Yes agree, the issue seemed to be earlier in Jan and is now fixed?
![SA_coal_cons](https://user-images.githubusercontent.com/26208482/215653701-4b7f3fdc-fda2-43b7-a922-d653a0d2eea6.png)

**Comment by madsnedergaard** [comment]
> Yes agree, the issue seemed to be earlier in Jan and is now fixed? ![SA_coal_cons](https://user-images.githubusercontent.com/26208482/215653701-4b7f3fdc-fda2-43b7-a922-d653a0d2eea6.png)

Oh okay, well I'm happy it's fine now - let us know if you spot the problem again :)
