### ISSUE TITLE
New mobile app : back button

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#4974]
When I click on a country, I used to tap the back button on my GS7 to go back to the map. With the new app,the back button close the app.

**Comment by VIKTORVAV99** [comment]
Thanks for the feedback!
I do agree it would be great if it worked like the old app.

cc @tonypls @madsnedergaard just so you guys are aware of it too.

**Comment by tonypls** [comment]
Nice catch, yes we should set up our routing to handle the native buttons in app. I'll create a task!
