### ISSUE TITLE
New App: Click on arrow between countries no longer works

### ISSUE THREAD

**Issue by Bln76** [electricitymaps/electricitymaps-contrib#4977]
Click on arrow between countries in the map doesn't work anymore. (Device Sony xperia 10 iii with Android 12)

**Comment by VIKTORVAV99** [comment]
Thanks for reporting the issue, we will look into it!

**Comment by madsnedergaard** [comment]
Fixed in https://github.com/electricitymaps/electricitymaps-contrib/pull/5070
