### ISSUE TITLE
New mobile App: Missing translation popup "Strompreis"/"price"

### ISSUE THREAD

**Issue by Bln76** [electricitymaps/electricitymaps-contrib#4991]
Clicking on the price chart results in an untranslated popup
![Screenshot_20230130-230438](https://user-images.githubusercontent.com/123670957/215607027-894be0ca-d880-451c-b677-1e714644fb2b.png)

**Comment by VIKTORVAV99** [comment]
It looks like the translated strings are simply not used, so the translations should still be there for most of the languages we simply need to switch to use i18n for particular string.
