### ISSUE TITLE
Hydro storage capacity is mixed up with hydro capacity

### ISSUE THREAD

**Issue by pierresegonne** [electricitymaps/electricitymaps-contrib#5006]
**Describe the bug**

There is a mixup of hydro and hydro storage in the tooltip:

<img width="649" alt="Screenshot 2023-02-01 at 18 20 29" src="https://user-images.githubusercontent.com/32778266/216116209-51a68b8d-6371-4063-8d3f-3e7360d83d91.png">

<img width="649" alt="Screenshot 2023-02-01 at 18 20 41" src="https://user-images.githubusercontent.com/32778266/216116253-a9744171-99f9-4e50-bd6b-63e4e00feac9.png">

You can see that even though there is no hydro discharge, the tooltip gives the same production value as for hydro

**To Reproduce**
1. Go to app
2. Go to `US-NW-WACM`
3. Compare hydro and hydro storage

**Expected behavior**
Hydro storage production seems to be at 0 not the same as hydro

**Comment by VIKTORVAV99** [comment]
@madsnedergaard didn't we fix this already?

**Comment by madsnedergaard** [comment]
> @madsnedergaard didn't we fix this already?

Yes, I thought so too - but maybe it was only for the capacity, and not the actual production? I'll investigate 🤔

**Comment by VIKTORVAV99** [comment]
#5042 is also related to this.
