### ISSUE TITLE
Historical aggregates should show electricity production as sum (GWh) instead of average (GW)

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#5015]
**Describe the bug**
The historical aggregates should show electricity production as the sum (GWh) and not the average power (GW). 
A simple way to fix this is to multiply the average by number of hours (it's also robust to missing data).

**To Reproduce**
1. Go to a zone
2. Select a time aggregate (e.g. years)
3. Hover over production breakdown (or see production graph when production is selected)
4. See problem

**Expected behavior**

Data should show production sums instead of average.

**Screenshots**

![Screenshot 2023-02-02 at 15 22 00](https://user-images.githubusercontent.com/3296643/216350760-14df8aec-8020-4673-bc36-ab70f3ef3334.png)

**Comment by VIKTORVAV99** [comment]
The question here is really where we should sum things up, in the front-end or the app backend? I'm partial to doing it directly in the app-backend to avoid unnecessary computations in the front-end but there might be other considerations to be made here.

**Comment by qwjhvbxi** [comment]
This would make it harder to compare historical data with live data though. I personally prefer to have the average power which is independent of the aggregation time

**Comment by VIKTORVAV99** [comment]
> This would make it harder to compare historical data with live data though. I personally prefer to have the average power which is independent of the aggregation time

The scales themselves would be the same (each bar would be the same length) and the percentages would be the same as well so I don't think this is a big concern. I think it's a bigger concern that we are miss representing historical data right now by showing averages instead of total like other data sources does.

**Comment by VIKTORVAV99** [comment]
Related issue / duplicate #4428

**Comment by madsnedergaard** [comment]
Closing in favor of #4428
