### ISSUE TITLE
[Data Issue]: Add derivative check of wind in DE

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#5020]
### When did this happen?

See screenshot

### What zones are affected?

DE

### What is the problem?

It seems like a datapoint with almost no wind snuck its way into our system.
Maybe we could add a quality check on the derivative of wind (such that it can't loose 80% of its value during an hour?)

<img width="428" alt="image" src="https://user-images.githubusercontent.com/1655848/216626396-0e744b8a-ddd9-4cd2-89fd-394ba3ebb514.png">

**Comment by VIKTORVAV99** [comment]
Good idea!
I assume this would be something we add in the validation "layer".
The only thing I'm unsure is at which point should we invalidate it (threshold)? 
And should we only look at the previous data points or in this case since Germany use 15 min MTUs both a hourly check and a per data point check?

(Just trying to flesh out how we should shape/design this)

**Comment by corradio** [comment]
I think we have parser-level validation functions that can do this no? I
don't think necessarily it needs to be outside of the parser.

**Comment by VIKTORVAV99** [comment]
I was thinking we should add it as check in `validators/zone_specific_checks.py` as a validator function.
Documentation:
```python
def validator(
    kind: str, zone_keys: List[str] = None, not_zone_keys: List[str] = None
) -> Callable:
    """
    Decorator function to mark a function as a validator.
    The backend will run all functions marked as validators.

    A validator function is expected to return as a pandas Series of values between 0 and 1,
    where 1 means that no problems was found and 0 means that the data point is invalid.
    Floating points between 0 and 1 can be used to indicate suspicious data points.

    Parameters
    ----------
    kind : str
        The kind of data that validator supports. e.g. "production", "exchange"
    zone_keys : List[str]
        If this is included, the validator will only be run for the given zone keys.
    not_zone_keys : List[str]
        If this is included, the validator will run for ALL OTHER zones.
    """
```

**Comment by corradio** [comment]
Ah yes indeed! I was referring to this code, but it might be deprecated:
https://github.com/electricitymaps/electricitymaps-contrib/blob/master/parsers/lib/validation.py#L46-L108

**Comment by VIKTORVAV99** [comment]
It's still used but I think we wanted to move away from the old parser level validation towards this new unified validation system.
Pierre should have some more insight if you are curious.

**Comment by corradio** [comment]
Quite possibly! I think @unitrium would know best.

**Comment by unitrium** [comment]
At the moment the internal validation layer is on hold, I think we wanted to do more investigations before launching it.

**Comment by VIKTORVAV99** [comment]
I'll close this now since we have better internal validation.
