### ISSUE TITLE
Nuclear capacity for Slovakia needs to updated to include Mochovce units 3 and 4

### ISSUE THREAD

**Issue by glaubitz** [electricitymaps/electricitymaps-contrib#5035]
The nuclear capacity for Slovakia needs to be extended to accommodate for the new power units 3 and 4 at Mochovce nuclear power plant. Unit 3 first synchronized with the grid on January 31, 2023 [1], unit 4 is supposed to follow one or two years later.

Currently, Electricity Maps shows the nuclear generation in Slovakia to be at 102% which is a result of the outdated information regarding the installed generation capacity for nuclear power in the country, see screenshot below:

![em-bug-20230206](https://user-images.githubusercontent.com/1647645/216978058-2c2310c7-01f9-4d51-a937-6a55300700e0.png)

> [1] https://www.world-nuclear-news.org/Articles/Mochovce-3-supplies-first-electricity-to-grid

**Comment by VIKTORVAV99** [comment]
Thanks for reporting this issue. It's perfectly fine to add the unit 3 capacity but I think we should wait with the unit 4 capacity until it's connected to the grid (and producing power, even if it's testing).
