### ISSUE TITLE
Avoid displaying price data from ENTSO-E

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#5036]
## Description

It has recently come to our attention that we are not allowed to show this information in the app due to licensing terms. This is the case for both for real-time and aggregated views.

If anyone knows of other sources for price data for these zones (that we are allowed to share) we would love to hear more :)

We hope to have pricing data back on the app in the future, but for now we're removing the price graph for the affected zones. 

### Zones affected

- AT
- BE
- CH
- DE
- LU
- DK (DK-DK1, DK-DK2, DK-BHM)
- FR
- GB
- NL
- NO (NO-NO1, NO-NO2, NO-NO3, NO-NO4, NO-NO5)
- PL
- SE (SE-SE1, SE-SE2, SE-SE3, SE-SE4)
- FI
- AX
- EE 
- LT
- LV

**Comment by madsnedergaard** [comment]
Reopening as this has not been merged on backend yet.

**Comment by Trolli132** [comment]
> ## Description
> It has recently come to our attention that we are not allowed to show this information in the app due to licensing terms. This is the case for both for real-time and aggregated views.
> 
> If anyone knows of other sources for price data for these zones (that we are allowed to share) we would love to hear more :)
> 
> We hope to have pricing data back on the app in the future, but for now we're removing the price graph for the affected zones.
> 
> ### Zones affected
> * AT
> * BE
> * CH
> * DE
> * LU
> * DK (DK-DK1, DK-DK2, DK-BHM)
> * FR
> * GB
> * NL
> * NO (NO-NO1, NO-NO2, NO-NO3, NO-NO4, NO-NO5)
> * PL
> * SE (SE-SE1, SE-SE2, SE-SE3, SE-SE4)
> * FI
> * AX
> * EE
> * LT
> * LV

Hi would the following site be a solution. It’s a site from the German government where you can download market data in 15min lot‘s. https://www.smard.de/en/downloadcenter/download-market-data/

**Comment by VIKTORVAV99** [comment]
We need to double check this first but it is licensed under CC BY 4.0 even though the data comes from ENTSO-E so we might be able to use it.

It should contain data for the following regions:

Germany/Luxembourg   [€/MWh] Original resolutions | ∅ DE/LU neighbours [€/MWh] Original   resolutions | Belgium [€/MWh] Original resolutions | Denmark 1 [€/MWh] Original resolutions | Denmark 2 [€/MWh] Original resolutions | France [€/MWh] Original resolutions | Netherlands [€/MWh] Original resolutions | Norway 2 [€/MWh] Original resolutions | Austria [€/MWh] Original resolutions | Poland [€/MWh] Original resolutions | Sweden 4 [€/MWh] Original resolutions | Switzerland [€/MWh] Original resolutions | Czech Republic [€/MWh] Original resolutions | DE/AT/LU [€/MWh] Original resolutions | Northern Italy [€/MWh] Original resolutions | Slovenia [€/MWh] Original resolutions | Hungary [€/MWh] Original resolutions
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

@madsnedergaard can you double check if we can use this data before we start building a parser / open a issue for it?
