### ISSUE TITLE
Hydro storage values in Middle Norway (NO3) is all over the place

### ISSUE THREAD

**Issue by Gazer75** [electricitymaps/electricitymaps-contrib#5042]
Seems the numbers go wild for some hours of the day.
![image](https://user-images.githubusercontent.com/13599949/217048314-b879d2b9-db5d-476d-84bf-b97ffcbd2dc6.png)

**Comment by VIKTORVAV99** [comment]
This is a visual bug where hydro is reported as both hydro and hydro storage hence why it looks so strange. I thought we had fixed this but apparently not.
