### ISSUE TITLE
Make background data refresh work again

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#5064]
It seems like the functionality isn't working any more. 
We should get it back, so that the app will call `/state` and recolor the map on an interval. This is especially useful for anyone using the app as a dashboard.

**Comment by tonypls** [comment]
AFAIK this is currently working with a refetch interval of 5 minutes. I've tested it by watch it check over a new hour and the data was loaded in as expected.

**Comment by VIKTORVAV99** [comment]
> AFAIK this is currently working with a refetch interval of 5 minutes. I've tested it by watching it tick over a new hour and the data was loaded in as expected.

Have you tested it when leaving the tab to idle as well? That is where I have had issues and had to do a manual refresh when going back to the tab or navigate around in the app to trigger data fetching and get rid of a all gray map.
