### ISSUE TITLE
A react error message show up when I select luxembourg in 5 year time mode

### ISSUE THREAD

**Issue by AntoineGuillemaud** [electricitymaps/electricitymaps-contrib#5075]
**Describe the bug**
A react error message show up containing this message :
`Error message: Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Url: https://app.electricitymaps.com/zone/LU`

**To Reproduce**
1. Go in 5 year time mode
2. Click on Luxembourg
3. Click on an other country (eg: France)
4. Click on Luxembourg

**Expected behavior**
The error message show up

**Desktop :**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Build officiel) (64 bits)

**Comment by VIKTORVAV99** [comment]
The full error text for invariant 300 is:
```
Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
```

**Comment by madsnedergaard** [comment]
I could reproduce with Kosovo as well! Seems like there's something fishy going on in the panel here:

![Image](https://user-images.githubusercontent.com/3296643/221673065-b15f7f60-a349-47b8-84ea-d33073a828ce.png)

**Comment by madsnedergaard** [comment]
This has been fixed since :)
