### ISSUE TITLE
Close mobile exchange tooltip when opening another

### ISSUE THREAD

**Issue by tonypls** [electricitymaps/electricitymaps-contrib#5089]
## Description
As mentioned in #5070

As a mobile user I want the previous exchange tooltip to close when I select a different exchange so that I can clearly see that map

Current state:
![image](https://user-images.githubusercontent.com/18622768/218732130-550a52a5-9ae7-424d-9c45-e6890413c62b.png)

**Comment by VIKTORVAV99** [comment]
@tonypls didn't one of your latest PRs fix this?

**Comment by tonypls** [comment]
Yeah #5195
