### ISSUE TITLE
Graph tooltip don't show the same value as the header

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#5097]
## Description
The graph tooltip don't show the same co2intensity value as the header.

![image](https://user-images.githubusercontent.com/30777521/219175070-210a03b7-240b-4af6-ba66-27119b5a9889.png)

**Comment by phiphou** [comment]
I think it's not a bug.

On the snapshot, time slider is on 13h and on the graph mouse is on 15h. So values are obviously not the same.

**Comment by VIKTORVAV99** [comment]
> I think it's not a bug.
> 
> On the snapshot, time slider is on 13h and on the graph mouse is on 15h. So values are obviously not the same.

The problem is that the slider itself is set to 13:00 but the indicators/lines show up on the 15:00 mark instead, which is a bug.

**Comment by phiphou** [comment]
No bug for me...

![FireShot Capture 1336 - Electricity Maps - Émissions CO₂ de la consommation électrique en te_ - app electricitymaps com](https://user-images.githubusercontent.com/364418/220055699-ff676e58-22d7-41c2-92da-1ecf2907cca3.png)

**Comment by VIKTORVAV99** [comment]
I know, it's not always there, which makes it hard to replicate and debug. But sometimes it shows up (might be when there is a missing datapoint or two).

**Comment by tonypls** [comment]
I believe this is an index issue when there is missing data for a given time period

Here's Japan which has missing data as it's a new zone

![image](https://user-images.githubusercontent.com/18622768/224333224-b80c0f0b-ebbb-40dd-810b-e0d1d5a1fcc3.png)
