### ISSUE TITLE
Belgium Day ahead pricing data delayed.

### ISSUE THREAD

**Issue by svaeyens** [electricitymaps/electricitymaps-contrib#5099]
Belgium Day afead pricing data is often delayed. Info should normally be available between 12pm and 14pm (Brussels Time), It's 17:30 now and day ahead pricing for tomorrow still isn't available.

**Comment by VIKTORVAV99** [comment]
Unfortunately due to licensing issues we are not allowed to show price data from nordpool anymore which was the original source for the ENTSO-E price data. So the "missing" price data is an intentional change that won't be "fixed" for the foreseeable future.
