### ISSUE TITLE
What happened to the price per MWh graph?
Seems to have gone with the last update.

Other new features are 👍. 
Thx. :)

### ISSUE THREAD

**Issue by mnoethe** [electricitymaps/electricitymaps-contrib#5101]

**Comment by jarek** [comment]
Many European regions are currently not displaying prices due to a licensing issue: https://github.com/electricitymaps/electricitymaps-contrib/issues/5036

Other regions (e.g. Ontario, Alberta, South Australia) where we have data available display it as before.
