### ISSUE TITLE
Wiki page: Parser Issues

### ISSUE THREAD

**Issue by IV1T3** [electricitymaps/electricitymaps-contrib#5106]
## Description
The wiki page [Parser Issues](https://github.com/electricitymaps/electricitymaps-contrib/wiki/Parser-issues) is a great resource to keep track of broken, unreliable or just late parsers. The content is supposed to be auto-generated and frequently updated. However, the last update was on Mon, 05 Dec 2022 07:01:37 +0000 - more than 2 months ago.

Is this wiki page still supposed to work correctly/maintained? Would love to be able to reliably use it again to find which parsers can be improved.

**Comment by VIKTORVAV99** [comment]
It is supposed to be updated but there seems to be an issue with the bot. We are already tracking this internally but we have been pretty busy and have not had the time to prioritize this but I'll if we can increase it's priority a bit now that the rewrite is "done".

**Comment by VIKTORVAV99** [comment]
Things should be up and running again! 😅
![image](https://user-images.githubusercontent.com/30777521/221677285-7de0b7ee-68ba-4b85-868f-4706978b7a23.png)
Thank you @madsnedergaard for fixing it!
