### ISSUE TITLE
Solar generation forecast for Finland

### ISSUE THREAD

**Issue by msaynevirta** [electricitymaps/electricitymaps-contrib#5117]
## Description

FI parser is based on ENTSO-E data which currently lacks solar generation data. Solar capacity has been growing quickly in Finland with a total of 606 MW online as of November 2022.

The grid operator Fingrid provides [a rolling hourly](https://data.fingrid.fi/en/dataset/solar-power-generation-forecast-updated-every-hour) and [a 36 hour day-ahead](https://data.fingrid.fi/en/dataset/solar-power-generation-forecast-updated-once-a-day) solar generation forecast along with an API for this estimated data going back to February 2017. I presume these resources could serve as a foundation for a solar generation estimation model also within this project?

**Comment by VIKTORVAV99** [comment]
We currently don't support external estimations (but we are working on it).
With that said there could be a few things we can do to get solar data added to Finland but we need to know the following to have a place to start.

Do you know if Solar is included in unknown (other or other renewable) in the ENTSO-E TP?

Is this the same data as published on [Transparency ENTSO-E | Generation Forecasts for Wind and Solar](https://transparency.entsoe.eu/generation/r2/dayAheadGenerationForecastWindAndSolar/show?name=&defaultValue=true&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=23.02.2023+00:00|UTC|DAYTIMERANGE&dateTime.endDateTime=23.02.2023+00:00|UTC|DAYTIMERANGE&area.values=CTY|10YFI-1--------U!BZN|10YFI-1--------U&productionType.values=B16&productionType.values=B18&productionType.values=B19&processType.values=A18&processType.values=A01&processType.values=A40&dateTime.timezone=UTC&dateTime.timezone_input=UTC)?

I'd also like to just mention that it might be worth to reach out to Fingrid and ask if they have any plans to publish solar production information to the ENTSO-E TP, either if you yourself do it or someone else.

**Comment by msaynevirta** [comment]
Fingrid seems to have retroactively added solar generation data to the ENTSO-E dataset since 1 January 2023. It might be worth updating the backend database but otherwise this issue seems to be ready to be closed.

**Comment by VIKTORVAV99** [comment]
I'll let the team know they retroactively added the solar values, we are already tracking the change though (but was not aware of the retroactive change) and I agree that the issue can be closed (so I'm closing it now).
