### ISSUE TITLE
Fix all TS errors and enable typechecking in CI

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#5122]
## Description

We have 67 TypeScript errors in 26 files. These should be fixed and typechecking should be enabled in CI and be required for merging PRs.

**Comment by VIKTORVAV99** [comment]
We need to see if required workflows work if they are not run as a part of a conditional. It SHOULD work if I read githubs documentation right but we should probably test it ourselves as well.

**Comment by madsnedergaard** [comment]
> We need to see if required workflows work if they are not run as a part of a conditional. It SHOULD work if I read githubs documentation right but we should probably test it ourselves as well.

Not sure what you mean, can you give an example?
 I have added the Prettier step as a required check to pass, so I assumed we could just add more checks :)

**Comment by VIKTORVAV99** [comment]
It should still work tho

> > We need to see if required workflows work if they are not run as a part of a conditional. It SHOULD work if I read githubs documentation right but we should probably test it ourselves as well.
> 
> Ah wait, now I get it - it's weird having it as required if it is not running, e.g. for parser changes :D

Right, but since they are technically run (i.e. not pending but skipped) it should work even if we add required to TSC or ESLint for example.
