### ISSUE TITLE
Maybe a solution to missing Price data

### ISSUE THREAD

**Issue by Trolli132** [electricitymaps/electricitymaps-contrib#5128]
There is a German government site that has the missing data included.
You can break down the day ahead pricing in quarter hours.
Maybe it’s possible do read the data out and merge it with the app

https://www.smard.de/en/downloadcenter/download-market-data/
The site is free to use and you can download everything within the last few 
![IMG_4554](https://user-images.githubusercontent.com/87663978/221263859-89058763-00a2-4679-afb0-8efa9b172d71.png)
years timeline

**Comment by VIKTORVAV99** [comment]
We need to double check this first but it is licensed under CC BY 4.0 even though the data comes from ENTSO-E so we might be able to use it.

It should contain data for the following regions:

Germany/Luxembourg   [€/MWh] Original resolutions | ∅ DE/LU neighbours [€/MWh] Original   resolutions | Belgium [€/MWh] Original resolutions | Denmark 1 [€/MWh] Original resolutions | Denmark 2 [€/MWh] Original resolutions | France [€/MWh] Original resolutions | Netherlands [€/MWh] Original resolutions | Norway 2 [€/MWh] Original resolutions | Austria [€/MWh] Original resolutions | Poland [€/MWh] Original resolutions | Sweden 4 [€/MWh] Original resolutions | Switzerland [€/MWh] Original resolutions | Czech Republic [€/MWh] Original resolutions | DE/AT/LU [€/MWh] Original resolutions | Northern Italy [€/MWh] Original resolutions | Slovenia [€/MWh] Original resolutions | Hungary [€/MWh] Original resolutions
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

@madsnedergaard can you double check if we can use this data before we start building a parser / open a issue for it?

_Originally posted by @VIKTORVAV99 in https://github.com/electricitymaps/electricitymaps-contrib/issues/5036#issuecomment-1444236672_

**Comment by VIKTORVAV99** [comment]
For the Nordic grid we could potentially use https://www.energidataservice.dk/tso-electricity/Elspotprices but we need to make sure we are allowed to use that data before we do anything as well. But the license seems to support it.

**Comment by Trolli132** [comment]
License is given on page 9 and 10 in the English version. Be aware that the German version is a few weeks newer in case of any changes. You can find that information at https://www.smard.de/en/user-guide


[smard-benutzerhandbuch-07-2022-data.pdf](https://github.com/electricitymaps/electricitymaps-contrib/files/10828003/smard-benutzerhandbuch-07-2022-data.pdf)
[smard-user-guide-09-2021-data.pdf](https://github.com/electricitymaps/electricitymaps-contrib/files/10828004/smard-user-guide-09-2021-data.pdf)

**Comment by madsnedergaard** [comment]
Hey @Trolli132, thanks for sharing this! We'll look into it and reach out to them to learn what's allowed :) 
@VIKTORVAV99, where did you see that their data comes from ENTSO-E?

**Comment by VIKTORVAV99** [comment]
> Hey @Trolli132, thanks for sharing this! We'll look into it and reach out to them to learn what's allowed :) @VIKTORVAV99, where did you see that their data comes from ENTSO-E?

Here: https://www.smard.de/en/datennutzung

> Data quality is of the utmost importance. SMARD receives the data directly from the European Network of Transmission System Operators for Electricity (ENTSO-E). Only data verified by the Bundesnetzagentur is published on SMARD. The Bundesnetzagentur is constantly exchanging information with the transmission network operators (TSOs) in order to continuously improve data quality.

**Comment by madsnedergaard** [comment]
Ah, thanks! In that case I'm afraid we cannot use it, even though SMARD say it's under a specific license. 
We cannot use price data directly from ENTSO-E, so I'm pretty sure going through a third party will not help anything :)

**Comment by madsnedergaard** [comment]
There is also a very high chance that the data Energinet has comes from Nord Pool, which have [a specific license for redistribution](https://www.nordpoolgroup.com/en/services/power-market-data-services/faq/faq-premium-container/redistribution/), although they don't state it directly.

**Comment by VIKTORVAV99** [comment]
> There is also a very high chance that the data Energinet has comes from Nord Pool, which have [a specific license for redistribution](https://www.nordpoolgroup.com/en/services/power-market-data-services/faq/faq-premium-container/redistribution/), although they don't state it directly.

Here is the license for Energinet: https://www.energidataservice.dk/Conditions_for_use_of_Danish_public_sector_data-License_for_use_of_data_in_ED.pdf

I wonder who actually has ownership of this data though. While Nordpool is the market place the TSOs should have full ownership rights if I have understood things properly. 

Nordpool also specifies this in the license:
> The Customer shall pay a license fee per each of its customer/user of that service.

Wouldn't ENERGINET / SMARD be the Customer here and we would be the user covered by the respective services licences?

**Comment by mirkoschaefer** [comment]
> Ah, thanks! In that case I'm afraid we cannot use it, even though SMARD say it's under a specific license. We cannot use price data directly from ENTSO-E, so I'm pretty sure going through a third party will not help anything :)

I am pretty sure you can use it - SMARD is the official data portal issued by the German Federal Network Agency and according to my knowledge their license applies to all data they publish, even if it is identical to data also published by ENTSO-E. Ask them via mail to be sure though ;-)

**Comment by Trolli132** [comment]
Any updates or challenges we can help with

**Comment by VIKTORVAV99** [comment]
While at first glance the license(s) should support us using the data there are some legal ambiguity that need to be figured out first and we need to determine exactly to what extent are we allowed to use this (price) data.

There seems to be conflicting languages between the Nord pool license and "use documentation" and Energinet as well as SMARD. While these last licenses say we are free to use any data how we see fit more or less the Nord pool license seems to directly contradict that and for the Nordic grid at least they are the origin of this data. So until we know exactly which license is valid we will unfortunately not be moving forward with displaying any kind of price related data for now.

With that said we do hope this will be resolved in the future and if that happens we will add back the price data as soon as we can.

Just to note: We are still parsing this data and saving it internally so there is no risks of data losses (even if these particular sources have historical data available) so if we can add it back in the future we will have the full historical data as well if the license permits it.

**Comment by VIKTORVAV99** [comment]
We will be using Nordpool data in the next release so this is now considered fixed.
