### ISSUE TITLE
[Data Issue]: Suspiciously high CO2 intensity for gas in Romania (RO)

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#5139]
### When did this happen?

After regional emission factors were introduced.

### What zones are affected?

RO

### What is the problem?

Feedback given in the feedback form:
> The CO2 impact of Romania's electricity generation from GAS is suspiciously high. The CO2 impact of it is 1188 gCO2Eq/kWh. It is likely that this is incorrect as in all other markets the CO2 impact of gas is much lower. this 1188 is likely the equivalent of Coal. Please can you correct this? Thanks  

![Screenshot 2023-02-28 at 12 21 58](https://user-images.githubusercontent.com/3296643/221839944-e2667fdc-0b0b-4e02-bd91-549feabaf559.png)

**Comment by madsnedergaard** [comment]
cc @pierresegonne

**Comment by pierresegonne** [comment]
I'll escalate this to our error handling

**Comment by wobniarin** [comment]
Hey, we have triaged it as a medium priority issue and we have suggested to work during Slack week, since it will need to be rolled out to many different countries.
