### ISSUE TITLE
Incorrect axis labels in emissions chart (production mode)

### ISSUE THREAD

**Issue by tonypls** [electricitymaps/electricitymaps-contrib#5140]
**Describe the bug**
When using the emissions chart in production mode the y axis changes to an incorrect scale

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the app
2. Select production mode
3. Open the country panel
4. Select carbon emissions
5. The carbon emissions chart will have incorrect labels for the Y axis

**Expected behavior**
The axis labels match the data

**Screenshots**
<img width="530" alt="image" src="https://user-images.githubusercontent.com/18622768/221870969-9a9658d2-d107-4189-8894-a50191c08190.png">

**Comment by mrSeoD** [comment]
I could look into this!

**Comment by VIKTORVAV99** [comment]
> I could look into this!

Sure thing! I'll assign the issue to you.

Thanks for taking a look at it!

**Comment by mrSeoD** [comment]
My apologies for a delayed look into this, but I wanted to ask about another bug that I ran into as I was looking into this issue. I was able to find a place where I could scale the y-axis, but I noticed another bug:
![image](https://user-images.githubusercontent.com/64814632/233685117-78e601d0-2469-4c8c-8a47-f45ce9c17671.png)

As you can see from the screenshot above, I clicked South Central Sweden, which as 28g Intensity, but the panel on the left shows 696g. And this is the case for every single country. No matter what country I press, the carbon intensity on the left panel is always set to 696g and the graph that needs to be fixed for this issue has the same values as well. 

I checked the official website, and it doesn't have this problem. But this only happens within the mockserver. Do you have an idea why this may be happening?

**Comment by VIKTORVAV99** [comment]
> My apologies for a delayed look into this, but I wanted to ask about another bug that I ran into as I was looking into this issue. I was able to find a place where I could scale the y-axis, but I noticed another bug:
> ![image](https://user-images.githubusercontent.com/64814632/233685117-78e601d0-2469-4c8c-8a47-f45ce9c17671.png)
> 
> As you can see from the screenshot above, I clicked South Central Sweden, which has a correct intensity of 28g, but the panel on the left shows 696g. And this is the case for every single country. No matter what country I press, the carbon intensity on the left panel is always set to 696g and the graph that needs to be fixed for this issue has the same values as well. 
> 
> I checked the official website, and it doesn't have this problem. But this only happens within the mockserver. Do you have an idea why this may be happening?

The reason for this is quite simple, we have only added mock data for two zones, DE and DK-DK2 and every other zone will fall back to DE data. As for the tool tips they get their data from the global state file. A file that contains a lot less information about each zone but has the basics. Like the carbon intensity.

**Comment by mrSeoD** [comment]
Thanks for the clarification! I was able to fix the error and made a pull request. I would appreciate it if you could look into it and please let me know if you have any questions!

**Comment by mrSeoD** [comment]
Just wanted to follow up! Thanks!

**Comment by madsnedergaard** [comment]
Thanks for working on this! We should probably also change the mockserver to not fallback to DE, but just return "no data" for zones we don't have mock data for :)
