### ISSUE TITLE
Charts don't re-size when the window size changes

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#5141]
## Description
If you start with the app open in let's say split screen and then later expand the window to full screen you get a state where the charts are narrower than they should be.

For example:
![image](https://user-images.githubusercontent.com/30777521/221908885-f0ec36b5-57fb-4fe4-a45a-f883b0bd0cab.png)

Then if you refresh the page the charts render correctly:
![image](https://user-images.githubusercontent.com/30777521/221909068-c26ec1ff-a2f5-4905-b66a-62e6e6ff340a.png)

**Comment by madsnedergaard** [comment]
Maybe this could be fixed by replacing our custom ref resize observer with a third-party tool like https://github.com/ZeeCoder/use-resize-observer :)

**Comment by 15Arindam** [comment]
Hey, I would like to try this, I'm new in OS contrib., could you please guide me how to setup locally & reproduce this issue

**Comment by VIKTORVAV99** [comment]
> Hey, I would like to try this, I'm new in OS contrib., could you please guide me how to setup locally & reproduce this issue

Hey @15Arindam!

Local setup should be documented in the [CONTRIBUTING.md](https://github.com/electricitymaps/electricitymaps-contrib/blob/master/CONTRIBUTING.md) file. There isn't really much more too it than that for the frontend 🙂.

As for reproducing the issue that's pretty easy so all you need to do is the same as I did in the description of this issue.

If you have any questions feel free to reach out any time!

**Comment by 15Arindam** [comment]
Thanks @VIKTORVAV99 
I was able to locally setup, did some changes (need more help on it) but unable to push them.

**Comment by VIKTORVAV99** [comment]
> Thanks @VIKTORVAV99 I was able to locally setup, did some changes (need more help on it) but unable to push them.

Hi again @15Arindam 
If you are trying to push directly to this repo that is expected and by design.
If you haven't already you need to fork the repository and then clone that instead of this one.
Once that is done you can push your changes to your fork and then open a pull request, PR, to this repository. That will also make sure all our automated tests run and give me and other members of the team time to review it before it's merged. (It's actually required.)

You can follow the detailed steps here: https://docs.github.com/en/get-started/quickstart/contributing-to-projects

Just make sure you make a copy of your local changes first.

**Comment by 15Arindam** [comment]
Hey @VIKTORVAV99 ,
I've raised this [PR](https://github.com/electricitymaps/electricitymaps-contrib/pull/5166) please have a look if its okay
