### ISSUE TITLE
Wrong data

### ISSUE THREAD

**Issue by MasterVargen** [electricitymaps/electricitymaps-contrib#5152]
Hi

I think the data on south Sweden is wrong because the data seems to low.

**Comment by VIKTORVAV99** [comment]
Hi @MasterVargen!

Could you expand on this a little more?
Do you mean the co2intensity or the amount of produced electricity?

**Comment by MasterVargen** [comment]
the amount of produced electricity but now that i checked it seemed right,
I dont know why it happend. Thanks for the fast response


Best regards

**Comment by VIKTORVAV99** [comment]
> the amount of produced electricity but now that i checked it seemed right, I dont know why it happend. Thanks for the fast response Best regards


No problem!
If there is anything else don't hesitate to reach out!
