### ISSUE TITLE
Potentially outdated capacity information for Czechia

### ISSUE THREAD

**Issue by FelixDQ** [electricitymaps/electricitymaps-contrib#5160]
## Description
Feedback retrieved through the feedback form:
> Dear Electricity Maps,
You might have old data about solar energy in Czechia. Your app shows installed capacity 2.05 GWp, but according to Czech Solar Association, current installed capacity is 2.46 GWp as of 31. 12. 2022. https://www.solarniasociace.cz/cs
Also, solar instalations have 484 MWh in battery storage, and other battery storage also exists in Czechia. Could you please add battery storage to Czechia?

It would be great if someone could investigate and possibly submit a PR!

**Comment by VIKTORVAV99** [comment]
With some major help from @Frantisek12 we looked into this and it looks like the source provided seems to be behind a pay wall and from a private organization. Therefore I think it would be better to continue using ENTSO-E as it is in line with official ministry sources for Czechia. It is likely that ENTSO-E will be updated with the correct numbers later on and is just on a slower update cadence. 

Therefore I will close this issue and we should wait for ENTSO-E to be updated instead.
