### ISSUE TITLE
Faroe islands data seem wrong ?

### ISSUE THREAD

**Issue by Oocedar** [electricitymaps/electricitymaps-contrib#5167]
Hello !
Curious to what was causing the Faroe Islands to be so black (967g-CO2/kWh), I clicked on them to see the detail and I see it's a mix of oil (650g), biomass (230g), hydro (24g) and wind (11g). I guess that you're actually using the oil coefficient of 1125g (instead of 650g) as in the rest of the continent but just didn't update the label...
Thanks for your attention !

**Comment by VIKTORVAV99** [comment]
It does look like the value for the aggregated zone is indeed wrong but the subzones are correct. I'll update it later today.
