### ISSUE TITLE
Indian Map is wrong

### ISSUE THREAD

**Issue by PadmarajBhat** [electricitymaps/electricitymaps-contrib#5177]
Kashmir map is not shown correctly. It is whole and sole part of India. Please correct the same.
![TheJammuNKashmir](https://user-images.githubusercontent.com/29166528/224027322-03ba0827-fd56-4be4-b162-72dad6df2d30.png)
![WrongKashmir](https://user-images.githubusercontent.com/29166528/224027338-19f9d17a-8dee-4e68-8e63-a2abbe76d4eb.png)

**Comment by VIKTORVAV99** [comment]
@PadmarajBhat Thanks for reporting this.
We'll look into it as soon as we can but in the meantime I have added the help wanted label if someone else wanted to take a crack at fixing it.

**Comment by madsnedergaard** [comment]
Thanks for raising this. Can you be more precise about what you think is wrong here, are you referring to Aksai Chin?

I have also tried overlaying our map on top of Google Maps to make it more easy to compare the two:

![Frame 1 (3)](https://user-images.githubusercontent.com/3296643/227357936-01287810-4df4-4216-9c70-504aacbfb768.png)

**Comment by PadmarajBhat** [comment]
What is shown as part of Pakistan & China is part of India. When you hover
over northern India, the Jammu & Kashmir portion is chopped. And
furthermore, when hovered over pakistan it shows Kashmir part as the part
of it...it is wrong. That's why I gave another image as in how it has to be
reflected from google map. I am talking about boundaries here.

The Indian region occupied by Pak is Pok. The Indian region occupied by
China is called COK. Those are occupied regions which does not mean it is
their land. it should still be reflected as Indian.

**Comment by jarek** [comment]
I don't think there is one "right" way to display these disputed borders.

Google Maps shows different borders depending where you're using it, to comply with local laws. Viewing it in Canada shows the border with several dashed lines indicating different claimed and actual borders, rather than one solid line:

![image](https://user-images.githubusercontent.com/47415/227663936-8d4482ff-2785-49b8-b516-dab953894a48.png)

The empty triangle in the Electricity Maps view seems to correspond to the "disputed area" indicated in https://en.wikipedia.org/wiki/File:Kashmir_Region_November_2019.jpg (source of that image is https://maps.lib.utexas.edu/maps/kashmir.html which claims it is originally by the U.S. CIA). CIA's World Factbook https://www.cia.gov/the-world-factbook/countries/india/map has a map of India with borders in Kashmir area generally matching what Electricity Maps is showing.

**Comment by jarek** [comment]
On a more fundamental level, Electricity Maps map is intended to show the electrical reality as it exists on the ground, so the question is really which grids supply the electricity to areas in question and/or who reports the electricity generation there.

**Comment by madsnedergaard** [comment]
> On a more fundamental level, Electricity Maps map is intended to show the electrical reality as it exists on the ground, so the question is really which grids supply the electricity to areas in question and/or who reports the electricity generation there.

Yes, exactly! I haven't dived too deep into the research here, but as far as I can tell the grid in the disputed area between Pakistan and India is connected to the grid of Pakistan: https://www.aninews.in/news/world/asia/pakistan-ends-electricity-subsidy-for-people-of-pok20230201064020/

**Comment by jarek** [comment]
> as far as I can tell the grid in the disputed area between Pakistan and India is connected to the grid of Pakistan: https://www.aninews.in/news/world/asia/pakistan-ends-electricity-subsidy-for-people-of-pok20230201064020/

That's about the part of the disputed area which is controlled by Pakistan.

"The disputed area between Pakistan and India" includes the Indian-controlled area, which Pakistan claims as their own. Hence no single "right" way.

**Comment by PadmarajBhat** [comment]
If both the parties claim the region then why are you supporting only one
country ? At least, you could show the region of both the countries and not
be biased to one.

**Comment by madsnedergaard** [comment]
> If both the parties claim the region then why are you supporting only one country ? At least, you could show the region of both the countries and not be biased to one.

Sorry if I wasn't clear, our map boundaries attempt to match the physical electricity grids across the globe. If you can link to a reputable source that indicates that our map boundaries does not match the reality of who supplies the electricity to a certain area, we'd be happy to improve the geometries.

Until then, I will close this issue as it we don't have the capacity to investigate this topic further - but feel free to reopen if you manage to find a good source :)
