### ISSUE TITLE
Data Issue: 

### ISSUE THREAD

**Issue by bbaswaraj** [electricitymaps/electricitymaps-contrib#5178]
### When did this happen?

"2023-03-02 12:00"

### What zones are affected?

"IN_MH" parser not working and throwing an error like `Error opening data file /usr/share/tesseract-ocr/4.00/tessdata/digits_comma.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'digits_comma\' Tesseract couldn\'t load any languages! Could not initialize tesseract.`

### What is the problem?

Not able fetch the data

**Comment by VIKTORVAV99** [comment]
Hi @bbaswaraj!
Data issues are really just for underlying data being incorrect or missing and not for the parsers.

But with that said have you installed tesseract and set the correct env variable as suggested by the issue?

**Comment by VIKTORVAV99** [comment]
Since this is not a problem with the underlying data or the code it self from what I can gather I'm going to close this issue.
