### ISSUE TITLE
Solar installed capacity in Hungary 

### ISSUE THREAD

**Issue by wobniarin** [electricitymaps/electricitymaps-contrib#5194]
## Description
From the feedback form: 

> The installed capacity of Hungarian industrial-sized (over 50 kW) PV producers is currently 2,630 MW, while household-sized PV producers (HMKE, under 50 kW) amount to about 1,632.3 MW. 
> 
> source: https://mavir.hu/web/mavir/-/folytatodik-a-kerecsensolyom-valosagshow?returnPlid=16273527
> [MAVIR] - Hungarian Electricity Industry Transmission System Controller

## To be done 
- [ ]  Validate source and value using statistical reports from the TSO or another trustworthy source. 
- [ ] Update `DATA_SOURCES.md` including the source where the total installed capacity matches the link above reported by the TSO. 
- [ ]  Update PV installed capacity under the zone configuration file `HR.yaml`
- [ ] Create PR to include the new capacity.

**Comment by MuffinCompiler** [comment]
I found this nice infographic by MAVIR (Hungary TSO), showing a lot of solar power data, including the solar power capacity (<50kW and >50kW) since 2010 (linked by [this](https://www.portfolio.hu/uzlet/20230220/nagyot-fekeztek-a-hazai-naperomu-telepitesek-2011-ota-nem-lattunk-ilyet-597914) news article).

https://www.mavir.hu/documents/10258/245818953/PV+STATISZTIKA_HU_20230213_ig_v1+(1).pdf

The last entry shows a capacity of (2545.166 MW / 1531.008 MW) on Feb 1 2023, which is reasonable given the numbers in the article (2630 MW / 1632.3 MW) for March 2023. ENTSO-E reports 2868 MW total. We could update the capacity based on this source.

**Comment by VIKTORVAV99** [comment]
> I found this nice infographic by MAVIR (Hungary TSO), showing a lot of solar power data, including the solar power capacity (<50kW and >50kW) since 2010 (linked by [this](https://www.portfolio.hu/uzlet/20230220/nagyot-fekeztek-a-hazai-naperomu-telepitesek-2011-ota-nem-lattunk-ilyet-597914) news article).
> 
> https://www.mavir.hu/documents/10258/245818953/PV+STATISZTIKA_HU_20230213_ig_v1+(1).pdf
> 
> The last entry shows a capacity of (2545.166 MW / 1531.008 MW) on Feb 1 2023, which is reasonable given the numbers in the article (2630 MW / 1632.3 MW) for March 2023. ENTSO-E reports 2868 MW total. We could update the capacity based on this source.

If you want feel free to open a PR with the new capacity figures from Feb 1 2023 🙂

**Comment by torokati44** [comment]
Does the data source for the hourly rate of production (and total consumption) also take into account both <50kW and >50kW installations?

**Comment by VIKTORVAV99** [comment]
> Does the data source for the hourly rate of production (and total consumption) also take into account both <50kW and >50kW installations?

Good question!

We get the data from ENTSO-E which in turn get the data from the local TSO, so we would need to reach out to ENTSO-E. I'll put it on my todo list and reach out on Monday.

**Comment by torokati44** [comment]
BTW I checked since, and at peak solar production today, Hungary was at a similar 60-70% utilization as some similarly sized neighboring countries, so there probably isn't a significant mismatch in how the capacity and the production is measured.
But it's better to make sure, so thank you!
