### ISSUE TITLE
[Bug]: Flinders Island missing low carbon percentage

### ISSUE THREAD

**Issue by strassburger** [electricitymaps/electricitymaps-contrib#5207]
### When did this happen?

Time: 2023-03-2:50, but issue was seen last week before.

### What zones are affected?

Flinders Island

### What is the problem?

Low Carbon comes with "?",
Should be 100o%

![grafik](https://user-images.githubusercontent.com/28303688/226150922-6e5688c3-c7a7-455d-b9e6-c2ffea29a1bf.png)

**Comment by VIKTORVAV99** [comment]
Thanks for opening the issue. 
The first part of this is definitely looks like a bug but the wind and solar capacity is `1.5 MW` and `4.2 MW` respectively, not `150 MW` and `420 MW`

It would also be great if you could update the title to be more descriptive (keep the [Data Issue]: part and add the title after that.)

**Comment by strassburger** [comment]
@VIKTORVAV99
Thanks for revisting.
Did check again and found out you are right:
the wind and solar capacity is 1.5 MW and 4.1.
Have to ask for new glasses...
Have Problems to rename the title. 
It was planed by me just Flinders Island, but do not know how to change the title, sorry.
Can you help please?

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99
> Just was able to help myself.
> Thanks again

Great! And thanks for changing it.

I'll see if I can take a look and determine if this is a data issue or front-end issue later today. After that we can begin to dig into it.
