### ISSUE TITLE
[Data Issue]: Flinders Islans South Island  missing low carbon percentage

### ISSUE THREAD

**Issue by strassburger** [electricitymaps/electricitymaps-contrib#5225]
### When did this happen?

2023-03-22

### What zones are affected?

Flinders Islans South Island

### What is the problem?

it looks same problem like solved in in this Issue by VIKTORVAV99:
Flinders Island missing low carbon percentage #5207

CO2: ?

![grafik](https://user-images.githubusercontent.com/28303688/226919892-543ab418-d400-4358-892a-55d7f4e6e186.png)

**Comment by strassburger** [comment]
@VIKTORVAV99 
Thanks for taking care and watching the issue

**Comment by VIKTORVAV99** [comment]
With the deployment of version 1.17 this should be resolved. If you are on the app it might take some time until the mobile apps are updated though.
