### ISSUE TITLE
CA-SK (Saskatchewan) daily data is available in real-time

### ISSUE THREAD

**Issue by pierresegonne** [electricitymaps/electricitymaps-contrib#5241]
## Description

(Saskpower)[https://www.saskpower.com/Our-Power-Future/Our-Electricity/Electrical-System/Where-Your-Power-Comes-From] provides a live dashboard with daily avg 
- Full power production breakdown
- Total consumption
- Total production
- Total imports/exports

We could start fetching that daily avg data to enable us down the line to build an estimation model to break it down per hour

**Comment by pierresegonne** [comment]
Not yet unfortunately. What we've done for IN-NO is just to duplicate the values for all hours of the day, with beginning of the hour convention :)

**Comment by VIKTORVAV99** [comment]
> Page says "Supply Data as of Mar 26, 2023" right now, so it's not quite real-time...

That's not really a concern as far as I know as we will be estimating this zone to get the hourly approximations.

**Comment by jarek** [comment]
See also https://github.com/electricitymaps/electricitymaps-contrib/pull/3587 for draft of a consumption parser that might be more useful now to give better estimates.

**Comment by jarek** [comment]
Saskatchewan is now on the map.

Was the idea to have EM backend use the consumption data to adjust estimated production values over the day? Is this possible?

Currently, the 24h production chart is flat throughout the day, which doesn't look very realistic and will create a bit of a credibility gap.

![image](https://user-images.githubusercontent.com/47415/232226552-2ba25a0e-5780-4735-a8ec-ddf2b06babc0.png)

**Comment by VIKTORVAV99** [comment]
> Saskatchewan is now on the map.
> 
> Was the idea to have EM backend use the consumption data to adjust estimated production values over the day? Is this possible?
> 
> Currently, the 24h production chart is flat throughout the day, which doesn't look very realistic and will create a bit of a credibility gap.

We will estimate the hourly production later on but I think we needed to collect some data to base our estimations on first and since there is no historical parsing all we can do it wait for now.

I'll double check with the data team though.
