### ISSUE TITLE
Wind animation.

### ISSUE THREAD

**Issue by MichaelWMcLeod** [electricitymaps/electricitymaps-contrib#5252]
Preferred the previous animation for the wind. The new one starts out the same, then coalesces into a large smudge, totally obscuring the underlying map.

**Comment by VIKTORVAV99** [comment]
As far as I know we haven't changed the wind layers, could you maybe provide a image/screenshot showcasing the issue?

**Comment by madsnedergaard** [comment]
Hi, this is definitely a bug. Can you provide some more context (device, etc.) and hopefully also a video or screenshot to help us debug? I've not been able to reproduce it, but you're not the first to raise this :)

**Comment by tonypls** [comment]
<img width="442" alt="image" src="https://user-images.githubusercontent.com/18622768/231972025-6919bf7f-541c-45a5-a6e7-fe2c22ddcaf2.png">

**Comment by corradio** [comment]
Is this still an issue? I think @tonypls mentioned it was fixed.

**Comment by VIKTORVAV99** [comment]
Yes it should now be fixed!
