### ISSUE TITLE
Add exports and storage to Origin of electricity graph

### ISSUE THREAD

**Issue by ghost** [electricitymaps/electricitymaps-contrib#5259]
**Is your feature request related to a problem? Please describe.**
Today, we do not display exports or storage (hydro/battery) on the origin of electricity graph available on the app. This can be a bit misleading because it doesn't accurately display the electricity available in a give zone.

_Origin of electricity graph for AT on 04-02-2023 at 12:00 PM_
<img width="453" alt="Screenshot 2023-04-03 at 13 26 43" src="https://user-images.githubusercontent.com/107848894/229524344-543200df-c14d-41a8-b8c8-ac3313b84252.png">

_Electricity production by source for AT on 04-02-2023 at 12:00 PM_
<img width="453" alt="Screenshot 2023-04-03 at 13 26 33" src="https://user-images.githubusercontent.com/107848894/229524297-46b7108a-980c-4634-afdf-bc8daf2e95ac.png">

**Describe the solution you'd like**
The Origin of electricity graph could include exports and storage and display values as negatives on the Y-axis

**Describe alternatives you've considered**
TBD

**Additional context**
This would enable us to have consistency across all visuals on the app and increase the accuracy of our charts.

**Comment by VIKTORVAV99** [comment]
I know we have had this up for discussion before but there was no clear decision made on the matter.

But I personally think this is a good idea and I'll add it to the agenda for the Avo meeting so we can discuss it more in detail. I think the biggest questions where how we should display the emissions and such but we should be able to work something out in that regard.

**Comment by corradio** [comment]
@VIKTORVAV99 curious: how do you define load and consumption? I've been using both interchangeably, but that might have been a mistake :)

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 curious: how do you define load and consumption? I've been using both interchangeably, but that might have been a mistake :)

Personally I define consumption as the usage of electricity in that particular zone and load as the total grid stress which would be consumption + export if that makes sense.

**Comment by VIKTORVAV99** [comment]
This has now been added!
