### ISSUE TITLE
Sweden installed capacity

### ISSUE THREAD

**Issue by Henrik575** [electricitymaps/electricitymaps-contrib#5268]
New numbers for Sweden, same source.

https://pxexternal.energimyndigheten.se/pxweb/sv/N%c3%a4tanslutna%20solcellsanl%c3%a4ggningar/-/EN0123_1.px/table/tableViewLayout2/

2383 Mw

**Comment by VIKTORVAV99** [comment]
While this is has the total installed capacity for Sweden as a whole it does not have the bidding zone capacities. So I'm waiting for SVK to publish their new version of the report "Kraftbalansen på den svenska elmarknaden" which we switched to when we split up Sweden. This also breaks down the installed capacity per bidding zone. They should publish this either 2023-05-31 or 2023-06-01.

**Comment by Henrik575** [comment]
Thank you :)
