### ISSUE TITLE
TERNA (Italy TSO) technical difficulties with production uploads to ENTSO-E

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#5278]
## Description
TERNA the Italian TSO currently has issues with uploading aggregated production data that is the cause of:
- #5275
- #5274
- #5273
- #5272
- #5271 
- #5270

Once the internal issues have been resolved by TERNA these issues will resolve on their own but we should re-fetch the data for this period as TERNA will backfill the data as soon as they can. The issue started 2023-04-05 and is ongoing as of this moment.

**Comment by VIKTORVAV99** [comment]
@mathilde-daugy could you re-fetch the data from the above zones? Should be from 2023-04-05 to about 2023-04-20.

**Comment by mathilde-daugy** [comment]
Is the data back online?
