### ISSUE TITLE
Languages selection menu doesn't work in mobile app

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#5283]
I'm not able to use the languages selection menu. When I click on the languages button in settings panel, the languages menu is displayed, but I can't scroll it down to select a lang that's not displayed. The menu is like frozen.

![2023-04-12-12 06](https://user-images.githubusercontent.com/364418/231427271-48c96560-94c2-49e0-ad3e-da7c90ad8e73.png)

The menu works well in the web application.

**Comment by phiphou** [comment]
I'll close it on next mobile app deployment.

**Comment by tonypls** [comment]
Should be fixed but we'll do another deployment tomorrow 🚀

**Comment by VIKTORVAV99** [comment]
> I confirm it's fixed with version 1.20.0.
> 
> Should I wait tomorow's version and check if it's still fixed before closing the issue.

Maybe waiting until the new deployment tomorrow would be best but if you want to close it already you can go ahead with that as well.

**Comment by phiphou** [comment]
Works on 1.21.0.
