### ISSUE TITLE
[Data Issue]: ridiculous hydro and nuclear estimates for South Africa

### ISSUE THREAD

**Issue by q--** [electricitymaps/electricitymaps-contrib#5327]
### When did this happen?

2023-04-24 17:42 South Africa Standard Time

### What zones are affected?

ZA

### What is the problem?

Nuclear and Hydro production are well over an order of magnitude higher than installed capacity

https://archive.is/d3aiY

**Comment by pierresegonne** [comment]
We probably ingested some nasty outliers there!

**Comment by StefanB7** [comment]
Also saw this. Here is an example:
![image](https://user-images.githubusercontent.com/22056509/234238390-0881b5dc-1e07-4eb5-99fd-dc3a16affbb9.png)

**Comment by pierresegonne** [comment]
Yes indeed. To be transparent, it looks like our data source has been providing us with completely erroneous values.
We'll refetch and if that fails mark them as ouliers

**Comment by q--** [comment]
It happened again yesterday

![Screenshot from ElectricityMap South Africa page showing nuclear generation at 235.76% of installed capacity](https://user-images.githubusercontent.com/2470175/235451135-1754f47b-8607-44f3-8826-82ef61e92b94.png)

**Comment by pierresegonne** [comment]
We have reparsed the whole data and removed the faulty data points - it shouldn't happen anymore
