### ISSUE TITLE
Update translation for zh-tw

### ISSUE THREAD

**Issue by leafoliage** [electricitymaps/electricitymaps-contrib#5344]
## Description

A lot of the translations for the zones and other parts such as buttons and title are missing in Zh-TW Chinese. I would like to update those translations. I would also do #5262 and #4782.

**Comment by VIKTORVAV99** [comment]
Not really sure what this issue is for?
If you want to update the translations, you need to create a PR for it.

I have assigned you #5262 but I will be closing this issue.
