### ISSUE TITLE
Zone name in panel is too wide and pushes gauges out

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#5352]
### Describe the bug
In some cases, especially for US zones in German (as the "USA" translation is long itself), the zone name is way too wide for the panel and therefore content is pushed out.

There's two bugs here: 

1. The gauges should not extend so far, and 
2. we should handle long zone names better so it does not overflow.

### To Reproduce

**Gauge missing:**

1. Go to https://app.electricitymaps.com/zone/US-MIDW-MISO on a mobile device
2. Change language to "Deutsch" 
3. See how the Renewable/regenerativ gauge is not showing any longer

**Overflow on mobile:**

1. Go to https://app.electricitymaps.com/zone/US-NW-NEVP on a mobile device
2. Change language to "Deutsch" 
3. See how the country label is overflowing

**Overflow on desktop:**

1. Go to https://app.electricitymaps.com/zone/US-MIDW-MISO on a desktop
2. Change language to "Deutsch" 
3. See how the country label is overflowing

### Expected behavior

1. The gauge should always show. Should be a somewhat easy CSS fix I'd imagine?
2. The zone name with Country label should not overflow. Harder to fix... A very simple quickfix could be to rename "Vereinigte Staaten" to "USA" in the German translation? 😅 

### Screenshots

<img width="426" alt="Screenshot 2023-05-03 at 08 57 55" src="https://user-images.githubusercontent.com/3296643/235851014-690c7524-0957-49dc-80f3-7f96dd57812a.png">

<img width="426" alt="Screenshot 2023-05-03 at 09 01 51" src="https://user-images.githubusercontent.com/3296643/235851024-e86acda8-284d-4181-8302-3ba910ade473.png">

<img width="483" alt="Screenshot 2023-05-03 at 08 57 42" src="https://user-images.githubusercontent.com/3296643/235851039-436dd9ee-c9aa-420c-b7bc-719cbb9e56f5.png">

**Comment by patrickwchoi** [comment]
Hi, I think I fixed this and I submitted a pull request here: https://github.com/electricitymaps/electricitymaps-contrib/pull/5365

**Comment by luuu-xu** [comment]
Hi @madsnedergaard, I have created a PR fixing this CSS issue at https://github.com/electricitymaps/electricitymaps-contrib/pull/5461.
