### ISSUE TITLE
More up-to-date data source for Bangladesh

### ISSUE THREAD

**Issue by MuffinCompiler** [electricitymaps/electricitymaps-contrib#5370]
Hey all,

the Power Grid Company of Bangladesh has a new table for its production and import data. They seem to be updated only in batches every 5-6 hours, therefore afaik basically never fulfill the real time requirement of a <2h delay. The current parser parses Daily Reports from the day before via excel files (which match this data source). Is there interest in a parser for this data source, because it contains more recent data, but still not real-time?

https://erp.pgcb.gov.bd/web/generations/view_generations
https://erp.pgcb.gov.bd/web/generations/imported_power

**Comment by VIKTORVAV99** [comment]
Hi @MuffinCompiler and thanks for finding the source!

Looks like the current parser isn't even functioning as expected so if you want to either fix that up or create a new one with this source that would be great and much appreciated.

Having realtime data would be great but if there is just a few hours delay that is not an issue.
I also noticed that the exchange config for the exchange between Bangladesh and India is wrong and should be a subzone of India instead so take note of that if you want to create a parse so you don't have to change it later.
