### ISSUE TITLE
Missing Interconnection Czechia and Slovakia 

### ISSUE THREAD

**Issue by asfi30** [electricitymaps/electricitymaps-contrib#5405]
## Description
Hi All,

There is a missing connection between Czechia and Slovakia. Entso E reports that there is a physical flow. Please see the link
https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_CTY&atch=false&dateTime.dateTime=15.05.2023+00:00|CET|DAY&border.values=CTY|10YCZ-CEPS-----N!CTY_CTY|10YCZ-CEPS-----N_CTY_CTY|10YSK-SEPS-----K&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2) 

However Electricity maps does not show the arrow as a flow between the two countries.

Regards,
Aleks

**Comment by VIKTORVAV99** [comment]
Hi @asfi30 and thanks for reporting the issue!

There is a misconfiguration in the parser that makes it always return 0 for the CZ->SK exchange. I have implemented a fix and we will re-fetch the data for the exchange once it's merged into our backend.
