### ISSUE TITLE
Bildung einer Summe

### ISSUE THREAD

**Issue by Isegrim1962** [electricitymaps/electricitymaps-contrib#5414]
Ich könnte mir vorstellen bzw. würde mir wünschen, für manche Regionen oder die Welt insgesamt eine Summe. So z.B. eine Summe für Europa oder eben die Welt als Ganzes.

Vielen Dank, Wolfgang

**Comment by VIKTORVAV99** [comment]
Hi Wolfgang!

We have been talking about aggregating bigger regions than just countries, like power grids but that is nothing that has been planned just yet so I'll close this as not planned. But do feel free to add your support for #5236 or create a more specific discussion if you have a specific region in mind.
