### ISSUE TITLE
[Data Issue]: CO2 emission shown with wrong bar length for hydro storage

### ISSUE THREAD

**Issue by RobertH-prog** [electricitymaps/electricitymaps-contrib#5510]
### When did this happen?

everyday

### What zones are affected?

Romania, Bulgaria, Sweden , Finland are just the ones I saw for EU. 

### What is the problem?

For carbon emissions, the bar showed for hydro storage is very high even though there is either 0 production hence 0 emission or not known. Even when it says 0% (eg. for Romania), the bar makes it look like it's the main polluter. 
Something wrong either with frontend or with not declaring hydro storage.

**Comment by jarek** [comment]
Indeed, I see this as well. Here are two screenshots (timezone of screenshots is UTC-4):

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/47415/6f905534-4ddd-4a3e-ad1e-76eff6000e95)

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/47415/933f1057-c9b0-4cd2-9e70-36d3c6fcded3)

**Comment by luuu-xu** [comment]
I can confirm this issue is present now. Is this a data issue or front-end? I can try working on this but I am not sure how to approach if it is data issue since I have only been working on front-end with mock server.

**Comment by VIKTORVAV99** [comment]
> I can confirm this issue is present now. Is this a data issue or front-end? I can try working on this but I am not sure how to approach if it is data issue since I have only been working on front-end with mock server.

Not sure yet, I'll try to dig into it tomorrow to determine what might be the cause.

**Comment by VIKTORVAV99** [comment]
Update: This seems to be a frontend issue only (although I have not yet found the exact cause) but the data passed to the fronted does not have any values for storage emissions (as they don't have any production values).

**Comment by luuu-xu** [comment]
@VIKTORVAV99 Did you have an idea how this is bugging out? I can try looking into it if I can run out app locally with live data. Looking through our wiki, I only found a guide on running the mock server which is what I am doing now. Can you guide me a bit on how to work on this issue? Thanks a bunch!

**Comment by VIKTORVAV99** [comment]
I don't think there is any way to run it locally with live data unfortunately (at least not without a API key).

I didn't have time to dig into where the issue is but if I had to guess it's a missing or innacurate conditional somewhere that is falling back to a value it shouldn't when the data is missing for that zone.

**Comment by lele-mathis** [comment]
This problem appears to affect the Canadian provinces as well. Has it been determined whether it's a data issue or a frontend issue? I am a newcomer interested in working on this.

**Comment by VIKTORVAV99** [comment]
It should only be an issue with the front-end. Haven't had time to determine the exact cause yet though.
