### ISSUE TITLE
[Data Issue]: hydro storage emissions in romania

### ISSUE THREAD

**Issue by Astharioss** [electricitymaps/electricitymaps-contrib#5517]
### When did this happen?

26/6/23

### What zones are affected?

Romania

### What is the problem?

In the carbon emissions chart, we can see around 30 t/min of emissions from hydro storage. If we click on the bar, it then shows 0 contributions (so I don't think it affects most of the calculations - but would be good to check?). I think it is still confusing as it seems hydro is releasing most of the emissions.

![romania](https://github.com/electricitymaps/electricitymaps-contrib/assets/82760565/35d938c6-8ca0-4115-acc9-901193e2536e)

**Comment by Astharioss** [comment]
ops sorry. didnt notice there was a ticket opened on this just below - Im blind this morning.

**Comment by VIKTORVAV99** [comment]
Closing this in favor of #5510 but thanks for reporting the issue.
