### ISSUE TITLE
[Data Issue]: aggregated yearly data has changed for 2022

### ISSUE THREAD

**Issue by Gozzima** [electricitymaps/electricitymaps-contrib#5527]
### When did this happen?

between 2023-03-11 and 2023-06-28

### What zones are affected?

Fr

### What is the problem?

The data for yearly CO2 emissions has changed for France. It was 101 gCO2eq/kWh on 11th of March and is now 90 qCO2eq/kWh.

Is this a bug or is there any explanation for this data change ?

![Screenshot_20230311_093137_Chrome](https://github.com/electricitymaps/electricitymaps-contrib/assets/71219175/ac32d164-fbcc-43b5-a8a5-09baff87bf46)
![Screenshot_20230628_134318_Chrome](https://github.com/electricitymaps/electricitymaps-contrib/assets/71219175/e031132a-837e-4072-bc7e-fcb3aae856f1)

**Comment by VIKTORVAV99** [comment]
I don't know exactly why the data for France in particular changed but we are re-running and re-processing a bunch of data right now and it could be that the data in ENTSO-E has been updated since it was first parsed by us.

Data get updated all the time in ENTSO-E and is expected to change.

I'll try and double check FR in particular though.

**Comment by w-flo** [comment]
I suspect France in 2022 would be mostly affected by import data changes?

The bars in both screenshots look quite similar with only minor changes that probably won't explain a 10% difference in emissions. In fact, the low-carbon share of production has actually decreased from 87% to 86% while emissions decreased from 101g CO2/kWh to 90, which is counter-intuitive.

However, as far as I know, there were some issues with French nuclear reactors in 2022. So France had to ramp up electricity imports in the Winter, and that imported electricity had pretty high CO2 emissions compared to what is normal for the French grid. Hence the emissions increase from 61g CO2/kWh in 2021 to 90 in 2022.

If the cross-border flows have a tendency to be updated retroactively by ENTSO-E, and that data was recently re-downloaded and re-processed too, that might explain this difference.

It could be an indication that this kind of re-download and re-processing of import/export data should be the norm, after some time has passed to let the retroactive updates settle down a bit.

**Comment by VIKTORVAV99** [comment]
We are working on an automatic re-fetch system but re-processing is very compute heavy so I don't think we will do that automatically (yet) but we have procedures for it and do so manually when we deem it needed (a few times per year). (We are exploring solutions for this).

As far as I can tell there is nothing wrong with the new data and even if the imports changed 10% reduction in carbon intensity seems a bit much but it's likely there is several factors contributing to this change that became apparent when all the data was re-processed.

What comes to mind is retroactive updates of both the production and exchange values but also improvements to estimation models.

I'll follow up with some people from the platform (data) team and see if they have any insight into why it changed that much but they are on vacation now so might take some time.

**Comment by w-flo** [comment]
> We are working on an automatic re-fetch system but re-processing is very compute heavy so I don't think we will do that automatically (yet) but we have procedures for it and do so manually when we deem it needed (a few times per year). 

Oh, I'd say a few times per year is already good enough. I simply assumed the data was usually fetched only once, shortly after it is initially published, which might be "too soon" for "final" cross-border flow data. Doing it a few times per year should be fine.

**Comment by VIKTORVAV99** [comment]
Just like to note that since this is a manual procedure right now it varies a lot between zones and when it's actually run. So for some it might be several times per year and for some far less. Which is why we are working on automatic re-fetching.

**Comment by madsnedergaard** [comment]
Closing this again since our data infrastructure has improved a lot since this issue was created.
