### ISSUE TITLE
Balearic Islands exchange capacities

### ISSUE THREAD

**Issue by silimotion** [electricitymaps/electricitymaps-contrib#5535]
REE just built a new link between Ibiza and Formentera. I went on to check if this was updated on the app, and I discovered there's no exchange capacity for the links between any of the Balearic Islands. I've searched the Internet and compiled the following data:
- Mallorca-Menorca: 100 MW
- Mallorca-Ibiza: 200 MW
- Ibiza-Formentera: New link has 2x53 MW, previous links accounted for 11 and 17 MW each

Sources:

- This [PDF](https://www.planificacionelectrica.es/sites/webplani/files/2022-12/REE_PLAN_DESARROLLO_EN.pdf) by REE
    - Page 466 has an image with several built and planned cables
    - Page 295-297 explains the Ibiza-Formentera link (2x53 MVA)
- This older and slightly outdated [PDF](<https://energia.gob.es/planificacion/Planificacionelectricidadygas/desarrollo2015-2020/Documents/Planificación 2015_2020%20 2016_11_28 VPublicación.pdf>) confirms some of the data (Pages 74 and 241) (I could only find it in Spanish)

In the case of the Ibiza-Formentera link, I've found no official statement whether the old cables are gonna be used. Probably they will be kept in case there's a grid failure or something. In any case, the new capacity would be much higher than the island's consumption, so I think joining both grids would make sense, as with Lanzarote and Fuerteventura.

Regarding the Mallorca-Menorca link, REE historical data shows that it has never been used for more than ~20MW. Apparently, this is because of grid stability concerns, and is being worked on by REE. I believe we should put 100 MW maximum capacity even though it will not reach it in the near future.

I can submit a PR with the changes to the config/exchanges files, but I would like to know your opinion about this (especially what to report in Ibiza-Formentera), and whether there's a reason this data is not in the app (maybe previous discussions I couldn't find?)

**Comment by VIKTORVAV99** [comment]
Why do you think we should combine the Ibiza and Formentera grids when the production is reported separately and we have exchange data between the two? It would lower the granularity and accuracy of the data if we did. 

The reason Lanzarote and Fuerteventura is combined is because they have a combined area (as well as separate ones) in the demanda.ree.es platform and that there is no data for the exchange between them.

It sounds to me like they are only planing on using a maximum of 53 MW and keeping the other as a redundancy in case of a sudden failure or at least have the option to do so otherwise it would be cheaper to build one bigger line.

**Comment by silimotion** [comment]
Sorry, I though Lanzarote and Fuerteventura REE data included the exchange between the islands and that this was a similar case. I now acknowledge it isn't, and I concur that Ibiza and Formentera grids should be kept separated.

On the other hand, I share your opinion that they will probably use the previous links as backup. Should we then report that the link capacity is 106 MW? (there are two 53 MW circuits)

**Comment by VIKTORVAV99** [comment]
Let's just add up the capacities for now and if we find a official capacity report (not technical capacity but NTC).

**Comment by silimotion** [comment]
Ok, but I haven't found any official report about the capacity between islands, that's why I searched the linked PDFs for the indivual cables information. It seems they only publish international links...

So, to sum up, the reported capacities should be:
- Mallorca-Menorca: 100 MW
- Mallorca-Ibiza: 200 MW
- Ibiza-Formentera: 134 MW (106+11+17)

I'll make a PR with the changes to config/exchanges soon, now that the amounts to report are clear
