### ISSUE TITLE
Data for Wrangell, Petersburg and Ketchikan (Alaska, USA)

### ISSUE THREAD

**Issue by q--** [electricitymaps/electricitymaps-contrib#5552]
The Southeast Alaska Power Agency services Ketchikan, Wrangell and Petersburg in Alaska.

They have a page with SCADA data available: https://seapahydro.org/scada

The abbreviations seem pretty intuitive: TYL =TYEE LAKE hydropower plant, SWL = SWAN LAKE  hydropower plant; WRG = WRANGELL, PTG = PETERSBURG, KTN = KETCHIKAN

The page has hydro and diesel generation. As the latter is currently 0 MW, I think it's only used as a backup.

![SEAPA SCADA](https://github.com/electricitymaps/electricitymaps-contrib/assets/2470175/1554331b-83b2-4ecf-a66a-b53ef5e2ef4d)

**Comment by VIKTORVAV99** [comment]
Looks like we can split off part of Alaska and add it as a zone with this data!
As far as I can tell there is no historical data but the realtime data seems to be of high quality and updated every few seconds.

What we need to do now is:

1. Create a new zone config for The Southeast Alaska Power Agency
2. Create a parser to fetch the new data.
3. Update the geographies to split Alaska.
4. Update the US zone config with the new zone in both the aggregated array and the excluded array (for now).

**Comment by wrma6** [comment]
Can I take this one? The task I'm currently working through with Lord Howe Island seems pretty similar so I'm hoping that I can apply what I learned from there to this task 😄

**Comment by q--** [comment]
Feel free to do so, I wasn't planning on working on this anytime soon.
