### ISSUE TITLE
pumped hydro consumption shown as generation in some parts of Europe

### ISSUE THREAD

**Issue by KabelWlan** [electricitymaps/electricitymaps-contrib#5589]
## Description
Generation is displayed correctly but it seems like consumption is shown as generation as well. I've seen this happen for Austria, Belgium, Germany, Italy, Lithuania, Portugal, Slovakia and Spain (all countries with available pumped hydro consumption on EntsoE).

Here's an example:
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/49598085/b108107c-00cb-49d0-9d7f-7aeecc2e284a)

**Comment by VIKTORVAV99** [comment]
I'll look into this as soon as possible.
