### ISSUE TITLE
[Data Issue]: Netherlands "Data is temporarily unavailable for the selected time"

### ISSUE THREAD

**Issue by Alevale** [electricitymaps/electricitymaps-contrib#5602]
### When did this happen?

Since around 12PM 16/07/2023

### What zones are affected?

"NL"

### What is the problem?

I've been following actively from my Home assistant plugin the historical of CO2 and I noticed that it stopped getting updates since around that time.

Then when I went to https://app.electricitymaps.com/ I see that at the left the graph for the pollution based on source "Electricity production by source" is saying "Data is temporarily unavailable for the selected time"

Just giving a heads up in case it doesn't resolve by itself (I feel like 12 hours is more than enough to consider that it has an underlaying issue)

**Comment by jarek** [comment]
https://storage.googleapis.com/electricitymap-parser-logs/NL.html has a lot of errors like this:

`Negative production values were detected: {'unknown'}.                    They have been set to None.`

`Negative production values were detected: {'gas'}.                    They have been set to None.    `

I have heard that it's super windy in the North Sea area today, with prices going negative. This is a pretty wild guess, but maybe NL spun down all gas and is reporting self-consumption as negative, and this makes Electricity Maps reject the data points and not calculate carbon intensity?

**Comment by VIKTORVAV99** [comment]
> Those warnings do not indicate that the data point have been rejected. It's just a warning that there were negative values in the production modes, usually self consumption and they have been set to None in the dictionary.

While true regularly could it be that the estimation model for NL expects all values to exist/be numbers and is falling because we are setting the values to None instead of 0?

**Comment by madsnedergaard** [comment]
Thanks for opening this issue and the comments! 
We found the problem in the estimation model for Netherlands and have now fixed it.

Data is back on app and API, so closing this again :)
