### ISSUE TITLE
Agregated means method

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#5617]
I'm wondering how agregated means are computed. 

For instance, for a given month, do you compute a mean with all hourly datas or do you adjust it with hourly consumption, applying different multiply factors in high comsuption period during the day ?

**Comment by madsnedergaard** [comment]
Hi, we've created a page on the wiki that explains this topic in depth :) 
https://github.com/electricitymaps/electricitymaps-contrib/wiki/Historical-aggregates

**Comment by madsnedergaard** [comment]
Hope this answers your questions, otherwise feel free to reopen this issue :)

**Comment by phiphou** [comment]
Perfect ! ;)
