### ISSUE TITLE
[Data Issue]: Western Australia data not the same as source

### ISSUE THREAD

**Issue by davidsthompson** [electricitymaps/electricitymaps-contrib#5628]
### When did this happen?

23/07/23

### What zones are affected?

Western Australia

### What is the problem?

Appears to be a significant discrepancy between wind generation shown in the app (~3%), and that shown by the energy market operator (24%) in Western Australia.

Data available below.

https://aemo.com.au/energy-systems/electricity/wholesale-electricity-market-wem/data-wem/data-dashboard#generation-fuelmix

**Comment by VIKTORVAV99** [comment]
Hi @davidsthompson!

I'm not really seeing any issue with the wind data for Western Australia? Could you mind giving a bit more detail?

**Comment by davidsthompson** [comment]
Now it seems to have switched the other way around. The Electricity Map is
saying 23% from wind but aemo
<https://aemo.com.au/energy-systems/electricity/wholesale-electricity-market-wem/data-wem/data-dashboard#generation-fuelmix>is
saying 11%. Maybe we are measuring different time periods?

Electricity map also seems to be missing landfill gas and distillate.

[image: image.png]

[image: image.png]

Thanks

Dave

**Comment by VIKTORVAV99** [comment]
The app is on a two hour delay so some lag is normal.

Landfill gas and destilite should be reported under biogas and oil respectively.

**Comment by davidsthompson** [comment]
Hi, just looking quickly again it looks like some numbers in the
electricity map are erroneous, when I go back to the same hour to match.

Oil appears to have "?" next to it when it has been dispatched during
that period and is currently being dispatched (distillate), it is currently
sitting at 3.3%.

Sorry I dont have time to compare properly today, but seem like some issues
are there to iron out.

Thanks

Dave

**Comment by VIKTORVAV99** [comment]
I have opened a issue with OpenNEM at https://github.com/opennem/opennem/issues/314 but we will have to wait and see what they say until we can proceed with this issue.

**Comment by madsnedergaard** [comment]
Closing this again until we hear back from OpenNEM
