### ISSUE TITLE
[Data Issue]: US-SE-SOCO unrealistic data being reported by the EIA

### ISSUE THREAD

**Issue by unitrium** [electricitymaps/electricitymaps-contrib#5638]
### When did this happen?

2023-07-25 01:00:00.000000 +00:00

### What zones are affected?

US-SE-SOCO

### What is the problem?

The data source reports 0s since the 2023-07-25 01:00:00.000000 +00:00 for every production on the EIA side.
Those data points are most likely errors and are influencing the numbers shown on the app.
We are monitoring the situation and will update the data once the real numbers have been published.

**Comment by unitrium** [comment]
The source is again reporting normal values but the 0s have not been back filled for now.

**Comment by enkrypt3d** [comment]
Is this taking into account the added capacity from the Vogtle Nuclear plant in GA?

**Comment by VIKTORVAV99** [comment]
> Is this taking into account the added capacity from the Vogtle Nuclear plant in GA?

What do you mean?

**Comment by unitrium** [comment]
The EIA seems to have backfilled the data from the 25th of July. I will refetch the data and start a flowtracing afterwards close this issue.

**Comment by unitrium** [comment]
Marking this issue as resolved as it only covers the 0s that were reported for US-SE-SOCO on the 25th.
Feel free to create a new issue regarding the nuclear data @enkrypt3d.
