### ISSUE TITLE
Aria labels for icon buttons

### ISSUE THREAD

**Issue by mikkelsonnenschein** [electricitymaps/electricitymaps-contrib#5695]
Hey 👋 I have some accessibility input.

### Problem
Aria labels for icon button are not sufficiently descriptive for screen reader users (something that is also flagged when running lighthouse)

### Proposal
1. Add aria labels as a prop to the icon buttons ( such as the map buttons )

It could be something like this:
```
<MapButton ariaLabel={__('ariaLabel.selectLanguage')} />
```
2. Add aria labels as a string to the localisation files 

It could be something like this:
```
"ariaLabels": {
  "selectlanguage": "Select language",
  "colorblindmode": "Color blind mode toggle",
  "windtoggle": "Wind layer toggle",
  "solartoggle": "Solar layer toggle",
  "changetheme": "Change theme"
}
```

I would like to help out with this, but unsure about to go about the translation part?

**Comment by VIKTORVAV99** [comment]
Thanks for opening this issue!
This is something we have planned on doing eventually but simply have not had the time to prioritize it.

I think your suggested approach works well and I would suggest opening a PR so we can give more direct feedback in the review.

As for the translations. Just add English ones for now (and any other language you know but avoid machine translations). Then the community can add translations later on.
(Missing translations will fall back to the English strings instead)

**Comment by mikkelsonnenschein** [comment]
Alright, sounds good. I will look into and open a PR.
