### ISSUE TITLE
Production graph tooltip is showing total consumption GW instead of only production GW

### ISSUE THREAD

**Issue by otmezger** [electricitymaps/electricitymaps-contrib#5701]
**Describe the bug**
See screenshot 
![IMG_5678](https://github.com/electricitymaps/electricitymaps-contrib/assets/2758346/1dc4ccbc-c73b-448e-97b7-c4443ed507fb)

Chart shows a total power of about 0,6GW. However, the percentage calculation of solar (shown at 22%) uses a power of 1,66GW. 

**To Reproduce**
1. Go to Lithuania 
2. Scroll to the required hour 
3. Tap the solar power in chart 
4. 

**Expected behavior**
According to the chart, solar needs to be much higher than 22%

**Smartphone (if relevant):**
 - Device: iPhone 13 mini

**Comment by VIKTORVAV99** [comment]
This is likely due to the fact that the tooltip shows all available electricity (production + imports) even when the app is set to production. So while it's a bug it's not related to the precentages.

**Comment by otmezger** [comment]
Oh right. I set the app to consumption and this happens: 
![IMG_5679](https://github.com/electricitymaps/electricitymaps-contrib/assets/2758346/91a0f807-c89f-46ae-8d38-9a781808ea0d)

now the percentage for solar is OK. 

As you mentioned, I expect in production mode to see the correct share of production for a selected energy source.
