### ISSUE TITLE
Incorrect installed solar capacity in Hungary, discussion needed

### ISSUE THREAD

**Issue by RolandSzep** [electricitymaps/electricitymaps-contrib#5712]
## Description
First of all there is new data available for the installed solar capacity in Hungary here: https://www.mavir.hu/documents/10258/246425808/PV+STATISZTIKA_HU_20230701_ig_v1.pdf/06d76259-877f-6064-4a55-cf46ac1fbbac?t=1689240158131

The reason why I opened this issue instead of doing a PR is because the installed solar capacity currently includes both the industrial-sized (over 50 kW) and the household-sized (under 50 kW) PV capacity, however the Hungarian TSO (MAVIR) only provides data about the industrial-sized production on its website and to ENTSO-E (I verified this).
Should we still include household-sized PVs in the installed capacity (despite lack of production data) or not? How is it in other countries?

The new capacity should either be 5038,843 MW (total) or 3111,698 MW (only industrial-sized).

Related issues: #3826 #5194

**Comment by VIKTORVAV99** [comment]
I think we should include it all as that is what we are doing for other countries. But I'm willing to discuss it a bit if you feel otherwise.

**Comment by RolandSzep** [comment]
Okay, consistency is key. The only drawback is the utilization being incorrect, but I agree, it's more important to see the total/"real" capacity at least.

**Comment by torokati44** [comment]
> I think we should include it all as that is what we are doing for other countries. 

It seems that after the last update according to the above (https://github.com/electricitymaps/electricitymaps-contrib/pull/6446), it seems that https://github.com/electricitymaps/electricitymaps-contrib/pull/6450 reverted to include only the industrial sized power plants.
