### ISSUE TITLE
Solar in Ontario - add distributed capacity?

### ISSUE THREAD

**Issue by jarek** [electricitymaps/electricitymaps-contrib#5714]
Hi,

In https://github.com/electricitymaps/electricitymaps-contrib/issues/5712#issuecomment-1670956470 @VIKTORVAV99 said that we should include distributed (i.e. rooftop) solar capacity in capacity figures even if there is no production data available, "as that is what we are doing for other countries".

If this is desired for Ontario (CA-ON), here is the data:

#### High-voltage-grid-connected solar
Reported in the IESO real-time data. Capacity is 478 MW as of June 2023 per https://ieso.ca/en/Power-Data/Supply-Overview/Transmission-Connected-Generation

#### Distribution-connected solar 
Not reported in real-time data because it is connected below IESO's level. Capacity is 2175.2 MW as of April 2023. Sources:
- https://ieso.ca/-/media/Files/IESO/Document-Library/contracted-electricity-supply/progress-report-on-contracted-electricity-supply.ashx "A Progress Report on Contracted Electricity Supply - First Quarter 2023" Figure 1 on PDF page 11; Table 2 on PDF page 14 - note that RESOP is the grid-connected capacity of solar, which I have subtracted out (2649 MW total contracted solar minus 473.8 MW RESOP solar).
- Compare also with inexact chart "Distribution-connected Contracted Electricity Supply" on https://ieso.ca/en/Power-Data/Supply-Overview/Distribution-Connected-Generation which looks to be a little above 2000 MW but below 2500 MW

Currently Electricity Maps lists only 478 MW of solar capacity

**Comment by VIKTORVAV99** [comment]
Hi Jarek.

I think it should be added so we have as complete data as we can. But I'm thinking maybe we should add a disclaimer for the zone as well when we do? What do you think?

**Comment by jarek** [comment]
Closing issue, as per https://github.com/electricitymaps/electricitymaps-contrib/pull/6450#issuecomment-1944675685 it appears that having capacity match production values is more beneficial
