### ISSUE TITLE
Broken CY capacity parser

### ISSUE THREAD

**Issue by silimotion** [electricitymaps/electricitymaps-contrib#5743]
## Description
Cyprus capacity is broken, caused by a change in the website. This change happened before the one that needed my previous PR #5702.
I can fix this, but I need some guidance as to what does the backend expect. Should it return the capacity when asked for any date, or only for the current time? Also, why is the capacity and production data returned together, instead of separated? In this case being returned in different calls would be more reasonable, in my opinion. Does the backend support this?

**Comment by VIKTORVAV99** [comment]
> I can fix this, but I need some guidance as to what does the backend expect. Should it return the capacity when asked for any date, or only for the current time?

Only return the capacity if the capacity for that particular time is available, otherwise omit it.

> Also, why is the capacity and production data returned together, instead of separated?

Just legacy infrastructure, we are working on it but it has not been a priority.

> In this case being returned in different calls would be more reasonable, in my opinion. Does the backend support this?

Agreed, but the backend does not support this, _yet._

**Comment by VIKTORVAV99** [comment]
> > Only return the capacity if the capacity for that particular time is available, otherwise omit it.
> 
> Ok, but capacity is only available in the real time page. How do I know if i am asked for the current time data? 

If the backend wants realtime data it will call the parser without a target datetime. Then it's up to the parser to determine how that is handled but usually it means the most recent data should be returned.

> I've seen that when no time is given all parsers assume current time, however when I manually run the parser it is always given a date, even if I don't use --target_datetime. Does the backend also always give a date?

It should not be given a date but it should return objects that have valid dates. But depending how the parser is done it might create it's own target_datetime if the target_datetime that is passed to it are None.
