### ISSUE TITLE
Broken Vietnam parser

### ISSUE THREAD

**Issue by silimotion** [electricitymaps/electricitymaps-contrib#5775]
## Description
Vietnam parser (consumption and price) crashes when run. This happens because the currently used URLs redirect to the 404 page. Data seems to have moved to other URLs inside the same page. After investigating I've found:
- [https://www.nldc.evn.vn/api/services/app/Pages/GetChartPhuTaiVM](https://www.nldc.evn.vn/api/services/app/Pages/GetChartPhuTaiVM)
  - Contains consumption data for all subregions and whole country, but only for the present day
- [https://www.nldc.evn.vn/api/services/app/Pages/GetChartGiaBienVM](https://www.nldc.evn.vn/api/services/app/Pages/GetChartGiaBienVM)
  - Similar to previous but for price
- [https://www.nldc.evn.vn/api/services/app/Dashboard/GetBieuDoTuongQuanPT?day=24%2F08%2F2023](https://www.nldc.evn.vn/api/services/app/Dashboard/GetBieuDoTuongQuanPT?day=24%2F08%2F2023)
  - Contains consumption and price data for the whole country only, but allows historical
- [https://www.nldc.evn.vn/ThiTruongDien](https://www.nldc.evn.vn/ThiTruongDien)
  - This page contains a table with the last day production data. I link it because maybe the estimation model could use it to predict production.

The current parser seems to be designed to get historical regional data, so I ask for guidance as to what to implement in this case to fix the parser (only daily regional data, historical country data, both (don't now if backend supports this), other, etc)

**Comment by VIKTORVAV99** [comment]
Thanks for the report!
