### ISSUE TITLE
[Data Issue]: Indonesia generation data is a flat line

### ISSUE THREAD

**Issue by jarek** [electricitymaps/electricitymaps-contrib#5780]
### When did this happen?

2023-08-27 00:00 UTC

### What zones are affected?

ID

### What is the problem?

The generation data and carbon intensity for Indonesia appears to be an entirely flat line. I only see changes at start of the year - no hourly, daily, or monthly differences. Is this intended? Is this considered useful?

![screenshot of hourly chart of origin of electricity in Indonesia from Electricity Map](https://github.com/electricitymaps/electricitymaps-contrib/assets/47415/aa5164b7-1015-455e-8e0f-c57cb13a42bc)

![screenshot of daily chart of origin of electricity in Indonesia from Electricity Map](https://github.com/electricitymaps/electricitymaps-contrib/assets/47415/3b047795-0e66-42aa-b683-41f2ee84f194)

![screenshot of monthly chart of origin of electricity in Indonesia from Electricity Map](https://github.com/electricitymaps/electricitymaps-contrib/assets/47415/bdcf579d-6b10-426c-8b7e-0fff14a84fd5)

**Comment by VIKTORVAV99** [comment]
We don't have a hourly production parser for Indonesia and are estimating all of the production, something that is in the info tooltip.
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/30777521/ba4f46d4-492b-4f84-90a7-ba1316c2d2ed)
I'll check in with the team and see if we can improve this though. But usually the estimations depend on weather features to estimate weather dependent sources (wind and solar) and adjust the rest from there but it don't look like there is any production from those sources in Indonesia (at least not from the current source).

**Comment by jarek** [comment]
Estimations based only on yearly data feels like opening up a can of worms to me. I know we have repeatedly turned down requests to do this for other zones in the past. Certainly if estimates based only on yearly data are OK now, we can add at least all of Canada straight away. Is Indonesia particularly important to the Electricity Maps business?

**Comment by jarek** [comment]
Has there been any update?

**Comment by VIKTORVAV99** [comment]
Ah no update yet. We have been quite busy working on other parts.

I'll see if I can someone to take a look at it at least.

**Comment by jarek** [comment]
Cool, let me know. If desired I can make PRs for missing Canadian provinces and territories with yearly averages.

**Comment by VIKTORVAV99** [comment]
Just providing an update:

There has been a lot of back and forth about this internally with different views on the matter with their own (perfectly valid) reasoning. But we have decided the following:

We will hide data on zones that only support a higher aggregation than the one shown.
This means that if the zone only have daily data we will hide it from the hourly view and only show it on the daily, monthly and yearly view.

If a zone only support monthly data we will hide it from hourly and daily, and just show it on monthly and yearly.

This is only a measure so we can continue showing data we already have though. We will **NOT** be accepting parsers that **ONLY** parse daily, monthly and yearly data.

Parsers that parse daily production data **AND** hourly consumption data will be allowed though so we can use that data to build estimation models in the future.

**Comment by silimotion** [comment]
> Parsers that parse daily production data AND hourly consumption data will be allowed though so we can use that data to build estimation models in the future.

Does this mean an estimated production hourly parser for Vietnam (#5775) is buildable now?

**Comment by q--** [comment]
Can this issue be closed now?

**Comment by jarek** [comment]
It looks like the issue reported has been addressed, so I'll close it :+1:
