### ISSUE TITLE
How should we name balancing authorities in USA? Feedback needed! 🙏 

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#5837]
I'd like to get some feedback on how people would prefer the balancing authorities in US to be named.

Currently we're going with the full title on the app (e.g. California Independent System Operator) instead of the shorter California ISO (what they use on [their own website](http://www.caiso.com/about/Pages/News/default.aspx)) or even shorter CAISO.

Same with ERCOT vs Electric Reliability Council of Texas, and so on.

### Where we need your help

Since the internal team is either European or deeply involved in the energy sector, we're lacking an understanding of how everyday citizens in the US uses these names. How does the media use the names?

The current titles are often too long to be displayed in the app, so it would be nice if we could generally use the shorter names and maybe add the full title in a tooltip - but we don't want to make that move before hearing from you :)

**Comment by madsnedergaard** [comment]
Thanks @brandongalbraith, that's very helpful 🙏

**Comment by fhteagle** [comment]
Short abbreviation + tooltip for full BA name makes sense to me as well. In the specific case of the BA for my location, WAPA -> Western Area Power Administration is probably good enough. The geopgraphical and system boundary zones within WAPA are kind of a mess anyway. So trying to point at US-NW-WACM to match the EIA reporting pools is either necessary or overkill, depending on how you look at it.

**Comment by madsnedergaard** [comment]
Thanks both! Just to make sure it's clear, it's column D that is the new, simplified name :)
So we are already planning on droppoing PUD.

> I would drop the hyphens

Do you mean the ones used in the new name, like "Duke Energy - Progress East"?

**Comment by fhteagle** [comment]
What I get for looking at it on mobile, did not even see column D lol

Agreed that the hyphens are probably not necessary. "WAPA Rocky Mountain" works for me.
