### ISSUE TITLE
Data for Guadeloupe (up to somewhere in 2022)

### ISSUE THREAD

**Issue by q--** [electricitymaps/electricitymaps-contrib#5851]
~~Hourly production data for Guadeloupe: https://opendata-guadeloupe.edf.fr/explore/dataset/mix-temps-reel-guadeloupe/~~

~~This one is only up-to-date to somewhere in 2022. ~~

~~Also mentioned in https://github.com/electricitymaps/electricitymaps-contrib/issues/1912, but that was closed due to inactivity after some of the data sources were implemented. Also, the URLs have changed.~~

Edit: looks like this one is already supported in the FR_O parser, I think

**Comment by VIKTORVAV99** [comment]
The Guadeloupe dataset is hourly but not exactly real time as it is delayed by 1 year...

I'll double check to make sure the data collection is working though.
