### ISSUE TITLE
13 Months tab instead of 12 Months

### ISSUE THREAD

**Issue by asfi30** [electricitymaps/electricitymaps-contrib#5865]
Hi All,

May I suggest an update to 13 Months tab instead of 12 Months. This way it is easier to compare the same month from the previous year. I noticed the 24 hours tab is in fact 25 hours. In any case my proposal is not associated with the  tab name, but rather with the display of the information. I find it useful to be able to compare the same hour from the previous day, same date from previous month and same month from previous year. Hope this makes sense. 

Regards,
Aleks

**Comment by VIKTORVAV99** [comment]
Hi and thanks for the suggestion!
I think it makes sense that you want to compare the data with the previous cycle (be it hourly or monthly) but I'm a bit afraid it could cause some confusion when we add a 13th month.

@madsnedergaard what do you think?

**Comment by asfi30** [comment]
Hi 

As can be seen the 25th hour displays already despite the tab is named "24 hours". This is way I suggested the same approach for the "12 months" tab and keep the name. Initial confusion would be temporary until people find out information is more beneficial. At the end of the day every change can cause some confusion, but this is part of the development and improvement.

Regards,
Aleks

**Comment by madsnedergaard** [comment]
The hourly case is a bit special because we also include latest time ("now"), whereas we in monthly cannot include the current, running month. That said, I still think it's a good point and it would definitely be cool to be able to compare things :)

So I think we should enable it and see how it goes

**Comment by asfi30** [comment]
Hi,

How about displaying the latest month from previous year? Right now in September 2023, we have information for last month - August 2023. Is it possible to display August 2022 instead of the current running month September 2023, while keeping August 2023 as well?

Regards,
Aleks

**Comment by JeanBaptisteScellier** [comment]
Hello!
What happened to this feature? I really liked it but it was reversed a few weeks ago.

**Comment by JeanBaptisteScellier** [comment]
@VIKTORVAV99 @madsnedergaard

**Comment by VIKTORVAV99** [comment]
We are updating how we are handling this but for the time being this will still be 12 months.
