### ISSUE TITLE
MN parser down

### ISSUE THREAD

**Issue by silimotion** [electricitymaps/electricitymaps-contrib#5905]
## Description
Mongolia parser is down, but the bot hasn't open an issue. I am opening this one to alert the maintainers.
It seems this time the parser is down because of a change in the json that was being parsed:
> raise ParserException(
parsers.lib.exceptions.ParserException: MN.py Parser: Fetched keys from source dict_keys(['date', 'syssum', 'tpp', 'sumnar', 'sums', 'energyimport', 't']) do not match expected keys dict_values(['date', 'syssum', 'sumnar', 'sums', 'energyimport', 't']).

A new key called tpp (thermal power plants?) has being added. The value of this new key doesn't match the previously calculated unknown production (so tpp plus other keys don't add up to consumption). What should be done to fix this? It seems an unknown source is being added.

By the way, a bit off-topic, but I have noticed that the Mongolia parser outputs global exchange data. We currently get the exchange with Russia from its parser, so we could calculate the exchange with China by substracting the other exchange. Is this possible?

**Comment by cameronjohnston** [comment]
The moldova parser (MD.py) considers "tpp" as gas. Not sure if the same assumption should apply here though. Wikipedia says Mongolia's electricity was 98% from coal (in 2012 for what it's worth), which would point to this "tpp" number representing coal: https://en.wikipedia.org/wiki/Energy_in_Mongolia 

If it is coal, I have a proposed fix ready. 

Maybe someone more familiar with these parsers / data could weigh in?

**Comment by VIKTORVAV99** [comment]
> The moldova parser (MD.py) considers "tpp" as gas. Not sure if the same assumption should apply here though. Wikipedia says Mongolia's electricity was 98% from coal (in 2012 for what it's worth), which would point to this "tpp" number representing coal: https://en.wikipedia.org/wiki/Energy_in_Mongolia
> 
> If it is coal, I have a proposed fix ready.
> 
> Maybe someone more familiar with these parsers / data could weigh in?

Looks like it is a mix of coal and oil if we look at IEA data from 2020 which means we can't assign it all to coal. But what we can do is assign it to unknown and try and use it to get the hydro share instead.

Since the current data contains wind, solar, thermal, imports and the consumption and Mongolia only have production from solar, wind, hydro, coal and oil we should be able to use that to get the hydro share with some simple math. It's not ideal but it's better than nothing.

(We have to verify it all adds up though).

**Comment by VIKTORVAV99** [comment]
> By the way, a bit off-topic, but I have noticed that the Mongolia parser outputs global exchange data. We currently get the exchange with Russia from its parser, so we could calculate the exchange with China by substracting the other exchange. Is this possible?

If the datetimes for the data match between the two sources it can probably be done but otherwise it is a lot trickier.

**Comment by silimotion** [comment]
> > By the way, a bit off-topic, but I have noticed that the Mongolia parser outputs global exchange data. We currently get the exchange with Russia from its parser, so we could calculate the exchange with China by substracting the other exchange. Is this possible?
> 
> If the datetimes for the data match between the two sources it can probably be done but otherwise it is a lot trickier.

They do! Checking so I've discovered that currently the datetime is saved incorrectly (code uses "datetime.replace(tzinfo=TZ))" instead of "datetime.astimezone(TZ)"
This causes the timezone to be +07:08 (yes, 8 minutes!)

**Comment by silimotion** [comment]
> > The moldova parser (MD.py) considers "tpp" as gas. Not sure if the same assumption should apply here though. Wikipedia says Mongolia's electricity was 98% from coal (in 2012 for what it's worth), which would point to this "tpp" number representing coal: https://en.wikipedia.org/wiki/Energy_in_Mongolia
> > If it is coal, I have a proposed fix ready.
> > Maybe someone more familiar with these parsers / data could weigh in?
> 
> Looks like it is a mix of coal and oil if we look at IEA data from 2020 which means we can't assign it all to coal. But what we can do is assign it to unknown and try and use it to get the hydro share instead.
> 
> Since the current data contains wind, solar, thermal, imports and the consumption and Mongolia only have production from solar, wind, hydro, coal and oil we should be able to use that to get the hydro share with some simple math. It's not ideal but it's better than nothing.
> 
> (We have to verify it all adds up though).

I am sorry to say that it doesn't add up:

This is the generation capacity according to [https://ndc.energy.mn/](https://ndc.energy.mn/):

![Screenshot_20230921_005014](https://github.com/electricitymaps/electricitymaps-contrib/assets/84802276/2bc2edc2-6259-4f7b-b681-c4ca80b54369)

However, many times the production left after substracting the other sources is over 23 MW. It is possible "tpp" only takes into account the power plants listed, meaning the rest comes from small coal, waste, oil or hydro power plants. We can be sure there are more plants than listed because the ones listed add up to 1532 MW of capacity.

I think we should fix the parser to work as it was doing previously, ignoring the tpp value until it is clear what all the keys mean exactly. Also to note is that the page contains several other categories, which may become populated in the future. Hydro is one of these categories:

![Screenshot_20230921_011817](https://github.com/electricitymaps/electricitymaps-contrib/assets/84802276/a55719af-baa1-45d2-b08e-67661c30f844)

(In case it is not clear, the image is powered by the data from the source the parser uses.)

**Comment by silimotion** [comment]
This is the output of the endpoint right now:
```
{"date":"2023-09-24 01:00:00","syssum":"726.23","tpp":634.74,"sumnar":45.48,"sums":67.08,"energyimport":"0.32","t":"7."} 
```

"tpp" plus the other values are over the demand value reported. I suppose this is because either erroneous reporting, or battery storage. This reinforces my point of ignoring the "tpp" value until it is clear what it is reporting/other modes are added and they sum up. I've opened #5940 with this change.

**Comment by VIKTORVAV99** [comment]
> This is the output of the endpoint right now:
> 
> ```
> {"date":"2023-09-24 01:00:00","syssum":"726.23","tpp":634.74,"sumnar":45.48,"sums":67.08,"energyimport":"0.32","t":"7."} 
> ```
> 
> "tpp" plus the other values are over the demand value reported. I suppose this is because either erroneous reporting, or battery storage. This reinforces my point of ignoring the "tpp" value until it is clear what it is reporting/other modes are added and they sum up. I've opened #5940 with this change.

How much above the consumption are we going (note consumption and demand/load is not always the same)?

Could it account for exports (consumption + exports)? if so then it should still be valid data.

**Comment by silimotion** [comment]
> How much above the consumption are we going (note consumption and demand/load is not always the same)?
Could it account for exports (consumption + exports)? if so then it should still be valid data.

Sometimes the data is over and sometimes is under. It may be due to the use of batteries, but not due to imports/exports as that is already reported.
