### ISSUE TITLE
Build parser for Saskatchewan

### ISSUE THREAD

**Issue by pierresegonne** [electricitymaps/electricitymaps-contrib#5929]
**Is your feature request related to a problem? Please describe.**
We don't have data for Saskatchewan (`CA-SK`). 
Someone reached out to show that there is a source that could enable us to build a parser https://www.saskpower.com/Our-Power-Future/Our-Electricity/Electrical-System/Where-Your-Power-Comes-From 

**Describe the solution you'd like**
Build a parser!

**Comment by VIKTORVAV99** [comment]
Eeh, @pierresegonne, we already got a parser for this one...

**Comment by pierresegonne** [comment]
Eh lol then it's broken I guess?

**Comment by pierresegonne** [comment]
Let's update the issue to "fix CA-SK" then?

**Comment by VIKTORVAV99** [comment]
It seems to be working? We have just hidden it from the app cause it only has daily data: 
<img width="729" alt="image" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/30777521/88d34816-5c18-4fe5-a948-5918819cfa32">

**Comment by VIKTORVAV99** [comment]
We will update it to show daily, monthly and yearly now that we have that capacity though.
