### ISSUE TITLE
[Data Issue]: TW missing geothermal value

### ISSUE THREAD

**Issue by shuuji3** [electricitymaps/electricitymaps-contrib#5950]
### When did this happen?

This week.

### What zones are affected?

TW

### What is the problem?

In #5903, we found the recent change of TW data source caused the incorrect geothermal value.

PR #5930 fixes the error and improved the parser code well, but it looks like the current expected geothermal value is overlooked.

The solution would be to use the English version of the source data. See #5903 for the details. ~~I'm planning to fix the issue this week.~~

**Comment by shuuji3** [comment]
closing in favor of #5939

**Comment by VIKTORVAV99** [comment]
Thanks for keeping an eye on this, but I don't think it should be closed until TW is back on the map/parser is parsing the value again.
