### ISSUE TITLE
switch from flat Mercator projection to something more 3d-related

### ISSUE THREAD

**Issue by bp-ouhaha** [electricitymaps/electricitymaps-contrib#5955]
**Is your feature request related to a problem? Please describe.**
I'm not happy to see the Electricity Live Map with all the distortion related to Mercator's projection in 2D. See here https://en.wikipedia.org/wiki/Mercator_projection#Distortion_of_sizes

**Describe the solution you'd like**
Like Google Earth, or any alternative in (real or fake) 3D, show the countries with their actual relative sizes in proportion. Ideally when scrolling around, notice it's a sphere or globe.

**Describe alternatives you've considered**
Many available that look more natural: https://en.wikipedia.org/wiki/List_of_map_projections

**Additional context**
Earth is not flat.

**Comment by jarek** [comment]
Hi, thanks for the note! Do you know of any web mapping platforms or libraries that support other projections, or have best practices for mapping on the web that you can share? I notice that Google Maps website shows me Mercator, for example.

**Comment by bp-ouhaha** [comment]
which platform are you currently using?

If it is Google Maps, I found these 2 links:
https://developers.google.com/maps/documentation/javascript/examples/map-projection-simple
https://developers.google.com/maps/documentation/javascript/maptypes#Projections

I'm not an expert in web mapping platforms...

**Comment by bp-ouhaha** [comment]
otherwise, there is a Google Earth API

**Comment by shuuji3** [comment]
ElectricityMaps uses the map library, `maplibre-gl` (ref. https://github.com/electricitymaps/electricitymaps-contrib/blob/5c0215ee5b9390169e7210294b9cebe7d0dcdb9b/web/package.json#L85C1-L85C1)

It seems like the projection feature is in a future plan, but it doesn't support other projections yet at this moment (see https://github.com/maplibre/maplibre-gl-js/issues/168).

**Comment by phiphou** [comment]
I don't think a 3D version would be as simple to use (Google Earth on mobile is a hell to use).

In a planar mode, the best compromise between shapes, areas and distances is the Winkel Triple projection.

It's more accurate and "real" but people would probably be confused with it.

Mercator projection is used everywhere, even if it's not the best. 

If projection is a wanted feature, it could be an option in settings panel.

**Comment by bp-ouhaha** [comment]
when I read about `maplibre`, I end up on these 2 interesting pages:
- https://maplibre.org/roadmap/globe-view/
- https://maplibre.org/roadmap/non-mercator-projection/

does it sound like it's coming soon?

**Comment by VIKTORVAV99** [comment]
As many have pointed out in here this is technically not possible right now so even if we wanted to do this is it not possible. Not to mention that updating to a new maplibre version will not be a trivial task as they have introduced a lot of breaking changes.

This means I will be closing this issue (for now).

With that said, I do hope maplibre adds support for it sooner rather than later so we can start testing if this is something we can actually do with our current maps and overlays.
