### ISSUE TITLE
Animations as a user setting

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#5996]
I'm not a fan of animations in the application. 

I'm talking about those for intensity square colors and gauges in left panel.

But I'm aware some love it. 

It would be cool is this was something we can specify in the settings panel, with a turn animations on and off switcher.

**Comment by VIKTORVAV99** [comment]
We can look into it for sure but I'm not sure how easy it would be to implement. I'll put it on my todo list though.

**Comment by madsnedergaard** [comment]
Thanks for sharing your feedback. 

As a first simple solution, we can easily support disabling most animations for users with [reduced motion settings](https://stackoverflow.com/a/59709067) enabled: https://react-spring.dev/docs/utilities/use-reduced-motion

Depending on browser and extensions, you can then disable "reduced motion" for a specific website (e.g. with https://www.helperbird.com/)
