### ISSUE TITLE
data needed

### ISSUE THREAD

**Issue by tammeryousef1006** [electricitymaps/electricitymaps-contrib#6002]
### When did this happen?

2023-10-11

### What zones are affected?

jordan - middle east no data

### What is the problem?

found those sources if can be added 
https://ourworldindata.org/co2/country/jordan
https://tradingeconomics.com/jordan/co2-emissions

**Comment by VIKTORVAV99** [comment]
Hi!

We don't add CO2 data directly to our database so we can't really use this data.

What we do is that we collect hourly energy production data then assign each production mode an emission factor. Once that is done we can calculate the emissions of the production on a hourly basis. Once that is done for all zones we look at the exchange flows between the zones and use a flow tracing algorithm to calculate the consumption emissions for each zones which include the emissions from production and imports (and the imports production and imports and so on).

So if we can't find the electricity production data we need we will have to close this issue unfortunately.

**Comment by VIKTORVAV99** [comment]
@tammeryousef1006 any update on this? Do you have any sources we could take a look at?

**Comment by tammeryousef1006** [comment]
Im still searching and asking around to get the right figures

**Comment by madsnedergaard** [comment]
Closing this for now, if anyone finds data feel free to reopen this issue :)
