### ISSUE TITLE
[Data Issue]: GB-NIR coal phase-out

### ISSUE THREAD

**Issue by AJDelusion** [electricitymaps/electricitymaps-contrib#6007]
### When did this happen?

2023-09-30

### What zones are affected?

GB-NIR

### What is the problem?

Northern Ireland grid mix continues to show coal use despite the fact that their last coal power plant closed down at the end of September.

https://www.bbc.com/news/uk-northern-ireland-66957611

**Comment by VIKTORVAV99** [comment]
Hi and thanks for letting us know!

I've assigned the issue to the people better suited to updating our estimation models. Hopefully it will be resolved soon but they are quite busy so it can take some time. But one it's fixed the data will be corrected retroactively.

**Comment by pierresegonne** [comment]
Thanks for flagging this! We'll be updating our estimation model shortly, I've just created an internal issue for it

**Comment by Ddock5** [comment]
<img width="283" alt="image" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/149702706/bf61f9ca-4345-47db-bd94-21fc1e5edc5f">
https://app.electricitymaps.com/zone/GB-NIR

It's still showing Coal .. no wind showing but probably 30% wind the past 24 hours

**Comment by pierresegonne** [comment]
Hey @Ddock5 thanks for raising this problem again, it's on our roadmap, we have limited capacity so it takes a bit of time before these sort of issues get fixed

**Comment by AJDelusion** [comment]
For some reason only battery and GB interconnector capacities are showing in the map. All the other capacities are 0 W.

**Comment by AJDelusion** [comment]
Looks like this one can be closed now. The coal power has been removed from GB-NIR estimations and capacity set to 0.
