### ISSUE TITLE
Add Viking Link interconnector between Great Britain and Denmark (commissioning to start next month, already listed in ENTSOE)

### ISSUE THREAD

**Issue by q--** [electricitymaps/electricitymaps-contrib#6009]
Viking Link is a 1.4 GW interconnector between Great Britain and Denmark. [Commissioning is planned throughout November and December 2023; the planned Commercial Go Live date is 1st January 2024 00.00 CET](https://www.viking-link.com/project-updates/).

ENTSOE [already lists the interconnector](https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_BZN&atch=false&dateTime.dateTime=11.10.2023+00:00|CET|DAY&border.values=CTY|10Y1001A1001A65H!BZN_BZN|10YDK-1--------W_BZN_BZN|10YGB----------A&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)). That means it's possible to add it to ElectricityMap, right?

**Comment by VIKTORVAV99** [comment]
I've been waiting for this and me and @brandongalbraith have been monitoring the situation but it seems we missed the exact date it was added.

We'll get it included as soon as possible as the parser already supports it and just need a config file for the exchange added.

**Comment by VIKTORVAV99** [comment]
I mean that would be amazing as we can't check the website all the time. But it's nothing that is expected.
