### ISSUE TITLE
Error message: TypeError: error loading dynamically imported module: https://app.electricitymaps.com/assets/MapWrapper-50dce7e7.js

### ISSUE THREAD

**Issue by shane-kerr** [electricitymaps/electricitymaps-contrib#6022]
**Describe the bug**

Web page reports an error.

**To Reproduce**
1. Go to 'https://app.electricitymaps.com/zone/NL'
2. Change to another tab
3. Change back to tab with electricitymaps

> Oh no, something went wrong...
> 
> Please let us know [on Github](https://github.com/electricityMaps/electricitymaps-contrib) so we can fix this
>
> `Error message: TypeError: error loading dynamically imported module: https://app.electricitymaps.com/assets/MapWrapper-50dce7e7.js`
> `Url: https://app.electricitymaps.com/zone/NL`

**Expected behavior**
A lovely view of the shameful carbon output of the Netherlands.

**Screenshots**
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/1943584/d7820584-111f-4d09-85c4-64ca787792e2)

**Desktop (if relevant):**
 - OS: Ubuntu 23.04
 - Browser: Firefox
 - Version: 118.0 (Canonical Snap)

**Additional context**
The tab was not viewed for a few hours. I have seen this error before, but only now felt guilty enough to report it as requested.

**Comment by shane-kerr** [comment]
This error is not trivially reproducible. I love the electricity maps and keep them open almost all the time, and only have seen this error a few times over the past several weeks.

**Comment by VIKTORVAV99** [comment]
Just wanted to let you know we haven't forgotten about this!

We are working a bit around the modules and code that is part of this so we will monitor the situation after those parts have been merged.

**Comment by shane-kerr** [comment]
I just got a similar error:

> Error message: TypeError: error loading dynamically imported module: https://app.electricitymaps.com/assets/ZoneDetails-3c3c20cf.js
> Url: https://app.electricitymaps.com/zone/NL

So it's still an issue. :smile:

**Comment by VIKTORVAV99** [comment]
It seems to be an issue that more or less only happens when we push an update with new assets and we have a plan that will hopefully fix it.

**Comment by madsnedergaard** [comment]
This has been fixed :)
