### ISSUE TITLE
[Data Issue]: No gas for Panama - PA parser

### ISSUE THREAD

**Issue by tonypls** [electricitymaps/electricitymaps-contrib#6069]
### When did this happen?

2023-10-18

### What zones are affected?

PA

### What is the problem?

There has been no gas production in Panama since the 18th of October:

<img width="573" alt="image" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/18622768/6e75bf02-24c2-46c2-81e2-1054564c23ca">

**Comment by q--** [comment]
The only gas-fired plant in Panama is the Costa Norte power plant / LNG import terminal. Maybe it's just down for maintenance.

**Comment by q--** [comment]
![30-day generation graph for panama showing natural gas generation is back for some days now after a hiatus of around 2 weeks](https://github.com/electricitymaps/electricitymaps-contrib/assets/2470175/5465bb6c-dd3b-404b-a8b0-a14b4153ac41)

It's back.

I think this can be closed.

**Comment by VIKTORVAV99** [comment]
Closing this now. Thanks for keeping a close eye on this @q--!

@tonypls if you have any objections feel free to reopen it.
