### ISSUE TITLE
visible scrollbar when choosing language

### ISSUE THREAD

**Issue by rickyl3aks** [electricitymaps/electricitymaps-contrib#6072]
**Is your feature request related to a problem? Please describe.**
When choosing the language (on desktop) it not clear you have multiple selection, because the scrollbar is not quite visible
![language](https://github.com/electricitymaps/electricitymaps-contrib/assets/65684689/ce610ada-48bc-45d0-a833-29e7d1ad2dbf)

**Describe the solution you'd like**
i think it will be better if the scrollbar would be whiter so then it will be more visible to the user

**Describe alternatives you've considered**
expands the window of the languages but it can get too long

**Comment by phiphou** [comment]
Please provide more détails on OS, browser, version, résolution, etc.

I'm not able to reproduce this on Chrome and Firefox on Windows...

**Comment by rickyl3aks** [comment]
- Ubuntu 22.04.3 LTS
- firefox
- full size desktop

the first time  i run this project i was on firefox, full size desktop, and when i was checking the languages available i didnt realize there was a scroll bar; on firefox when you press the button to switch the language you get to see the scroll bar for a few seconds then it dissapear, it is also really narrow and black, on chrome i guess its fine, it stays on the window but it is not quite visible as it is black

**Comment by madsnedergaard** [comment]
Thanks for the feedback and sorry for the lack of response, we'll reconsider this next time we're looking at the language selector :)
