### ISSUE TITLE
[Bug] [Firefox] Zone consumption data greyed-out on map after initial page-load

### ISSUE THREAD

**Issue by jayaddison** [electricitymaps/electricitymaps-contrib#6136]
**Describe the bug**
When the `electricitymap` app page is opened, initially the zone consumption data appears to be missing -- all of the zone polygons are displayed in grey.  Cross-border exports do appear as expected, however.

Workaround: toggle the time from the default of 'live' to an hour ago and then back again -- or toggle the view mode from the default of 'consumption' to 'production' and back again.

**To Reproduce**
1. https://app.electricitymaps.com/map
2. Observe that the country zone polygons are coloured grey initially.

**Expected behavior**

**Screenshots**
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/55152140/32bdfce8-8251-4561-9728-b88eb8110f4c)

**Desktop:**
 - OS: Debian Trixie (13) GNU/Linux
 - Browser: Firefox
 - Version: 115.4.0

**Additional context**
This is a problem that I've only noticed within the past week -- making me think that it could be a regression.

**Comment by jarek** [comment]
This also happens to me on Firefox. A reload usually fixes it. I wonder if this is some sort of race condition?

Here is developer console of a page load when it was greyed out. I have several privacy tools installed, I don't know if any of them are implicated, but the fact that it will usually load when I reload makes me suspect that it's not _directly_ causing it.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o192958.ingest.sentry.io/api/4504366922989568/envelope/?sentry_key=bbe4fb6e5b3c4b96a1df95145a91e744&sentry_version=7&sentry_client=sentry.javascript.react%2F7.77.0. (Reason: CORS request did not succeed). Status code: (null).

Loading failed for the <script> with source “https://plausible.io/js/plausible.local.js”. [map:117:105](https://app.electricitymaps.com/map)
Loading failed for the <script> with source “https://cdn.mouseflow.com/projects/8964f228-0fea-41ca-a8a6-dc23a38dc526.js”. [map:1:1](https://app.electricitymaps.com/map)
· · ·
· ϟ · Welcome to Electricity Maps!
· · ·
🌱 Ready to work on fixing climate change full-time?
https://electricitymaps.com/jobs
🐙 Got comments or want to contribute?
https://github.com/electricityMaps/electricitymaps-contrib
[instrument.js:123:19](https://app.electricitymaps.com/node_modules/.pnpm/@sentry+utils@7.77.0/node_modules/@sentry/utils/esm/instrument.js)
Environment Details (production) [createConsoleGreeting.ts:16:10](https://app.electricitymaps.com/src/utils/createConsoleGreeting.ts)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o192958.ingest.sentry.io/api/4504366922989568/envelope/?sentry_key=bbe4fb6e5b3c4b96a1df95145a91e744&sentry_version=7&sentry_client=sentry.javascript.react%2F7.77.0. (Reason: CORS request did not succeed). Status code: (null).

WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI. [map](https://app.electricitymaps.com/map)
Content Security Policy: The page’s settings observed the loading of a resource at blob:https://app.electricitymaps.com/b791811f-3009-4ab9-8d77-0bcc2d38d03e (“worker-src”). A CSP report is being sent. [map](https://app.electricitymaps.com/map)
Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI. [map](https://app.electricitymaps.com/map)
Content Security Policy: The page’s settings observed the loading of a resource at blob:https://app.electricitymaps.com/b791811f-3009-4ab9-8d77-0bcc2d38d03e (“worker-src”). A CSP report is being sent. [map](https://app.electricitymaps.com/map)
Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI. [map](https://app.electricitymaps.com/map)
Content Security Policy: The page’s settings observed the loading of a resource at blob:https://app.electricitymaps.com/b791811f-3009-4ab9-8d77-0bcc2d38d03e (“worker-src”). A CSP report is being sent. [map](https://app.electricitymaps.com/map)
Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI. [map](https://app.electricitymaps.com/map)
Content Security Policy: The page’s settings observed the loading of a resource at blob:https://app.electricitymaps.com/b791811f-3009-4ab9-8d77-0bcc2d38d03e (“worker-src”). A CSP report is being sent. [map](https://app.electricitymaps.com/map)
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 27
The resource at “https://app.electricitymaps.com/fonts/Poppins-Medium.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. [map](https://app.electricitymaps.com/map)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o192958.ingest.sentry.io/api/4504366922989568/envelope/?sentry_key=bbe4fb6e5b3c4b96a1df95145a91e744&sentry_version=7&sentry_client=sentry.javascript.react%2F7.77.0. (Reason: CORS request did not succeed). Status code: (null).```

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/47415/2a896904-718f-4a4d-a0a0-094adbc6b5e4)

**Comment by VIKTORVAV99** [comment]
I have not observed this myself on Safari or Edge (except for the split second it takes to load the data) does this happen all the time? Or is it somewhat random?

**Comment by jayaddison** [comment]
Thanks @VIKTORVAV99 for taking a look.  This seems to happen for around 90% of the page loads I attempt in Firefox; during those 9-out-of-10 cases, the zone colours never appear.

I've also now tried opening the app using Chromium: in that browser the zones are reliably displayed on first-page-load as expected.  So it does seem like this could be browser-specific to Firefox.

**Comment by VIKTORVAV99** [comment]
> Thanks @VIKTORVAV99 for taking a look.  This seems to happen for around 90% of the page loads I attempt in Firefox; during those 9-out-of-10 cases, the zone colours never appear.
> 
> 
> 
> I've also now tried opening the app using Chromium: in that browser the zones are reliably displayed on first-page-load as expected.  So it does seem like this could be browser-specific to Firefox.

Thanks for the additional information!

We are looking into and changing a few things with the layers right now (the zones are one of these) as well as how we load the data so hopefully that will resolve it.

If it doesn't we will take a deeper look at this but it's strange that it only affects Firefox.

**Comment by jayaddison** [comment]
One more item of context -- and I could be mistaken about this -- it looks to me like zone data _has_ been loaded despite the zone tiles appearing in grey, because data does appear in the mouseover tooltips: 

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/55152140/4944cead-558a-4842-b040-a2091c350d2a)

(I didn't notice any XHR or other network requests taking place between page load and that mouseover interaction)

**Comment by jayaddison** [comment]
I'll try some experiments related to this locally; I have an idea that #6109 could be related, but it'd be nice to prove (or at least have higher confidence) in that than to guess.

**Comment by VIKTORVAV99** [comment]
> I'll try some experiments related to this locally; I have an idea that #6109 could be related, but it'd be nice to prove (or at least have higher confidence) in that than to guess.

The change in #6109 was recently added so if it's a new thing that _shouldn't_ be it.

But yeah I think I want to wait a bit until we get those changes I talked a bit merged, should be any day now. And then dig into it if that doesn't fix it.

**Comment by jayaddison** [comment]
Ok - I think I missed the info about those planned changes, but that's ok.  It looks like the app version I've been using is [1.86.0](https://github.com/electricitymaps/electricitymaps-contrib/commit/6f673bdd489682c33d5f4de50a50e3ee46bf7b50) (that's from the contents of [`client-version.json`](https://app.electricitymaps.com/client-version.json)).

**Comment by jayaddison** [comment]
(ah: I guess you meant the layer-related changes, including zones.  my mistake!)

**Comment by jayaddison** [comment]
The page-load zone display issue is reproducible for me when developing locally (running the app on my own machine using the [`dev` script](https://github.com/electricitymaps/electricitymaps-contrib/blob/6f673bdd489682c33d5f4de50a50e3ee46bf7b50/web/package.json#L20)).

Additionally: reverting commit 6f673bdd489682c33d5f4de50a50e3ee46bf7b50 has not resolved the issue locally.  So I think that #6109 may be unrelated.

**Comment by VIKTORVAV99** [comment]
No problem, the PR I was thinking about just got merged today so I'll see if we can get a new release out.

**Comment by jayaddison** [comment]
The issue is still replicable here using version [1.87.0](https://github.com/electricitymaps/electricitymaps-contrib/commit/791e12741d2985484cd875d1ef5411fb9a5ef0ab) of the app (including in a private browser tab, which I _think_ should clear any local storage / skip cached-content reuse).

**Comment by strassburger** [comment]
@jayaddison
Can confirm  behavier discripted in comment beginning #6136

Desktop:

    OS: Ubuntu 22.04
    Browser: Firefox
    Version: 119.0.1 (64-Bit)

Additional context
This is a problem that I've  noticed within the past month...

**Comment by jayaddison** [comment]
@strassburger could you try testing the possible fix in #6167?

**Comment by strassburger** [comment]
@jayaddison, i understand that i need a local installation to run that test. That i do not have.
I am real sorry that i can not help.

**Comment by jayaddison** [comment]
@strassburger no problem - that's what I thought at first too, but @tonypls has also provided a hyperlink to a staging/test deployment of the fix that you could load in a browser.

**Comment by strassburger** [comment]
Aahh, found the Link:
https://a32116e2.electricitymaps-staging.pages.dev/map
that linksworks fine with me.
Thanks for that good job.

**Comment by jayaddison** [comment]
From testing the [latest version](https://github.com/electricitymaps/electricitymaps-contrib/commit/a46aa85e81d2e107216bd5121f7bc50977bd9be7) of the website: I can confirm that this is fixed when I view the site in Firefox: the zones appear filled-in correctly on every page load.

Thank you again @Ugzuzg!

**Comment by strassburger** [comment]
Looks like a hard job is done finaly, took really some time, but working fine now.
Thanks also again to @Ugzuzg and  to all other participants.
