### ISSUE TITLE
Tooltip overflows behind the top of the screen

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#6203]
**Describe the bug**
Tooltip goes out of bound

**To Reproduce**
1. Click on a country
2. Scroll the country panel down
3. However on a production mode high up on the screen

**Expected behavior**
Tooltip should not overflow behind the top of the screen

**Screenshots**
<img width="744" alt="image" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/1655848/66d35cc8-367e-4b7e-a8d1-e64fd3af92da">

**Desktop (if relevant):**
 - OS: MacOS
 - Browser Chrome

**Comment by PmplCode** [comment]
Hello,

I'm new to open source contributions, but I believe I've identified a potential solution for this bug. Could you please guide me on the best way to share my proposed solution with the team?

Thanks, and I appreciate the opportunity to contribute to this great project!

**Comment by corradio** [comment]
Thank you Eloi!

Olivier Corradi

Founder, CEO

Njalsgade 76

2300 Copenhagen S
electricitymaps.comlinkedin.com/electricitymaps
<https://www.linkedin.com/company/electricitymaps>[image: Electricity Maps]
<https://app.electricitymaps.com/?utm_source=signature&utm_medium=email&utm_campaign=signature>

<https://www.electricitymaps.com/jobs?utm_source=signature&utm_medium=email&utm_campaign=signature>
