### ISSUE TITLE
The graphs show the last label twice in monthly view

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#6217]
**Describe the bug**

**To Reproduce**
1. Go to any zone.
2. Change the view to show monthly aggregates.
3. Scroll down to the carbon intensity and electricity production graphs. (best visible in production mode)

**Expected behavior**
I expect the last label shown to be the month after the second last label.
(Oct -> Nov).

**Screenshots**
<img width="473" alt="image" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/30777521/f18477f9-6aa2-40d1-a4bf-8a9de39b18f3">

**Affected devices**

This affects all devices and both the app and web version of the app.

**Comment by Shadabdullah** [comment]
Have you fixed this Issue ? As it is not showing now

**Comment by VIKTORVAV99** [comment]
We haven't made any code changes that affects this.

I'm going to leave it open for now and see if it has anything to do with the dates when switching to a new month otherwise I'll close it in early January if I can't reproduce it.

**Comment by VIKTORVAV99** [comment]
This can still be reproduced so leaving the issue open.
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/30777521/8afd6260-0e39-4ccf-9c62-b97f953b204e)

**Comment by VIKTORVAV99** [comment]
@jamesg-the-dev thanks for looking into it!

I would very much appreciate a PR if you have the time. From your findings it looks like instead of counting the days we should just add one hour, day, month or year depending on what view we are on?

**Comment by james-guerra-medmate** [comment]
Yeah exactly! I'm going to try that
