### ISSUE TITLE
Country view broken unless switching to zone and back

### ISSUE THREAD

**Issue by jkfm** [electricitymaps/electricitymaps-contrib#6240]
**Describe the bug**
Since a couple of weeks, when I open Electricitymap the Country-level view map is gray without co2-intensities showing. When I switch to zone-view and back to country-view it works again.

This is pretty annoying, especially on mobile because the switching takes more clicks there.
It happens to me 

**To Reproduce**
1. Go to Electricitymap
2. The map is gray
3. Switch to zone view, the map shows colors again
4. Switch to country view, the map still shows colors

**Expected behavior**
I expect the map to show colors in country view from the beginning

**Screenshots**
This is the default view
![grafik](https://github.com/electricitymaps/electricitymaps-contrib/assets/17497479/57761b53-53fd-4509-9605-077a657c320c)

**Desktop (if relevant):**
 - OS: Win10
 - Browser Firefox
 - Version 120
 - ublock origin enabled, but the error happens without as well
 - clearing cache did not help

**Smartphone (if relevant):**
 - OS: Android 13
 - Browser Firefox
 - Version 114
 -

**Comment by tonypls** [comment]
Thanks for flagging this, looks like the same issue as #6136 

Will try get a fix out asap!

**Comment by jkfm** [comment]
Ah thanks, I had the suspicion that an issue already exists about this but
couldn't find one.

Regards,
Johannes

Tony ***@***.***> schrieb am Di., 12. Dez. 2023, 22:55:
