### ISSUE TITLE
[Data Issue]: United States - California & PJM 

### ISSUE THREAD

**Issue by Cammille-Mitchell** [electricitymaps/electricitymaps-contrib#6242]
### When did this happen?

12/12/23 approximately 3:00 pm EST

### What zones are affected?

California
PJM

### What is the problem?

The links provided for the regions California and PJM are broken. 

PJM lnk: https://www.pjm.com/page-not-found.aspx 
![pjm_connection](https://github.com/electricitymaps/electricitymaps-contrib/assets/96968550/8e45052d-74a1-40c2-aefa-f0574aaa7e62)

California CEC link: https://ww2.energy.ca.gov/almanac/electricity_data/electric_generation_capacity.html
![CEC_connection_chrome](https://github.com/electricitymaps/electricitymaps-contrib/assets/96968550/c602d4e9-e677-4db1-89eb-21bca9312430)

**Comment by UglySoftware** [comment]
I poked around a bit on the CEC and PJM sites and have some updated links:

CEC: https://www.energy.ca.gov/data-reports/energy-almanac/california-electricity-data/electric-generation-capacity-and-energy
PJM: https://www.pjm.com/-/media/markets-ops/ops-analysis/capacity-by-fuel-type-2022.ashx

I will update DATA_SOURCES.md and submit a PR.
