### ISSUE TITLE
mobile app - map displays as black screen if solar layer activated

### ISSUE THREAD

**Issue by Cammille-Mitchell** [electricitymaps/electricitymaps-contrib#6243]
**Describe the bug**
The map borders are not visible in the app if the "solar layer" is turned on. The entire map is black so there is no discernible information, except if the wind layer is also turned on. In that case the wind layer is displayed against a black background. This issue does not seem to apply to the desktop version of the map display. 

**To Reproduce**
1. Go to the app
2. Click on the settings icon 
3. Click 'Show solar layer'
4. Exit the settings window 
5. View map the map 

**Expected behavior**
Continental borders should still be visible against the darker background color. Solar power potential and carbon intensity information should be visible (based on results in the desktop version). 

**Screenshots**
Desktop version:
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/96968550/d4d92b12-7071-4509-a5bf-f41c83df94c0)
Mobile App version:

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/96968550/3731205a-88ae-4161-8972-93844d287587)

**Desktop (if relevant):**
 - OS: Windows 10
 - Browser Firefox

**Smartphone (if relevant):**
Galaxy 23

**Comment by martynas-sm** [comment]
Just a heads up, there's a related issue #6327 that seems to share similarities.

**Comment by madsnedergaard** [comment]
Thanks for reporting this @Cammille-Mitchell and thanks for fixing it @martynas-sm 😍
