### ISSUE TITLE
The labeler action is broken

### ISSUE THREAD

**Issue by pierresegonne** [electricitymaps/electricitymaps-contrib#6247]
## Description

The labeler action seems broken - it fails on all new PRs, whether they are valid or not.

Fails wiht: `Error: TypeError: Input does not meet YAML 1.2 "Core Schema" specification: sync-labels`

**Comment by VIKTORVAV99** [comment]
Yeah I noticed that, was a bit quick with a dependency update that passed all the check but I'll have a fix ready today.
