### ISSUE TITLE
[Data Issue]: Missing data for Italy since Dec. 21

### ISSUE THREAD

**Issue by q--** [electricitymaps/electricitymaps-contrib#6286]
### When did this happen?

Dec. 22 2023, 16:00

### What zones are affected?

All Italian zones, from IT-NO to Sardinia

### What is the problem?

Reported generation is only about  ¼ of actual generation

![Data error at 4PM for Sardinia, Italy - screenshot of part of the zone panel in ElectrictyMaps](https://github.com/electricitymaps/electricitymaps-contrib/assets/2470175/00e46066-388a-4497-ae17-d01f3e03a107)

**Comment by VIKTORVAV99** [comment]
Looks like there is an issue with all the data reported to ENTSO-E, so not a lot we can do about it until that is fixed.

However we are working on building a robust validation system that will hopefully prevent this in the future.

**Comment by madsnedergaard** [comment]
ENTSO-E still reports problems on behalf of TERNA, so all data is currently still estimated:

![Screenshot 2024-01-10 at 08 11 53](https://github.com/electricitymaps/electricitymaps-contrib/assets/3296643/90282f08-6dea-401f-bfa7-c01f32884062)

**Comment by VIKTORVAV99** [comment]
All the missing data seems to be available now, I have refetched it and will close this and the alerts tomorrow morning as everything should be resolved by then.

**Comment by madsnedergaard** [comment]
> ~~All~~ Most the missing data seems to be available now, I have refetched it and will close this and the alerts tomorrow morning as everything should be resolved by then.
> 
> 
> 
> The few missing hours that are left should be pretty well estimated now that we have surrounding data and will be refetched and flow traced automatically if the data is added soon-ish. Otherwise I'll do it manually.

Yay, happy to hear that! 😍

**Comment by VIKTORVAV99** [comment]
Closing this as the we now have the correct data for most of the estimated events, the rest should be automatically re-fetched and re-flowtraced soon.
