### ISSUE TITLE
[Data Issue]: Looks like Viking Link still missing

### ISSUE THREAD

**Issue by JRascagneres** [electricitymaps/electricitymaps-contrib#6300]
### When did this happen?

Noticed on 2023-12-30 but assume it was also the case previously... Link became live 2023-12-29

### What zones are affected?

DK & GB (Note not the zones)

### What is the problem?

When I filter the UI to 'Zones' I can see the DK1 <--> GB link but can't on the country view. Maybe just UI issue? Unsure.

**Comment by VIKTORVAV99** [comment]
Ah it seems I forgot to add the exchange to the country view as well as the zone view (it's available on the zone view).

I'll take care of that the coming days.

Thanks for opening the issue!

**Comment by JRascagneres** [comment]
> Ah it seems I forgot to add the exchange to the country view as well as the zone view (it's available on the zone view).
> 
> I'll take care of that the coming days.
> 
> Thanks for opening the issue!

Is this something I can easily help with?

**Comment by VIKTORVAV99** [comment]
Yeah if you want to.

We basically just need to copy the DK-DK1->GB exchange file to DK->GB and remove the parsers from it.
