### ISSUE TITLE
[data issue] Bonneville Power Administration

### ISSUE THREAD

**Issue by winkelho** [electricitymaps/electricitymaps-contrib#6301]
the data can't be correct: water power 29%, natural gas: 40% unknown: 27%
CO2: 63g

**Comment by jarek** [comment]
Was this an estimation issue, maybe?

Currently I'm seeing hydro 76% and resulting CO2eq intensity of 56 g/kWh

(timezone of screenshot is EST)

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/47415/1255fb0d-46c6-4b81-9a74-5ac4adf1454d)

**Comment by winkelho** [comment]
Sorry, I didn’t take a screenshot.

Today I’ve checked the data again and they are still wrong. Here’s my screenshot:

***@***.***

I can’t believe these data.


Von: jarek ***@***.***>
Gesendet: Montag, 1. Jänner 2024 02:29
An: electricitymaps/electricitymaps-contrib ***@***.***>
Cc: Georg Winkelhofer ***@***.***>; Author ***@***.***>
Betreff: Re: [electricitymaps/electricitymaps-contrib] [data issue] Bonneville Power Administration (Issue #6301)


Was this an estimation issue, maybe?

Currently I'm seeing hydro 76% and resulting CO2eq intensity of 56 g/kWh

(timezone of screenshot is EST)

image.png (view on web)<https://github.com/electricitymaps/electricitymaps-contrib/assets/47415/1255fb0d-46c6-4b81-9a74-5ac4adf1454d>

**Comment by VIKTORVAV99** [comment]
What part is wrong? I can't really see anything obvious that is wrong?

Nuclear, Hydro, Wind, Gas and unknown all seem to be in line with the previous days of measured data.

**Comment by winkelho** [comment]
The CO2 value

Von: Viktor Andersson ***@***.***>
Gesendet: Montag, 1. Jänner 2024 15:51
An: electricitymaps/electricitymaps-contrib ***@***.***>
Cc: Georg Winkelhofer ***@***.***>; Author ***@***.***>
Betreff: Re: [electricitymaps/electricitymaps-contrib] [data issue] Bonneville Power Administration (Issue #6301)


What part is wrong? I can't really see anything obvious that is wrong?

Nuclear, Hydro, Wind, Gas and unknown all seem to be in line with the previous days of measured data.

**Comment by jarek** [comment]
Your screenshot attachment didn't work, can you attach it directly on Github please?

**Comment by winkelho** [comment]
I've updated my comment with the screenshot

**Comment by winkelho** [comment]
The screenshot is now available in my yesterday comment

Von: jarek ***@***.***>
Gesendet: Dienstag, 2. Jänner 2024 01:48
An: electricitymaps/electricitymaps-contrib ***@***.***>
Cc: Georg Winkelhofer ***@***.***>; Author ***@***.***>
Betreff: Re: [electricitymaps/electricitymaps-contrib] [data issue] Bonneville Power Administration (Issue #6301)


Your screenshot attachment didn't work, can you attach it directly on Github please?

**Comment by jarek** [comment]
Thanks for posting the screenshot! It is showing the "emissions" mode, not the electricity consumption mode, so the percentages are how much emissions are associated with each source, not how much electricity is generated by them.

See the difference in the following two screenshots:

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/47415/8c6e97b9-aee2-4a50-be49-448202f5ab4f)

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/47415/1005ee78-6107-4c71-acff-ca8dcd7e5720)

**Comment by winkelho** [comment]
Thanks, sorry my fault, I didn’t check this. I was interested in the consumption and did not realize that I changed the view to emissions ☹

Thank you for your work! It is a great site with a lot of important data.

Von: jarek ***@***.***>
Gesendet: Dienstag, 2. Jänner 2024 19:27
An: electricitymaps/electricitymaps-contrib ***@***.***>
Cc: Georg Winkelhofer ***@***.***>; Author ***@***.***>
Betreff: Re: [electricitymaps/electricitymaps-contrib] [data issue] Bonneville Power Administration (Issue #6301)


Thanks for posting the screenshot! It is showing the "emissions" mode, not the electricity consumption mode, so the percentages are how much emissions are associated with each source, not how much electricity is generated by them.

See the difference in the following two screenshots:

image.png (view on web)<https://github.com/electricitymaps/electricitymaps-contrib/assets/47415/8c6e97b9-aee2-4a50-be49-448202f5ab4f>

image.png (view on web)<https://github.com/electricitymaps/electricitymaps-contrib/assets/47415/1005ee78-6107-4c71-acff-ca8dcd7e5720>

**Comment by jarek** [comment]
No problem, thanks for writing in and providing details!
