### ISSUE TITLE
[NEW CONNECTOR] Celtic Interconnector 2026

### ISSUE THREAD

**Issue by LucBerge** [electricitymaps/electricitymaps-contrib#6311]
**Is your feature request related to a problem? Please describe.**
In 2026 the [Celtic Interconnector](https://en.wikipedia.org/wiki/Celtic_Interconnector) between France and Ireland will be operationnal. I am openning an issue for 2026 🤣

**Comment by q--** [comment]
There's not much ElectricityMaps can do until the interconnector shows up in a data source used by ElectricityMaps.

If you want to help out, you can create a reminder in your (digital) calendar to check the interconnectors listed for France or Ireland in [ENTSO-E](https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_BZN&atch=false&dateTime.dateTime=11.10.2023+00:00|CET|DAY&border.values=CTY|10YFR-RTE------C!BZN_BZN|10YFR-RTE------C_BZN_BZN|10YBE----------2&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)) if Celtic is listed yet.

From a PDF linked as a source in the Wikipedia article

> The construction of the [Ar Merzher] converter station is scheduled from July 2023 to December 2026

so you should probably check somewhere around November 2026 (based on my experience with Viking Link, an interconnector might get added to ENTSO-E about 1-2 months before it goes live).

**Comment by VIKTORVAV99** [comment]
As q-- mentions we need the upstream changes if we want to make anything useful with this. We could in theory add the config files for it already but they would be pretty useless.

So I will close this for now as there is not much we can do about it right now but feel free to open a new one in a few years!
