### ISSUE TITLE
[Data Issue]: Upstream emissions for gas in Europe are not specified. 

### ISSUE THREAD

**Issue by Stefhis974** [electricitymaps/electricitymaps-contrib#6315]
### When did this happen?

Direct emissions in EU are calculated via EU ETS and ENTSO but nothing is said about upstream emissions for gas. How those are calculated ?  

### What zones are affected?

Europe

### What is the problem?

No explaination about uptsream natural gas emissions

**Comment by VIKTORVAV99** [comment]
Hi!

We use the EU-ETS data for the total emission of a plant and map that with the total generation from ENTSO-E and from those two values we derive the emission factor for that plant.

After that is done we average all the emissions from all plants in a zone that has the same production fuel (in this case gas) and use that as the emission factor.

You can find more details on how this works and the code used here: https://github.com/electricitymaps/electricitymaps-contrib/wiki/EU-emission-factors

**Comment by Stefhis974** [comment]
Viktor,

 

This does not answer the question. I understand how you estimate direct emissions. Here I would like to know how you calculate life cycle emissions including direct and indirect ghg emissions. For indirect emissions you cannot rely on ENSTO and EU ETS datanbase. This number as to come from elsewhere. So, how do you calculate indirect natural gas GHG emissions for Europe ? 

 

Best regards. 

 

De : Viktor Andersson ***@***.***> 
Envoyé : vendredi 5 janvier 2024 17:24
À : electricitymaps/electricitymaps-contrib ***@***.***>
Cc : Stefhis974 ***@***.***>; Author ***@***.***>
Objet : Re: [electricitymaps/electricitymaps-contrib] [Data Issue]: Upstream emissions for gas in Europe are not specified. (Issue #6315)

 

Hi!

We use the EU-ETS data for the total emission of a plant and map that with the total generation from ENTSO-E and from those two values we derive the emission factor for that plant.

After that is done we average all the emissions from all plants in a zone that has the same production fuel (in this case gas) and use that as the emission factor.

You can find more details on how this works and the code used here: https://github.com/electricitymaps/electricitymaps-contrib/wiki/EU-emission-factors

**Comment by q--** [comment]
Ah, I think I get it: the wiki [lists](https://github.com/electricitymaps/electricitymaps-contrib/wiki/EU-emission-factors#upstream-emissions) the source for the upstream emissions of Biomass,
Coal,
Hydro,
Nuclear,
Solar and
Wind, but gas isn't mentioned.

**Comment by Stefhis974** [comment]
Viktor

You got it. Gas is not mentioned! So we do not know the source of information used by electricitymap for upstream gas activities. Do you have any clue ?

Regards 

Stéphane His 

Envoyé de mon iPhone

**Comment by VIKTORVAV99** [comment]
Oh, not my area of expertise but I think we used the difference between IPCC direct emissions and IPCC lifecycle emissions as the upstream attribution. But I think this could be better explained by @mathilde-daugy or @pierresegonne if you need more details.

**Comment by Stefhis974** [comment]
Viktor 

It may be what you propose or may be something else. Can you connect me with Pierre or Mathilde to finalise this issue ?

Envoyé de mon iPhone

**Comment by VIKTORVAV99** [comment]
> Viktor It may be what you propose or may be something else. Can you connect me with Pierre or Mathilde to finalise this issue ? Envoyé de mon iPhone
> […](#)
> Le 5 janv. 2024 à 21:00, Viktor Andersson ***@***.***> a écrit : ﻿ Oh, not my area of expertise but I think we used the difference between IPCC direct emissions and IPCC lifecycle emissions as the upstream attribution. But I think this could be better explained by @mathilde-daugy or @pierresegonne if you need more details. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

I have pinged them in the github issue, and they'll likely respond when they have the time.

**Comment by Stefhis974** [comment]
Dear Viktor,

 

I trust you are doing well. I whish you a happy 2024 new year. About upstream natural gas emissions factors still no news from your colleagues. This is too bad,  since it’s important giving the role some EU countries wants natural gas to play. I hope one day I will have the answer. 

 

Best regards. 

 

Stéphane His 

 

De : Viktor Andersson ***@***.***> 
Envoyé : vendredi 5 janvier 2024 21:21
À : electricitymaps/electricitymaps-contrib ***@***.***>
Cc : Stefhis974 ***@***.***>; Author ***@***.***>
Objet : Re: [electricitymaps/electricitymaps-contrib] [Data Issue]: Upstream emissions for gas in Europe are not specified. (Issue #6315)

 

Viktor It may be what you propose or may be something else. Can you connect me with Pierre or Mathilde to finalise this issue ? Envoyé de mon iPhone
…
Le 5 janv. 2024 à 21:00, Viktor Andersson @.***> a écrit : ﻿ Oh, not my area of expertise but I think we used the difference between IPCC direct emissions and IPCC lifecycle emissions as the upstream attribution. But I think this could be better explained by @mathilde-daugy <https://github.com/mathilde-daugy>  or @pierresegonne <https://github.com/pierresegonne>  if you need more details. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

I have pinged them in the github issue, and they'll likely respond when they have the time.

**Comment by pierresegonne** [comment]
Hi @Stefhis974, sorry for the delay in answering, I was on holidays for an extended period of time. 

I have corrected the omission of some upstream emission factors in our wiki: https://github.com/electricitymaps/electricitymaps-contrib/wiki/EU-emission-factors 

Indeed, the upstream emission factors are computed as the difference between the default lifecycle and direct emission factors

**Comment by madsnedergaard** [comment]
Closing this as @pierresegonne has updated documentation :)
