### ISSUE TITLE
ElectricityMaps crashes after switching to another tab while the app is loading

### ISSUE THREAD

**Issue by q--** [electricitymaps/electricitymaps-contrib#6318]
# Steps to reproduce:
1. paste https://app.electricitymaps.com/zone/BE?wind=true in the address bar and hit Enter (note: any zone should work)
2. Immediately switch to another tab (Ctrl+Tab or Ctrl+Shift-Tab). You can also create a new tab with Ctrl+T
3. Wait a few seconds
4. Come back to the first tab. It has crashed instead of loading.

# Error message

>Error message: Error: Style is not done loading.
>Url: https://app.electricitymaps.com/zone/BE?wind=true

# Desktop
 - OS: Windows 10
 - Browser: Firefox 121.0 (latest stable)

**Comment by jayaddison** [comment]
Confirmed that I can replicate this error too (I hadn't encountered it while using the app organically, but it did occur by following the repro steps).

**Comment by q--** [comment]
Can't reproduce anymore now #6368 just went live https://github.com/electricitymaps/electricitymaps-contrib/releases/tag/v1.96.0, so closing this.
