### ISSUE TITLE
Net exchange is not translated

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#6343]
It seems net exchange is not translated in the web app.

You can see on the snapshot below that everything is translated in french except the net exchange part.

![FireShot-Capture-2210---Electricity-Maps---Émissions-CO₂-de-la-consommation-électrique-en-te_---app electricitymaps](https://github.com/electricitymaps/electricitymaps-contrib/assets/364418/f7bc58e2-c8f7-46e2-9e20-36046dd4d0e6)

**Comment by PmplCode** [comment]
Hello! You can try to update the translations of the different language files.
France: `web/public/locales/fr.json`

**Comment by phiphou** [comment]
Juste made a PR for that.

#6653
