### ISSUE TITLE
Precision of emission factors is misleading

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#6345]
## Description
The number of digits used for the emission factors are leading people to believe they are more precise than they are:
<img width="421" alt="image" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/1655848/96357a54-d8e2-46ce-a035-8275ef93ecf2">

This tweet made me realise it:
https://twitter.com/robbie_andrew/status/1733081430672941174

I suggest rounding to the nearest 10g (or the nearest g) to avoid this.

**Comment by VIKTORVAV99** [comment]
I think rounding to the whole number makes the most sense, at least for our calculated numbers, otherwise things might be even weirder since nuclear currently is below 10g for most of Europe.

But how should we handle it when some of the scientific sources we use have higher precision?

**Comment by corradio** [comment]
> But how should we handle it when some of the scientific sources we use have higher precision?

Good point - I think this could be an exception.

**Comment by w-flo** [comment]
I don't think these need to be rounded in the config file if they're just intermediate results from some calculation like the ETS/ENTSO-E mapping. Otherwise, you could argue that before starting the emission factor calculation, total emissions and total electricity generation of each plant should be rounded as well, and then round those intermediate emission factors of power plants before combining them for the country factor. So IMHO, intermediate values should be stored in high precision. (Of course we don't really need 7 decimal places, but I wouldn't say that's something that needs fixing either.)

When emission factors are displayed in the app / website for public consumption though, they should always be rounded in some way of course, to avoid the misleading impression. I believe that's already implemented everywhere?

**Comment by VIKTORVAV99** [comment]
> I don't think these need to be rounded in the config file if they're just intermediate results from some calculation like the ETS/ENTSO-E mapping. Otherwise, you could argue that before starting the emission factor calculation, total emissions and total electricity generation of each plant should be rounded as well, and then round those intermediate emission factors of power plants before combining them for the country factor. So IMHO, intermediate values should be stored in high precision. (Of course we don't really need 7 decimal places, but I wouldn't say that's something that needs fixing either.)
> 
> When emission factors are displayed in the app / website for public consumption though, they should always be rounded in some way of course, to avoid the misleading impression. I believe that's already implemented everywhere?

Thanks for your view and insights, and yes they are already rounded in the frontend.

And I suppose an argument could be made that these values are actually highly accurate (not accounting for floating point errors) but are missing some source data (not all plants have emissions reported and vice versa) which makes the derived value "wrong" but accurate.

**Comment by corradio** [comment]
I understand this argument. However, the problem remains: as a skeptical person who digs into the data sources and lands on the emission factor config file, seeing that much precision implies physical accuracy. I can thus imagine that person starting to argue about why country X has cleaner coal compared to country Y, and argue about the n-th decimal.

Maybe there's a way to decouple the concern of storing intermediary results with the concern of accurately conveying the associated accuracy of our emission factors? I guess the issue comes from the fact that the config file is also used as a "frontend" for some folks (see the tweet I mentioned).

> I think rounding to the whole number makes the most sense, at least for our calculated numbers, otherwise things might be even weirder since nuclear currently is below 10g for most of Europe.

I don't think that's an issue - we could simply avoid going under 10g.

**Comment by corradio** [comment]
@VIKTORVAV99 this seems stale - should we close it?

**Comment by VIKTORVAV99** [comment]
Yeah I think so @madsnedergaard also included some precision limits in the new emission factors so now it's just 1 or 2 decimals as well. Maybe a bit high still but it goes in the right direction at least.
