### ISSUE TITLE
Germany's solar load factor bug ?

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#6357]
From a discussion on Twitter, someone made me realized a possible bug on Germany's solar load factor.

With the datas on the webapp, I've computed solar load factor for Germany and Netherlands for the period from November 2023 to December 2023, using production and installed capacity values.

I got this : 

- Germany : 3.65% of load factor
- Netherlands : 8.74% load factor

This two countries have almost the same monthly hours of sun (see below).

![FireShot Capture 2217 - Comparaison climatique_ Allemagne _ Pays-Bas - www donneesmondiales com](https://github.com/electricitymaps/electricitymaps-contrib/assets/364418/e325df86-ebff-40cc-ab9f-866f022ea19e)

How do you explain the difference, a factor of x2.4.

I was told it maybe be because you add household's auto consumption for Germany's installed capacity but not in the production's computation.

Can you give us a more precise explanation, or confirm it's a known limitation or bug ?

**Comment by VIKTORVAV99** [comment]
Here is the notice on the transparency platform for the Netherlands data:
> TenneT NL: The publication represents the generation identifiable per fuel type, if not identifiable the data is published as "others" or not published. Data on Solar is mostly not available.

**Comment by phiphou** [comment]
I thought the problem was with Germany's data, witch seems to be lowered...

**Comment by phiphou** [comment]
Thank you for your quick and accurate answer ;)
