### ISSUE TITLE
[Data Issue]: Different URL needed for French regional pricing data

### ISSUE THREAD

**Issue by UglySoftware** [electricitymaps/electricitymaps-contrib#6367]
### When did this happen?

2020-01-01 00:00

### What zones are affected?

- FR-COR (Corsica)
- GF (French Guiana)
- GP (Guadeloupe)
- MQ (Martinique)
- RE (Réunion)

### What is the problem?

**Disclaimer:** I'm new to ElectricityMaps and this is my first time reporting an issue so I apologize in advance for all the mistakes I'm going to make :).

Possibly related to #6232, #5128 and/or #5036.

The FR_O.py parser for French overseas regions (FR-COR, GF, GP, MQ, RE) is not getting price data for any of these regions.  It looks like the pricing data field is not included in the data sets we are querying for production and consumption data.

The French energy company, eDF, provides a site with queryable data for each region.  For example, the site for French Guiana (GF) is https://opendata-guyane.edf.fr, and data can be queried at https://opendata-guyane.edf.fr/api/explore/v2.1/console.  Data is split into various datasets, each with a unique dataset_id.

The parser is querying the real-time dataset, which for GF is production-d-electricite-par-filiere-en-temps-reel (similar names for the other regions).  For pricing data it is looking for the field cout_moyen_de_production_eur_mwh, but that is not present in the real-time dataset.

There is a different dataset with production costs.  For GF it is called production-d-electricite-par-filiere-et-couts-de-production-au-pas-horaire, with similar names for the other regions.  This dataset goes back several years and does contain the cout_moyen_de_production_eur_mwh pricing field.  However, for GF at least (I haven't checked the other regions), the last valid pricing values are from 2019.  Starting in 2020, the pricing data field is still there but always Null.

We could update the FR_O parser to get pricing data from this other dataset.  Since the last good data is old, we would need to include query filters like cout_moyen_de_production_eur_mwh is not null, order by date descending, limit 1 record to just get the most recent price.  We would not want to use the usual target_datetime filter which would only retrieve newer data that is all null.

This would not be hard to do and I'd be happy to make this change.  However I wanted to put the idea out there first and see what the community thinks.  Is it useful to have some pricing data -- even if it's a few years old -- instead of no data at all?  Or would showing old pricing data be misleading?

Also I see from other issues like #6232 that perhaps more comprehensive solutions are being looked at for EU pricing data overall, and so maybe a fix for French overseas regions only is not desirable.

Thoughts?

**Comment by UglySoftware** [comment]
Replying to my own post here.  As I've come to understand the FR_O.py code better, I see that there are different URLs used depending on whether we are querying data for a specific target date, or just wanting latest real-time data:

```python
def generate_url(zone_key, target_datetime):
    if target_datetime:
        return "https://opendata.edf.fr/api/explore/v2.1/catalog/datasets/courbe-de-charge-de-la-production-delectricite-par-filiere/exports/json"
    return f"{DOMAIN_MAPPING[zone_key]}/api/v2/catalog/datasets/{LIVE_DATASETS[zone_key]}/exports/json"
```

Looks like the site https://opendata.edf.fr provides access to data for all French regions, while the other sites like https://opendata-guyane.edf.fr provides a single region only.  Oddly, the datasets returned from https://opendata.edf.fr do contain the cost data field ```cout_moyen_de_production_eur_mwh``` while the datasets returned from the region-specific sites do not.  That said, we still have the problem where the price data for recent years is null, even when retrieved from https://opendata.edf.fr.  To get price data, we'd still need to apply the filters I mentioned in my initial post, getting just the latest non-null record.

**Comment by VIKTORVAV99** [comment]
It would be great to get more realtime price data but I'm not sure if your solution would work. It seems like the dataset you linked has the same issue as the historical dataset I added last time, it only has data until December 31, 2022.

Now I only checked GF so it's possible the other overseas regions are updated more recently.

Not really sure it's worth it to change the dataset if it has the same data, especially since they had a tendency to differ a little between regions.

I'd be open to suggestions on how to improve the price data fetching though, as it has to be done manually now since the source data is so outdated.

**Comment by UglySoftware** [comment]
Sounds like we should just leave this alone for now.  I didn't realize there was a 2022 pricing dataset linked.  The "live" pricing data I found is only populated to end of 2019, so it's not an improvement.

I'll close this issue for now.  Thanks for the feedback; I'm just beginning to learn the code and how the app works.

**Comment by VIKTORVAV99** [comment]
Thanks for opening the issue, it helped to get some more insight into the EDF open data and helped explore our options!

If you need any help don't hesitate to reach out, slack would probably be easiest for this but a discussion on GitHub works too!
