### ISSUE TITLE
Spelling mistake in German translation

### ISSUE THREAD

**Issue by FlorianK13** [electricitymaps/electricitymaps-contrib#6376]
## Description
Within `web/public/locales/de.json`, the correct translation of "thisproject" is "Diese App ist". As this sentence is very prominent on the website, I wanted to report this mistake.

And of course, thanks for your great work on this project ;)

![grafik](https://github.com/electricitymaps/electricitymaps-contrib/assets/74312290/760bc175-d267-4a59-9e90-01492c06dd20)

**Comment by madsnedergaard** [comment]
Thanks for sharing it, I have created a PR in #6385 to fix it :)
