### ISSUE TITLE
Fastet Updates for the iOS and Android app

### ISSUE THREAD

**Issue by Chungaa** [electricitymaps/electricitymaps-contrib#6465]
Faster updates for Ios and Android apps. 
The Ios app is on version 1.89
The Android app is on 1.99
The web version when you visit the site with the browser is on version 1.104.0

It would be good if the updates came out faster why does it take so long for the devices.

**Comment by VIKTORVAV99** [comment]
Hi!

The reason for why it takes so long for the mobile apps to get updates is that we have to submit them for review at Apple and Google respectively, and we iterate fast for the web app driving the release numbers quickly.

We will be releasing a new mobile build next week though if things goes according to plan.
