### ISSUE TITLE
[Data Issue]: Coal production of Serbia is delayed most of the time

### ISSUE THREAD

**Issue by autipial** [electricitymaps/electricitymaps-contrib#6468]
### When did this happen?

2024-10-02 19:05

### What zones are affected?

RS

### What is the problem?

Coal production of Serbia is most of the time delayed, resulting in distorted real-time carbon-intensity.
E.g. on Feb. 10:

![Screenshot_20240210-190554_Electricity Maps](https://github.com/electricitymaps/electricitymaps-contrib/assets/7460404/e3b31066-859d-40c3-abf7-ae497826e730)

![Screenshot_20240210-190551_Electricity Maps](https://github.com/electricitymaps/electricitymaps-contrib/assets/7460404/f106229b-137b-443c-a75b-f5e477f5cfd1)

![Screenshot_20240210-190547_Electricity Maps](https://github.com/electricitymaps/electricitymaps-contrib/assets/7460404/df8ba83a-f511-49b4-bf09-24c764596b10)

**Comment by VIKTORVAV99** [comment]
Thanks for reporting the issue. I'll look into it and see what we can do about it.
