### ISSUE TITLE
[Data Issue]: South Africa Eskom ZA data not updated

### ISSUE THREAD

**Issue by intermittentnrg** [electricitymaps/electricitymaps-contrib#6475]
### When did this happen?

2024-02-03

### What zones are affected?

ZA

### What is the problem?

The Eskom data source URL does not contain data after 2024-02-03. The HTTP header of the csv file is currently `last-modified: Sun, 04 Feb 2024 17:25:35 GMT`.

https://www.eskom.co.za/dataportal/wp-content/uploads/2024/02/Station_Build_Up.csv

I use the same data to create [graphs with Grafana on my website](https://intermittent.energy/d/rK5XnQ7Vz/generation-mix?orgId=1&var-region=south_africa&var-area_type=country&var-area=All&var-demand=1&var-transmission=0&var-price=1&var-gapfill_function=interpolate&var-min_interval=5m&from=now-6M&to=now
), and noticed you have no open issue for this.

https://app.electricitymaps.com/zone/ZA also shows estimated data since 2024-02-03.

The Eskom website that links to the CSV https://www.eskom.co.za/dataportal/supply-side/station-build-up-for-the-last-7-days/ has an embedded PowerBi report which does have up to date data.

**Comment by intermittentnrg** [comment]
Sorry there seems to be an open issue for this already #5954, I didn't notice because the created date it was created last year and is being repeatedly reopened and closed.

**Comment by madsnedergaard** [comment]
The data source seems more stable now, and our estimation models have improved to cover it as well, so closing this issue again.

**Comment by intermittentnrg** [comment]
Thanks.

Worth noting that historical data can be retrieved by making a data request on the ESKOM website: https://www.eskom.co.za/dataportal/data-request-form/

Seems to automatically send a download link.
