### ISSUE TITLE
[Data Issue]: Glitch in solar production of Hungary on 2024-02-10

### ISSUE THREAD

**Issue by torokati44** [electricitymaps/electricitymaps-contrib#6482]
### When did this happen?

2024-02-10

### What zones are affected?

HU

### What is the problem?

The solar production on this day is a wild outlier, stating that 95%+ of electricity came from this source on this day.
This is physically impossible, there must be something wrong with the aggregation here.

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/288816/4b5057bd-35a3-4c74-892c-7aaa114edcee)

**Comment by VIKTORVAV99** [comment]
I have refetched the data and started processing the affected hours.

It should be fixed tomorrow.

Thanks for reporting it.

**Comment by torokati44** [comment]
Fix confirmed. Thanks!
