### ISSUE TITLE
[Data Issue]: Prefer live data from ergon.com.au in AU-QLD zone

### ISSUE THREAD

**Issue by Manu1400** [electricitymaps/electricitymaps-contrib#6503]
### When did this happen?

Now we use live data from opennem.org.au, but it's not very real-time data.

### What zones are affected?

AU-QLD

### What is the problem?

Now we use live data from opennem.org.au, but it's not very real-time data.

#### GET real-time JSON
from webpage https://www.ergon.com.au/network/manage-your-energy/managing-electricity-demand/peak-demand/electricity-network-demand:
GET https://www.ergon.com.au/static/Ergon/Network%20Demand/currentdemand.json
```json
{"db_connection":"ok","db_query":"ok","data":[{"currentdemand":{"data":"1362.798","time":"2024-02-22 01:19:32.000"}}]}
```

**Comment by VIKTORVAV99** [comment]
I'm a bit unsure how this would help us since it seems to just be demand data?

While it has its place of course we use the production data first and foremost.

**Comment by madsnedergaard** [comment]
Thanks for sharing this, but closing as it's not something we can use right now :)
