### ISSUE TITLE
Solar Layer doesn't work properly in Android App

### ISSUE THREAD

**Issue by DerHeld1** [electricitymaps/electricitymaps-contrib#6515]
Description:
When enabling the solar layer the map just turns completely black. This doesn't happen using a web browser on PC. 

Steps to reproduce:

- Enable solar layer
- observe how everything turn black

![Screenshot_20240227-092041](https://github.com/electricitymaps/electricitymaps-contrib/assets/150757004/d684f401-d8d3-4515-a96e-b3541ea6d76c)

Expected behaviour:

Solar layer being shown like in a web browser on PC with dark spots, light spots and yellow spots for that perfect solar energy production. 

Smartphone Data:

Google Pixel 7 Pro
Android 14 Build: UQ1A.240205.002
App Version: 1.99.0

**Comment by VIKTORVAV99** [comment]
Hi and thanks for the bug report!

This is indeed a bug and something we will take a look at as soon as we have the time 🙂

**Comment by VIKTORVAV99** [comment]
Just noticed we already have an issue for this here: https://github.com/electricitymaps/electricitymaps-contrib/issues/6327

So closing this in favour of that.
