### ISSUE TITLE
[Data Issue]: ENTSO-E outage. Missing data for Germany

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#6597]
### What zones are affected?

DE

### What is the problem?

The data reported to ENTSO-E is incomplete due to one or multiple TSOs not reporting any data. When this happens for a prolonged period we disable all estimations of the zone to avoid showing incorrect data.

We have no time horizon on when this will be fixed, we urge you to ask any further questions to ENTSO-E.

Here is the link to the ENTSO-E transparency platform showing the issue: [ENTSO-E Transparency - 
 Germany](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=CTA&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=03.04.2024+00:00%7CCET%7CDAYTIMERANGE&dateTime.endDateTime=03.04.2024+00:00%7CCET%7CDAYTIMERANGE&area.values=CTY%7C10Y1001A1001A83F!CTA%7C10YDE-ENBW-----N&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))
 
>[!NOTE]
>This issue is reused for whenever we have problems with ENTSOE data for Germany

**Comment by madsnedergaard** [comment]
Seems like it's back now :)

**Comment by madsnedergaard** [comment]
Problems started occuring again yesterday

**Comment by ablohm** [comment]
Is there any info from ENTSO-E or Amprion on this issue? This is going on for days now.

**Comment by VIKTORVAV99** [comment]
> Is there any info from ENTSO-E or Amprion on this issue? This is going on for days now.

Not as far as we have been able to find. So it would be best to reach out to ENTSO-E about the matter.

**Comment by madsnedergaard** [comment]
I also reached out to ENTSO-E yesterday asking about this, will update here when I get a response.

**Comment by ablohm** [comment]
Reached out to ENTSO-E and got this:

"Thank you for your e-mail. We have contacted the relevant data provider on your request and will update you on the matter as soon as we receive a response."

**Comment by ablohm** [comment]
Looks like Amprion data is available again on the ENTSO-E website. So we might just have to wait until electricitymaps.com picks the data up.

**Comment by fewrede** [comment]
Good morning.
As far as I can see, the data is still not complete. The PsrType B16 (solar) is still not being transmitted... I'm curious to see whether that changes over the course of the day. It is noticeable that such problems have been occurring more and more frequently in the German region in recent months.

Best regards.

**Comment by ablohm** [comment]
> The PsrType B16 (solar) is still not being transmitted...

Yeh... you're right. I was a bit too enthusiastic.

**Comment by fabboe** [comment]
On electricitymaps also all historical aggregates of Germany are missing, this wasn't the case on previous outages. Is this related? 

Also Netherlands has "100% estimated" for all 13 available monthly aggregates, similar for Switzerland. Maybe related?

**Comment by koyaanis** [comment]
^ Funny enough, when Germany did have the Daily historical aggregates available, it was 91% estimated on March 31 and showed that 13% of Germany's electricity was produced by nuclear. These estimates seem to be quite off

**Comment by VIKTORVAV99** [comment]
> On electricitymaps also all historical aggregates of Germany are missing, this wasn't the case on previous outages. Is this related? 
> 
> The issue isn't specific to what periods are missing so it sounds like only March 31 forward.
> 
> Also Netherlands has "100% estimated" for all 13 available monthly aggregates, similar for Switzerland. Maybe related?

Netherlands is being estimated because the solar value in ENTSO-E is an order of magnitude lower than they should be, this affects all the Netherlands data and is unrelated to this.

A fix for this is also under development at #6634. Please try and keep this issue focused on Germany though but feel free to leave comments in that PR.

**Comment by allocater2** [comment]
If https://energy-charts.info/charts/power/chart.htm can show the data, there should be a way to get it.

**Comment by VIKTORVAV99** [comment]
> If https://energy-charts.info/charts/power/chart.htm can show the data, there should be a way to get it.

Energy Charts is made together with Fraunhofer Institute for Solar Energy Systems ISE and use a combination of 10 different sources for their data in different fallback configurations. This is great and something we could benefit from as well but we don't (yet at least) support using multiple sources for the same region.

**Comment by StephanKaula** [comment]
But why are older data like the years averages for germany not available?

**Comment by madsnedergaard** [comment]
We are planning to allow monthly and yearly aggregates despite hourly outages, but it's not done yet :)

**Comment by ablohm** [comment]
The Amprion data is recovering. I can see today's data now. There still is a gap from 2-apr 19:45 UTC to 3-apr 22:00 UTC.

**Comment by ablohm** [comment]
The data seems to have been fully restored now. Get it into the database quickly... :-D

**Comment by VIKTORVAV99** [comment]
I have refetched the data and enabled the historical data again, it will take a 2-3 hours for everything to propagate and the daily data will be updated at the end of the day so should be all resolved tomorrow.

Will leave the issue open for now though.

**Comment by ablohm** [comment]
Got an update from ENTSO-E:

> To follow up on your request, please find below the feedback that we received.
>  
> "The data issues between March 29 and April 5 due to a technical problem have now been resolved. The underlying malfunction has now been resolved. The missing data has been updated in full and is available on the platform as usual."

**Comment by madsnedergaard** [comment]
Aaand we're back...

**Comment by madsnedergaard** [comment]
Data is back on the platform again now, I'll remove the outage message, but it has been on/off for the last few days so there's a high chance it's going to happen again :/

**Comment by madsnedergaard** [comment]
We are having issues again, reopening this one.
