### ISSUE TITLE
[Feedback Wanted]: Revise the colours used for electricity sources in all graphs

### ISSUE THREAD

**Issue by Alportan** [electricitymaps/electricitymaps-contrib#6615]
**Aim/purpose**
We want to ensure that the source of electricity colours closely resemble their real-world counterparts or follow industry standards, as well as align them better with existing mental models.

**Proposed solution**
We aim to enhance the colours distinction, coherence, saturation and contrast (for both light and dark themes).

Here's a quick overview of the major changes:
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/149581095/24069ce3-eb3b-4078-a905-11e79a7dff71)

⚛️ **nuclear** - after analysing data from multiple energy insights and statistical platforms, there were a quite few colours used to represent this source. We chose to follow the industry trends (regards to colours of electrolysed hydrogen - [pink](https://arc.net/l/quote/ndtaaekt)) gave it a purple touch for better contrast.
💨 **wind** - going towards a light blue, aligning it more closely with the hue of the sky.
☀️ **sun** - switched from orange to a warmer yellow [to reflect the boundaries of visible wavelengths here on Earth](https://arc.net/l/quote/mpgdfukc).
♨️ **geothermal** - switching from yellow to a more earthy (brown) shade of red.
🔋 **battery storage** - moved away from the pinkish purple towards a more lithium turquoise.
🔥 🪨 🛢️ **fossils** - deemphasised them altogether by giving them different shades of grey.

**The colours in action on a graph 👇** 
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/149581095/10dfbb9b-7424-4af4-abcc-a07c2d810411)

We want to ensure that these colour choices resonate with you and accurately represent the diverse range of energy sources. While we've put considerable thought into selecting these colours, we recognise that there may be room for improvement.

Let us know if any colours seem ambiguous or if there are suggestions for adjustments that would enhance clarity and comprehension. 🙏

Feel free to drop your thoughts or any questions in this thread.

**Comment by dzedler** [comment]
Love it!

**Comment by PmplCode** [comment]
I like it! 👍🏼

**Comment by q--** [comment]
I'm not sure about the different shades of green being added... Can you give an example with imports? I wonder if they don't look to much like those.

**Comment by Alportan** [comment]
> I'm not sure about the different shades of green being added... Can you give an example with imports? I wonder if they don't look to much like those.

Thank you for your feedback! 🙏

There is additional work being done on for the whole **Electricity production/consumption by source** graph as we speak, where the purpose is to simplify some things and add an explanatory layer on top for better understanding of the data being shown. 

Today we show the colour for carbon intensity on each bar which doesn't coincide with the sources and there is no explanation for it. The proposed solution is to bundle exchanges altogether under one source (since electricity exchanges are technically a source). It would look something like this 👇 
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/149581095/18dd7baf-2e9e-42d9-9265-0f7bf2b06ee3)

You can have a sneak peak into the design in [this prototype]. (which will be shared in a new issue soon)(https://www.figma.com/proto/qnPZB2pjFhiOQ3X7kQK911/Rethink-the-way-we-explain-and-show-exchange-data?page-id=4120%3A70&type=design&node-id=4165-3046&viewport=-1753%2C731%2C0.5&t=I6ekmpyBErVaDm7p-1&scaling=contain&starting-point-node-id=4165%3A3046&mode=design)

Let me know if you have any questions! 🙌

**Comment by q--** [comment]
> Let me know if you have any questions! 🙌

Will the origin of electricity graph not have the carbon intensity coulors either, like it is shown in the mockup? I'd consider it one of the most interesting things on ElectricityMap that you can see that e.g. a country is exporting greener electricity at a time the sun is shining, or that e.g. Germany reduced the carbon emissions of its power plants in in spite of the Atomausstieg, but some of that is simply due to importing more polluting power from elsewhere etc.

This is especially the case where a country is importing from a lot of this others (Germany is the best example, especially  when there's low rememberable generation) and it isn't feasible to click through to every other country.

**Comment by Alportan** [comment]
> Will the origin of electricity graph not have the carbon intensity coulors either, like it is shown in the mockup? 
Sounds like a good use-case, the biggest issue with the origin of electricity graph (if you are talking about this graph 👇 ) is that it's using 2 different colour scales, one for the sources and another one for the carbon intensity. Since there are usually 3-5 exporting players for most countries, all with different carbon intensities, the graph can easily become cluttered and rather hard to read/distinguish the sources from carbon intensity from exchanges. **If you are talking about the initial graph I shared, continue reading. 🙂**

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/149581095/3bde2914-6b71-430b-ac40-56b5a7a080bb)

> This is especially the case where a country is importing from a lot of this others (Germany is the best example, especially when there's low rememberable generation) and it isn't feasible to click through to every other country.

I do see now that keeping the carbon intensity colours for each exchange in the first graph (with a legend for the scale itself underneath) does make sense, as you can immediately see why the carbon intensity at a current time changes so much due to exports.

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/149581095/73fabb1b-0780-426c-83f3-92e69f3127c0)

Ideally we want to make it easy for anyone, new or old to the app to understand our data better, and this is the general direction we're heading at the moment. Hope that makes sense!

**Comment by phiphou** [comment]
For me, grey means unknown and brown dirty. So I would keep brown for oil and coal...

**Comment by Alportan** [comment]
> For me, grey means unknown and brown dirty. So I would keep brown for oil and coal...

Thanks for the feedback! Would a pastel brown work instead? 

We want to downplay fossils as much as we can, making the low-carbon sources stand out. @phiphou

**Comment by Alportan** [comment]
> I'd consider it one of the most interesting features of ElectricityMap that you can see that e.g. a country is exporting greener electricity at a time the sun is shining, or that e.g. Germany reduced the carbon emissions of its power plants in in spite of the Atomausstieg, but some of that is simply due to importing more polluting power from elsewhere etc.

What if you would still have access to this information in the exchanges graph below, instead of bundling it with the data sources? @q-- This way the information is clearer in the first graph, and we group information more logically into their categories. 🤔

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/149581095/93697845-8856-4b5a-8e25-f0a47005e8e3)

**Comment by phiphou** [comment]
@Alportan Not a design expert but don't understand why you don't take a dark brown for oil and coal (and maybe gas). 

However, I understand you want to have a beautifull color scheme, and distinct colors for all energy sources (ortherwise nuclear should be green).

Maybe you can keep proposal but just with darker colors for oil, coal and gas, and brighter color for geothermal.

![FireShot Capture 031 -  Feedback Wanted _ Revise the colours used for electricity sources in_ - github com2](https://github.com/electricitymaps/electricitymaps-contrib/assets/364418/287bdce2-a1d0-4a7b-86d9-fd71b35a26dd)

**Comment by Alportan** [comment]
> @Alportan Not a design expert but don't understand why you don't take a dark brown for oil and coal (and maybe gas).
> 
> [...]
> 
> Maybe you can keep proposal but just with darker colors for oil, coal and gas, and brighter color for geothermal.

I see your point! The main reason for having neither a very light or dark colours is to keep them consistent in a range which would work on both our light and dark theme, to comply with the APCA accessibility guidelines of at [least Lc 15](https://arc.net/l/quote/ofmukbcf) on graphic elements. 

With this in mind, we want to make sure that our app is compliant with most visual impairments by following these standards, so there is a possibility to switch the dark grey for coal to a more browner shade, but we still need to keep a lightness level above these guidelines.

I hope that answers your question. @phiphou

**Comment by phiphou** [comment]
We may have two color schemes, one classic mode and one for the color-blind mode ?

**Comment by Alportan** [comment]
> We may have two colour schemes, one classic mode and one for the colour-blind mode ?

Thank you for your follow-up message and suggestion! 

While our existing colour-blind mode targets specific impairments, we also want to ensure that our app is accessible to a broader audience with common conditions affecting vision, including nearsightedness, farsightedness, and other refractive errors.

**Comment by phiphou** [comment]
Consider #6700 for this big desgin change.

**Comment by VIKTORVAV99** [comment]
> Consider #6700 for this big desgin change.

This issue focuses just on the colours themselves and how they are represented, it is unrelated to any potential tooltips or any other features. Please do try and keep the issues separate.

**Comment by madsnedergaard** [comment]
This has been implemented, thanks for the feedback!
