### ISSUE TITLE
Separate the disputed area of Western Sahara

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#6618]
## Description

We currently show the Moroccan-controlled area of Western Sahara as part of Morocco.
Since the actual ownership of this areas is disputed and unclear, it would make sense to merge the area into a full Western Sahara zone.

See our [guide on how to edit the geometries](https://github.com/electricitymaps/electricitymaps-contrib/wiki/Edit-world-geometries) if you want to pick this up :) 

![Screenshot 2024-04-03 at 09 37 47](https://github.com/electricitymaps/electricitymaps-contrib/assets/3296643/91f8e7c2-9265-49d0-8a35-39b709be3045)

More details on the conflict: 
- https://www.aljazeera.com/news/2020/12/11/western-sahara-conflict-in-500-words
- https://www.bbc.com/news/world-africa-14115273

How Google Maps shows the area:

![Screenshot 2024-04-03 at 09 37 03](https://github.com/electricitymaps/electricitymaps-contrib/assets/3296643/a015d7a8-360c-423c-93ec-13195bd071d9)

**Comment by ryanguomd** [comment]
Hi, I would like to work on this!

**Comment by VIKTORVAV99** [comment]
> Hi, I would like to work on this!

Hi and thanks!

I'll asking you the issue.

**Comment by VIKTORVAV99** [comment]
> I'm getting a yarn install error when I try to run `yarn && yarn update-world` in the 'web' folder. 
> 
> ![Screenshot 2024-04-15 at 4 47 21 PM](https://github.com/electricitymaps/electricitymaps-contrib/assets/114361288/f46ff102-b074-470e-8d6b-0511480b552a)

Ah it appears this wiki page has slipped us by. We shifted to using PNPM a while back so it should work with that instead.

**Comment by ryanguomd** [comment]
> Double check your node version as well, we have not tested that any packages work on node 21 as we only increment LTS versions (even version numbers).

Thanks, I'm using node v20 now. I changed the borders in an untitled project on QGIS, but I'm a bit confused on how I can see if I'm actually directly editing the world.geojson file. Also, running `pnpm generate-world` gives this error:

![Screenshot 2024-04-15 at 8 03 42 PM](https://github.com/electricitymaps/electricitymaps-contrib/assets/114361288/0a027d3f-5099-4154-8b5e-94ed4beeda9e)

Couldn't find much from debugging so far.
