### ISSUE TITLE
RFC: New production mode colors!

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#6622]
## Description

We are rethinking the colors we use for our production modes! 🎨 

On our Slack channel @Alportan is sharing more details and asking for feedback if you have any opinions you want to share :)

https://electricitymaps-cntrb.slack.com/archives/C06GS9N6B0C/p1712052936642069

![Screenshot 2024-04-03 at 10 19 36](https://github.com/electricitymaps/electricitymaps-contrib/assets/3296643/420b15bc-0856-4695-98fe-d60ea0f5248f)

**Comment by VIKTORVAV99** [comment]
Eeh, Mads...

We already have a pinned issue about this at https://github.com/electricitymaps/electricitymaps-contrib/issues/6615 😅

**Comment by madsnedergaard** [comment]
Oh, totally missed it - I searched for "colors" and not "colo**u**rs" 🤦

**Comment by VIKTORVAV99** [comment]
> Oh, thanks Viktor! I totally missed it - I searched for "colors" and not "colo**u**rs" 🤦

You'll have to talk with Alex about that 😉

**Comment by Alportan** [comment]
Oups... 🙈 I might have Britishized it a tad too much 😅

**Comment by madsnedergaard** [comment]
Haha no it's fine, I'm the one who should have been a bit more thorough before creating a new issue 😂

**Comment by VIKTORVAV99** [comment]
Should we hide your misstakes by deleting this issue? 😉
