### ISSUE TITLE
[frontend] Climate Impact by Area ranking: some zones without data are sorted below low-impact areas.

### ISSUE THREAD

**Issue by jayaddison** [electricitymaps/electricitymaps-contrib#6636]
**Describe the bug**
The homepage displays a ranking of areas by climate impact, and it appears that these should be sorted with the lowest-impact area at the top of the list.

When viewing the homepage at the moment, I find three regions where data is unavailable displayed at the top of the list; after those a region with data and less-than 20g CO2/kWh appears next.

That's the bugreport; the regions without data shouldn't be ranked at the top of the list I don't think?

**To Reproduce**
1. Go to https://app.electricitymaps.com/
2. Inspect the "Climate Impact by Area" widget near the top-left of the page.
3. Observe regions where data is currently unavailable at the top of the list.

**Expected behavior**
The top-rated area/zone should be one with the lowest climate impact based on currently available data.

**Screenshots**
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/55152140/0fdad69f-9807-46d6-8f9b-0b84d8c82730)

**Desktop:**
 - OS: Debian Linux
 - Browser: Firefox
 - Version: v155.9

**Additional context**
Data seems to have previously been available in Canada's Saskatchewan, another zone that currently appears ranked as lower-impact than others despite an absence of live data at the moment.

**Comment by jarek** [comment]
More data points: both Hong Kong and Indonesia have only yearly data, and Saskatchewan only has daily (but not hourly) data. (You can see this with the "Display data from the past" switcher in lower left corner of the page.)

I see Hong Kong and Indonesia at the top of "hourly" climate impact by area list, and after viewing Saskatchewan, it is also added to that list. When viewing the "daily" climate impact by area list, Hong Kong and Indonesia are still at the top, but Saskatchewan is in the correct place.

So it seems related to not having hourly/daily data for an area.

**Comment by andiz2** [comment]
Hi guys! I would like to dive deep into this 😄 
Is there any documentation about where the datas is fetched from and where is it saved into so the browser would took it from?

Regards,
andiz2

**Comment by VIKTORVAV99** [comment]
We should be able to fix this in the front end by filtering out nullish data but I'll also check if there is a simple fix for this that can be made in the backend.

**Comment by andiz2** [comment]
I've sorted it from front-end side.
Changed the filter from getRankingPanelData to:
`    .filter(
      (zone) =>
        zone.co2intensity !== undefined && zone.co2intensity !== null &&
                filterZonesBySpatialAggregation(zone.zoneId, spatialAggregation)
    );`
    Now it looks to filter the datas as it should.

**Comment by VIKTORVAV99** [comment]
> I've sorted it from front-end side. Changed the filter from getRankingPanelData to: ` .filter( (zone) => zone.co2intensity !== undefined && zone.co2intensity !== null && filterZonesBySpatialAggregation(zone.zoneId, spatialAggregation) );` Now it looks to filter the datas as it should.
> 
> Got this err when trying to push git push --set-upstream origin bugfix-frontend-null remote: Permission to electricitymaps/electricitymaps-contrib.git denied to andiz2. fatal: unable to access 'https://github.com/electricitymaps/electricitymaps-contrib.git/': The requested URL returned error: 403

You need to fork the repository and push your changes to branch and then open a pull request from that branch as you don't have write access to the electricity maps repo.

I would suggest starting here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by andiz2** [comment]
Thanks @VIKTORVAV99 I've followed the steps from description and created a pull request. 
There were some dependency issues on running the scripts but I would ignore them since I've changed only one line of code.
