### ISSUE TITLE
[Data Issue]: Great app. Indian map is wrong in that part of its territory is missing. Please make sure to update as per official records.

### ISSUE THREAD

**Issue by SunilAnandatheertha** [electricitymaps/electricitymaps-contrib#6669]
### When did this happen?

As seen on 15-04-2024, 16-04-2024 and 17-04-2024 (see attached).
![Wrong indian map](https://github.com/electricitymaps/electricitymaps-contrib/assets/66170566/c6cf9091-9adf-43da-a8e5-23f4b6d02de4)

### What zones are affected?

Northern India.

### What is the problem?

Indian map is wrong in that part of the northern territory is missing (see highlight in attached image). Please make sure to update as per official records. We Indian citizens are very keen to see accurate map of our country being depicted here.
![Wrong indian map](https://github.com/electricitymaps/electricitymaps-contrib/assets/66170566/c6cf9091-9adf-43da-a8e5-23f4b6d02de4)

Below are the official records:
* https://surveyofindia.gov.in/pages/political-map-of-india

**Comment by VIKTORVAV99** [comment]
That area which you say belong to the Northern Parts of India is a disputed area and claimed by several countries. This means that whatever we attribute the area to it will be subjectively wrong and therefore we will not be making any changes to the map concerning this. Once those border disputes have been settled in the eyes of the International community or the UN we will happily edit the map.

**Comment by SunilAnandatheertha** [comment]
Disputed areas of map must indicate the border of dispute in dotted or dashed lines as is done in all maps including those by UN. It is therefore pertinent to include it here as well. Below is the map by UN:
https://www.un.org/geospatial/sites/www.un.org.geospatial/files/files/documents/2020/Nov/world_map_4170_r19_oct20.pdf

**Comment by VIKTORVAV99** [comment]
This is not something that is possible with our current map system unfortunately.

**Comment by VIKTORVAV99** [comment]
The amount of changes required to support this is not something fit for a single issue. Especially not one focusing on just a single region. If you want to suggest deeper changes into the architecture of the app I recommend opening specific issues about that instead. Once that is done this can potentially be revisited.
