### ISSUE TITLE
Wind layer not working anymore

### ISSUE THREAD

**Issue by Alberto4412** [electricitymaps/electricitymaps-contrib#6683]
I love your page/information. I noticed that since a couple days the "wind indiicator" (indicating the wind streams) does not work anymore on my display. Do you have any idea what the cause might be ? Thanks and regards
albert

**Comment by VIKTORVAV99** [comment]
Hi!

If we are going to look into what might be the specific cause we need a bit more information.

What operating system do you have?
What browser are you using? (please include version number if possible).
If you are using a mobile device are you using the app or the website?

**Comment by Alberto4412** [comment]
Hi Victor,

 

thanks for your quick response  !

I have included my responses into your below eMail. A general comment: The Windpattern worked very well until a couple days ago ! Now if I click on the Solarlayer or Windlayer they get into an “endless loop” and the features never shows. I am using the “German language” version of the Electricity Maps – I could use the English version as well – what would I have to do to change to the English version ?

 

Regards

albert

 

Von: Viktor Andersson ***@***.***> 
Gesendet: Samstag, 20. April 2024 16:10
An: electricitymaps/electricitymaps-contrib ***@***.***>
Cc: Alberto4412 ***@***.***>; Author ***@***.***>
Betreff: Re: [electricitymaps/electricitymaps-contrib] WIND DATA (Issue #6683)

 

Hi!

If we are going to look into what might be the specific cause we need a bit more information.

What operating system do you have ? Microsoft 365 Family 
 What browser are you using? (please include version number if possible). Firefox – Version 125.0.1 (64 bit)
If you are using a mobile device are you using the app or the website? I am using my PC – the Website.

**Comment by strassburger** [comment]
Same Problem like Alberto4412 (Windlayer not shown, additional Solarlayer not shown)

my config:
Lenovo Thinkpad T440P
Ubuntu 22.04 LTS / 64-bit
Gnome 42.9
Fenstermanager: Wayland

Browser:
Firefox 125.0 (64-Bit)
Same Problem with Chromium V124.0.6367.60

Thanks for checking
Rainer

**Comment by strassburger** [comment]
Maybee a hint:
With this link no problem at all:
https://a32116e2.electricitymaps-staging.pages.dev/zone/ES-CN-HI
Hope helps

**Comment by phiphou** [comment]
It seems solar layer is not working anymore too... 

Tested in Chrome 124.0.6367.61 and Firefox 125.0.1 on Windows 11

**Comment by VIKTORVAV99** [comment]
I think I have identified the issue and have opened the appropriate PRs in the front and backend so hopefully this should be fixed soon.

**Comment by Alberto4412** [comment]
Thanks Victor ! I will get back to you confirming when it works.  

 

Von: Viktor Andersson

***@***.***> 
Gesendet: Sonntag, 21. April 2024 19:58
An: electricitymaps/electricitymaps-contrib ***@***.***>
Cc: Alberto4412 ***@***.***>; Author ***@***.***>
Betreff: Re: [electricitymaps/electricitymaps-contrib] Wind layer not working anymore (Issue #6683)

 

I think I have identified the issue and have opened the appropriate PRs in the front and backend so hopefully this should be fixed soon.

**Comment by Alberto4412** [comment]
Hi 

 

The orginal link does not correctly work (Wind & Sun layers not active) – but the following link provided by one of the members works  <https://a32116e2.electricitymaps-staging.pages.dev/zone/ES-CN-HI> https://a32116e2.electricitymaps-staging.pages.dev/zone/ES-CN-HI
So I changed my link to this new working link provided by one of the users …  Thanks !

 

 

Von: Viktor Andersson ***@***.***> 
Gesendet: Montag, 22. April 2024 09:36
An: electricitymaps/electricitymaps-contrib ***@***.***>
Cc: Alberto4412 ***@***.***>; Author ***@***.***>
Betreff: Re: [electricitymaps/electricitymaps-contrib] Wind layer not working anymore (Issue #6683)

 

Closed #6683 <https://github.com/electricitymaps/electricitymaps-contrib/issues/6683>  as completed via #6685 <https://github.com/electricitymaps/electricitymaps-contrib/pull/6685> .

**Comment by VIKTORVAV99** [comment]
The deployment is in progress and should work soon.

**Comment by strassburger** [comment]
Working fine now, thanks.

**Comment by phiphou** [comment]
I confirm it works fine.
