### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#6684]
I want to provide a french translation for this message (the one in the tooltip over the chart) but I'm not able to find any relative string in locales for the web app (`web/public/locales`). 

![FireShot Capture 051 - Electricity Maps - Live 24_7 CO₂ emissions of electricity consumption_ - app electricitymaps com](https://github.com/electricitymaps/electricitymaps-contrib/assets/364418/f0c52413-dfe1-41d3-9b31-42ba76390e2f)

**Comment by LucBerge** [comment]
The string was updated. I cannot find in which commit.

![](https://www.pixenli.com/image/7UCpQKzl)

https://github.com/electricitymaps/electricitymaps-contrib/blob/64f291255369ff9442775feb6d52537917f39557/web/src/locales/en.json#L80
