### ISSUE TITLE
Add tooltips for icons in charts

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#6700]
Maybe we can add tooltips on icons in this chart legend, that would show a text description for energy sources.

![FireShot Capture 057 - Electricity Maps - Émissions CO₂ de la consommation électrique en tem_ - app electricitymaps com](https://github.com/electricitymaps/electricitymaps-contrib/assets/364418/878ef810-535a-41cc-a54a-4d9d43b6c1e7)

**Comment by VIKTORVAV99** [comment]
I think that might already be planned but let's double check with @silkeholmebonnen and @Alportan!

**Comment by Alportan** [comment]
Great input! 🙌 We'll pick it up together with the other usability improvements we have planned for our graphs 🎉

**Comment by madsnedergaard** [comment]
This has been fixed :)
