### ISSUE TITLE
Client version vs Github release

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#6706]
Hi,

I noticed that version information on [https://app.electricitymaps.com/client-version.json](https://app.electricitymaps.com/client-version.json) is not synced with latest Github release.

Right now, app version says v1.132.0 while latest Github release says v1.131.0.

Is it a bug ?

![Capture d'écran 2024-05-01 112840](https://github.com/electricitymaps/electricitymaps-contrib/assets/364418/22a1a8bf-5c26-492e-82b2-2ea9c7fff316)

![FireShot Capture 069 - Release v1 131 0 · electricitymaps_electricitymaps-contrib - github com](https://github.com/electricitymaps/electricitymaps-contrib/assets/364418/294b55fa-2cfb-4d88-beb9-5c882bb6bcfc)

**Comment by VIKTORVAV99** [comment]
It's possible it's off by one error. I have been meaning to look into it at some point but since it don't really change anything it not a priority.

**Comment by madsnedergaard** [comment]
Thanks for creating the issue, should be fixable in one of our scripts - I'll take a look :)

**Comment by madsnedergaard** [comment]
I manually created a new GH tag and release with `v1.132.0`, so next time we do a release everything should match up 🤞 
Keeping this issue open until we have verified that it matches!

**Comment by phiphou** [comment]
I confirm last release (1.133.0) is in sync with client-version.json. 

I let you close this.

**Comment by VIKTORVAV99** [comment]
I'll close it but I'll keep an eye on the next release as well so it don't re-introduce this.
