### ISSUE TITLE
 Average of carbon intensity data for the whole world.

### ISSUE THREAD

**Issue by Gabriel2V** [electricitymaps/electricitymaps-contrib#6734]
## Description
Hello everyone. I would like to ask if there is an API request to get an average of carbon intensity data for the whole world. That is, to get an average ultimate value of the present data. Thanks

**Comment by ThisCatLikesCrypto** [comment]
it would be complicated, but you could make this yourself by getting the CO2 impact for each country, getting generation for each country, and then adding up all CO2 data together, adding up all generation data together, and dividing.

**Comment by VIKTORVAV99** [comment]
Hi!
There is currently not such an API endpoint. But if you can motivate it a bit why you need a global average (which doesn't cover all countries in the world) I could raise the idea with the team and see what they say.

**Comment by Gabriel2V** [comment]
For academic purposes, I would need the world average value (although it doesn't cover every country), to include it in estimates where I don't know exactly the area of interest

**Comment by madsnedergaard** [comment]
This is not something we have or would do until the day where we have 100% coverage of the world, as averaging on existing numbers would be incorrect (currently it would miss China as an example) and misrepresent the reality.

Perhaps you can use Ember for this data instead?
https://ember-climate.org/data/data-tools/data-explorer/

![Screenshot 2024-05-14 at 22 22 34](https://github.com/electricitymaps/electricitymaps-contrib/assets/3296643/7f8b9cb7-7544-45ba-8480-1221045af6ac)
