### ISSUE TITLE
Enable nav bar links to open in a new tab

### ISSUE THREAD

**Issue by ecraven1** [electricitymaps/electricitymaps-contrib#6760]
**Is your feature request related to a problem? Please describe.**
I noticed that while all the other links in the UI open a new tab when clicked, the links in the nav bar do not. 

These links open up new tabs:
![Screenshot 2024-05-16 163835](https://github.com/electricitymaps/electricitymaps-contrib/assets/114367783/98e0d28f-9fd5-48ec-907b-6fc45d45fc9a)

These do not:
![Screenshot 2024-05-16 163903](https://github.com/electricitymaps/electricitymaps-contrib/assets/114367783/e3185190-7d3a-42d7-befc-9ec2ec4c53dc)

**Describe the solution you'd like**
Perhaps the nav bar links could open a new tab when clicked, rather than navigating away from the application.

**Describe alternatives you've considered**
While I noticed that when hovering over the nav bar links, an icon is displayed which implies that you will be navigating away from the page, I think it might be more convenient to have these links act in accordance with the style of all the other links in the application.

**Additional context**
None

**Comment by vladimirmak02** [comment]
I agree with your judgement, link behavior throughout the app should be consistent!

There is an easy fix for this: adding `target="_blank"` to the external nav bar link elements.

As I see it, the most straightforward way of implementing this is using the already existing `isExternal ` flag in the `MenuLink` component, and adding the appropriate property to the link if it's true.

Also, I'd recommend to add the frontend label to this issue.

**Comment by madsnedergaard** [comment]
> I agree with your judgement, link behavior throughout the app should be consistent!
> 
> There is an easy fix for this: adding `target="_blank"` to the external nav bar link elements.
> 
> As I see it, the most straightforward way of implementing this is using the already existing `isExternal` flag in the `MenuLink` component, and adding the appropriate property to the link if it's true.
> 
> I can implement this if someone approves my approach.
> 
> Also, I'd recommend to add the frontend label to this issue.

Sounds good to me, feel free to go ahead on implementation :)
