### ISSUE TITLE
Publish Electricitymap app on f-droid App Store

### ISSUE THREAD

**Issue by Chungaa** [electricitymaps/electricitymaps-contrib#6767]
Hello, could you publish the electricitymap on the F-droid App Store.

**Comment by VIKTORVAV99** [comment]
Hi!

It don't seem entirely straight forward to do and would involve a lot of extra steps on our side.
Is there a reason why you want it specifically on the F-droid App Store?

**Comment by Chungaa** [comment]
No, I just had the idea because in the f-droid app store there are a lot of apps that are open source, and they don't have app trackers,.I thought because your app is very helpful and you don't have trackers because of that and some people use the Google PlayStore.
But anyway, if it's very complicated to publish your electricitymap app there, then you don't have to do that. It was just an idea of mine. But you don't have to implement the idea.

**Comment by VIKTORVAV99** [comment]
I think it might make sense to do at one point but I can't guarantee anything and we have some other priorities right now but I'll leave the issue open.

**Comment by madsnedergaard** [comment]
Just to share the knowledge here, it seems like every app update requires making a new PR against the f-droid repository with updated metadata and then wait until the PR is approved. It seems quite cumbersome and additional manual work for making new releases, so for now I see it as too much additional work and an increased risk in having outdated versions in f-droid store. Perhaps if they improve the workflow in the future we can reconsider :)

**Comment by corradio** [comment]
@madsnedergaard should we close this issue based on your comment? We can always re-open if it becomes possible.
