### ISSUE TITLE
Location of the color blind mode switch, as stated in FAQ, seems inaccurate 

### ISSUE THREAD

**Issue by q--** [electricitymaps/electricitymaps-contrib#6780]
The [FAQ](//app.electricitymaps.com/faq) says it's at the bottom of the left panel. I couldn't find it there, but there is a toggle among the icons at the right of the screen.

![The FAQ says: I am color blind. How can I read your map?
You can change the colours displayed in the map by enabling the “color blind mode” setting. It is located on the bottom of the left panel on desktop and in the information tab on the mobile app., but the icon is actually in the row of icons at the right. (Image indicates this with yellow marker, red arrow and red circle.)](https://github.com/electricitymaps/electricitymaps-contrib/assets/2470175/22cce58b-f52f-4d6a-b44c-72a2c13569c5)

**Comment by qalbun-salim** [comment]
I would like to work on this. Is it preferable if we add the color blind button on the left panel rather than changing the FAQ description? I don't think the color blind button fits in the context of information in the left panel
