### ISSUE TITLE
[Data Issue]: Poland->Ukraine transmission incorrectly reported.

### ISSUE THREAD

**Issue by intermittentnrg** [electricitymaps/electricitymaps-contrib#6799]
### When did this happen?

2024-06-03

### What zones are affected?

PL > UA

### What is the problem?

electricityMaps reports transmission from Poland to Ukraine today.

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/96312338/a606b46a-9545-4669-932c-a39c9ef6cca2)

But [ENTSO-E Physical flows](https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_CTY&atch=false&dateTime.dateTime=03.06.2024+00:00|CET|DAY&border.values=CTY|10YPL-AREA-----S!CTY_CTY|10YPL-AREA-----S_CTY_CTY|10Y1001C--00003F&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)) reports zero.
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/96312338/d7cdd466-bcb2-4182-bd41-6fc0f82d8ad8)

The [query_exchange method](https://github.com/electricitymaps/electricitymaps-contrib/blob/master/parsers/ENTSOE.py#L561) in ENTSOE.py uses documentType=A11 which [per ENTSO-E API guide](https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html#_physical_flows_12_1_g) corresponds to Physical flows report data.

Seems like a bug?

**Comment by VIKTORVAV99** [comment]
Hi!
We use the Bidding zone border, not the country border.
As you can see here https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_BZN&atch=false&dateTime.dateTime=03.06.2024+00:00|CET|DAY&border.values=CTY|10YPL-AREA-----S!BZN_BZN|10YPL-AREA-----S_BZN_BZN|10Y1001C--000182&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2) the bidding zone border has reported data flows.

**Comment by intermittentnrg** [comment]
Thanks for quick response! But wtf 😅

So Ukraine has multiple bidding zones, the aggregate should be available from the country? Is this an ENTSO-E data bug then?

**Comment by VIKTORVAV99** [comment]
> Thanks for quick response! But wtf 😅
> 
> So Ukraine has multiple bidding zones, the aggregate should be available from the country? Is this an ENTSO-E data bug then? Or is Ukraine not aggregating the data they send to ENTSO-E correctly.

It could be an issue with the ENTSO-E aggregation as Ukraine switched bidding zones when they made an emergency synchronisation with the continental European grid. 

Ukraine also have some special dispensation due to the war so they don't need to report data, I don't exactly know what data are included in that dispensation but it would not surprise me if it has something to do with that as well, but then I would assume the bidding zone data would be missing as well...

**Comment by intermittentnrg** [comment]
I noticed there is historical data for Ukraine but it stopped flowing when war broke out. https://intermittent.energy/d/rK5XnQ7Vz/electricity-mix?orgId=1&var-region=europe&var-area_type=country&var-area=284&var-demand=1&var-transmission=1&var-price=0&var-gapfill_function=&var-min_interval=5m&from=now-5y&to=now
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/96312338/281ccdac-3dc4-43a3-9a88-e22385198938)

Did not know there is dispensation, but totally understandable that they don't share data during war.
I might raise this aggregation issue with ENTSO-E helpdesk tho. Thanks!

**Comment by intermittentnrg** [comment]
ENTSO-E helpdesk replied
1
> We have contacted the relevant data provider on your request and will update you on the matter as soon as we receive a response.

2
 > please find below the feedback that we received.
>"We are working on making changes to the data publication configuration so that data is presented in the correct aggregation."

neither old nor new data is corrected, but sounds like it is in progress.

**Comment by intermittentnrg** [comment]
Success!

Data is now available on "border - country": https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_CTY&atch=false&dateTime.dateTime=23.06.2024+00:00|CET|DAY&border.values=CTY|10YPL-AREA-----S!CTY_CTY|10YPL-AREA-----S_CTY_CTY|10Y1001C--00003F&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

Historic data was  not backfill/correct historical data, I received following reply from Ukraine data provider when I requested this to be in scope:

> "We are planning to change that regarding on-live publication as of June 14th. We are going to consider correcting historical data."

Sorry to keep updating here, but the data source discussions here are such an incredible resource! I wish ENTSO-E and other data sources had public issue trackers.

**Comment by VIKTORVAV99** [comment]
Nice!

This will be great for everyone that consumes this data and help both us and others validate it when needed! 🙌🏻

**Comment by intermittentnrg** [comment]
Since 2nd July there is no data for Poland <-> Ukraine for either country or bidding zone.
