### ISSUE TITLE
Feedback card not translated while the translation is available

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#6816]
The feedback card has been translated in a recent pull request.

But the survey is displayed in English, while I'm in french in the settings panel.

![Capture d'écran 2024-06-08 163600](https://github.com/electricitymaps/electricitymaps-contrib/assets/364418/fda8f11c-9b6a-43d1-9a23-6c15e212ae8e)

**Comment by VIKTORVAV99** [comment]
We have not done a new app deployment yet, it will be included as soon as we do which will probably be on Monday to avoid potentially breaking things on the weekend.

**Comment by phiphou** [comment]
So I think this is the same for #6817 ? Let me know so I'll close it.

**Comment by VIKTORVAV99** [comment]
> So I think this is the same for #6817 ? Let me know so I'll close it.

Yep should be the same, for reference here is the changes that have not yet been deployed:
https://github.com/electricitymaps/electricitymaps-contrib/compare/v1.143.0...master

**Comment by phiphou** [comment]
Thanks. I'll take an aye on it and close my two issues when I check both are fixed.

**Comment by VIKTORVAV99** [comment]
Update has been created and should be deployed momentarily.
