### ISSUE TITLE
[Data Issue]: Poland and Germany temporarily unavailable

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#6828]
### What zones are affected?

Germany + Poland

### What is the problem?

> Dear Transparency Platform users,
> Due to the implementation of the new balancing market policy at PSE as of June 14th, there may be temporary delays in the market information publishing.
> PSE will respond to potential problems on an ongoing basis for the timely publication of the market information.
> 
> Kind regards,
> TP Team on behalf of PSE

**Comment by rogacz1988** [comment]
This is a good thing because Poland was honestly reporting co2 emissions, while their neighbor was deliberately hiding the true level of emissions ;)
