### ISSUE TITLE
[Data Issue]: Suspiciously low solar generation for Poland

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#6901]
### When did this happen?

It started June 14th, 2024.

### What zones are affected?

Poland (PL)

### What is the problem?

Solar production is consistently significantly lower than it has been previous days.

**Comment by intermittentnrg** [comment]
Can confirm. Also no solar on the 14th?
![bild](https://github.com/electricitymaps/electricitymaps-contrib/assets/96312338/2a206e2a-a9a4-4f86-ad14-d8a0544f6705)
https://intermittent.energy/d/rK5XnQ7Vz/electricity-mix?orgId=1&var-region=europe&var-area_type=country&var-area=26&var-demand=1&var-transmission=1&var-price=0&var-gapfill_function=interpolate&var-min_interval=5m

**Comment by VIKTORVAV99** [comment]
> Can confirm. Also no solar on the 14th? ![bild](https://private-user-images.githubusercontent.com/96312338/343239708-2a206e2a-a9a4-4f86-ad14-d8a0544f6705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTk0NDYsIm5iZiI6MTcxOTQxOTE0NiwicGF0aCI6Ii85NjMxMjMzOC8zNDMyMzk3MDgtMmEyMDZlMmEtYTlhNC00Zjg2LWFkMTQtZDhhMDU0NGY2NzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE2MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MTU4NzhjYjIxYjQ5YmU5ZDg1MTA1MTliMGNiYjgzMDFmMDk1NjdlMDRhZjMwNDJlOGY4NmNkOTA5OGJjY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IDTG0kK_F11q5C3sKPZ5Yh7COm0NCIrRWxp1wE3sVhw) https://intermittent.energy/d/rK5XnQ7Vz/electricity-mix?orgId=1&var-region=europe&var-area_type=country&var-area=26&var-demand=1&var-transmission=1&var-price=0&var-gapfill_function=interpolate&var-min_interval=5m

As far as I can tell there is no data at all for the 14th. Which is suspicious in it self.
It also seems like they switched to a 15 minute resolution on the 14th.

**Comment by intermittentnrg** [comment]
Actual Total Load very jiggly on the 14th also, the rest of the data (I import gen, tx, load and price) looks fine visually. Tho electricityMaps doesn't use load.
![bild](https://github.com/electricitymaps/electricitymaps-contrib/assets/96312338/b0c44b51-c402-4b6a-94d0-b58ed9f3a3be)
[ENTSO-E load on 14th](https://transparency.entsoe.eu/load-domain/r2/totalLoadR2/show?name=&defaultValue=false&viewType=GRAPH&areaType=CTY&atch=false&dateTime.dateTime=14.06.2024+00:00|CET|DAY&biddingZone.values=CTY|10YPL-AREA-----S!CTY|10YPL-AREA-----S&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
)

Generation per production type is actually broken on ENTSO-E website on the 14th
![bild](https://github.com/electricitymaps/electricitymaps-contrib/assets/96312338/0547f643-ac5d-4e38-830a-1cdac150be4b)
[ENTSO-E generation per production type on the 14th ](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=GRAPH&areaType=CTY&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=14.06.2024+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=14.06.2024+00:00|CET|DAYTIMERANGE&area.values=CTY|10YPL-AREA-----S!CTY|10YPL-AREA-----S&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))


Did you e-mail helpdesk or other contact? I might do the same, I guess you didn't look at load data.

**Comment by VIKTORVAV99** [comment]
> Actual Total Load very jiggly on the 14th also, the rest of the data (I import gen, tx, load and price) looks fine visually.
> 
> Tho electricityMaps doesn't use load.
> 
> ![bild](https://github.com/electricitymaps/electricitymaps-contrib/assets/96312338/b0c44b51-c402-4b6a-94d0-b58ed9f3a3be)
> 
> [ENTSO-E load on 14th](https://transparency.entsoe.eu/load-domain/r2/totalLoadR2/show?name=&defaultValue=false&viewType=GRAPH&areaType=CTY&atch=false&dateTime.dateTime=14.06.2024+00:00|CET|DAY&biddingZone.values=CTY|10YPL-AREA-----S!CTY|10YPL-AREA-----S&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
> 
> )
> 
> 
> 
> Generation per production type is actually broken on ENTSO-E website on the 14th
> 
> ![bild](https://github.com/electricitymaps/electricitymaps-contrib/assets/96312338/0547f643-ac5d-4e38-830a-1cdac150be4b)
> 
> [ENTSO-E generation per production type on the 14th ](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=GRAPH&areaType=CTY&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=14.06.2024+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=14.06.2024+00:00|CET|DAYTIMERANGE&area.values=CTY|10YPL-AREA-----S!CTY|10YPL-AREA-----S&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))
> 
> 
> 
> 
> 
> Did you e-mail helpdesk or other contact? I might do the same, I guess you didn't look at load data.

Yeah we reached out to them an got this back:

> Due to the implementation of the new balancing market policy at PSE as of June 14th, there may be temporary delays in the market information publishing. All data uploaded so far will be revised and potentially updated.

**Comment by neglesaks** [comment]
Poland PV production stats appears to be normalized again.

**Comment by intermittentnrg** [comment]
Last 90 days of solar in Poland [link](https://intermittent.energy/d/rK5XnQ7Vz/electricity-mix?orgId=1&var-region=europe&var-area_type=country&var-area=26&var-demand=1&var-transmission=1&var-price=0&var-gapfill_function=interpolate&var-min_interval=5m&from=now-90d&to=now):
![bild](https://github.com/electricitymaps/electricitymaps-contrib/assets/96312338/70349882-2724-4bdf-8b05-e06c9b69e2d8)

Data is not fixed retroactively, and ENTSO-E website is still broken on the 14th.

**Comment by VIKTORVAV99** [comment]
I'll open a new ticket with them tomorrow about retroactively fixing the solar production values.

I'll update this issue with their response.

**Comment by madsnedergaard** [comment]
Seems like data is somewhat stable again (thanks @intermittentnrg for the nice dashboard):

![Screenshot 2024-07-19 at 15 39 50](https://github.com/user-attachments/assets/90397a4a-e1e5-4900-b91b-58ba05c615b8)

**Comment by VIKTORVAV99** [comment]
ENTSO-E got back to me with:
> Dear Viktor,
 
To follow up on your request, please find below the feedback that we received from data provider:
 
"We are aware of the problem with data accuracy since 15th June. We can guarantee that this data will be updated with correct values ASAP. Also for days for which data is missing."
 
We will keep you updated. Thank you for your patience!
 
Best regards,
Transparency Platform Team

We have refetched the data and are re-processing it right now so we will consider this resolved.

**Comment by intermittentnrg** [comment]
> ENTSO-E needs to start relying on EM for data flow validation 😉 🚀

Yeah seriously can't they do basic data validation themselves? Not just Europe/ENTSO-E but other grids & continents too.
I also maintaining [validation rules](https://github.com/intermittentnrg/intermittent-importers/blob/master/validate.yaml) to filter out extreme values.
Do we need to setup some tool to automatically raise issues with them?
Y'all are doing gods work on this - thanks!

**Comment by VIKTORVAV99** [comment]
> > ENTSO-E needs to start relying on EM for data flow validation 😉 🚀
> 
> 
> 
> Yeah seriously can't they do basic data validation themselves? Not just Europe/ENTSO-E but other grids & continents too.
> 
> I also maintaining [validation rules](https://github.com/intermittentnrg/intermittent-importers/blob/master/validate.yaml) to filter out extreme values.
> 
> Do we need to setup some tool to automatically raise issues with them?
> 
> Y'all are doing gods work on this - thanks!

We are building out a set of automatic validation rules ourselves, unfortunately they didn't catch this. There are a few rules that have been suggested internally that would probably have caught this specific issue that the relevant team will take a look at after some well deserved vacation! 🏝️
