### ISSUE TITLE
Hourly Albania data

### ISSUE THREAD

**Issue by sawyer-morgan** [electricitymaps/electricitymaps-contrib#6909]
## Description
Hourly data is available for Albania at https://ost.al/en/.  This includes total production, total load, and cross-border exchanges with Montenegro, Kosovo, and Greece. Even if it's not broken down by source (100% of generation is renewable, almost all hydro but a few solar projects have come online), it would be great to have Albania added to the map. 

I would note that the map already shows that Kosovo, Montenegro, and Greece import from Albania, but the carbon intensity is 461 g/kWh – this is incorrect since Albania's power is 100% renewable. This can be fixed and emissions for Albania estimated even if this source can't be imported live.

Without making a new thread, the Crete-Peloponnese Interconnection https://www.hellenic-cables.com/references/crete-peloponnese-interconnection/ was completed in 2022, adding Crete to the mainland Greek grid. The islands of Andros and Tinos are also connected to the main grid, so these islands should be colored with the Greece zone instead of Aegean Islands.

Thanks so much!

**Comment by VIKTORVAV99** [comment]
Hi!

We are already tracking this development in #4180 and have been in touch with ENTSO-E about getting the data into the ENTSO-E Transparency platform. That way it will be easier for us to implement and others can benefit as well.

I will therefore close this issue in favor of that.

As for the Greece interconnection it should be pretty straightforward and we just need to update the map. I'll see if I can do that tomorrow.

**Comment by sawyer-morgan** [comment]
Sorry I didn't see that item first! Thanks for your work on this!
