### ISSUE TITLE
[Data Issue]: Italian data appears to be 100% estimated

### ISSUE THREAD

**Issue by Gianfilippo980** [electricitymaps/electricitymaps-contrib#6957]
### When did this happen?

2024-06-22

### What zones are affected?

IT-NO, IT-CNO, IT-CSO, IT-SO, IT-SIC, IT-SAR

### What is the problem?

All the data appears to be estimated since the 22nd of June 2024.
I don't know if Terna updated their transparency section or if this project even uses their API (https://developer.terna.it/#en) or get the data from someone else.

**Comment by VIKTORVAV99** [comment]
Hi and thanks for the report!
Seems like this is expected for now as ENTSO-E has posted this bulletin:
> Dear Transparency Platform users,
> 
> Please be informed that since 23/06/2024 TERNA has experienced technical problems for the publication of report [16.1.B] “Actual Generation per Production Type”.
TERNA is working on the issue with the highest priority and we are going to start again the publication by 12/07/2024.
> 
> Best regards,
> Transparency Platform Team on behalf of TERNA

I will create a outage message that links to this issue but there don't appear to be anything we can do at the moment.

**Comment by g1za** [comment]
I contacted ENTSO-E and even if they are waiting for an official communication by Terna they replied the issue seems to be fixed.

**Comment by VIKTORVAV99** [comment]
I have refetched all the data and it will be reprocessed soon. We will consider this closed now.
