### ISSUE TITLE
iOS header overlaps with UI

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#6966]
**Describe the bug**
The iOS header (time, date, battery etc..) overlaps with the UI (see top right of the screen).

**To Reproduce**
Open app

**Expected behavior**
iOS header should not overlap

**Screenshots**
<img width="810" alt="Screenshot 2024-07-09 at 14 15 47 jpeg" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/1655848/bf1f5c45-75e4-466b-b776-ccdfc3679d46">

**Additional context**
Using the app on iPad (classic)

**Comment by Xeno-Tek** [comment]
Could I work on this issue ?

**Comment by Xeno-Tek** [comment]
<img width="387" alt="Screenshot 2024-10-06 at 6 54 37 pm" src="https://github.com/user-attachments/assets/dd5db2de-b907-43dd-a3e0-c90d7a803b9d">
Removed the overlap on iPad 10th generation.

**Comment by Xeno-Tek** [comment]
<img width="569" alt="Screenshot 2024-10-06 at 7 29 20 pm" src="https://github.com/user-attachments/assets/0d29f534-4cf4-4ce6-ba2a-66a40da8ce40">

Works horizontally as well

**Comment by VIKTORVAV99** [comment]
@Xeno-Tek can you make a PR so we can take a look at the code changes?

**Comment by Xeno-Tek** [comment]
I think I have a permanent fix, could I be assigned to work on this issue for the coming days. 

Thank you very much

<img width="416" alt="Screenshot 2024-10-06 at 10 32 31 pm" src="https://github.com/user-attachments/assets/946e6ccf-916e-4ad6-96c6-3c046f8de167">

**Comment by VIKTORVAV99** [comment]
@Xeno-Tek I've assigned you the issue. 🙂
