### ISSUE TITLE
Github issue icon has incorrect color in darkmode

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#6967]
**To Reproduce**
1. Set to darkmode
2. Go to a country that has an associated issue (I used Poland)
3. The github icon is black

**Expected behavior**
It should be white

**Screenshots**
<img width="810" alt="Screenshot 2024-07-09 at 14 20 56 jpeg" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/1655848/7c588e0d-394f-4af6-808e-408982d4553e">

**Table (if relevant):**
 - Device: iPad (regular) -- but should be the same issue on other systems.

**Comment by VIKTORVAV99** [comment]
Eeh it will be even blacker in #6867 but it should have a higher contrast.

We are switching to using the brand colors as backgrounds but maybe we should use their light theme color for the background in dark mode instead.

Let me know what you think of the color change in that PR.

**Comment by VIKTORVAV99** [comment]
Oh I just realized you meant the icon in the outage message, that should be an easy fix.

**Comment by corradio** [comment]
Thanks @VIKTORVAV99 !

**Comment by VIKTORVAV99** [comment]
Happy to fix it! It helped us find some legacy inline SVG code as well which is now removed!
