### ISSUE TITLE
Can not find Zone with CTRL+F anymore

### ISSUE THREAD

**Issue by strassburger** [electricitymaps/electricitymaps-contrib#6971]
Can not find Zone with CTRL+F anymore
Bug shows up in:
https://app.electricitymaps.com/map

CTRL+F + Hierro
Zone not found 
See:
![grafik](https://github.com/electricitymaps/electricitymaps-contrib/assets/28303688/88a19803-b861-450f-8609-7946ecfc5b66)

Bug does not show up in:
https://a32116e2.electricitymaps-staging.pages.dev/map

CTRL+F + Hierro
Zone found

See:
![grafik](https://github.com/electricitymaps/electricitymaps-contrib/assets/28303688/9058cbe7-c4d7-44d1-a5f0-322eca9ba3b9)

Issue exist a while now

**Comment by strassburger** [comment]
Looks like it was a tempory problem.
Can not reproduce it right now 2024-07-11 17:40.
Sorry

**Comment by strassburger** [comment]
Problem shows up again 2024-07-12.

**Comment by strassburger** [comment]
Problem shows up again 2024-07-12 ca17:00

**Comment by VIKTORVAV99** [comment]
Hi!

Maybe you can give some more insights into why you need this in particular and why the search field is not enough?

We recently changed how the ranking panel works internally so we don't have to render all of the list at once.

Also would binding the CTRL+F shortcut to the search field be enough?

**Comment by strassburger** [comment]
Hi,
i regular use "CTRL+F" for years  to see the Ranking of the Zone and then to switch directly into the Zone.
For me this funcion it is really very helpful.

**Comment by strassburger** [comment]
Looks like fixed.
Thanks
Rainer

**Comment by madsnedergaard** [comment]
> Looks like fixed. Thanks Rainer

I would imagine it's working for you when the zone you search for is part of top X elements, but not when it's further down the list and as such is not rendered.

Would you mind sharing what zone you're using, and what letters you type to get it? (E.g. is "GE" usually enough to get the correct zone)?

**Comment by strassburger** [comment]
@madsnedergaard
I would imagine it's working for you when the zone you search for is part of top X elements, but not when it's further down the list and as such is not rendered.
This situacion was before, correct.
Now i do not use CTRL+F anymore, just the searchfield what is working fine.

I just put hier in the searchfield to get El Hierro data:
![grafik](https://github.com/user-attachments/assets/b7c384d4-56d3-486a-b785-4d805edfb653)

**Comment by madsnedergaard** [comment]
Okay great, thanks for the update :)
