### ISSUE TITLE
Preselect Solar layer is not transfered in new TAB

### ISSUE THREAD

**Issue by strassburger** [electricitymaps/electricitymaps-contrib#6972]
*Preselect Solar layer is not transfered in new TAB

Bug shows in:
Starting here:
https://app.electricitymaps.com/zone/ES-CN-HI with windlayer and solarlayer activ
![grafik](https://github.com/electricitymaps/electricitymaps-contrib/assets/28303688/8e907767-2e3e-443e-b8e9-af4f9debccf8)

select arrow top left left of "El Hierro" with right mouse switch to open new window.
Windlayer  active at once, solarlayer inactiv

See:
![grafik](https://github.com/electricitymaps/electricitymaps-contrib/assets/28303688/810d39eb-f85d-4cec-b0f7-fcde2301bf1f)

solarlayer can be acivated:
disable Solarlayer
enable Solarlayer

Bug exist really a while

**Comment by strassburger** [comment]
2024-July-20 ca 12:20
Looks perfect now.
Thanks for fixing it.

**Comment by strassburger** [comment]
2024-09-26
Looks perfect now.
Hope problem will not come back again.
Thanks for fixing it.

**Comment by strassburger** [comment]
Problem back again in other form:

select arrow top left left of "El Hierro" with right mouse no reaction at all.
Can live with it, but really was more comfotabel with reaction of right moue-click

**Comment by VIKTORVAV99** [comment]
If you have a new issue please create a new issue for it, people won't see closed issues if they haven't engaged with it before.
