### ISSUE TITLE
[Feedback wanted]: Add day-ahead pricing to Nordpool zones

### ISSUE THREAD

**Issue by Alportan** [electricitymaps/electricitymaps-contrib#7021]
## Description

We are currently conceptualising a way to show future price data and we want to hear your thoughts on a first version that can be added to our current app without impacting current functionality.

A few things to consider:
- the solution should be displayed ONLY if we have the day-ahead price data, therefore certain modularity/flexibility is needed
- we want to unify some things by switching from /MWh to /kWh to accommodate existing mental models when analysing electricity data 

What we are looking for:
- does this pattern make sense?
- is there any information missing?
- is there too much information? (considering we are adding some new summaries/correlation with carbon intensity)

![image](https://github.com/user-attachments/assets/28f2508c-433a-4d0c-a5d3-48803409f363)

Let us know what you think! 🙏

**Comment by silimotion** [comment]
Hi!
I really like the design of this new feature, congrats!

A few remarks/questions:
- How will negative prices be rendered?
- I believe many people confuse the electricity market price with the price **they** pay (i.e. they may have a different tariff, or don't know about other grid fees such as peak/valley, etc). Now that it could become an important feature it could be wise to briefly explain these concepts to users to avoid complaints and overall confusion. Although there is a note at the end, I believe it will probably be overlooked. Could it be at the top, in a different color, and possibly include a link to a wiki or page that explains these concepts to users? The link could be customized for each country that includes this new feature.

**Comment by Alportan** [comment]
Thanks for your feedback @silimotion ! 🙌 

> * How will negative prices be rendered?

Here's an idea of how negative prices could be rendered. 👇 
![image](https://github.com/user-attachments/assets/1dd6e02f-4e4e-46de-a35b-ff11edd5cbb8)


> * I believe many people confuse the electricity market price with the price **they** pay (i.e. they may have a different tariff, or don't know about other grid fees such as peak/valley, etc). Now that it could become an important feature it could be wise to briefly explain these concepts to users to avoid complaints and overall confusion. Although there is a note at the end, I believe it will probably be overlooked. Could it be at the top, in a different color, and possibly include a link to a wiki or page that explains these concepts to users? The link could be customized for each country that includes this new feature.

Very good points on this! I think I initially had it at the top but I moved it lower as it seemed a bit crowded, but looking at it now, I agree that it might be missed if at the bottom. I'll play a bit more with the idea of including a link with more explanation and colour and get back to you later! 😊
