### ISSUE TITLE
ManxLink interconnector between England and Isle of Man is missing

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#7123]
## Description
We currently don't have any data for the ManxLink interconnector between England and the Isle of Man. 

If anyone know where we could get this data that would be most helpful!

**Comment by AJDelusion** [comment]
`[Terravolt](https://terravolt.co.uk/uk-grid-visual/)` includes live info for the Manx interconnector. It says it uses data from Elexon and bmreports.

**Comment by VIKTORVAV99** [comment]
I checked the Elexon BMRS portal but I don't see any data for this exchange in particular: https://bmrs.elexon.co.uk/interconnector-flows

Which is a bit curious I must say.

**Comment by AJDelusion** [comment]
> I checked the Elexon BMRS portal but I don't see any data for this exchange in particular: https://bmrs.elexon.co.uk/interconnector-flows
> 
> Which is a bit curious I must say.

I checked with the maker of Terravolt and they confirmed that the data is provided by this link on Elexon BMRS:

https://bmrs.elexon.co.uk/balancing-mechanism-bmu-view?bmuId=E_MANXENR-1&activeTab=Physical&startDate=2024-09-24T23%3A00%3A00.000Z&endDate=2024-09-25T15%3A00%3A00.000Z

It is not treated the same as the other interconnectors, but is it still possible to extract live data for Electricity Maps from it?

**Comment by VIKTORVAV99** [comment]
> > I checked the Elexon BMRS portal but I don't see any data for this exchange in particular: https://bmrs.elexon.co.uk/interconnector-flows
> > Which is a bit curious I must say.
> 
> I checked with the maker of Terravolt and they confirmed that the data is provided by this link on Elexon BMRS:
> 
> https://bmrs.elexon.co.uk/balancing-mechanism-bmu-view?bmuId=E_MANXENR-1&activeTab=Physical&startDate=2024-09-24T23%3A00%3A00.000Z&endDate=2024-09-25T15%3A00%3A00.000Z
> 
> It is not treated the same as the other interconnectors, but is it still possible to extract live data for Electricity Maps from it?

Nice! 🙌🏻

We might have to build a new or adjust the parsers but if there data is there we can sure add it!

I'm personally a bit busy this week but I'll add the help wanted label if someone wants to pick it up otherwise I'll try and take a look at it next week.

**Comment by VIKTORVAV99** [comment]
I just opened a PR for it here #7238 as it turned out to be a bit easier than I expected. We still need to do some testing and double check a few things before it can be merged though.

**Comment by AJDelusion** [comment]
I'm guessing an emission factor will be needed for when the Isle of Man is exporting electricity to GB?
In the absence of live data, I've found the below data for 2022/23.

315 million kWh gas (98.8%)
2.2 million kWh hydro (0.7%)
1.7 million kWh oil (0.5%)

Using same emission factors as for GB I get 487 g CO2e/kWh.
Not perfect but probably not that far off given how gas currently dominates Manx electricity generation.

Source (page 21): https://www.manxutilities.im/media/2830/mu_annual-report_r9.pdf

**Comment by VIKTORVAV99** [comment]
> I'm guessing an emission factor will be needed for when the Isle of Man is exporting electricity to GB?
> 
> In the absence of live data, I've found the below data for 2022/23.
> 
> 
> 
> 315 million kWh gas (98.8%)
> 
> 2.2 million kWh hydro (0.7%)
> 
> 1.7 million kWh oil (0.5%)
> 
> 
> 
> Using same emission factors as for GB I get 487 g CO2e/kWh.
> 
> Not perfect but probably not that far off given how gas currently dominates Manx electricity generation.
> 
> 
> 
> Source (page 21): https://www.manxutilities.im/media/2830/mu_annual-report_r9.pdf

So far I've only seen imports from GB to the Isle of Man but it makes sense to adjust this just in case so we don't need the fallback emission factors. I'll make sure it's included in the PR.

**Comment by VIKTORVAV99** [comment]
@AJDelusion you didn't happen to ask about the Isle of Wright and Orkney Island data as well?

Would be nice to get Isle of Wright added as well and make the Orkney Island data a bit more reliable.

**Comment by AJDelusion** [comment]
> @AJDelusion you didn't happen to ask about the Isle of Wright and Orkney Island data as well?
> 
> Would be nice to get Isle of Wright added as well and make the Orkney Island data a bit more reliable.

I didn't ask about Isle of Wight or Orkney. Feel free to reach out to them if you think they may be able to point you in the right direction.
I wonder if the following could be put to use for IoW? https://www.ssen.co.uk/our-services/active-network-management/iow-anm/


From Electricity Map's perspective it would be worth reflecting whether it is possible to report them separately without double counting them in the GB Grid. Unlike the Isle of Man, which is a crown dependency with its own national grid, the other islands are integral parts of the UK and so generation from their power plants would likely be reported as part of the GB National Grid. For example, Isle of Wight's main power plant (Cowes) is reported in Elexon, whereas Isle of Man's main power station (Pulrose) is not reported.

**Comment by VIKTORVAV99** [comment]
> > @AJDelusion you didn't happen to ask about the Isle of Wright and Orkney Island data as well?
> > Would be nice to get Isle of Wright added as well and make the Orkney Island data a bit more reliable.
> 
> I didn't ask about Isle of Wight or Orkney. Feel free to reach out to them if you think they may be able to point you in the right direction. I wonder if the following could be put to use for IoW? https://www.ssen.co.uk/our-services/active-network-management/iow-anm/
> 
> From Electricity Map's perspective it would be worth reflecting whether it is possible to report them separately without double counting them in the GB Grid. Unlike the Isle of Man, which is a crown dependency with its own national grid, the other islands are integral parts of the UK and so generation from their power plants would likely be reported as part of the GB National Grid. For example, Isle of Wight's main power plant (Cowes) is reported in Elexon, whereas Isle of Man's main power station (Pulrose) is not reported.

Thanks!

We'll take a look at it when/if we decide to split out Isle of Wight from the main GB zone. Right now Orkney might be affected but it shouldn't cause any huge problems since it's pretty small scale. But it's definitely something we should address as soon as possible.
