### ISSUE TITLE
Germany -> Luxembourg exchange disappeared?

### ISSUE THREAD

**Issue by thomasgibon** [electricitymaps/electricitymaps-contrib#7161]
Hi all!

In the new version of the map app, there is no more interconnection between Germany and Luxembourg (in the "Country" map).

I believe this is fairly recent, as last year the data clearly showed significant exchanges were taking place:
![image](https://github.com/user-attachments/assets/747fd0fc-08df-4c6f-bb6f-1cd39055ab93)

This is how it looks now:
![image](https://github.com/user-attachments/assets/e7ec0aca-156c-4146-9692-9e9eec3d6993)

This issue probably appeared because DE and LU are in the same (DE-LU) bidding zone, so this behavior is normal for the "Zone" map. However ENTSOE has always been tracking exchanges between the two countries, so this data should be available for the "Country" map.

**Comment by VIKTORVAV99** [comment]
Hi!

The exchange is still there but there has been data issues in the ENTSO-E Transparency platform for this exchange on and off the last few months, there really isn't much we can do about it but I'll reach out to them about it.

For reference: https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_CTY&atch=false&dateTime.dateTime=06.09.2024+00:00%7CCET%7CDAY&border.values=CTY%7C10Y1001A1001A83F!CTY_CTY%7C10Y1001A1001A83F_CTY_CTY%7C10YLU-CEGEDEL-NQ&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

**Comment by VIKTORVAV99** [comment]
Should be resolved now 🙂
