### ISSUE TITLE
[Data Issue]: nuclear is back in Germany !

### ISSUE THREAD

**Issue by Oocedar** [electricitymaps/electricitymaps-contrib#7230]
### When did this happen?

"2024-09-24 0:00"

### What zones are affected?

DE

### What is the problem?

Self-explanatory

![image](https://github.com/user-attachments/assets/6b564cfa-1df5-4717-b326-d7efd348373c)

**Comment by VIKTORVAV99** [comment]
We are already looking into it, stay tuned!

**Comment by VIKTORVAV99** [comment]
This should be fixed now. We'll continue to monitor it but hopefully it's resolved.
