### ISSUE TITLE
Greenlink Interconnector active

### ISSUE THREAD

**Issue by AJDelusion** [electricitymaps/electricitymaps-contrib#7235]
As of 19 September Elexon BMRS has begun showing that the new 500MW Greenlink Interconnector between GB and IE is operating (currently in testing prior to full operation later in the year).
Can this please be added to the existing exchange between Great Britain and Ireland?

Source: https://bmrs.elexon.co.uk/interconnector-flows

<img width="902" alt="Greenlink" src="https://github.com/user-attachments/assets/69f182f5-607a-4696-8ae1-e110f467f0b2">

**Comment by eli-goodfriend** [comment]
Hello! Normally I would ask before opening a PR on an issue, but this looked like a small fix so I just went for it. If that's not preferred, please let me know, I'm happy to adjust.

**Comment by VIKTORVAV99** [comment]
> Hello! Normally I would ask before opening a PR on an issue, but this looked like a small fix so I just went for it. If that's not preferred, please let me know, I'm happy to adjust. 

That's perfectly fine! I'll take a look and make sure it's working as expected in a moment. But like you said it's a small change, previously the data was not available in this particular endpoint but if that has changed it's great!
