### ISSUE TITLE
Missing exchange configuration between South Africa (ZA) and Lesotho (LS)

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#7270]
## Description

Lesotho have a interconnector with South Africa and rely on them for a large part of their electricity. It would be nice to get the config added as a first step in getting this exchange on the map.

**Comment by u7262835** [comment]
Hi ElectricityMaps Team, 

I am interested in working on this issue. It's my first time contributing to this project, and I think it would be a great opportunity for me to learn how the data-parsing works (whilst helping the project in the process). 

I have looked at other successfully-completed issues and pull-requests (such as Issue #7123 and Pull Request #7238) in an attempt to understand what these types of issues involve, and how the connections and parsers are implemented. 

What would I need to do/who would I need to contact to be assigned to this issue, and is there any additional information about this issue (or general exchange parser implementations) that I should be aware of? 

Thanks in advance!

**Comment by VIKTORVAV99** [comment]
Hi!

This initial issue was only really meant to add the exchange configuration to the app so we can inform people that there is a exchange but we are missing the data.

But if you want to try and build a parser for it you are very welcome to do so, I would like that to be a separate PR though.

> What would I need to do/who would I need to contact to be assigned to this issue, and is there any additional information about this issue (or general exchange parser implementations) that I should be aware of?

This is the hard part, finding the data, I don't have a data source I can link to but for ZA data we are using data from [eskom.co.za](http://eskom.co.za/) so that would be a good start.

As for the parser implementation itself that will be different depending on what data can be found. But generally it includes transforming the data to our format and using our parser classes to get some general validation of the data. Information around this can be found here: https://github.com/electricitymaps/electricitymaps-contrib/wiki/Building-a-new-parser

**Comment by u7262835** [comment]
Perfect, thank you very much for your speedy and thorough reply Viktor!

I will start by attempting the exchange configuration in the coming days, and after that is completed (if it is approved as an appropriate solution) I will have a deeper look into data sources and parsing. 

Thanks once again!

**Comment by VIKTORVAV99** [comment]
Sounds like a plan!

Thanks for taking on this issue!

**Comment by u7262835** [comment]
Hi Viktor (or other maintainers),

What's the best way to locally verify that the config file that I've created is correct? Is there an easy way to locally view the exchange configuration on a non-live map, or another preferred method of verification (or for changes such as the config files, is it just confirmed by the reviewing developer in the pull request)?

**Comment by VIKTORVAV99** [comment]
> Hi Viktor (or other maintainers),
> 
> 
> 
> What's the best way to locally verify that the config file that I've created is correct? Is there an easy way to locally view the exchange configuration on a non-live map, or another preferred method of verification (or for changes such as the config files, is it just confirmed by the reviewing developer in the pull request)? 

Since the exchanges are hidden if they don't have any data this is not super straightforward. But you can modify the hourly state file in the mock server to include the exchange with some random values for flows.

Otherwise I can just take a look at it.

**Comment by u7262835** [comment]
Thanks Viktor, I'll create a pull request and assign you as the reviewer!

**Comment by u7262835** [comment]
Sorry about the delay, the pull request has been submitted. Thanks once again for all of your help, and any feedback is appreciated!

**Comment by VIKTORVAV99** [comment]
> Sorry about the delay, the pull request has been submitted. Thanks once again for all of your help, and any feedback is appreciated!

No need to worry! I'll take a look at it right away!

**Comment by u7262835** [comment]
@VIKTORVAV99 this issue hasn’t closed automatically with the merge (despite being linked), so you may need to close this manually.

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 this issue hasn’t closed automatically with the merge (despite being linked), so you may need to close this manually.

Thanks for the heads up! I just closed it!

**Comment by u7262835** [comment]
> Perfect, thank you very much for your speedy and thorough reply Viktor!
> 
> I will start by attempting the exchange configuration in the coming days, and after that is completed (if it is approved as an appropriate solution) I will have a deeper look into data sources and parsing.
> 
> Thanks once again!

Update regarding the parser: I've had an extensive look after the past couple of weeks, but (at least with my level of expertise) a parser does not seem viable at the moment with the available data. Sorry that I couldn't complete this part; hopefully data availability will improve for this in the future (or someone can extract more from the currently available data than I could)!!

**Comment by VIKTORVAV99** [comment]
That's okay, I'm very aware of the data challenges we face with some zones. So this is by no means a problem on your part!
