### ISSUE TITLE
[Data Issue]: Improved data source for Great Britain 

### ISSUE THREAD

**Issue by senanm01** [electricitymaps/electricitymaps-contrib#7283]
### When did this happen?

2024-10-05 22:50

### What zones are affected?

GB

### What is the problem?

The data source used for Great Britain is not accurate. 
As of 22:50 - 5/10/24 co2/kWh was 211g. 
![image](https://github.com/user-attachments/assets/e60f91a0-80a8-4b57-b845-5db0975b3bb9)

Official data from the NESO showed CO2 at 47. 
![image](https://github.com/user-attachments/assets/63386821-7375-4121-82ca-9eaf93f80e04)

I suggest the data source is changed to the NESO official data source for more accurate data at https://carbonintensity.org.uk/.

**Comment by VIKTORVAV99** [comment]
Hi!

The website you linked don't use the same methodology and only include direct emissions and not lifecycle emissions.

Furthermore Electricity Maps don't parse reported emission factors, only reported power generation and exchange data to keep a consistent methodology for all zones.

Therefore we will not switch to this data source.
