### ISSUE TITLE
"Installed capacity" label is shown for aggregated data

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#7320]
**Describe the bug**
"Installed capacity" label should not be shown for aggregated data

**To Reproduce**
1. Pick any zone
2. Select Yearly view

**Expected behavior**
"Installed capacity" label should not be shown for aggregated data.

**Screenshots**
<img width="446" alt="image" src="https://github.com/user-attachments/assets/b0ee6e71-7205-423b-9c6a-1b2e6b85c735">

**Comment by VIKTORVAV99** [comment]
Let's see if someone want to fix this as a part of Hacktoberfest otherwise I'll pick it up. 👍🏼

**Comment by Reterics** [comment]
I am happy to work on it as part of Hacktoberfest, if it is still available

**Comment by Nivedhitha-dp** [comment]
I am interesting in picking up this issue, can this be assigned to me.

**Comment by VIKTORVAV99** [comment]
> I am interesting in picking up this issue, can this be assigned to me.

Sure thing, please try and do it in a way that don't cause CLS when shifting between the aggregations.
