### ISSUE TITLE
Reverse engineer historical NL data

### ISSUE THREAD

**Issue by DutchPower24** [electricitymaps/electricitymaps-contrib#7323]
Since the NL data is now using NED.nl as the data source we have the option to reverse engineer the historical relativity incorrect data (which is reflected in the high share of unknown sources of electricity production).

NED.nl is available for at least a few years in the past.

**Comment by VIKTORVAV99** [comment]
Hi!

We have already done this internally and it should be visible in the app next month when the new aggregations have been created.

**Comment by DutchPower24** [comment]
Awesome. Looking forward to the improved results.

**Comment by VIKTORVAV99** [comment]
> Awesome. Looking forward to the improved results.

Likewise!

**Comment by DutchPower24** [comment]
Could it be that something went wrong? 2019 & 2020 numbers are looking very strange at the moment.

**Comment by VIKTORVAV99** [comment]
> Could it be that something went wrong? 2019 & 2020 numbers are looking very strange at the moment. 

Please open a new issue for this. Most of our team are not watching closed issues. Thanks in advance!
