### ISSUE TITLE
[Data Issue]: Incorrect emissions factors used for Australian coal

### ISSUE THREAD

**Issue by timinclimate** [electricitymaps/electricitymaps-contrib#7341]
### When did this happen?

Ongoing

### What zones are affected?

WA, Vic, NSW, Qld

### What is the problem?

The emissions factors being used for Australian coal fired power stations are very wrong. 

This problem is especially acute for Victoria. The emissions factor used for Victoria is 820 kg CO₂e/MWh. However, Victoria's three coal power stations all burn lignite. Their average emissions intensities range between 1,100 and 1,200 kg CO₂e/MWh. This leads to a significant difference in your final figures. The emissions intensity your team derived for Victoria across 2023 averaged just under 500 kg CO₂e/MWh. A better estimate would be approximately ~700 kg CO₂e/MWh. 

The IPCC emissions factor of 820 kg CO₂e/MWh is likewise wrong for New South Wales and Queensland, though less so. The average emissions intensity for coal in these states is more like 900 kg CO₂e/MWh. This leads to the overall emissions intensity in these states too low by ~15%.

I'm not sure which approach is best to determine a single CO₂e emissions factor for each jurisdiction, because I'm not sure what the resolution of your generation data is in the back end (e.g. do you pull per facility generation data from opennem then aggregate it, or do you just pull the totals?). However, the CO₂e emissions intensity of each east coast generator in the country is included in the [2023 AEMO IASR assumptions workbook](https://aemo.com.au/en/energy-systems/major-publications/integrated-system-plan-isp/2024-integrated-system-plan-isp/current-inputs-assumptions-and-scenarios). If needed these could be production-weighted to give a single state-wide emissions factor for coal in each jurisdiction.

I am not a coder, but could help derive those figures if it would be useful.

**Comment by VIKTORVAV99** [comment]
Hi!
What we have done for most European zones are to take reported emissions from each power source (on a total level) and then divide it by the total amount of electricity produced to get a emission factor (this method kind of only works for fossil fuels).

So if you have a place where we can find how much emissions where released from carbon in each zone/jurisdiction then we could maybe do this. But it all depends on what kind of data we can find.

But if we know the Victoria coal plants all use lignite maybe we can update that to use IPCCs lignite values instead, at least as a temporary solution, I remember seeing them somewhere in the past.

**Comment by timinclimate** [comment]
I'm not aware of an official source for electricity sector emissions by state and fuel type. To my knowledge, any available sources that show this are unofficial and use derived values. But we do have official emissions intensities in the AEMO IASR and authoritative emissions data provided by OpenElectricity (which opennem is now called).

I've calculated the 2023 emissions for each power station using the above in this CSV: [Eastern Australian coal emissions by power station.csv](https://github.com/user-attachments/files/17457818/Eastern.Australian.coal.emissions.by.power.station.csv)

I subsequently totalled emissions and generation to give production-weighted emissions intensity for each state. This gives emissions intensities for coal in each state as:

- NSW: 884.91 kg CO₂/MWh
- Qld: 891.06 kg CO₂/MWh
- Vic: 1184.67 kg CO₂/MWh

If you want to use these values, the sources are [OpenElectricity](https://openelectricity.org.au/) and [AEMO](https://aemo.com.au/en/energy-systems/major-publications/integrated-system-plan-isp/2024-integrated-system-plan-isp/current-inputs-assumptions-and-scenarios)

**Comment by VIKTORVAV99** [comment]
Unfortunately we don't accept 3rd party emission factors unless they have been peer-reviewed in academic papers as we can't validate their methodology.

I'll pass along this info though and see what the rest of the teams think, it might be enough that we have the emissions for each plant and then we can calculate it our selves an publish a notebook that has each step for it.

Preferably we would also do gas and oil in at the same time if we find data for it.

**Comment by FelixDQ** [comment]
Hi @timinclimate,
Thank you for reporting. We have some previous discussion around this here: https://github.com/electricitymaps/electricitymaps-contrib/issues/5383

We want to do this, but we haven't had the time yet. Adding and validating the data requires a lot of time, as there are often many data discrepancies that require us to investigate many single power plants.

Would you be able to read through the issue above and add a comment?

**Comment by stewart958** [comment]
I left a comment on the other thread that I've been keen to pick this up for a while and finally have a bit of time to. There are fuel-specific emission factors available for each state - I'm fairly familiar with the process for DCCEEW setting them but not so familiar with Python. Will take some time to get across the issue before seeing what I can do.
