### ISSUE TITLE
[Data Issue]: backward calculation Netherlands went wrong?

### ISSUE THREAD

**Issue by DutchPower24** [electricitymaps/electricitymaps-contrib#7391]
### When did this happen?

Today

### What zones are affected?

Nl

### What is the problem?

Could it be that something went wrong? 2019 & 2020 numbers are looking very strange at the moment. Looks like fossil based energy is missing?

**Comment by FelixDQ** [comment]
Thank you for reporting @DutchPower24 

@Nivedhitha-dp I think that we might just need to refetch and reprocess the data using the parser, but it would be good to validate. If you can use the parser to check if there are any problems in 2019/2020, that would be great! After you've validated the data, I can start a refetch/reprocess.

There are instructions for how to run the parser here: https://github.com/electricitymaps/electricitymaps-contrib/wiki/Fixing-a-broken-parser

Thanks!

**Comment by FelixDQ** [comment]
From a quick look, it seems like ned.nl aren't reporting gas production before 2021. Can you check if we are using their API wrong or alternatively if we can get the gas production from an alternative source for the historical data? It looks like we can get it from [ENTSO-E](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=01.05.2019+00:00%7CCET%7CDAYTIMERANGE&dateTime.endDateTime=01.05.2019+00:00%7CCET%7CDAYTIMERANGE&area.values=CTY%7C10YNL----------L!BZN%7C10YNL----------L&productionType.values=B01&productionType.values=B25&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))

**Comment by annaib00** [comment]
I have updated the parser to include historic ENTSOE data before 2021 for types where there is no NED.nl data in the PR #7401. Thanks for reporting and looking into this!

**Comment by DutchPower24** [comment]
> I have updated the parser to include historic ENTSOE data before 2021 for types where there is no NED.nl data in the PR #7401. Thanks for reporting and looking into this!

When will the data be updated? I see the pull request merged but the data is still wrong.

**Comment by FelixDQ** [comment]
We are currently refetching and reprocessing the data. We had to fix a few issues in the backend, but I expect the data to be available in ~1-2 weeks.

**Comment by DutchPower24** [comment]
> We are currently refetching and reprocessing the data. We had to fix a few issues in the backend, but I expect the data to be available in ~1-2 weeks.

Great, looking forward.
