### ISSUE TITLE
Auto-Zoom exchange capacity ?

### ISSUE THREAD

**Issue by KptKuck** [electricitymaps/electricitymaps-contrib#7420]
## Description

As can be seen in the image, the current display is of little use in providing a quick overview of imports or exports.
I think it would be helpful to have an auto-zoom function for the data.

![image](https://github.com/user-attachments/assets/314a0c49-f728-49f5-8c45-bfd93a4fe5ff)

**Comment by phiphou** [comment]
Duplicate with #7321

**Comment by KptKuck** [comment]
That is correct

**Comment by VIKTORVAV99** [comment]
Closed since this is a duplicate. Please add any additional insights or context to the original issue.
