### ISSUE TITLE
Using a lowercase zone in URL does not work

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#7436]
**Describe the bug**

Going to https://app.electricitymaps.com/zone/DK-dk2 no longer works.

This seems to be related to the new `24h` parameter, as this works: https://app.electricitymaps.com/zone/DK-dk2/24h 🤔 

**To Reproduce**
1. Open the link above

**Comment by silkeholmebonnen** [comment]
It works for me

**Comment by madsnedergaard** [comment]
Really? I tried going to https://app.electricitymaps.com/zone/DK-dk2 in both Safari and Arc/Chrome, getting same result where it's going to `/map` instead of the zone 😅

**Comment by VIKTORVAV99** [comment]
Even valid ones like https://app.electricitymaps.com/zone/AU don't seem to work for me.

**Comment by madsnedergaard** [comment]
Here's a video showing what the experience is like for me:

https://github.com/user-attachments/assets/2a2d84a5-7844-41cc-9d52-08ff6d4bf990

**Comment by silkeholmebonnen** [comment]
My mistake, doesn't work for me either
