### ISSUE TITLE
Auth token not recognised

### ISSUE THREAD

**Issue by tvwerkhoven** [electricitymaps/electricitymaps-contrib#7477]
## Description

Since around 11:00 CET today my API token is no longer recognised. I requested a new one via https://api-portal.electricitymaps.com however using this fresh token also returns "Invalid auth-token". I can share the token in PM if helpful.

```
curl 'https://api.electricitymap.org/v3/carbon-intensity/latest?zone=BE' -H 'auth-token: mytoken'
{"error":"Invalid auth-token"}
```

Surprisingly, **not** specifying an auth token **does** return data:

```
curl 'https://api.electricitymap.org/v3/carbon-intensity/latest?zone=BE'
{"zone":"BE","carbonIntensity":214,"datetime":"2024-11-28T15:00:00.000Z","updatedAt":"2024-11-28T14:46:10.233Z","createdAt":"2024-11-25T15:43:23.481Z","emissionFactorType":"lifecycle","isEstimated":true,"estimationMethod":"TIME_SLICER_AVERAGE"}
```

**Comment by VIKTORVAV99** [comment]
@madsnedergaard mind taking a look at this?

**Comment by madsnedergaard** [comment]
I've found the issue, thanks again for reporting this! It has been fixed now, would you mind testing again? :)

**Comment by tvwerkhoven** [comment]
> I've found the issue, thanks again for reporting this! It has been fixed now, would you mind testing again? :)

Thanks, it's working again, for both my tokens! However note that without auth-token also (still) works. Is this by design?

**Comment by madsnedergaard** [comment]
> > I've found the issue, thanks again for reporting this! It has been fixed now, would you mind testing again? :)
> 
> Thanks, it's working again, for both my tokens! 

Great, happy to hear that 🥳 

> However note that without auth-token also (still) works. Is this by design?

We are temporarily allowing unauthenticated requests to certain endpoints while we're migrating to a new system for managing tokens (all existing tokens will continue working as before), but thanks for flagging it :)
