### ISSUE TITLE
[Data Issue]: Data not available for IQ (Iraq) parser?

### ISSUE THREAD

**Issue by jayaddison** [electricitymaps/electricitymaps-contrib#7487]
### When did this happen?

Observed locally attempting to run the IQ (Iraq) parser and access the dashboard URL referenced in the corresponding code.

### What zones are affected?

IQ, IQ-KUR

### What is the problem?

I've been examining the status of various parsers for #6135, and as part of that process, began reading the IQ (Iraq) parser code.

Although the relevant website is still online, the URL retrieved by the parser ( https://www.gdoco.org/vueips.php ) does not appear to return relevant generation/dispatch data at the moment.

I also checked a previous dashboard API IP address used previously ( until b54f446e2abb0d2391c67f65263723918a7bc15d ) and confirmed that that it remains non-functional.

**Comment by VIKTORVAV99** [comment]
There really isn't much we can do about this if we don't have access to the data. It's very unfortunate but not something we'll be able to fix if the page don't exist anymore (and the rest of er website seems to be behind a login).

**Comment by jayaddison** [comment]
Thanks @VIKTORVAV99 - I've been considering creating a pull request to archive the scraper - would that make sense?

**Comment by VIKTORVAV99** [comment]
> Thanks @VIKTORVAV99 - I've been considering creating a pull request to archive the scraper - would that make sense?

We usually only archive parsers if we remove the zone or if they have been replaced but if there is no way to fix it I guess it makes sense to archive it.
