### ISSUE TITLE
Enhance onboarding experience for new more options dropdown

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#7519]
The new feature popover talks about more options dropdown but doesn't show where to find it.

I think many non IT people won't easily find it. 

Is it possible to enhance the onboarding experience with a tooltip near the three dots that explain you need to click on them to reveal sharing options ?

**Comment by phiphou** [comment]
@VIKTORVAV99 May I close this, because of #7524 ?

**Comment by VIKTORVAV99** [comment]
Yeah I think so, at least for now. We are looking into if we should have multiple popovers and/or replace some of the onboarding slides but I think that’s a separate task.
