### ISSUE TITLE
Buttons for averages.. 24h, 7d, 1month, 1year

### ISSUE THREAD

**Issue by danbates2** [electricitymaps/electricitymaps-contrib#7542]
Given this is hourly, it feels limited in a sense. 

I'd like buttons that either alter the map itself, or just a country profile page, enabling views of averages over a longer time period. 

I regularly use grid.iamkate.com and like the time element there. 

I hope that's clear and helpful.

Thanks for the sterling job.

**Comment by tonypls** [comment]
Thanks for the feedback! 

Are you looking for something more than what's available in our time controller?
<img width="368" alt="image" src="https://github.com/user-attachments/assets/36b9dc19-343a-42ae-aca9-ff30edaa741c" />

You can view aggregated data here. We're looking to expand this to also include 72 hours and would appreciate your feedback on improving the interaction.

**Comment by danbates2** [comment]
Huh, how recently was this implemented?

I just downloaded the app to Android and found the feature..

Then reloaded my Firefox browser and the feature appeared.

I must've been out of date!

...

I've just had a play with the feature. It doesn't seem to be providing averages over longer time periods, but rather a slider to select a moment from longer ago.

Is that right?

**Comment by danbates2** [comment]
It's a really useful feature.

> 24 and 72 hours are hourly averages, 30 days are daily averages, 12 months are monthly averages and All is yearly averages.

Makes sense. Thanks.

I think that's all clear enough..
I prefer the desktop version, where it states "Hourly data for: <the hour in question>".
But really the slider in the mobile app implies the same thing. All good.

All the best.
